### ISSUE TITLE
Hero Rotation Buttons not showing up on shaman[Bug]: 

### ISSUE THREAD

**Issue by cantthinkofaname69** [herotc/hero-rotation#1000]
### What version of HeroRotation are you using?

10.2.0.06

### What version of HeroLib are you using?

10.2.0.01

### What version of HeroDBC are you using?

10.2.0.02

### What is the issue?

Randomly during combat in dungeons the buttons wont show up anymore and stop showing up for a longer amount randomly ( 5+ globals) happened after i updated the addon today on curseforge

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
Elemental? Enhancement?

Link your talent build.

If the icon is disappearing, a lua error is occurring. Please enable lua errors with `/console scriptErrors 1` and post the error here. You can later disable errors with `/console scriptErrors 0`.

**Comment by cantthinkofaname69** [comment]
Enhancement

BcQAzii1bx6MdXWQl8y/78bs6KRSKRCCJhcgk0QJRCAAAAAAAAAAAAoEhkQiWKiCJtkkCEKBBBC

happens mostly after i use elemental blast or have to use elemental blast ( it will not only not show elemental blast but also other abilities will not be shown)

**Comment by Cilraaz** [comment]
Did you enable lua errors? What error do you receive when the icon disappears?

**Comment by cantthinkofaname69** [comment]
Message: Interface/AddOns/HeroRotation_Shaman/Enhancement.lua:146: attempt to index global 'Shaman' (a nil value)
Time: Sat Nov 11 21:57:18 2023
Count: 64
Stack: Interface/AddOns/HeroRotation_Shaman/Enhancement.lua:146: attempt to index global 'Shaman' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroRotation_Shaman/Enhancement.lua"]:146: in function <Interface/AddOns/HeroRotation_Shaman/Enhancement.lua:136>
[string "@Interface/AddOns/HeroRotation_Shaman/Enhancement.lua"]:683: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:456: in function <Interface/AddOns/HeroRotation/Main.lua:434>

Locals: (*temporary) = <function> defined =[C]:-1

------------------------------------

It´s a issue with Elemental Blast when i swapped away from it everything was fine

**Comment by Cilraaz** [comment]
I have no idea why that didn't generate errors for me. It really should have. In any case, it's fixed in commit https://github.com/herotc/hero-rotation/commit/b22b184de782a65669f702b876c63b3e33c506ea

You can either pull an updated Enhancement.lua file from the github or add a line after line 70.

Line 70: local Everyone = HR.Commons.Everyone
New Line: local Shaman = HR.Commons.Shaman

It'll also be included in future version 10.2.0.08.
