### ISSUE TITLE
Pet icon is shown.

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#1001]
### What version of HeroRotation are you using?

10.2.0.08

### What version of HeroLib are you using?

10.2.0.01

### What version of HeroDBC are you using?

10.2.0.02

### What is the issue?

Hello

The pet symbol is shown to me in the rotation even though my pet is called.

thx 

![Screenshot (132)](https://github.com/herotc/hero-rotation/assets/43277089/171e814f-e7bf-42c4-99a4-228d553cfb53)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
What class?
What spec?
Describe the situation before this occurred. What series of actions had you taken?

**Comment by cyberbook78** [comment]
oh sorry.

Hunter - Survival

**Comment by Cilraaz** [comment]
I can't replicate the issue. I'm going to need more information surrounding the situation. What were you doing when this occurred? Had you recently changed specs? Had you recently entered a Mythic+ key? Had you recently cast Play Dead?

**Comment by cyberbook78** [comment]
I start the game. My character is in the city and I see the icon. Or I flew and after dismounting, even though my animal is called, see picture he shows me the symbol

**Comment by Cilraaz** [comment]
I can't replicate this in any way. Logging out and back in with a pet active shows me no Summon Pet suggestion, nor does dragonriding or taking a flight point. In game, please type `/hr debug` and provide the chat output. In addition, please type `/dump HeroRotation.Commons.Hunter` and provide the output of that command as well.

**Comment by cyberbook78** [comment]
this comes.

[1]={
  pet={
    GUID=0
    SummonSpells={
        [1]=883,
        [2]=83242,
        [3]=83243,
        [4]=83244,
        [5]=53245
        [6]=982
    },
    FeignGUID=0
    Status=0
  }
}

**Comment by Cilraaz** [comment]
If you dismiss and re-summon your pet, does the icon go away? Does it come back at any point?

**Comment by cyberbook78** [comment]
yes

**Comment by Cilraaz** [comment]
Yes to which question?

**Comment by cyberbook78** [comment]
> If you dismiss and re-summon your pet, does the icon go away? Does it come back at any point?

yes to this

**Comment by Cilraaz** [comment]
That's two questions...

**Comment by cyberbook78** [comment]
yes to both :)

**Comment by Cilraaz** [comment]
So, if re-summoning makes it go away, what series of actions causes it to come back?

**Comment by cyberbook78** [comment]
I don't know. Sometimes after loading directly from the screen or when I've landed

**Comment by Cilraaz** [comment]
Can't replicate. Dismissing and re-summoning the pet resets the variables used in determining if a pet is currently summoned.  You may have another addon interfering or other local configuration issue. Additionally, `/hr debug` output was not provided.
