### ISSUE TITLE
[Bug]: Feral Druid Error

### ISSUE THREAD

**Issue by KTom71** [herotc/hero-rotation#1002]
### What version of HeroRotation are you using?

10.2.0.14

### What version of HeroLib are you using?

10.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

LUA Error on Line 660.
```
    if I.MydasTalilsman:IsEquippedAndReady() then
      if Cast(I.MydasTalilsman, nil, Settings.Commons.DisplayStyle.Trinkets) then return "mydas_talisman cooldown 30"; end
    end
```
MydasTalilsman makes the mistake.
I think it should be called MydasTalisman.
```
    if I.MydasTalisman:IsEquippedAndReady() then
      if Cast(I.MydasTalisman, nil, Settings.Commons.DisplayStyle.Trinkets) then return "mydas_talisman cooldown 30"; end
    end
```

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/c2ada60eb3f4f7ac4be1979ee96aae44741b4b7f
