### ISSUE TITLE
[Bug]: Enhancment shaman Rotation

### ISSUE THREAD

**Issue by heilporsche** [herotc/hero-rotation#1003]
### What version of HeroRotation are you using?

10.2.0.15

### What version of HeroLib are you using?

10.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

enhancement shaman AoE rotation constantly says to WAIT for pool  single target works fine

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Issue began with Blizzard's protection of the IsItemInRange function. This is having an impact to the entire addon. Closing this for now until a solution is found or Blizzard un-protects IsItemInRange.
