### ISSUE TITLE
[Bug]: bm hunter after 11/16 patch

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1004]
### What version of HeroRotation are you using?

10.2.0.14

### What version of HeroLib are you using?

10.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

With aoe mode on, when the pet is fighting near multiple mobs, it gets stuck on kill command being dark/red. If you turn off aoe mode, it gets unstuck and continues the rotation. If you fight a single mob, it doesn't get stuck regardless of whether aoe mode is on.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
The entire addon is currently broken due to Blizzard API changes. We're currently working on a fix.
