### ISSUE TITLE
Enhancement Shaman not working 

### ISSUE THREAD

**Issue by Vyper222** [herotc/hero-rotation#1005]
### What version of HeroRotation are you using?

10.2.0.14

### What version of HeroLib are you using?

10.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

Was working fine yesterday, now all it shows is the 'pool' icon as soon as I enter combat and never changes to any kind of cast suggestion. 

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
CurseForge's version is out of date. Current versions are:
- HeroRotation 10.2.0.16
- HeroLib 10.2.0.5
