### ISSUE TITLE
[Bug]: Many feral druid errors

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1006]
### What version of HeroRotation are you using?

10.2.0.16

### What version of HeroLib are you using?

10.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

387x HeroRotation_Druid/Feral.lua:666: attempt to index field 'FyrakksTaintedRageheart' (a nil value)
[string "@HeroRotation_Druid/Feral.lua"]:666: in function <HeroRotation_Druid/Feral.lua:591>
[string "@HeroRotation_Druid/Feral.lua"]:765: in function `?'
[string "@HeroRotation/Main.lua"]:456: in function <HeroRotation/Main.lua:434>

Locals:
HighTTD = 0
_ = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = <table> {
 ItemName = "Bandolier of Twisted Blades"
 ItemSlotIDs = <table> {
 }
 ItemRarity = 4
 ItemMinLevel = 70
 ItemID = 207165
 ItemUseSpell = <table> {
 }
 ItemLevel = 441
 LastDisplayTime = 0
 LastHitTime = 0
}
(*temporary) = <table> {
 1 = 13
 2 = 14
}
(*temporary) = 207165
(*temporary) = <table> {
 IsEquipped = false
}
(*temporary) = false
(*temporary) = <table> {
 1 = 207606
 2 = 209356
 3 = 210364
 5 = 204760
 6 = 204399
 7 = 202514
 8 = 204782
 9 = 191996
 10 = 209403
 11 = 209358
 12 = 209367
 13 = 193477
 14 = 204736
 15 = 209414
 16 = 209376
}
(*temporary) = 2
(*temporary) = 2
(*temporary) = "attempt to index field 'FyrakksTaintedRageheart' (a nil value)"
Settings = <table> {
 Feral = <table> {
 }
 Commons = <table> {
 }
 General = <table> {
 }
}
I = <table> {
 BandolierofTwistedBlades = <table> {
 }
 MydasTalisman = <table> {
 }
 BeacontotheBeyond = <table> {
 }
 SpoilsofNeltharus = <table> {
 }
 AshesoftheEmbersoul = <table> {
 }
 IrideusFragment = <table> {
 }
 MirrorofFracturedTomorrows = <table> {
 }
 Djaruun = <table> {
 }
 ManicGrieftorch = <table> {
 }
 Jotungeirr = <table> {
 }
 AlgetharPuzzleBox = <table> {
 }
 WitherbarksBranch = <table> {
 }
}
FightRemains = 20.094425
VarAlign3Mins = false
Cast = <function> defined @HeroRotation/Core.lua:152
BsInc = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Berserk"
 IsMelee = true
 SpellType = "Player"
 MaximumRange = 0
 MinimumRange = 0
 LastDisplayTime = 27111.632000
 SpellID = 106951
}
VarLastZerk = false
VarLastConvoke = false
S = <table> {
 FrenziedRegenerationBuff = <table> {
 }
 MightyBash = <table> {
 }
 LIMoonfire = <table> {
 }
 SouloftheForest = <table> {
 }
 RakeDebuff = <table> {
 }
 AdaptiveSwarm = <table> {
 }
 Sabertooth = <table> {
 }
 FranticMomentum = <table> {
 }
 RipandTear = <table> {
 }
 Starfire = <table> {
 }
 Predator = <table> {
 }
 HeartoftheWild = <table> {
 }
 MoonfireDebuff = <table> {
 }
 Thrash = <table> {
 }
 SmolderingFrenzyBuff = <table> {
 }
 CatForm = <table> {
 }
 PredatorRevealedBuff = <table> {
 }
 NaturesVigil = <table> {
 }
 AdaptiveSwarmHeal = <table> {
 }
 WildCharge = <table> {
 }
 AdaptiveSwarmDebuff = <table> {
 }
 RipDebuff = <table> {
 }
 HeartoftheWildBuff = <table> {
 }
 Rake = <table> {
 }
 Rip = <table> {
 }
 MarkoftheWild = <table> {
 }
 Berserk = <table> {
 }
 Starsurge = <table> {
 }
 BrutalSlash = <table> {
 }
 ConvoketheSpirits = <table> {
 }
 IronfurBuff = <table> {
 }
 Sunfire = <table> {
 }
 DoubleClawedRake = <table> {
 }
 ProtectorofthePack = <table> {
 }
 LIMoonfireDebuff = <table> {
 }
 MarkoftheWildBuff = <table> {
 }
 LionsStrength = <table> {
 }
 RampantFerocity = <table> {
 }
 UnbridledSwarm = <table> {
 }
 AshamanesGuidance = <table> {
 }
 Shred = <table> {
 }
 Clearcasting = <table> {
 }
 ApexPredatorsCraving = <table> {
 }
 PrimalWrath = <table> {
 }
 DireFixationDebuff = <table> {
 }
 TigersFury = <table> {
 }
 MoonkinForm = <table> {
 }
 PredatorySwiftnessBuff = <table> {
 }
 BerserkHeartoftheLion = <table> {
 }
 TearOpenWounds = <table> {
 }
 SabertoothBuff = <table> {
 }
 ThrashingClaws = <table> {
 }
 SurvivalInstincts = <table> {
 }
 Prowl = <table> {
 }
 PoPHealBuff = <table> {
 }
 FrenziedRegeneration = <table> {
 }
 SkullBash = <table> {
 }
 DireFixation = <table> {
 }
 BearForm = <table> {
 }
 Swipe = <table> {
 }
 ThrashDebuff = <table> {
 }
 SuddenAmbushBuff = <table> {
 }
 Incarnation = <table> {
 }
 Pool = <table> {
 }
 OverflowingPowerBuff = <table> {
 }
 ApexPredatorsCravingBuff = <table> {
 }
 BloodtalonsBuff = <table> {
 }
 LunarInspiration = <table> {
 }
 Bloodtalons = <table> {
 }
 WildSlashes = <table> {
 }
 MomentofClarity = <table> {
 }
 CircleofLifeandDeath = <table> {
 }
 SunfireDebuff = <table> {
 }
 Ironfur = <table> {
 }
 Moonfire = <table> {
 }
 FeralFrenzy = <table> {
 }
 Renewal = <table> {
 }
 Regrowth = <table> {
 }
 Maim = <table> {
 }
 Berserking = <table> {
 }
 Shadow

Errors started popping up today. 

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
Fixed in release version 10.2.0.17, which should (hopefully) be on CurseForge or wherever you update your addons soon.

**Comment by Profoundsoup** [comment]
Thank you. Been using your guys addon for awhile. I appreciate your work.
