### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SAB3RX** [herotc/hero-rotation#1007]
### What version of HeroRotation are you using?

10.2.0.17

### What version of HeroLib are you using?

10.0.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

Feral is acting weird now just keeps saying pool or not showing icons at all. u disable aoe and cds and get some functionality back.

### Icon Behavior

N/A

**Comment by GuthenTV** [comment]
I have the same problem, just as described above, only works two spells in, and instantly disappears and rarely showing only Tigers Fury or a Ultimate Power potion of your lucky. Same happens when i use Whiterbarks Branch, it crashes instant after use.

In addons menu it shows a error sign in HeroLib that says addon interface errors are ongoing too.

**Comment by Mehdi718** [comment]
i have the same problem with shaman :( 
![Uploading Untitled.png…]()
just showing pool

**Comment by ChrisPi14** [comment]
You can thank Blizzard for that. Yesterday - without a warning - they blocked access to 2 range check functions that were used by addons like HeroRotation, ElvUI, Plater and many more to check things like how far enemies are away from you or how many enemies you are up against (e.g. to recommend if you should use single target or AoE abilities). People are working on new solutions but until then things will not work properly or be at least quite wonky. But there was an update for this addon 4 hours ago so maybe things are already looking better now.

**Comment by Cilraaz** [comment]
Current versions of the addon are:
- HeroRotation: 10.2.0.17
- HeroLib: 10.2.0.05
- HeroDBC: 10.2.0.03

There are several fixes since your version of HeroLib that should fix your issue. Unfortunately, CurseForge was being weird yesterday and wasn't pulling our updates. At this time, it looks like the above versions are now (finally) on CurseForge. Please update to the latest and see if you still have the issue. From a quick test, the current versions appear to be working fine.

**Comment by SAB3RX** [comment]
Can confirm it's fixed for me.

**Comment by GuthenTV** [comment]
Nope this didnt fix the trinket problem for me..

**Comment by Cilraaz** [comment]
You'll need to be more specific. Your previous comment also mentioned lua errors. I'd need those errors to be able to fix the problem.

**Comment by GuthenTV** [comment]
which console command is it to check?

**Comment by Cilraaz** [comment]
`/console scriptErrors 1` will enable lua errors. You can later use `/console scriptErrors 0` to disable them.

**Comment by GuthenTV** [comment]
do i need a addon for that?

**Comment by Cilraaz** [comment]
No. That's built into the game itself.

**Comment by GuthenTV** [comment]
so just type /console scriptErrors 1 in chat?

**Comment by Cilraaz** [comment]
Yes

**Comment by GuthenTV** [comment]
and where do i find them? nothing pops up

**Comment by Cilraaz** [comment]
After running that command, any lua error that occurs will show in a pop-up. So you'd need to use the addon until an error occurs.

**Comment by GuthenTV** [comment]
im so sorry for being dumb here..

**Comment by GuthenTV** [comment]
just gonna kill a mob fast

**Comment by GuthenTV** [comment]
Message: Interface/AddOns/HeroRotation_Druid/Feral.lua:659: attempt to index global 'WitherbarksBranch' (a nil value)
Time: Fri Nov 17 15:44:29 2023
Count: 76
Stack: Interface/AddOns/HeroRotation_Druid/Feral.lua:659: attempt to index global 'WitherbarksBranch' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:152: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:150>
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroRotation_Druid/Feral.lua"]:659: in function <Interface/AddOns/HeroRotation_Druid/Feral.lua:591>
[string "@Interface/AddOns/HeroRotation_Druid/Feral.lua"]:766: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:456: in function <Interface/AddOns/HeroRotation/Main.lua:434>

Locals:

**Comment by GuthenTV** [comment]
https://www.wowhead.com/guide/classes/druid/feral/bis-gear bis trinket, thats why im so sad that it doesnt work

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/e3d84a18d16d1ce6781612756dfc15f2d3a2d984

**Comment by GuthenTV** [comment]
so its fixed now?

**Comment by Cilraaz** [comment]
If you grab the updated files from the github, yes. Otherwise, it'll be included in the next release version when 10.2.0.18 is released shortly.

**Comment by GuthenTV** [comment]
okay! so i just grab the feral.lua then?

**Comment by Cilraaz** [comment]
Yep. That should work.

**Comment by GuthenTV** [comment]
you are the man, thank you so much!!
