### ISSUE TITLE
[Bug]: Lua errors and "No Rotation Found" Dev Evoker 

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1009]
### What version of HeroRotation are you using?

10.2.0.17

### What version of HeroLib are you using?

10.2.0.03

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

6x HeroRotation_Evoker/Devastation.lua:1 HeroRotation_Evoker/Devastation.lua:186: ')' expected near 'then'

Rotation will not load and Lua errors are popping up

Thank you

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/13c033f229071cdca302910845047304100a8d4e

Also, if your HeroLib version isn't a typo, please be sure to update to 10.2.0.05. Blizzard broke a lot of things yesterday that have been fixed since 10.2.0.03 was released.

**Comment by Profoundsoup** [comment]
Thanks for the heads up. Yeah I noticed that. Went ahead and updated everything. Appreciate the response and work.
