### ISSUE TITLE
[Bug]: Errors on Elemental Shaman and Enhance shaman

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1010]
### What version of HeroRotation are you using?

10.2.0.18

### What version of HeroLib are you using?

10.2.0.05

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

213x HeroRotation/Core.lua:47: attempt to index local 'Object' (a nil value)
[string "@HeroRotation/Core.lua"]:47: in function `GetTexture'
[string "@HeroRotation/Core.lua"]:153: in function <HeroRotation/Core.lua:152>
[string "@HeroRotation_Mage/Frost.lua"]:342: in function <HeroRotation_Mage/Frost.lua:306>
[string "@HeroRotation_Mage/Frost.lua"]:476: in function `?'
[string "@HeroRotation/Main.lua"]:456: in function <HeroRotation/Main.lua:434>

Locals:
Object = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Object' (a nil value)"
Cache = <table> {
 GUIDInfo = <table> {
 }
 Set = <function> defined @HeroCache/Main.lua:271
 APLVar = <table> {
 }
 Enemies = <table> {
 }
 Get = <function> defined @HeroCache/Main.lua:255
 HasBeenReset = true
 SpellInfo = <table> {
 }
 UnitInfo = <table> {
 }
 MiscInfo = <table> {
 }
 Persistent = <table> {
 }
 ItemInfo = <table> {
 }
 Reset = <function> defined @HeroCache/Main.lua:44
}
tostring = <function> defined =[C]:-1

Getting this error when selecting target while speced as elemental.

"Pool" icon is showing permanently on enhance shaman after putting on weapon buffs. No Lua error. 

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
You've posted a lua error referencing Frost Mage. You're getting this while playing Shaman? I can't replicate this error. There was a typo on the line referenced in your lua error, but that was fixed as of 10.2.0.15.

**Comment by Profoundsoup** [comment]
Sorry you are right. Not sure why that was in the bug sack. It was an error from before you fixed it. My mistake.

**Comment by Cilraaz** [comment]
Please let me know if you are still having issues with HeroRotation version 10.2.0.20 and HeroLib version 10.2.0.06.
