### ISSUE TITLE
[Bug]: [Fury] Shows "Pool" most of the time

### ISSUE THREAD

**Issue by chrissismoove** [herotc/hero-rotation#1011]
### What version of HeroRotation are you using?

10.2.0.19

### What version of HeroLib are you using?

10.2.0.05

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

While using it for the new fury annihilator build it shows "pool" most of the times, when the specc doesnt pool at all

### Icon Behavior

None

**Comment by Cilraaz** [comment]
I'm unable to replicate this issue. Can you please provide your talent build export string? Also, I will be releasing new versions of HeroRotation and HeroLib shortly. You may wish to try those versions.

**Comment by Scavindari** [comment]
For me this error seems to only really pop up on Boss Classification mobs and I tend to have to stand directly under the mob to get the pooling icon to finally start showing my rotation...works fine on normal mobs for me. has been working on and off for me since I got 2p tier 31 and switched to the new build.

**Comment by Cilraaz** [comment]
If you're not within 5 yards of the target (or if you have your nameplates disabled), melee targets will not be counted properly, potentially causing the issue you are seeing. I've added a bit of a buffer, forcing a minimum target count of 1, to hopefully alleviate this issue. This was added in HeroRotation version 10.2.0.31. If you are still having issues, it may be something that has to wait until Blizzard opens IsItemInRange during combat. They've stated they will do so, but gave no time frame.

**Comment by Cilraaz** [comment]
Is this issue resolved since the range system update in HeroLib version 10.2.0.20 (released Dec 5)?

**Comment by Scavindari** [comment]
For the most part, some huge mobs you have to be standing under for it to
work but it's mostly just trash mobs no bosses

**Comment by Cilraaz** [comment]
I've noticed it on the fire giants in Amirdrassil while playing my VDH. I think it's a bug on Blizzard's side, or at least it's one I haven't been able to nail down yet.

I'm going to go ahead and close this issue. If the issue pops back up or the issue around huge mobs becomes a problem, please feel free to post again and I can re-open it.

**Comment by Scavindari** [comment]
Will do and thanks for reaching out, have a great holiday

**Comment by Cilraaz** [comment]
You as well!
