### ISSUE TITLE
[Bug]: Survival hunter rotational bugs. Butchery not showing up in AOE situations and being asked to "pool" even at 100 focus. 

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1012]
### What version of HeroRotation are you using?

10.2.0.19

### What version of HeroLib are you using?

10.2.0.05

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

Currently butchery is not being shown to be used in AOE. 

Commonly the addon will say to "pool" even when at 100 focus. 

### Icon Behavior

None

**Comment by Cilraaz** [comment]
This is fixed in a HeroLib update. Commit https://github.com/herotc/hero-lib/commit/9da6641cefb89e3fced236f10e32dad1a63551b6

If you don't want to update from github, it will be included in the 10.2.0.06 release of HeroLib, which will be released soon.
