### ISSUE TITLE
[Bug]: Brewmaster Monk melee abilities show out of range coloring

### ISSUE THREAD

**Issue by Splitix** [herotc/hero-rotation#1013]
### What version of HeroRotation are you using?

10.2.0.20

### What version of HeroLib are you using?

10.2.0.06

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

Brewmaster melee abilities (e.g. Blackout Kick, Rising Sun Kick, Breath of Fire) show a red tint like I'm out of range, even though i'm in melee range. I switched to windwalker and I don't have this issue. 

The Brewmaster range abilities (e.g. Keg Smash, Chi Wave) show the normal colored icon. 

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
I'm unable to replicate this issue. Can you please provide your talent build export string? Perhaps it's related to your specific selection of talents.

**Comment by Splitix** [comment]
Yeah, after some more testing. It looks like it happens when I use the choice talent "Press the Advantage" But if I switch it to "Weapons of Order" the addon works as expected

**Comment by Splitix** [comment]
Talent Export with the Issue: BwQAPOfh8E5EV1u1/5sg+UnhAAAAAAAASAAAAgUiSLJJQSSrRAAAASLUSiEJUKkkSSSJBcAFJSLtSIA

**Comment by Cilraaz** [comment]
Ah, that was it. We were using Tiger Palm for the 5y range checking, but PTA replaces it. I've added Blackout Kick as a backup range checking spell. This is effective as of HeroLib commit https://github.com/herotc/hero-lib/commit/991088c41c8c5a1e99d75175504a028bdd997a69

I'll be pushing new versions of HeroRotation (will be 10.2.0.21) and HeroLib (will be 10.2.0.07) shortly. They will include the fix.
