### ISSUE TITLE
[Enhancement]: [Rogue] CheckWillWasteCooldown founction

### ISSUE THREAD

**Issue by mizone** [herotc/hero-rotation#1014]
### What feature would you like to have added?

Hi,

I see you keep the function CheckWillWasteCooldown in Assassination Profile [line 308 to 321]. Please active this function in Assassination and Outlaw profile. It is realy usefull when do Mythic +. Just want to keep Cooldowns for next big pull, thus will increase the DPS huge. 

Best regards.

**Comment by Seny951** [comment]
function no longer exists but I do work these checks into the profiles in other way where applicable
