### ISSUE TITLE
[Bug]: (In aoe only} shows Wild charge, rake, then it only shows pool for the rest of combat, no matter my energy level.

### ISSUE THREAD

**Issue by KingKlauswow** [herotc/hero-rotation#1015]
### What version of HeroRotation are you using?

10.2.0.21

### What version of HeroLib are you using?

10.2.0.07

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

At combat start it shows Wild charge, rake, then it only shows pool for the rest of combat, no matter my energy level. This only happenes in aoe, not in single target.

Talents: BcGAORarfDaLt4uMx8TYOtl8GAAAAAAASk0STCSSSSJtDgSSkIJAAAAAAKAkIBAkkkkIJUSol4AAAAAAAIBAA

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Unable to replicate the issue. With the talents specified by you, on the 5 Cleave Training Dummies in Valdrakken, the rotation works as expected.

**Comment by KingKlauswow** [comment]
whats weird about it is it worked fine at first and this problem just appeared. Ive tried reloading and relogging and it hasnt worked. will update if it just spontaneously starts working again

**Comment by KingKlauswow** [comment]
So it fixed itself for about an hour and now it is doing it again. I have no idea what is causing it

**Comment by KingKlauswow** [comment]
i figured it out, it happens when i turn enemy nameplates off

**Comment by Cilraaz** [comment]
Ah, yes. Nameplates are required for the addon to operate properly.
