### ISSUE TITLE
[Bug]: Outlaw Rogue - Roll The Bones not showing as OffGCD

### ISSUE THREAD

**Issue by Exsol-bit** [herotc/hero-rotation#1016]
### What version of HeroRotation are you using?

10.2.0.21

### What version of HeroLib are you using?

10.2.0.07

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

RollTheBones only shows on main icon, even when toggled to GCDasOffGCD.

On the off chance this helps locate the issue I've noticed during out of combat/opener Blade Flurry, Adrenaline Rush, RTB and Slice are all shown as main icon, once in combat all other abilities except Roll The Bones move to OffGCD correctly.

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
Roll the Bones does not have an OffGCD option currently. I can add one, if it could be useful, though.

**Comment by NStrategy** [comment]
> Roll the Bones does not have an OffGCD option currently. I can add one, if it could be useful, though.

My guess is that he is using the settings.lua from my fork :D But I guess having it in the offical version wouldnt hurt.

Edit: Just saw that I deleted that settings line in my lasted update, so he is probably using my lua as well. Sorry for the inconvenience.

**Comment by Exsol-bit** [comment]
> > Roll the Bones does not have an OffGCD option currently. I can add one, if it could be useful, though.
> 
> My guess is that he is using the settings.lua from my fork :D But I guess having it in the offical version wouldnt hurt.
> 
> Edit: Just saw that I deleted that settings line in my lasted update, so he is probably using my lua as well. Sorry for the inconvenience.

I definitely was/am. 

I did a fresh download of the offical branch off GitHub and tested it prior to submitting the bug report just in case it was a local issue to your fork (thank you BTW for making it). Unless I didn’t overwrite the setting file when I copied across - apologies.

**Comment by NStrategy** [comment]
Happens, I did make a fix now, should be working again (besides in the opener, I kept it as a main icon there). This issue can probably be closed.

**Comment by Cilraaz** [comment]
I added an OffGCD option for Roll the Bones in commit https://github.com/herotc/hero-rotation/commit/bdb88232527c9267d4857631237ff191782d9c68
