### ISSUE TITLE
[Bug]: Spellflash not working

### ISSUE THREAD

**Issue by orbital253** [herotc/hero-rotation#1017]
### What version of HeroRotation are you using?

10.20.0.26

### What version of HeroLib are you using?

10.20.0.14

### What version of HeroDBC are you using?

10.20.0.03

### What is the issue?

I tried using enabling spellflash with /hr flash but it doesnt see work. i tried it without ElvUIand with ElvUI. I can't make it to to flash on the abilities on my action bars

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
And you've installed the SpellFlashCore addon?

**Comment by orbital253** [comment]
It seems i haven't. I though it was for version 8.0.1 for game. I should have tried it before opening a bug

**Comment by Cilraaz** [comment]
We didn't add internal support for spell flashing, unfortunately. Only support for that addon at a user's request. To my knowledge, it's still working, but if not, please let us know.
