### ISSUE TITLE
[Bug]: VDH gets stuck on soul_cleave maintenance 20 sometimes

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1018]
### What version of HeroRotation are you using?

10.2.0.26

### What version of HeroLib are you using?

10.2.0.14

### What version of HeroDBC are you using?

10.2.0.03

### What is the issue?

After some time, it seems it gets stuck on recommending soul cleave with a dimmed/darker icon. The debug message is
**soul_cleave maintenance 20**. I am not sure what triggers it; it usually happens after some minutes of working normally. Reloading the UI gets it back to working until the next random time it gets stuck.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
I ran 4 minutes on a solo dummy and 4 minutes on AoE dummies. I wasn't able to replicate the issue in either scenario. Please provide your talent build export string so I can do more 1-to-1 testing. Also, does this occur in single target or AoE situations?

**Comment by lab1702** [comment]
BUkAzqt9tQbK6xteCyjwasgfTCAiIRiIBJJBhEtkIJaJSkIBJplk0kESIBAAAAkISA

Also, I have not ben able to replicate with dummies, only seen it while out in the world.
Just now it happened after using infernal strike.

**Comment by lab1702** [comment]
It can get stuck during either st or aoe for me.

**Comment by lab1702** [comment]
After the latest HeroLib update I can't get this to fail anymore, I'm thinking maybe it was something in the range checking since the soul cleave icon got stuck with that out of range coloring? Not sure here as I've not read the HeroLib code before, but was a thought that popped in my mind.

**Comment by Cilraaz** [comment]
It's possible that previous range checking problems caused an issue with target counts that led to the issue you were seeing. Glad to hear it doesn't get stuck any more though!
