### ISSUE TITLE
[Bug]: Hunter suggested summon pet with pets up

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1021]
### What version of HeroRotation are you using?

10.2.0.31

### What version of HeroLib are you using?

10.2.0.17

### What version of HeroDBC are you using?

10.2.0.04

### What is the issue?

Hunter module will suggest pet summon with pets up.

Tested in valdrakken, to recreate:
1. Summon pets
2. Get on mount
3. Log out
4. Log in
5. Dismount

Pets reappear, but pet summons still suggested until you dismiss and resummon.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/b27181a89ed2527570abcaabb9ae7dd3c9e56614
