### ISSUE TITLE
[Enhancement]: [Rogue] Add OffGCD Option for Stealth

### ISSUE THREAD

**Issue by mhunk** [herotc/hero-rotation#1024]
### What feature would you like to have added?

add stealth to the OffGCD options list for rogue both as a QOL item but to also counter shadowmeld dropping combat in dungeons and forcing the stealth recommendation over the finisher "up next"

**Comment by Cilraaz** [comment]
I've added a DisplayStyle setting for Stealth in commit https://github.com/herotc/hero-rotation/commit/e332a05b2b9b0e75e63c71711fddaf34b0a32a5d

This will allow you to place the suggestion for Stealth in the main icon, OffGCD/cooldown icon, suggested icon, or suggested right icon.
