### ISSUE TITLE
[Bug]: [Enhancement] Earth Shield suggestion always shown when Elemental Orbit is talented

### ISSUE THREAD

**Issue by nechyu** [herotc/hero-rotation#1026]
### What feature would you like to have added?

Take the talents BcQAAAAAAAAAAAAAAAAAAAAAAIJJpEJgkESSSDlEAAAAAAAAAAAAAKRIJkgmAJtkkSAKBJSgA
and if Elemental Orbit is selected in the talents, there will always be a recommendation to use Earth Shield and recommendations beyond rotation will not work. It will always show only Earth Shield

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/507f091a67b6b97c60e3381afd7ba290703a00d8
