### ISSUE TITLE
[Bug]: Mindgames lua error on shadow priest 

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1028]
### What version of HeroRotation are you using?

10.2.0.36

### What version of HeroLib are you using?

10.2.0.21

### What version of HeroDBC are you using?

10.2.0.06

### What is the issue?

304x HeroRotation/Commons.lua:103: attempt to call local 'TargetIfCondition' (a nil value)
[string "@HeroRotation/Commons.lua"]:103: in function `CastTargetIf'
[string "@HeroRotation_Priest/Shadow.lua"]:507: in function <HeroRotation_Priest/Shadow.lua:488>
[string "@HeroRotation_Priest/Shadow.lua"]:701: in function <HeroRotation_Priest/Shadow.lua:633>
[string "@HeroRotation_Priest/Shadow.lua"]:766: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
Object = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Mindgames"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 375901
}
Enemies = <table> {
 1 = <table> {
 }
}
TargetIfMode = "max"
TargetIfCondition = nil
Condition = nil
OutofRange = false
OffGCD = nil
DisplayStyle = "Suggested"
TargetCondition = true
BestUnit = nil
BestConditionValue = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
CycleUnit = <table> {
 UnitExists = true
 UnitNPCID = 209574
 UnitGUID = "Creature-0-4217-2548-8940-209574-0000735226"
 UnitID = "Nameplate2"
 UseCache = true
 UnitCanBeAttacked = true
 UnitName = "Aurostor"
}
(*temporary) = <table> {
 UnitExists = true
 UnitNPCID = 209574
 UnitGUID = "Creature-0-4217-2548-8940-209574-0000735226"
 UnitID = "Nameplate2"
 UseCache = true
 UnitCanBeAttacked = true
 UnitName = "Aurostor"
}
(*temporary) = nil
(*temporary) = <table> {
 UnitExists = true
 UnitNPCID = 209574
 UnitGUID = "Creature-0-4217-2548-8940-209574-0000735226"
 UnitID = "Nameplate2"
 UseCache = true
 UnitCanBeAttacked = true
 UnitName = "Aurostor"
}
(*temporary) = "attempt to call local 'TargetIfCondition' (a nil value)"
Target = <table> {
 UnitExists = true
 UnitName = "Aurostor"
 UnitNPCID = 209574
 UnitGUID = "Creature-0-4217-2548-8940-209574-0000735226"
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
}
AoEON = <function> defined @HeroRotation/Core.lua:418
Cast = <function> defined @HeroRotation/Core.lua:152
pairs = <function> defined =[C]:-1
Utils = <table> {
 FindValueIndexInArray = <function> defined @HeroLib/Utils.lua:58
 SubStringCount = <function> defined @HeroLib/Utils.lua:113
 MergeTableByKey = <function> defined @HeroLib/Utils.lua:80
 SortMixedASC = <function> defined @HeroLib/Utils.lua:151
 ValueIsInArray = <function> defined @HeroLib/Utils.lua:47
 EndsWith = <function> defined @HeroLib/Utils.lua:127
 BoolToInt = <function> defined @HeroLib/Utils.lua:24
 RevertTableIndex = <function> defined @HeroLib/Utils.lua:132
 StringToNumberIfPossible = <function> defined @HeroLib/Utils.lua:107
 SortDESC = <function> defined @HeroLib/Utils.lua:146
 ShortenHotKey = <function> defined @HeroLib/Utils.lua:161
 IntToBool = <function> defined @HeroLib/Utils.lua:28
 StartsWith = <function> defined @HeroLib/Utils.lua:123
 UpperCaseFirst = <function> defined @HeroLib/Utils.lua:33
 SortASC = <function> defined @HeroLib/Utils.lua:141
 MergeTable = <function> defined @HeroLib/Utils.lua:68
 CompareThis = <function> defined @HeroLib/Utils.lua:101
 ValueIsInTable = <function> defined @HeroLib/Utils.lua:37
}
CastLeftNameplate = <function> defined @HeroRotation/Core.lua:263

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
This is now fixed in commit https://github.com/herotc/hero-rotation/commit/4358fcdf57ea3c25e95cbc9093f9bbbc6310abdf
