### ISSUE TITLE
[Bug]: Herolib Devouring Plague bug 

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1029]
### What version of HeroRotation are you using?

10.2.0.36

### What version of HeroLib are you using?

10.2.0.21

### What version of HeroDBC are you using?

10.2.0.06

### What is the issue?

21x HeroLib/Events/Aura.lua:146: You forgot to register the spell: Devouring Plague
[string "=[C]"]: in function `error'
[string "@HeroLib/Events/Aura.lua"]:146: in function `AuraActiveCount'
[string "@HeroRotation_Priest/Shadow.lua"]:574: in function <HeroRotation_Priest/Shadow.lua:554>
[string "@HeroRotation_Priest/Shadow.lua"]:762: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
(*temporary) = "You forgot to register the spell: Devouring Plague"

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
This is now fixed in commit https://github.com/herotc/hero-rotation/commit/4358fcdf57ea3c25e95cbc9093f9bbbc6310abdf
