### ISSUE TITLE
[Bug]: [SHADOW_PRIEST] the icon disappears during the "normal" dps cycle

### ISSUE THREAD

**Issue by Sparckx** [herotc/hero-rotation#1030]
### What version of HeroRotation are you using?

10.2.0.36

### What version of HeroLib are you using?

10.2.0.21

### What version of HeroDBC are you using?

10.2.0.06

### What is the issue?

Hello everyone, I'm taking the liberty of reporting this bug which has been going on for a few versions now. When I downgrade the verison I no longer have any problems (version ok = 10.2.0.32). Basically I have the impression that the bug comes from the shadow word death but I preferred to copy the entire message, do not hesitate to come back to me if I can do something more.

thank you for your help and have a nice day.

(message from BugSack)

3551x HeroRotation/Commons.lua:103: attempt to call local 'TargetIfCondition' (a nil value)
[string "@HeroRotation/Commons.lua"]:103: in function `CastTargetIf'
[string "@HeroRotation_Priest/Shadow.lua"]:579: in function <HeroRotation_Priest/Shadow.lua:554>
[string "@HeroRotation_Priest/Shadow.lua"]:762: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
Object = <table> {
 LastCastTime = 148094.105000
 LastHitTime = 148094.105000
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Shadow Word: Death"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 148102.516000
 SpellID = 32379
}
Enemies = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
}
TargetIfMode = "max"
TargetIfCondition = nil
Condition = nil
OutofRange = false
OffGCD = nil
DisplayStyle = nil
TargetCondition = true
BestUnit = nil
BestConditionValue = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
}
(for control) = 1
_ = 1
CycleUnit = <table> {
 UnitExists = true
 UnitNPCID = 39616
 UnitGUID = "Creature-0-3890-643-13561-39616-00026C80E8"
 UnitID = "Nameplate2"
 UseCache = true
 UnitName = "Naz'jar Invader"
 UnitCanBeAttacked = true
}
(*temporary) = <table> {
 UnitExists = true
 UnitNPCID = 39616
 UnitGUID = "Creature-0-3890-643-13561-39616-00026C80E8"
 UnitID = "Nameplate2"
 UseCache = true
 UnitName = "Naz'jar Invader"
 UnitCanBeAttacked = true
}
(*temporary) = nil
(*temporary) = <table> {
 UnitExists = true
 UnitNPCID = 39616
 UnitGUID = "Creature-0-3890-643-13561-39616-00026C80E8"
 UnitID = "Nameplate2"
 UseCache = true
 UnitName = "Naz'jar Invader"
 UnitCanBeAttacked = true
}
(*temporary) = "attempt to call local 'TargetIfCondition' (a nil value)"
Target = <table> {
 UnitCanBeAttacked = true
 UnitName = "Vicious Snap Dragon"
 UnitGUID = "Creature-0-3890-643-13561-212681-00056C80E8"
 UnitID = "target"
 UseCache = true
 UnitExists = true
 UnitNPCID = 212681
}
AoEON = <function> defined @HeroRotation/Core.lua:418
Cast = <function> defined @HeroRotation/Core.lua:152
pairs = <function> defined =[C]:-1
Utils = <table> {
 FindValueIndexInArray = <function> defined @HeroLib/Utils.lua:58
 SubStringCount = <function> defined @HeroLib/Utils.lua:113
 MergeTableByKey = <function> defined @HeroLib/Utils.lua:80
 SortMixedASC = <function> defined @HeroLib/Utils.lua:151
 ValueIsInArray = <function> defined @HeroLib/Utils.lua:47
 EndsWith = <function> defined @HeroLib/Utils.lua:127
 BoolToInt = <function> defined @HeroLib/Utils.lua:24
 RevertTableIndex = <function> defined @HeroLib/Utils.lua:132
 StringToNumberIfPossible = <function> defined @HeroLib/Utils.lua:107
 SortDESC = <function> defined @HeroLib/Utils.lua:146
 ShortenHotKey = <function> defined @HeroLib/Utils.lua:161
 IntToBool = <function> defined @HeroLib/Utils.lua:28
 StartsWith = <function> defined @HeroLib/Utils.lua:123
 UpperCaseFirst = <function> defined @HeroLib/Utils.lua:33
 SortASC = <function> defined @HeroLib/Utils.lua:141
 MergeTable = <function> defined @HeroLib/Utils.lua:68
 CompareThis = <function> defined @HeroLib/Utils.lua:101
 ValueIsInTable = <function> defined @HeroLib/Utils.lua:37
}
CastLeftNameplate = <function> defined @HeroRotation/Core.lua:263

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
Bug already fixed in commit https://github.com/herotc/hero-rotation/commit/4358fcdf57ea3c25e95cbc9093f9bbbc6310abdf
