### ISSUE TITLE
[Bug]: Error on BDK

### ISSUE THREAD

**Issue by nechyu** [herotc/hero-rotation#1031]
### What version of HeroRotation are you using?

10.2.0.36

### What version of HeroLib are you using?

10.2.0.21

### What version of HeroDBC are you using?

10.2.0.06

### What is the issue?

3x [ADDON_ACTION_BLOCKED] Модификация 'HeroLib' пыталась вызвать защищенную функцию 'IsItemInRange()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "@HeroLib/Class/Unit/Range.lua"]:156: in function <HeroLib/Class/Unit/Range.lua:135>
[string "=(tail call)"]: ?
[string "@HeroLib/Class/Unit/Player/Enemies.lua"]:40: in function <HeroLib/Class/Unit/Player/Enemies.lua:33>
[string "@HeroLib/Class/Unit/Player/Enemies.lua"]:116: in function `GetEnemiesInMeleeRange'
[string "@HeroRotation_Shaman/Enhancement.lua"]:546: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

### Icon Behavior

None

**Comment by Cilraaz** [comment]
It sounds like perhaps your region hasn't yet received the IsItemInRange hotfix, though I'm not sure why that would be. Downgrade HeroLib to version 10.2.0.19 as a temporary fix and then try the latest version again after the next server reset.
