### ISSUE TITLE
[Bug]: Outlaw using Ambush in Nonhidden Opportunity Build

### ISSUE THREAD

**Issue by GodsfavoritePerson** [herotc/hero-rotation#1032]
### What version of HeroRotation are you using?

10.2.0.36

### What version of HeroLib are you using?

10.2.0.21

### What version of HeroDBC are you using?

10.2.0.06

### What is the issue?

Hero Rotation is recommending Ambush in the Keep it Rolling/ Resounding Clarity mythic plus build; and according to the Outlaw FAQ: builds without HO do not press  Ambush because it does not proc  Fan the Hammer, and  Sinister Strike was changed to proc  Count the Odds so SS is always a better global.
Stealth by the dummy, use Roll the Bones, Adrenaline Rush, Slice and Dice, and then the first recommended attack will be Ghostly Strike. Use Ghostly Strike, immediately stop hitting the dummy till you're out of combat and then restealth. It shows Ambush as the recommendation for me. Just thought you might want to know. 

### Icon Behavior

None

**Comment by Seny951** [comment]
I can't reproduce this but I am fairly sure I updated HR to handle this awhile back.

here's what should happen:
The KiR build will vanish at full CPs into crackshot windows with BtE and the opener will open with Ghostly into Echoing Reprimand.

Can you provide your full talent build and / or a short video clip of it happening?

**Comment by Seny951** [comment]
found it - fix incoming
