### ISSUE TITLE
[Bug]:[Affliction Warlock] Errors

### ISSUE THREAD

**Issue by Joromonni** [herotc/hero-rotation#1035]
### What version of HeroRotation are you using?

10.2.0.41

### What version of HeroLib are you using?

10.2.0.21

### What version of HeroDBC are you using?

10.2.0.6

### What is the issue?

Errors during Affliction Warlock Gameplay

600x HeroRotation_Warlock/Affliction.lua:100: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@HeroRotation_Warlock/Affliction.lua"]:100: in function <HeroRotation_Warlock/Affliction.lua:96>
[string "@HeroRotation_Warlock/Affliction.lua"]:440: in function <HeroRotation_Warlock/Affliction.lua:401>
[string "@HeroRotation_Warlock/Affliction.lua"]:563: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
Skipped (In Encounter)

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/32bc75354f0618f95a2e77d4caf6ffc101f7ef30
