### ISSUE TITLE
[Bug]: HeroRotation disappeared on MoonGuard

### ISSUE THREAD

**Issue by Hadiroyo** [herotc/hero-rotation#1036]
### What version of HeroRotation are you using?

10.2.0.42.zip

### What version of HeroLib are you using?

10.2.0.21.zip

### What version of HeroDBC are you using?

10.2.0.06.zip

### What is the issue?

Hey, the HeroRotation does not show up on my toons from Moon Guard, so can you please fix this? Thank you

### Icon Behavior

None

**Comment by Cilraaz** [comment]
I would need more information.

What classes or specs are you having trouble with?
What, if any, message displays in your chat box upon loading the game?
What version of the three addons are you using (10.2.0 is _not_ a valid version number)?

**Comment by Hadiroyo** [comment]
Really? Where can I find the valid version number besides 10.2.0?

**Comment by Hadiroyo** [comment]
I edited it

**Comment by Hadiroyo** [comment]
> I would need more information.
> 
> What classes or specs are you having trouble with? What, if any, message displays in your chat box upon loading the game? What version of the three addons are you using (10.2.0 is _not_ a valid version number)?

I edited it

**Comment by Cilraaz** [comment]
Any answers to the other two questions?

**Comment by Hadiroyo** [comment]
What other two questions?

**Comment by Cilraaz** [comment]
> I would need more information.
> 
> What classes or specs are you having trouble with?
> What, if any, message displays in your chat box upon loading the game?
> What version of the three addons are you using (10.2.0 is _not_ a valid version number)?

There are three questions...

**Comment by Hadiroyo** [comment]
Well, HeroRotation addon does not show up on Moon Guard obviously, even though they're all enabled. It shows up on Wyrmrest Accord. It's just that Moon Guard doesn't have HeroRotation show up.

**Comment by Cilraaz** [comment]
Nothing in the addon would stop it from working on a specific retail server.

**Comment by Hadiroyo** [comment]
I checked my toons on Moon Guard, and I see no HeroRotation. And then I checked my toons on Wyrmrest Accord, and I see HeroRotation.

**Comment by Cilraaz** [comment]
I created a character on Moon Guard and it loads perfectly fine. Make sure all addons (as well as HeroRotation's sub-addons) are enabled. Also, ensure that nameplates are enabled.

You've also not answered the question about what message output HeroRotation puts in your chat box upon loading a character.

**Comment by Hadiroyo** [comment]
They WERE enabled

**Comment by Hadiroyo** [comment]
Do you want me to write down all of my Moon Guard toons' names?

**Comment by Cilraaz** [comment]
No. I've asked twice what output HeroRotation dumps to your chat box upon loading. Also, you can enable lua errors with `/console scriptErrors 1`, then reload your UI to see if it is generating any errors. You can later disable error popups with `/console scriptErrors 0`.

**Comment by Hadiroyo** [comment]
I'll check it out and let you know because I'm at work right now

**Comment by Hadiroyo** [comment]
Back, and how am I suppose to do that?

**Comment by Hadiroyo** [comment]
Message: Interface/AddOns/HeroRotation/Main.lua:200: attempt to call global 'LibStub' (a nil value)
Time: Tue Dec 19 23:30:02 2023
Count: 1
Stack: Interface/AddOns/HeroRotation/Main.lua:200: attempt to call global 'LibStub' (a nil value)
[string "@Interface/AddOns/HeroRotation/Main.lua"]:200: in function <Interface/AddOns/HeroRotation/Main.lua:188>

Locals: self = HeroRotation_MainFrame {
 0 = <userdata>
 Lock = <function> defined @Interface/AddOns/HeroRotation/Main.lua:143
 ResizeButtons = <function> defined @Interface/AddOns/HeroRotation/Main.lua:104
 ToggleLock = <function> defined @Interface/AddOns/HeroRotation/Main.lua:151
 Unlock = <function> defined @Interface/AddOns/HeroRotation/Main.lua:123
 ResizeUI = <function> defined @Interface/AddOns/HeroRotation/Main.lua:79
}
Event = "ADDON_LOADED"
Arg1 = "HeroRotation"
(*temporary) = nil
(*temporary) = "Masque"
(*temporary) = true
(*temporary) = "attempt to call global 'LibStub' (a nil value)"
MasqueFrameList = <table> {
 Top Icons = HeroRotation_SmallIconFrame {
 }
 Part Overlay = HeroRotation_MainIconPartOverlayFrame {
 }
 Main Icon = HeroRotation_MainIconFrame {
 }
 Right Suggested Icon = HeroRotation_RightSuggestedIconFrame {
 }
 Left Icon = HeroRotation_LeftIconFrame {
 }
 Suggested Icon = HeroRotation_SuggestedIconFrame {
 }
}
HR = <table> {
 CastPooling = <function> defined @Interface/AddOns/HeroRotation/Core.lua:193
 MaxQueuedCasts = 3
 CmdHandler = <function> defined @Interface/AddOns/HeroRotation/Core.lua:315
 PulseInit = <function> defined @Interface/AddOns/HeroRotation/Main.lua:370
 GetTexture = <function> defined @Interface/AddOns/HeroRotation/Core.lua:45
 APLInits = <table> {
 }
 CastSuggested = <function> defined @Interface/AddOns/HeroRotation/Core.lua:287
 CastQueuePooling = <function> defined @Interface/AddOns/HeroRotation/Core.lua:224
 CastAnnotated = <function> defined @Interface/AddOns/HeroRotation/Core.lua:183
 PulsePreInit = <function> defined @Interface/AddOns/HeroRotation/Main.lua:312
 LeftIconFrame = HeroRotation_LeftIconFrame {
 }
 CastRightSuggested = <function> defined @Interface/AddOns/HeroRotation/Core.lua:301
 GUISettings = <table> {
 }
 ChangePulseTimer = <function> defined @Interface/AddOns/HeroRotation/Main.lua:486
 Ready = <function> defined @Interface/AddOns/HeroRotation/Main.lua:473
 Pulse = <function> defined @Interface/AddOns/HeroRotation/Main.lua:438
 Timer = <table> {
 }
 CastMainNameplate = <function> defined @Interface/AddOns/HeroRotation/Core.lua:271
 MainFrame = HeroRotation_MainFrame {
 }
 AoEON = <function> defined @Interface/AddOns/HeroRotation/Core.lua:418
 NameplateIconFrame = HeroRotation_NameplateIconFrame {
 }
 Nameplate = <table> {
 }
 ToggleIconFrame = HeroRotation_ToggleIconFrame {
 }
 RightSuggestedIconFrame = HeroRotation_RightSuggestedIconFrame {
 }
 Commons = <table> {
 }
 Print = <function> defined @Interface/AddOns/HeroRotation/Core.lua:30
 ResetIcons = <function> defined @Interface/AddOns/HeroRotation/UI.lua:39
 Cast = <function> defined @Interface/AddOns/HeroRotation/Core.lua:152
 CreateBackdrop = <function> defined @Interface/AddOns/HeroRotation/UI.lua:70
 SuggestedIconFrame = HeroRotation_SuggestedIconFrame {
 }
 NameplateSuggestedIconFrame = HeroRotation_NameplateSuggestedIconFrame {
 }
 Locked = <function> defined @Interface/AddOns/HeroRotation/Core.lua:429
 SmallIconFrame = HeroRotation_SmallIconFrame {
 }
 CastLeftCommon = <function> defined @Interface/AddOns/HeroRotation/Core.lua:247
 FlashON = <function> defined @Interface/AddOns/HeroRotation/Core.lua:404
 APLs = <table> {
 }
 MainIconPartOverlayFrame = HeroRotation_MainIconPartOverlayFrame {
 }
 DebugON = <function> defined @Interface/AddOns/HeroRotation/Core.lua:399
 CastSuggestedOffset = 1
 CastLeftNameplate = <function> defined @Interface/AddOns/HeroRotation/Core.lua:263
 CastRightSuggestedOffset = 1
 CastLeftOffset = 1
 CastQueue = <function> defined @Interface/AddOns/HeroRotation/Core.lua:217
 MainIconFrame = HeroRotation_MainIconFrame {
 }
 GUI = <ta

**Comment by Hadiroyo** [comment]
![WoWScrnShot_121923_232843](https://github.com/herotc/hero-rotation/assets/154378712/3408e64e-1172-4bff-88dc-952f6b887c2e)
That's from Wyrmrest Accord

**Comment by Hadiroyo** [comment]
![WoWScrnShot_122023_014325](https://github.com/herotc/hero-rotation/assets/154378712/b5f08ec1-192b-416e-bf54-b4ecf355c993)
And that is from Moon Guard

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/7e70abacc48ff8de1c1bc0d8e35d274d8c648c8b

The fix will also be included in future version 10.2.0.43.
