### ISSUE TITLE
[Bug]: BM hunter icon mostly not showing up

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1038]
### What version of HeroRotation are you using?

10.2.0.44

### What version of HeroLib are you using?

10.2.0.22

### What version of HeroDBC are you using?

10.2.0.26

### What is the issue?

Error messages seen in BugSack:

114x HeroRotation_Hunter/BeastMastery.lua:433: attempt to call method 'CastTime' (a nil value)
[string "@HeroRotation_Hunter/BeastMastery.lua"]:433: in function <HeroRotation_Hunter/BeastMastery.lua:424>
[string "@HeroRotation_Hunter/BeastMastery.lua"]:520: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
Trinket1ToUse = <table> {
 ItemName = "Witherbark's Branch"
 ItemSlotIDs = <table> {
 }
 ItemRarity = 3
 ItemMinLevel = 0
 ItemID = 109999
 ItemUseSpell = <table> {
 }
 ItemLevel = 44
 LastDisplayTime = 0
 LastHitTime = 0
}
_ = 13
Trinket1Range = 100
(*temporary) = nil
(*temporary) = <table> {
 ItemName = "Witherbark's Branch"
 ItemSlotIDs = <table> {
 }
 ItemRarity = 3
 ItemMinLevel = 0
 ItemID = 109999
 ItemUseSpell = <table> {
 }
 ItemLevel = 44
 LastDisplayTime = 0
 LastHitTime = 0
}
(*temporary) = "attempt to call method 'CastTime' (a nil value)"
VarSyncReady = false
S = <table> {
 PoisonInjection = <table> {
 }
 FrenzyPetBuff = <table> {
 }
 ArcaneTorrent = <table> {
 }
 BeastCleave = <table> {
 }
 BeastCleavePetBuff = <table> {
 }
 Smack = <table> {
 }
 SummonPet5 = <table> {
 }
 CalloftheWild = <table> {
 }
 SteelTrap = <table> {
 }
 BerserkingBuff = <table> {
 }
 BestialWrathPetBuff = <table> {
 }
 CalloftheWildBuff = <table> {
 }
 HuntersMark = <table> {
 }
 ArcaneShot = <table> {
 }
 Barrage = <table> {
 }
 Flare = <table> {
 }
 SerpentStingDebuff = <table> {
 }
 Stampede = <table> {
 }
 SummonPet2 = <table> {
 }
 ScentofBlood = <table> {
 }
 BloodyFrenzy = <table> {
 }
 AMurderofCrows = <table> {
 }
 HuntersMarkDebuff = <table> {
 }
 SeethingRageBuff = <table> {
 }
 BagofTricks = <table> {
 }
 KillerInstinct = <table> {
 }
 Intimidation = <table> {
 }
 Exhilaration = <table> {
 }
 KillCleave = <table> {
 }
 LatentPoisonDebuff = <table> {
 }
 KillCommand = <table> {
 }
 Savagery = <table> {
 }
 AncestralCall = <table> {
 }
 LightsJudgment = <table> {
 }
 AspectoftheWild = <table> {
 }
 Muzzle = <table> {
 }
 KillShot = <table> {
 }
 ArcanePulse = <table> {
 }
 SerpentSting = <table> {
 }
 AnimalCompanion = <table> {
 }
 Stomp = <table> {
 }
 TarTrapDebuff = <table> {
 }
 Bloodshed = <table> {
 }
 Fireblood = <table> {
 }
 TarTrap = <table> {
 }
 BloodFuryBuff = <table> {
 }
 DeathChakram = <table> {
 }
 PoolFocus = <table> {
 }
 SummonPet3 = <table> {
 }
 Growl = <table> {
 }
 Claw = <table> {
 }
 CobraShot = <table> {
 }
 BestialWrathBuff = <table> {
 }
 SummonPet = <table> {
 }
 BloodBolt = <table> {
 }
 Bite = <table> {
 }
 CounterShot = <table> {
 }
 BeastCleaveBuff = <table> {
 }
 BarbedShot = <table> {
 }
 WildCall = <table> {
 }
 WildInstincts = <table> {
 }
 DireBeast = <table> {
 }
 BestialWrath = <table> {
 }
 MendPet = <table> {
 }
 OneWithThePack = <table> {
 }
 SummonPet4 = <table> {
 }
 FreezingTrap = <table> {
 }
 WailingArrow = <table> {
 }
 AspectoftheWildBuff = <table> {
 }
 BarbedShotDebuff = <table> {
 }
 BloodFury = <table> {
 }
 HydrasBite = <table> {
 }
 MultiShot = <table> {
 }
 RevivePet = <table> {
 }
 Berserking = <table> {
 }
 AlphaPredator = <table> {
 }
 ExplosiveShot = <table> {
 }
 BeastMaster = <table> {
 }
 ScareBeast = <table> {
 }
}
Player = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:595
 GCDStartTime = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:70
 Race = <function> defined @HeroLib/Class/Unit/Player/Main.lua:45
 Insanityrain = <function> defined @HeroLib/Class/Unit/Player/Power.lua:647
 FocusLossOnCastEnd = <function> defined @HeroLib/Class/Unit/Player/Power.lua:226
 PainMax = <function> defined @HeroLib/Class/Unit/Player/Power.lua:724
 IsInVehicle = <function> defined @HeroLib/Class/Unit/Player/Main.lua:104
 IsInParty = <function> defined @HeroLib/Class/Unit/Player/Main.lua:32
 EnergyDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:279
 Fury = <function> defined @HeroLib/Class/Unit/Player/Power.lua:697
 InstanceInfo = <function> defined @HeroLib/Class/Unit/Player/Instance.lua:22
 RageDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:119
 ArcaneChargesDeficitPercentage 

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
I forgot to push the HeroLib portion of the update. The fix is included in commit https://github.com/herotc/hero-lib/commit/368fcbb29f0467848d30ce16a1a7ae7212f6b4ce

It will also be in HeroLib version 10.2.0.23 when it hits CurseForge.
