### ISSUE TITLE
[Bug]: [Enhancement] Small problem with Pwave on Tindral Sageswift

### ISSUE THREAD

**Issue by nechyu** [herotc/hero-rotation#1041]
### What feature would you like to have added?

The problems are not critical, they can only be controlled in ST mode on the shaman. When tindral restrains players, roots appear. A lot of plates appear and addon recommends that I paint all these plates first through Flame shock and then when the addon sees 6 targets it recommends to use light bolt. Is it possible to make that addon on tindaral does not seek to use 6 targets to maximise the efficiency in dps on the boss in AOE mode ? If not, then ok. 
And another small problem is that when we make flights on tindral addon starts rotation from 0. To be more precise, it starts the rotation from the beginning as if the battle began only and not continue and for this rotation is also a little bit on the boss is broken not critical but unpleasant.

**Comment by Cilraaz** [comment]
Will no longer be an issue once the profile is updated for 11.0
