### ISSUE TITLE
[Bug]:  Iridal on Devastation evoker

### ISSUE THREAD

**Issue by sebastianpaiva** [herotc/hero-rotation#1045]
### What version of HeroRotation are you using?

10.2.5.06

### What version of HeroLib are you using?

10.2.5.01

### What version of HeroDBC are you using?

10.2.5.01

### What is the issue?

Lua errors on Iridal
Line 188 Devastation.lua
`
if CastTargetIf
`
fixed with
`
if Everyone.CastTargetIf
`

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
Fix pushed in commit https://github.com/herotc/hero-rotation/commit/0ebaa3d3b011cf24be1220154bda6e62bb9c9964
