### ISSUE TITLE
[Bug]:  Nitro Boosts Tinker Bug

### ISSUE THREAD

**Issue by Sephirithane** [herotc/hero-rotation#1048]
### What version of HeroRotation are you using?

10.2.5

### What version of HeroLib are you using?

10.2.5

### What version of HeroDBC are you using?

10.2.5

### What is the issue?

My belt seems to be the cause of the error, or perhaps more specifically my Nitro Boosts engineering tinker. I even tried disabling "Show Items" but it didn't help.

I also tried equipping belts with no tinker and did not receive any errors. After adding the Nitro Boost to those belts, I got the errors again (with the belts name included in the error like below) 

76x HeroLib/Class/Item.lua:210: attempt to index a nil value
[string "@HeroLib/Class/Item.lua"]:210: in function `IsReady'
[string "@HeroLib/Class/Unit/Player/Equipment.lua"]:369: in function `GetUseableItems'
[string "@HeroRotation_Paladin/Retribution.lua"]:173: in function <HeroRotation_Paladin/Retribution.lua:145>
[string "@HeroRotation_Paladin/Retribution.lua"]:368: in function `?'
[string "@HeroRotation/Main.lua"]:460: in function <HeroRotation/Main.lua:438>

Locals:
self = <table> {
ItemRarity = 4
ItemMinLevel = 70
ItemID = 207858
ItemSlotIDs = <table> {
}
ItemName = "Unwinding Eon Girdle"
ItemLevel = 379
LastDisplayTime = 0
LastHitTime = 0
}
(*temporary) = <table> {
204734 = 0
212926 = 0
368502 = 0
196543 = 0
116705 = 0
343928 = 0
241598 = 0
135106 = 1000
204736 = 0
106466 = 0
302972 = 0
278397 = 0
57330 = 1500
83939 = 0
139203 = 0
176066 = 1000
147395 = 1000
62450 = 0
63474 = 0
98275 = 0
368509 = 0
376701 = 0
147396 = 1000
270209 = 0
155588 = 1500
368511 = 0
204739 = 0
384895 = 1500
45043 = 1500
23034 = 0
233411 = 1500
51187 = 1500
54259 = 4000
155590 = 1000
327556 = 1500
122852 = 5000
124900 = 1500
135112 = 0
147400 = 0
384902 = 1500
319369 = 0
425862 = 1500
335753 = 1500
126949 = 0
225223 = 0
425863 = 1500
69607 = 1500
184265 = 0
221128 = 0
79847 = 1500
425865 = 1500
116710 = 0
204745 = 0
425866 = 1500
96231 = 0
131046 = 0
167883 = 0
17 = 1500
360334 = 0
196555 = 1500
167884 = 0
384911 = 0
425870 = 1500
5759 = 0
126951 = 0
352145 = 0
200652 = 1500
54261 = 1500
55285 = 1000
79849 = 1500
425873 = 1500
335764 = 1500
139215 = 1500
7807 = 0
31739 = 1500
8063 = 1500
8191 = 1500
71658 = 1000
343960 = 0
245710 = 0
270235 = 0
311194 = 1500
12542 = 1500
204752 = 0
71659 = 1000
53 = 1000
343963 = 0
79851 = 1000
327580 = 1500
233424 = 0
155603 = 0
319390 = 0
196562 = 0
66 = 1500
71660 = 1000
79852 = 1000
196563 = 0
116715 = 0
417694 = 1500
212947 = 1500
126955 = 0
129003 = 1000
49143 = 1500
303011 = 1500
100 = 0
147414 = 1500
258003 = 8000
112 = 0
116 = 1500
118 = 1500
120 = 1500
122 = 1500
63479 = 1500
126 = 1500
393124 = 1000
136 = 1500
176087 = 0
212950 = 0
77806 = 0
393126 = 1000
376743 = 1500
172 = 1500
122861 = 1500
184 = 0
286635 = 1500
393128 = 1000
233431 = 2000
139226 = 1000
176089 = 0
245719 = 0
434088 = 0
192473 = 1500
393130 = 1000
228 = 1500
139227 = 1000
176090 = 0
393131 = 1000
393132 = 1000
303023 = 1500
102383 = 0
176091 = 0
147420 = 1500
38905 = 0
393134 = 1000
200667 = 1500
343984 = 0
176092 = 0
245722 = 0
155613 = 0
393136 = 1000
25085 = 0
311219 = 1500
408 = 1000
147422 = 0
303028 = 0
440 = 0
393138 = 1000
368563 = 1500
30717 = 0
63481 = 0
32253 = 1500
512 = 1500
528 = 1500
319415 = 0
393141 = 1000
327608 = 0
200671 = 1500
204767 = 0
688 = 1500
122865 = 1500
249822 = 0
253918 = 1500
319418 = 0
768 = 1500
100338 = 0
800 = 0
143330 = 0
393145 = 1000
311228 = 1500
79859 = 1500
401338 = 1500
122866 = 1500
368572 = 0
188386 = 0
225249 = 0
100339 = 0
204770 = 15000
217058 = 1500
311232 = 1500
401342 = 1500
311233 = 1500
286658 = 0
122867 = 1500
311234 = 1500
327618 = 0
172005 = 0
393153 = 1000
188389 = 1500
393154 = 1000
1856 = 0
319429 = 0
122868 = 1500
253924 = 1500
32254 = 0
131060 = 0
335814 = 0
34812 = 1500
143336 = 0
180199 = 0
38908 = 0
225254 = 1500
163816 = 0
83958 = 0
384967 = 0
45052 = 0
335817 = 0
155625 = 1000
286667 = 0
98294 = 0
3136 = 0
51196 = 1500
143338 = 0
393161 = 1000
401353 = 1500
55292 = 1000
417737 = 1500
3584 = 0
286670 = 0
122870 = 1500
401355 = 1500
253928 = 1500
159723 = 0
196586 = 1500
33789 = 0
176107 = 0
294864 = 0
217066 = 0
253929 = 1500
79864 = 1000
135149 = 0
409550 = 1000
176108 = 0
23039 = 1500
409551 = 1000
6016 = 0
229355 = 0
51197 = 1500
176109 = 0
294868 = 0
401361 = 1500
79865 = 0
401362 = 1500
59389 = 1500
120824 = 0
147439 = 0
7808 = 0
188398 = 1500
270296 = 0
69626 = 1500
417748 = 1500
352215 = 0
196591 = 0
401366 = 0
11264 = 1500
335833 = 1500
409559 = 1000
417751 = 1500
12544 = 0
51198 = 1500
294876 = 0
188401 = 0
200689 = 0
409562 = 1000
176114 = 0
360412 = 0
409563 = 1000
129018 = 1500
327646 = 0
135156 = 1500
36863 = 0
335839 = 0
221170 = 0
192499 = 1500
114683 = 1500
167924 = 0
118779 = 1500
208883 = 0
294882 = 0
401375 = 0
278499 = 0
129019 = 1500
51199 = 1500
384993 = 1500
180213 = 1500
151542 = 0
409570 = 1000
352228 =

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
This has already been fixed. Update HeroLib to version 10.2.5.06

**Comment by Sephirithane** [comment]
Thank you!
