### ISSUE TITLE
[Bug]: Issue with latest update arms warrior no longer supported 

### ISSUE THREAD

**Issue by J603** [herotc/hero-rotation#1054]
### What version of HeroRotation are you using?

10.2.6.18

### What version of HeroLib are you using?

10.2.6.02

### What version of HeroDBC are you using?

10.2.6.03

### What is the issue?

Message: Interface/AddOns/HeroRotation_Warrior/Arms.lua:438: '<name>' expected near ')'
Time: Sun May  5 19:27:53 2024
Count: 1
Stack: Interface/AddOns/HeroRotation_Warrior/Arms.lua:438: '<name>' expected near ')'
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'

[string "@Interface/AddOns/HeroRotation/Main.lua"]:395: in function `PulseInit'
Message: Interface/AddOns/HeroRotation_Warrior/Arms.lua:1 Interface/AddOns/HeroRotation_Warrior/Arms.lua:438: '<name>' expected near ')'
Time: Sun May  5 19:27:53 2024
Count: 2
[string "@Interface/AddOns/HeroRotation/Main.lua"]:303: in function <Interface/AddOns/HeroRotation/Main.lua:300>

Locals: (*temporary) = <function> defined =[C]:-1

### Icon Behavior

Icon does NOT disappear

**Comment by neogia** [comment]
https://github.com/herotc/hero-rotation/blob/d26b94ad4ca71ad7676d0d5a9486f8d004c3a11d/HeroRotation_Warrior/Arms.lua#L438
Looks like just an extra period in this conditional was added in yesterday's patch. This changed line fixed it for me.
`if S.Whirlwind:IsReady() and (S.StormofSwords:IsAvailable() and not S.TestofMight:IsAvailable()) then`

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/eb543ffaebc818384983c87c81d3da58c9014224 which will be included in release version 10.2.6.19.
