### ISSUE TITLE
[Bug]: Ominous Chromatic Essence 

### ISSUE THREAD

**Issue by Profoundsoup** [herotc/hero-rotation#1056]
### What version of HeroRotation are you using?

10.2.7.17

### What version of HeroLib are you using?

10.2.7.04

### What version of HeroDBC are you using?

10.2.7.03

### What is the issue?

<img width="151" alt="Orb" src="https://github.com/herotc/hero-rotation/assets/140456261/1ac5f72c-3c5b-4a3a-922e-e3a117253a8b">

Ominous Chromatic Essence is currently showing up on my survival hunter as a dps rotation trinket... 

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
There was an issue with a recent change to how our item blacklist code worked. This has been resolved as of commit https://github.com/herotc/hero-lib/commit/a37d1275204b2127915120351cf2d6416bca7db9

Please update to HeroLib 10.2.7.05. That should resolve your issue. Closing this issue, but if it is still a problem after the HeroLib update, please let us know and we'll re-open it.

**Comment by Profoundsoup** [comment]
That fixed it! Thanks for the update but another super random effect is being asked to be used....If you have the weapon "Spring's Keeper" it will ask you to transform the weapon in combat. 
<img width="148" alt="Ax" src="https://github.com/herotc/hero-rotation/assets/140456261/88fb5df9-5fcd-49a9-ad3d-fcbaf539c1b4">

**Comment by Cilraaz** [comment]
Spring's Keeper is now excluded as of HeroLib version 10.2.7.06.

We include all usable items by default, then exclude on a per-item basis. There are likely other items that also should be excluded that we haven't noticed yet. If you run into any others, please let us know!

**Comment by Profoundsoup** [comment]
Will do!Appreciate all your guys hard workAndrewOn May 31, 2024, at 3:10 PM, Cilraaz ***@***.***> wrote:﻿
Spring's Keeper is now excluded as of HeroLib version 10.2.7.06.
We include all usable items by default, then exclude on a per-item basis. There are likely other items that also should be excluded that we haven't noticed yet. If you run into any others, please let us know!
