### ISSUE TITLE
[Bug]: Getting a frost dk error on my unholy dk

### ISSUE THREAD

**Issue by Devil-Kal** [herotc/hero-rotation#1060]
### What version of HeroRotation are you using?

11.0.0.05

### What version of HeroLib are you using?

11.0.0.03

### What version of HeroDBC are you using?

11.0.0.01

### What is the issue?

I have this lua error on my unholy dk

8x HeroRotation_DeathKnight/Frost.lua:135: attempt to index field 'FrigidExecutioner' (a nil value)
[string "@HeroRotation_DeathKnight/Frost.lua"]:135: in function <HeroRotation_DeathKnight/Frost.lua:134>
[string "@HeroRotation_DeathKnight/Frost.lua"]:172: in function `Handler'
[string "@HeroLib/Events/Main.lua"]:85: in function <HeroLib/Events/Main.lua:83>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'FrigidExecutioner' (a nil value)"
S = <table> {
 DarkTalons = <table> {
 }
 ArcaneTorrent = <table> {
 }
 HornofWinter = <table> {
 }
 ReapersMark = <table> {
 }
 AntiMagicZone = <table> {
 }
 ChillStreak = <table> {
 }
 BloodFury = <table> {
 }
 RageoftheFrozenChampion = <table> {
 }
 BitingCold = <table> {
 }
 RuneofHysteriaBuff = <table> {
 }
 MindFreeze = <table> {
 }
 SoulReaper = <table> {
 }
 ChainsofIce = <table> {
 }
 SacrificialPact = <table> {
 }
 FrostwyrmsFury = <table> {
 }
 DeathAndDecay = <table> {
 }
 ArcticAssault = <table> {
 }
 TheLongWinter = <table> {
 }
 GatheringStorm = <table> {
 }
 RazoriceDebuff = <table> {
 }
 ShatteredFrost = <table> {
 }
 ReapersMarkDebuff = <table> {
 }
 UnleashedFrenzy = <table> {
 }
 ImprovedObliterate = <table> {
 }
 BagofTricks = <table> {
 }
 PillarofFrost = <table> {
 }
 EmpowerRuneWeaponBuff = <table> {
 }
 IceboundFortitude = <table> {
 }
 FrostFeverDebuff = <table> {
 }
 ColdHeart = <table> {
 }
 Pool = <table> {
 }
 CleavingStrikes = <table> {
 }
 VirulentPlagueDebuff = <table> {
 }
 EmpowerRuneWeapon = <table> {
 }
 ArcanePulse = <table> {
 }
 DeathCoil = <table> {
 }
 UnleashedFrenzyBuff = <table> {
 }
 ColdHeartBuff = <table> {
 }
 Avalanche = <table> {
 }
 ApocalypseNow = <table> {
 }
 AFeastofSouls = <table> {
 }
 MograinesMightBuff = <table> {
 }
 Everfrost = <table> {
 }
 Fireblood = <table> {
 }
 DeathStrike = <table> {
 }
 DeathStrikeBuff = <table> {
 }
 HowlingBlast = <table> {
 }
 BloodPlagueDebuff = <table> {
 }
 GatheringStormBuff = <table> {
 }
 MightoftheFrozenWastes = <table> {
 }
 IcyTalonsBuff = <table> {
 }
 RaiseDead = <table> {
 }
 ShatteringBlade = <table> {
 }
 LightsJudgment = <table> {
 }
 GlacialAdvance = <table> {
 }
 PillarofFrostBuff = <table> {
 }
 ChillingRageBuff = <table> {
 }
 AncestralCall = <table> {
 }
 AbominationLimbBuff = <table> {
 }
 RunicAttenuation = <table> {
 }
 Frostscythe = <table> {
 }
 SoulReaperDebuff = <table> {
 }
 UnholyStrengthBuff = <table> {
 }
 EnduringStrength = <table> {
 }
 DeathAndDecayBuff = <table> {
 }
 Icebreaker = <table> {
 }
 FrostStrike = <table> {
 }
 KillingMachineBuff = <table> {
 }
 BreathofSindragosa = <table> {
 }
 UnholyGround = <table> {
 }
 Assimilation = <table> {
 }
 Obliteration = <table> {
 }
 AFeastofSoulsBuff = <table> {
 }
 RimeBuff = <table> {
 }
 Icecap = <table> {
 }
 RemorselessWinter = <table> {
 }
 Obliterate = <table> {
 }
 AbominationLimb = <table> {
 }
 SmotheringOffense = <table> {
 }
 IcyTalons = <table> {
 }
 Berserking = <table> {
 }
 Asphyxiate = <table> {
 }
 AntiMagicShell = <table> {
 }
 MarkofFyralathDebuff = <table> {
 }
 FatalFixation = <table> {
 }
}
Var2HCheck = false

### Icon Behavior

None

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/ce4ecc1846f588b912b46dfc3f8edd327c3485ed
