### ISSUE TITLE
[Bug]: Mistwalker crashes for Pre-Patch TWW

### ISSUE THREAD

**Issue by Aidenrhys** [herotc/hero-rotation#1063]
### What version of HeroRotation are you using?

11.0.0.07

### What version of HeroLib are you using?

11.0.0.04

### What version of HeroDBC are you using?

11.0.0.01

### What is the issue?

108x HeroRotation_Monk/Windwalker.lua:2245: attempt to index field 'Serenity' (a nil value)
[string "@HeroRotation_Monk/Windwalker.lua"]:2245: in function `?'
[string "@HeroRotation/Main.lua"]:476: in function <HeroRotation/Main.lua:455>

Locals:
ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = false
(*temporary) = "attempt to index field 'Serenity' (a nil value)"
Enemies5y = <table> {
 1 = <table> {
 }
}
Player = <table> {
 UseCache = true
 UnitNPCID = -2
 UnitCanBeAttacked = false
 UnitID = "player"
 UnitGUID = "Player-1184-07A4071D"
 UnitExists = true
 TimeToXResourceMap = <table> {
 }
 PredictedResourceMap = <table> {
 }
 UnitName = "Arhys"
}
Enemies8y = <table> {
 1 = <table> {
 }
}
EnemiesCount8y = 1
Everyone = <table> {
}
BossFightRemains = 11111
HL = <table> {
 MAXIMUM = 40
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 PulseInitialized = true
 Item = <table> {
 }
 CacheHasBeenReset = false
 Spell = <table> {
 }
 Action = <table> {
 }
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 0
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 MultiSpell = <table> {
 }
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 CombatStarted = 60397.632000
 SpecID_ClassesSpecs = <table> {
 }
 GUI = <table> {
 }
 Timer = <table> {
 }
}
FightRemains = 5.039322
XuenActive = false
S = <table> {
 PoolEnergy = <table> {
 }
 MarkoftheCrane = <table> {
 }
 Skyreach = <table> {
 }
 FortifyingBrew = <table> {
 }
 InnerStrengthBuff = <table> {
 }
 CracklingJadeLightning = <table> {
 }
 FistsofFlowingMomentumBuff = <table> {
 }
 Transcendence = <table> {
 }
 BloodFury = <table> {
 }
 JadefireStomp = <table> {
 }
 WhirlingDragonPunchBuff = <table> {
 }
 RushingJadeWindBuff = <table> {
 }
 BonedustBrewBuff = <table> {
 }
 StrengthofSpirit = <table> {
 }
 MarkoftheCraneDebuff = <table> {
 }
 FlyingSerpentKickLand = <table> {
 }
 StopFoF = <table> {
 }
 JadefireBrandDebuff = <table> {
 }
 EyeoftheTiger = <table> {
 }
 TigerTailSweep = <table> {
 }
 Roll = <table> {
 }
 QuakingPalm = <table> {
 }
 ChiBurst = <table> {
 }
 GiftoftheNaaru = <table> {
 }
 HitComboBuff = <table> {
 }
 ChiWave = <table> {
 }
 TheEmperorsCapacitorBuff = <table> {
 }
 StormEarthAndFireFixate = <table> {
 }
 RushingJadeWind = <table> {
 }
 BagofTricks = <table> {
 }
 DiffuseMagic = <table> {
 }
 ExpelHarm = <table> {
 }
 FastFeet = <table> {
 }
 StrikeoftheWindlord = <table> {
 }
 TransferthePowerBuff = <table> {
 }
 TouchofDeath = <table> {
 }
 ChiTorpedo = <table> {
 }
 Resuscitate = <table> {
 }
 WhirlingDragonPunch = <table> {
 }
 AncestralCall = <table> {
 }
 Vivify = <table> {
 }
 ImpTouchofDeath = <table> {
 }
 XuensBattlegear = <table> {
 }
 ChiEnergyBuff = <table> {
 }
 JadeIgnition = <table> {
 }
 TouchofKarma = <table> {
 }
 BlackoutKickBuff = <table> {
 }
 DanceofChijiBuff = <table> {
 }
 StormEarthAndFire = <table> {
 }
 Detox = <table> {
 }
 JadefireHarmony = <table> {
 }
 SkyreachCritDebuff = <table> {
 }
 PowerStrikesBuff = <table> {
 }
 SerenityBuff = <table> {
 }
 ArcaneTorrent = <table> {
 }
 PressurePointBuff = <table> {
 }
 TranscendenceTransfer = <table> {
 }
 Fireblood = <table> {
 }
 Celerity = <table> {
 }
 Skytouch = <table> {
 }
 FlyingSerpentKick = <table> {
 }
 TigerPalm = <table> {
 }
 Provoke = <table> {
 }
 BlackoutKick = <table> {
 }
 BonedustBrew = <table> {
 }
 SkyreachExhaustionDebuff = <table> {
 }
 Disable = <table> {
 }
 DomineeringArroganceBuff = <table> {
 }
 DampenHarm = <table> {
 }
 DampenHarmBuff = <table> {
 }
 StormEarthAndFireBuff = <table> {
 }
 HiddenMastersForbiddenTouchBuff = <table> {
 }
 FuryofXuenBuff = <table> {
 }
 SummonWhiteTigerStatue = <table> {
 }
 CraneVortex = <table> {
 }
 KicksofFlowingMomentumBuff = <table> {
 }
 SpearHandStrike = <table> {
 }
 TeachingsoftheMonasteryBuff = <table> {
 }
 BonedustBrewDebuff = <table> {
 }
 FistsofFury = <table> {
 }
 Thunderfist = <table> {
 }
 ShadowboxingTreads = <table> {
 }
 InvokeXuenTheWhiteTiger = <table> {
 }
 TigersLust = <table> {
 }
 RisingSunKick = <table> {
 }
 CalltoDominanceBuff = <table> {
 }
 DanceofChiji = <table> {
 }
 Li

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Mistwalker is not a supported spec. Brewmaster and Windwalker have not yet been updated for 11.0.
