### ISSUE TITLE
[Bug]: ASSASINATION Fix the Kingbane icon appearing while the spell is on cooldown

### ISSUE THREAD

**Issue by Sparckx** [herotc/hero-rotation#1064]
### What version of HeroRotation are you using?

11.0.0.07

### What version of HeroLib are you using?

11.0.0.04

### What version of HeroDBC are you using?

11.0.0.01

### What is the issue?

When we use Vendetta and other burst cooldowns, after a certain period, the icon for the next spell gets stuck on Kingsbane. Generally, there are about 14 seconds left on the spell's cooldown. This mostly happens towards the end of boss fights (the last 20%) but can also occur sometimes on trash mobs.

Do you need me to provide a video or logs for this? How can I help further?

Thank you for your response.

### Icon Behavior

N/A

**Comment by Seny951** [comment]
Found the issue.

The Kingsbane condition has a small logic error in it causing it to evaluate as (kingsbane is ready or fight remains <= 15 seconds) hence it showing when on cooldown.

raised a pull request for the fix it should be available in the next release

**Comment by Cilraaz** [comment]
This is fixed as of version 11.0.0.08
