### ISSUE TITLE
[Bug]: Lua Error

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1068]
### What version of HeroRotation are you using?

11.0.0.10

### What version of HeroLib are you using?

11.0.0.06

### What version of HeroDBC are you using?

11.0.0.02

### What is the issue?

This is the error I get:

118x HeroRotation_DemonHunter/Events.lua:109: attempt to index field 'SigilofChains' (a nil value)
[string "@HeroRotation_DemonHunter/Events.lua"]:109: in function `Handler'
[string "@HeroLib/Events/Main.lua"]:247: in function <HeroLib/Events/Main.lua:236>
[string "@HeroLib/Events/Main.lua"]:283: in function `Handler'
[string "@HeroLib/Events/Main.lua"]:85: in function <HeroLib/Events/Main.lua:83>

Locals:
SpellID = 393438
IncAmt = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = 389813
(*temporary) = "attempt to index field 'SigilofChains' (a nil value)"
SpellVDH = <table> {
 SigilofFlame = <table> {
 }
 FirstoftheIllidari = <table> {
 }
 RendingStrikeBuff = <table> {
 }
 InfernalStrike = <table> {
 }
 FieryBrandDebuff = <table> {
 }
 StudentofSuffering = <table> {
 }
 ImmolationAuraBuff = <table> {
 }
 Fracture = <table> {
 }
 SigilofDoom = <table> {
 }
 ReaversMarkDebuff = <table> {
 }
 Shear = <table> {
 }
 FieryBrand = <table> {
 }
 ConsumingFire = <table> {
 }
 TheHunt = <table> {
 }
 MetamorphosisBuff = <table> {
 }
 SigilofMiseryDebuff = <table> {
 }
 Demonsurge = <table> {
 }
 SpiritBurst = <table> {
 }
 SoulSunder = <table> {
 }
 BulkExtraction = <table> {
 }
 SigilofDoomDebuff = <table> {
 }
 DemonSpikesBuff = <table> {
 }
 Glide = <table> {
 }
 FelDesolation = <table> {
 }
 StudentofSufferingBuff = <table> {
 }
 SoulCarver = <table> {
 }
 GlaiveFlurryBuff = <table> {
 }
 ThrilloftheFightDmgBuff = <table> {
 }
 FoddertotheFlame = <table> {
 }
 FelDevastation = <table> {
 }
 FieryDemise = <table> {
 }
 DowninFlames = <table> {
 }
 SigilofMisery = <table> {
 }
 SigilofSpite = <table> {
 }
 SpiritBomb = <table> {
 }
 AscendingFlame = <table> {
 }
 DemonSpikes = <table> {
 }
 SoulCleave = <table> {
 }
 ReaversGlaive = <table> {
 }
 CollectiveAnguish = <table> {
 }
 ThrowGlaive = <table> {
 }
 Felblade = <table> {
 }
 ArtoftheGlaiveBuff = <table> {
 }
 ThrilloftheFightAtkBuff = <table> {
 }
 ReaversGlaiveBuff = <table> {
 }
 Pool = <table> {
 }
 ArcaneTorrent = <table> {
 }
 VengefulRetreat = <table> {
 }
 SigilofFlameDebuff = <table> {
 }
 Disrupt = <table> {
 }
 DarkglareBoon = <table> {
 }
 Demonic = <table> {
 }
 ChaosNova = <table> {
 }
 IlluminatedSigils = <table> {
 }
 SoulFurnaceDmgBuff = <table> {
 }
 QuickenedSigils = <table> {
 }
 SoulFurnaceBuff = <table> {
 }
 Metamorphosis = <table> {
 }
 SoulSigils = <table> {
 }
 ImmolationAura = <table> {
 }
 UnhinderedAssault = <table> {
 }
}
Soul = <table> {
 AuraSouls = 0
 IncomingSouls = 0
}

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
This is due to a change I made yesterday. Once I'm near a computer, I'll push a quick fix and a new version of the addon.

**Comment by Cilraaz** [comment]
This was fixed in version 11.0.0.11
