### ISSUE TITLE
[Bug]: lua error

### ISSUE THREAD

**Issue by Facelessmeat** [herotc/hero-rotation#1069]
### What version of HeroRotation are you using?

11.0.0.11

### What version of HeroLib are you using?

11.0.0.06

### What version of HeroDBC are you using?

11.0.0.02

### What is the issue?

This is what i get when trying to use Hero rotation for Windwalker monk. Hero rotation works for brewmaster monk, and beast master hunter. ( not to sure what i am looking at) but this is what i have

Interface/AddOns/HeroRotation_Monk/Windwalker.lua:2217: attempt to index field 'Serenity' (a nil value)
[string "@Interface/AddOns/HeroRotation_Monk/Windwalker.lua"]:2217: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:470: in function <Interface/AddOns/HeroRotation/Main.lua:455>

Locals: ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 2
(*temporary) = 2
(*temporary) = "player"
(*temporary) = 12
(*temporary) = 2
(*temporary) = "Power"
(*temporary) = <table> {
 1 = 191914
 2 = 191913
 3 = 191912
 4 = 191907
 5 = 191906
 6 = 191905
 7 = 191383
 8 = 191382
 9 = 191381
 10 = 191389
 11 = 191388
 12 = 191387
}
(*temporary) = "attempt to index field 'Serenity' (a nil value)"
Enemies5y = <table> {
}
Player = <table> {
 UseCache = true
 UnitNPCID = -2
 UnitCanBeAttacked = false
 UnitID = "player"
 UnitGUID = "Player-86-0A804072"
 UnitExists = true
 TimeToXResourceMap = <table> {
 }
 PredictedResourceMap = <table> {
 }
 UnitName = "Selkamonk"
}
Enemies8y = <table> {
}
EnemiesCount8y = 0
Everyone = <table> {
}
BossFightRemains = 11111
HL = <table> {
 MAXIMUM = 40
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 PulseInitialized = true
 Item = <table> {
 }
 CacheHasBeenReset = false
 Spell = <table> {
 }
 Action = <table> {
 }
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 570150.601000
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 MultiSpell = <table> {
 }
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 CombatStarted = 0
 SpecID_ClassesSpecs = <table> {
 }
 GUI = <table> {
 }
 Timer = <table> {
 }
}
FightRemains = 6666
XuenActive = false
S = <table> {
 PoolEnergy = <table> {
 }
 MarkoftheCrane = <table> {
 }
 Skyreach = <table> {
 }
 FortifyingBrew = <table> {
 }
 InnerStrengthBuff = <table> {
 }
 CracklingJadeLightning = <table> {
 }
 FistsofFlowingMomentumBuff = <table> {
 }
 Transcendence = <table> {
 }
 BloodFury = <table> {
 }
 JadefireStomp = <table> {
 }
 WhirlingDragonPunchBuff = <table> {
 }
 RushingJadeWindBuff = <table> {
 }
 BonedustBrewBuff = <table> {
 }
 StrengthofSpirit = <table> {
 }
 MarkoftheCraneDebuff = <table> {
 }
 FlyingSerpentKickLand = <table> {
 }
 StopFoF = <table> {
 }
 JadefireBrandDebuff = <table> {
 }
 EyeoftheTiger = <table> {
 }
 TigerTailSweep = <table> {
 }
 Roll = <table> {
 }
 QuakingPalm = <table> {
 }
 ChiBurst = <table> {
 }
 GiftoftheNaaru = <table> {
 }
 HitComboBuff = <table> {
 }
 ChiWave = <table> {
 }
 TheEmperorsCapacitorBuff = <table> {
 }
 StormEarthAndFireFixate = <table> {
 }
 RushingJadeWind = <table> {
 }
 BagofTricks = <table> {
 }
 DiffuseMagic = <table> {
 }
 ExpelHarm = <table> {
 }
 FastFeet = <table> {
 }
 StrikeoftheWindlord = <table> {
 }
 TransferthePowerBuff = <table> {
 }
 TouchofDeath = <table> {
 }
 ChiTorpedo = <table> {
 }
 Resuscitate = <table> {
 }
 WhirlingDragonPunch = <table> {
 }
 AncestralCall = <table> {
 }
 Vivify = <table> {
 }
 ImpTouchofDeath = <table> {
 }
 XuensBattlegear = <table> {
 }
 ChiEnergyBuff = <table> {
 }
 JadeIgnition = <table> {
 }
 TouchofKarma = <table> {
 }
 BlackoutKickBuff = <table> {
 }
 DanceofChijiBuff = <table> {
 }
 StormEarthAndFire = <table> {
 }
 Detox = <table> {
 }
 JadefireHarmony = <table> {
 }
 SkyreachCritDebuff = <table> {
 }
 PowerStrikesBuff = <table> {
 }
 SerenityBuff = <table> {
 }
 ArcaneTorrent = <table> {
 }
 PressurePointBuff = <table> {
 }
 TranscendenceTransfer = <table> {
 }
 Fireblood = <table> {
 }
 Celerity = <table> {
 }
 Skytouch = <table> {
 }
 FlyingSerpentKick = <table> {
 }
 TigerPalm = <table> {
 }
 Provoke = <table> {
 }
 BlackoutKick = <table> {
 }
 BonedustBrew = <table> {
 }
 SkyreachExhaustionDebuff = <table> {
 }
 Disable = <table> {
 }
 Domineeri

Icons do not appear.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Monk has not yet been updated. https://github.com/herotc/hero-rotation#supported-rotations
