### ISSUE TITLE
[WW Monk] Feedback

### ISSUE THREAD

**Issue by Khirae** [herotc/hero-rotation#107]
Hello, somerandom feedback from the alpha build 7.3.2.02-18-g7ebc840-alpha

Emperor capacitor support : sometime no call to use CJL even with 20 stack ( had 5 GCD before a CJL call )
EE support : sometime call for EE with 4chi and 70+ energy and EE followed by a TP. On pull following the data from aer i got the following result
https://www.warcraftlogs.com/reports/D1J82K9GhtwXm3nN/#fight=2&view=timeline
really late call for EE , no FoF or WDP during ToD

Hit combo support : when above 4chi and with RSK FoF SotWL on CD call for TP BOK TP BOK is it possible to set a TP BoK FSK BoK?
SCK sometime randomly pop for 0.5s (i suppose it's to dump chi but it never stay long enought to react)

If i find something else i will try to open a new ticket

I am available on discord if you want

Regards
Mindra

**Comment by Hinalover** [comment]
Do you have access to the monk discord? If so do you have access to the wind_craft channel? post there since this seems to be also relate to the SimC APL (which Aethys uses verbatim). I'll re-post this there but it's best to get everything in one spot.

**Comment by aethys256** [comment]
Closing since BfA is around the corner and the discussion is no longer relevant.
