### ISSUE TITLE
[Bug]:  BM Hunter miss " VenomsBite= Spell(459565), " in Hunter.lua

### ISSUE THREAD

**Issue by mizone** [herotc/hero-rotation#1072]
### What version of HeroRotation are you using?

11.0.0.18

### What version of HeroLib are you using?

11.0.0.06

### What version of HeroDBC are you using?

11.0.0.02

### What is the issue?

Message: ...nterface/AddOns/HeroRotation_Hunter/BeastMastery.lua:231: attempt to index field 'VenomsBite' (a nil value)
Time: Tue Aug  6 08:40:37 2024
Count: 62
Stack: ...nterface/AddOns/HeroRotation_Hunter/BeastMastery.lua:231: attempt to index field 'VenomsBite' (a nil value)
[string "@Interface/AddOns/HeroRotation_Hunter/BeastMastery.lua"]:231: in function <...nterface/AddOns/HeroRotation_Hunter/BeastMastery.lua:201>
[string "@Interface/AddOns/HeroRotation_Hunter/BeastMastery.lua"]:455: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:476: in function <Interface/AddOns/HeroRotation/Main.lua:455>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = <table> {
 SpellTable = <table> {
 }
}
(*temporary) = nil
(*temporary) = true
(*temporary) = false
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = true
(*temporary) = "attempt to index field 'VenomsBite' (a nil value)"
S = <table> {
 PoisonInjection = <table> {
 }
 FrenzyPetBuff = <table> {
 }
 ArcaneTorrent = <table> {
 }
 BeastCleave = <table> {
 }
 BeastCleavePetBuff = <table> {
 }
 WildCall = <table> {
 }
 ScareBeast = <table> {
 }
 HuntersPreyBuff = <table> {
 }
 CalloftheWild = <table> {
 }
 SteelTrap = <table> {
 }
 BerserkingBuff = <table> {
 }
 BestialWrathPetBuff = <table> {
 }
 AspectoftheWildBuff = <table> {
 }
 HuntersMark = <table> {
 }
 ArcaneShot = <table> {
 }
 Barrage = <table> {
 }
 Flare = <table> {
 }
 SerpentStingDebuff = <table> {
 }
 Stampede = <table> {
 }
 SummonPet2 = <table> {
 }
 ScentofBlood = <table> {
 }
 BloodyFrenzy = <table> {
 }
 AMurderofCrows = <table> {
 }
 HuntersMarkDebuff = <table> {
 }
 SeethingRageBuff = <table> {
 }
 BagofTricks = <table> {
 }
 KillerInstinct = <table> {
 }
 Intimidation = <table> {
 }
 Exhilaration = <table> {
 }
 KillCleave = <table> {
 }
 LatentPoisonDebuff = <table> {
 }
 KillCommand = <table> {
 }
 FreezingTrap = <table> {
 }
 AncestralCall = <table> {
 }
 KillerCobra = <table> {
 }
 LightsJudgment = <table> {
 }
 AspectoftheWild = <table> {
 }
 Muzzle = <table> {
 }
 KillShot = <table> {
 }
 ArcanePulse = <table> {
 }
 SerpentSting = <table> {
 }
 AnimalCompanion = <table> {
 }
 Stomp = <table> {
 }
 TarTrapDebuff = <table> {
 }
 Bloodshed = <table> {
 }
 Fireblood = <table> {
 }
 TarTrap = <table> {
 }
 BloodFuryBuff = <table> {
 }
 DeathChakram = <table> {
 }
 PoolFocus = <table> {
 }
 CobraShot = <table> {
 }
 SummonPet3 = <table> {
 }
 SummonPet5 = <table> {
 }
 Smack = <table> {
 }
 WildInstincts = <table> {
 }
 BestialWrathBuff = <table> {
 }
 SummonPet = <table> {
 }
 Berserking = <table> {
 }
 Bite = <table> {
 }
 CounterShot = <table> {
 }
 BeastCleaveBuff = <table> {
 }
 BarbedShot = <table> {
 }
 HuntmastersCall = <table> {
 }
 CalloftheWildBuff = <table> {
 }
 BarbedShotDebuff = <table> {
 }
 BestialWrath = <table> {
 }
 MendPet = <table> {
 }
 OneWithThePack = <table> {
 }
 DireBeast = <table> {
 }
 Savagery = <table> {
 }
 SummonPet4 = <table> {
 }
 WailingArrow = <table> {
 }
 MultiShot = <table> {
 }
 Claw = <table> {
 }
 HydrasBite = <table> {
 }
 BloodFury = <table> {
 }
 RevivePet = <table> {
 }
 AlphaPredator = <table> {
 }
 BloodBolt = <table> {
 }
 ExplosiveShot = <table> {
 }
 BeastMaster = <table> {
 }
 Growl = <table> {
 }
}
Everyone = <table> {
}
Enemies40y = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
Target = <table> {
 UnitExists = true
 UnitNPCID = 198594
 UnitGUID = "Creature-0-3055-2444-19243-198594-0001B16511"
 UnitID = "target"
 UseCache = true
 UnitName = "顺劈训练假人"
 UnitCanBeAttacked = true
}
Pet = <table> {
 UnitExists = false
 UnitCanBeAttacked = false
 UnitID = "pet"
 UseCache = false
}
GCDMax = 1.290131
Settings = <table> {
 General = <table> {
 }
 CommonsDS = <table> {
 }
 BeastMastery = <table> {
 }
 Commons = <table> {
 }
 CommonsOGCD = <table> {
 }
}
Player = <table> {
 UseCache = true
 UnitNPCID = -2
 UnitCanBeAttacked = false
 UnitID = "player"
 UnitGUID =

### Icon Behavior

None

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/17cee1a608f91df73c36974b8e5a9553cc13cc05, which will be included in HeroRotation version 11.0.0.19. Thanks for the report!
