### ISSUE TITLE
[Bug]: [Shadow] Void Eruption is never suggested

### ISSUE THREAD

**Issue by Ragowit** [herotc/hero-rotation#1083]
### What version of HeroRotation are you using?

11.0.2.11

### What version of HeroLib are you using?

11.0.2.02

### What version of HeroDBC are you using?

11.0.2.02

### What is the issue?

I know it's early in the expansion, just the first day, but I believe Void Eruption should be suggested at some point during a rotation.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Void Eruption's requirements, per the APL, are:
- Fiend on cooldown
- Fiend active with 4+ seconds remaining on its cooldown OR Mindbender talent not selected OR 3+ enemies without Inescapable Torment talent selected
- Zero Mind Blast charges remaining OR player is 15+ seconds into combat

If you meet these conditions and still aren't receiving Void Eruption suggestions, let me know.

**Comment by Cilraaz** [comment]
A quick test confirmed that Void Eruption is being suggested at level 70.

**Comment by Ragowit** [comment]
Maybe it's because I have selected the Voidwraith talent then? Who replaces Shadowfiend/Mindbender.

**Comment by Cilraaz** [comment]
It absolutely was. This should be fixed in commit https://github.com/herotc/hero-rotation/commit/01dff9397314a98fa6dd69f9bbbd4a8977699c8e
