### ISSUE TITLE
[Bug]: ASSASINATION Fix the Ambush icon appearing while the spell is not available

### ISSUE THREAD

**Issue by MiszluDev** [herotc/hero-rotation#1084]
### What version of HeroRotation are you using?

11.0.2.12

### What version of HeroLib are you using?

11.0.2.03

### What version of HeroDBC are you using?

11.02.02

### What is the issue?

Sometimes after exiting Vanish during combat (most often), Ambush still displays as the main attack icon even though you can't use it. Problem occurs more often with multitargets, but it also occurs with solo targets.

If you need any more screenshot or video i can deliver it
![Ambush bug](https://github.com/user-attachments/assets/9c582027-4c7c-4233-8924-be2eb300e234)

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/ec860451d08f5178c979f989a712e5b774274229
