### ISSUE TITLE
[Bug]: Not showing on Fury Warrior

### ISSUE THREAD

**Issue by warriornoob** [herotc/hero-rotation#1085]
### What version of HeroRotation are you using?

11.0.2.13

### What version of HeroLib are you using?

11.0.2.04

### What version of HeroDBC are you using?

11.0.2.02

### What is the issue?

"_No Rotation found for this class/spec (SpecID: 72), addon disabled_" in chat, but Fury Warrior is listed as "good" in supported specs.

**LUA error:**
Message: Interface/AddOns/HeroRotation_Warrior/Fury.lua:104: attempt to perform arithmetic on global 'Trinket1CD' (a nil value)
Time: Sun Aug 25 10:13:17 2024
Count: 1
Stack: Interface/AddOns/HeroRotation_Warrior/Fury.lua:104: attempt to perform arithmetic on global 'Trinket1CD' (a nil value)
[string "@Interface/AddOns/HeroRotation_Warrior/Fury.lua"]:104: in function `SetTrinketVariables'
[string "@Interface/AddOns/HeroRotation_Warrior/Fury.lua"]:126: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroRotation/Main.lua"]:411: in function `PulseInit'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:316: in function <Interface/AddOns/HeroRotation/Main.lua:313>

Locals: T1 = <table> {
 Spell = <table> {
 }
 Object = <table> {
 }
 Cooldown = 0
 ID = 129898
 Blacklisted = false
 Range = 40
 CastTime = 0
}
T2 = <table> {
 Object = <table> {
 }
 Cooldown = 0
 ID = 194301
 Blacklisted = false
 Range = 100
 CastTime = 0
}
(*temporary) = nil
(*temporary) = <table> {
 ItemName = "Mark of Supremacy"
 ItemSlotIDs = <table> {
 }
 ItemRarity = 3
 ItemMinLevel = 30
 ItemID = 129898
 ItemUseSpell = <table> {
 }
 ItemLevel = 35
 LastDisplayTime = 0
 LastHitTime = 0
}
(*temporary) = true
(*temporary) = <table> {
 ItemName = "Mark of Supremacy"
 ItemSlotIDs = <table> {
 }
 ItemRarity = 3
 ItemMinLevel = 30
 ItemID = 129898
 ItemUseSpell = <table> {
 }
 ItemLevel = 35
 LastDisplayTime = 0
 LastHitTime = 0
}
(*temporary) = true
(*temporary) = "attempt to perform arithmetic on global 'Trinket1CD' (a nil value)"
Player = <table> {
 UseCache = true
 UnitNPCID = -2
 UnitCanBeAttacked = false
 UnitID = "player"
 UnitGUID = "Player-1305-0AE7524E"
 UnitExists = true
 TimeToXResourceMap = <table> {
 }
 PredictedResourceMap = <table> {
 }
 UnitName = "Furynoob"
}
VarTrinketFailures = 0
Trinket1 = <table> {
 ItemName = "Mark of Supremacy"
 ItemSlotIDs = <table> {
 }
 ItemRarity = 3
 ItemMinLevel = 30
 ItemID = 129898
 ItemUseSpell = <table> {
 }
 ItemLevel = 35
 LastDisplayTime = 0
 LastHitTime = 0
}
Trinket2 = <table> {
 ItemRarity = 4
 ItemMinLevel = 70
 ItemID = 194301
 ItemSlotIDs = <table> {
 }
 ItemName = "Whispering Incarnate Icon"
 ItemLevel = 395
 LastDisplayTime = 0
 LastHitTime = 0
}
VarTrinket1Spell = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Rage"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 194618
}
VarTrinket1Range = 40
VarTrinket1CastTime = 0
VarTrinket2Spell = nil
VarTrinket2Range = 100
VarTrinket2CastTime = 0
VarTrinket1CD = 0
VarTrinket2CD = 0
VarTrinket1BL = false
VarTrinket2BL = false
VarTrinket1Exclude = false
VarTrinket2Exclude = true
VarTrinket1Sync = 0.500000
VarTrinket2Sync = nil
VarTrinket1Buffs = nil
VarTrinket2Buffs = nil
VarTrinketPriority = nil
VarTrinket1Manual = nil
I = <table> {
 IrideusFragment = <table> {
 }
 CrimsonGladiatorsBadgeofFerocity = <table> {
 }
 BeacontotheBeyond = <table> {
 }
 ElementiumPocketAnvil = <table> {
 }
 ManicGrieftorch = <table> {
 }
 Fyralath = <table> {
 }
 AlgetharPuzzleBox = <table> {
 }
 VialofAnimatedBlood = <table> {
 }
}
VarTrinket2Manual = nil

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/56ae87c1699b20902450b32bcce23c56a694ed96

This fix will be included in version 11.0.2.14, which was just pushed.
