### ISSUE TITLE
[Bug]: [rogue] rotation stuck if not using adrenaline rush

### ISSUE THREAD

**Issue by Nelyaan** [herotc/hero-rotation#1088]
### What version of HeroRotation are you using?

11.0.2.16

### What version of HeroLib are you using?

11.0.2.04

### What version of HeroDBC are you using?

11.0.2.02

### What is the issue?

I use it with my outlaw rogue.
Adrenaline rush is set as off GCD
When after using adrenaline rush once, once it's available again, the rotation is stuck until I activate Adrenaline rush.

### Icon Behavior

None

**Comment by Seny951** [comment]
can you provide a screenshot of where it gets stuck please?

**Comment by Nelyaan** [comment]
seams to be stuck on finisher moves

**Comment by Nelyaan** [comment]
![Capture](https://github.com/user-attachments/assets/65eb7436-611c-4911-8a14-ba92b30f6839)

**Comment by Seny951** [comment]
Ahh I see, that's because you have improve adrenaline rush talented and it's basing your suggestion on using adrenaline rush and getting full combo points.

**Comment by Nelyaan** [comment]
it's not chacked

**Comment by Nelyaan** [comment]
![Capture](https://github.com/user-attachments/assets/dbd2e817-7ad1-4213-b583-0c2eacb2e9c4)

**Comment by Seny951** [comment]
sorry I meant The Improved Adrenaline Rush talent.

I will remove the dependency on using Improved AR from the finisher checks unless combos is enabled.

**Comment by Nelyaan** [comment]
thank you very much for your so fast answer and for all your work on the addon.

**Comment by Nelyaan** [comment]
"I will remove the dependency on using Improved AR from the finisher checks unless combos is enabled." 
That would be perfect

**Comment by Seny951** [comment]
This should be resolved in the latest commit with AR set as on OffGCD & Stealth / AR Combos disabled.

**Comment by Cilraaz** [comment]
Reported as fixed by the author. No further reports of issues. Closing.
