### ISSUE TITLE
[Bug]: [Item Use] Binding of Binding is being suggested

### ISSUE THREAD

**Issue by Ragowit** [herotc/hero-rotation#1089]
### What version of HeroRotation are you using?

11.0.2.19

### What version of HeroLib are you using?

11.0.2.04

### What version of HeroDBC are you using?

11.0.2.02

### What is the issue?

The ring Binding of Binding is being suggested. It does have a Use effect, but it's a no-combat one.

Wowhead: https://www.wowhead.com/item=215133/binding-of-binding

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-lib/commit/9e58be2774762fa05eb62d3d873e670ff0d7e4dd
