### ISSUE TITLE
[Bug]: VDH fel dev and meta always shows up as main icon

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1090]
### What version of HeroRotation are you using?

11.0.2.20

### What version of HeroLib are you using?

11.0.2.05

### What version of HeroDBC are you using?

11.0.2.02

### What is the issue?

For vengeance:
Meta shows up on main icon even when Suggested is selected on class displaystyles page.
Same with Fel Dev when Show GCD as Off GCD is selected on veng page.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
That's intended. At that point in the rotation, if Meta is set to OffGCD, it will always result in an OffGCD Meta suggestion and a Pool icon. Instead, we simply move Meta to the main icon.
