### ISSUE TITLE
[Bug]: [Outlaw] Between the Eyes being recommended when vanish is below 45s

### ISSUE THREAD

**Issue by fpsmax60** [herotc/hero-rotation#1095]
### What version of HeroRotation are you using?

11.0.2.22

### What version of HeroLib are you using?

11.0.2.07

### What version of HeroDBC are you using?

11.0.2.03

### What is the issue?

![btebug](https://github.com/user-attachments/assets/f662e03e-c750-4bfa-a3f9-353746987d6c)
Hello, I noticed a small bug where BtE is being recommended to press while Vanish is still on cooldown. While this is the intended way to play, it seems to be ignoring the rule of not using BtE when your Vanish cooldown is below 45 seconds.

### Icon Behavior

None

**Comment by Seny951** [comment]
Not a bug, the condition for using BtE outside of stealth has changed:

actions.finish+=/between_the_eyes,if=talent.crackshot&(cooldown.vanish.remains>45|**_talent.underhanded_upper_hand&talent.without_a_trace&(buff.adrenaline_rush.remains>10_**|buff.adrenaline_rush.down&cooldown.adrenaline_rush.remains>45))&(raid_event.adds.remains>8|raid_event.adds.in<raid_event.adds.remains|!raid_event.adds.up)

The part in bold is triggering your BtE usage here.

This being said I've already added a new setting to toggle this usage on and off entirely and also when on I've added a 30 second buffer (may end up tweaking this as I play more) that prevents BtE being used in short fights to avoid the bug with BtE appearing to reset when breaking stealth with it on cooldown.

**Comment by fpsmax60** [comment]
ah I see, I didn't know the spec has changed, I guess I'm still use to playing it the old way. Thanks for clearing this up! appreciate it!
