### ISSUE TITLE
[Bug]: AOE target recognition only works through Chain Lightning Elemental Shaman

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#1096]
### What version of HeroRotation are you using?

11.0.2.22

### What version of HeroLib are you using?

11.0.2.07

### What version of HeroDBC are you using?

11.0.2.03

### What is the issue?

AOE on a shaman only works when Chain Lightning is used. Please add Liquid Magma Totem Earthquake Tempest etc. Because the addon as soon as stops using Chain Lightning turns on ST mode and until I press Chain Lightning AOE will not work. It will ignore most AOE spells and will only turn on from Chain Lightning. Please add spell variability. You can even trivially include an elemental that also uses lightning, which can also activate AOE mode.     

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Elemental AoE triggers have been updated in HeroLib version 11.0.2.08
