### ISSUE TITLE
[Bug]: Retribution Paladin Rotation only cycles between Judgment and Blade of Justice

### ISSUE THREAD

**Issue by Santotaku** [herotc/hero-rotation#1098]
### What version of HeroRotation are you using?

11.0.2.25

### What version of HeroLib are you using?

11.0.2.08

### What version of HeroDBC are you using?

11.0.0.03

### What is the issue?

Herorotation will only recommend Blade of Justice and Judgement on rotation. When they are both on cooldown it recommends pooling and never recommends spending holy power. 

It will recommend Shield of Vengence off GCD, but that's it.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Retribution has not been updated for 11.0
