### ISSUE TITLE
[Bug]: Lua Error

### ISSUE THREAD

**Issue by wheatbread** [herotc/hero-rotation#1102]
### What version of HeroRotation are you using?

11.0.2.25

### What version of HeroLib are you using?

11.0.2.08

### What version of HeroDBC are you using?

11.0.2.03

### What is the issue?

Got the following error just now in LFR on outlaw rogue, in retail 11.0.2:

73x HeroRotation/Core.lua:229: attempt to index field '?' (a string value)
[string "@HeroRotation/Core.lua"]:229: in function <HeroRotation/Core.lua:222>
[string "@HeroRotation/Core.lua"]:240: in function <HeroRotation/Core.lua:239>
[string "@HeroRotation_Rogue/Outlaw.lua"]:420: in function <HeroRotation_Rogue/Outlaw.lua:388>
[string "@HeroRotation_Rogue/Outlaw.lua"]:499: in function <HeroRotation_Rogue/Outlaw.lua:491>
[string "@HeroRotation_Rogue/Outlaw.lua"]:816: in function `?'
[string "@HeroRotation/Main.lua"]:476: in function <HeroRotation/Main.lua:455>

Locals:
Skipped (In Encounter)

### Icon Behavior

None

**Comment by Seny951** [comment]
There is a new version of HR 11.0.2.32 and there has been updates to all rogue profiles since 25. Can you update first and then let me know if you see this issue again.

**Comment by Cilraaz** [comment]
No further report and reported as fixed by the author. Closing.
