### ISSUE TITLE
[Bug]: [Prot Warrior] unnecessary battleshout

### ISSUE THREAD

**Issue by SheepReaper** [herotc/hero-rotation#1105]
### What version of HeroRotation are you using?

11.0.2.25

### What version of HeroLib are you using?

11.0.2.08

### What version of HeroDBC are you using?

11.0.2.03

### What is the issue?

It might be specific to Delves, but Battleshout keeps getting suggested even though the buff is applied. Maybe it's Brann's fault for not accepting the buff? Maybe the party is a lie?

### Icon Behavior

None

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/77322a190537ddaa34b0de1bcc98c94ad053c0e8

Please let us know if it continues to occur. Thanks for the report!
