### ISSUE TITLE
[Bug]: [Prot Warrior] - Ascension trinket hiding heal suggestions

### ISSUE THREAD

**Issue by SheepReaper** [herotc/hero-rotation#1106]
### What version of HeroRotation are you using?

11.0.2.25

### What version of HeroLib are you using?

11.0.2.08

### What version of HeroDBC are you using?

11.0.2.03

### What is the issue?

whenever the Imperfect Ascendancy Serum trinked is off cooldown it's suggested and hiding heals like ignore pain. Maybe it's not a bug, but maybe provide a toggle to prioritize heals?

### Icon Behavior

None

**Comment by Cilraaz** [comment]
You can change which icon location is used for both trinkets and defensives in the settings.

**Comment by SheepReaper** [comment]
Thanks, this works.
