### ISSUE TITLE
[Bug]: [Rogue] Cold Blood causing a lua error

### ISSUE THREAD

**Issue by timwoj** [herotc/hero-rotation#1110]
### What version of HeroRotation are you using?

11.0.2.38

### What version of HeroLib are you using?

11.0.2.10

### What version of HeroDBC are you using?

11.0.2.04

### What is the issue?

Something about Cold Blood is causing a lua error when it's available. All other cooldowns seem fine except for that one.

```
10643x HeroRotation_Rogue/Assassination.lua:847: attempt to call field 'CooldownUp' (a nil value)
[string "@HeroRotation_Rogue/Assassination.lua"]:847: in function <HeroRotation_Rogue/Assassination.lua:751>
[string "@HeroRotation_Rogue/Assassination.lua"]:1211: in function `?'
[string "@HeroRotation/Main.lua"]:476: in function <HeroRotation/Main.lua:455>
```

### Icon Behavior

Icon disappears

**Comment by Seny951** [comment]
fixed, will be available in next release
