### ISSUE TITLE
[Bug]: [Hunter] Aspect of the Eagle range check issue

### ISSUE THREAD

**Issue by Nurbzz188** [herotc/hero-rotation#1112]
### What version of HeroRotation are you using?

11.0.2.38

### What version of HeroLib are you using?

11.0.2.10

### What version of HeroDBC are you using?

11.0.2.04

### What is the issue?

Seems to be an issue with the MBRS range checking as it does not suggest anything beyond Explosive shot or Wildfire bomb when out of melee range with eagle up and it just displays the pooling icon instead.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
Fixed as of commit https://github.com/herotc/hero-rotation/commit/389dec80c873d2b9e72c09fd3aa7d73007a58bc3
