### ISSUE TITLE
[Bug]: Still getting lua error spam on outlaw rogue

### ISSUE THREAD

**Issue by wheatbread** [herotc/hero-rotation#1116]
### What version of HeroRotation are you using?

11.0.2.41

### What version of HeroLib are you using?

11.0.2.10

### What version of HeroDBC are you using?

11.0.2.04

### What is the issue?

Hi,

I'm sorry for the delayed reply-- it took me a bit of time to get back to test.  I'm still getting spammed with the lua error when playing my outlaw rogue:

473x HeroRotation/Core.lua:229: attempt to index field '?' (a string value)
[string "@HeroRotation/Core.lua"]:229: in function <HeroRotation/Core.lua:222>
[string "@HeroRotation/Core.lua"]:240: in function <HeroRotation/Core.lua:239>
[string "@HeroRotation_Rogue/Outlaw.lua"]:420: in function <HeroRotation_Rogue/Outlaw.lua:388>
[string "@HeroRotation_Rogue/Outlaw.lua"]:499: in function <HeroRotation_Rogue/Outlaw.lua:491>
[string "@HeroRotation_Rogue/Outlaw.lua"]:816: in function `?'
[string "@HeroRotation/Main.lua"]:476: in function <HeroRotation/Main.lua:455>

Locals:
Skipped (In Encounter)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
The lines referenced in your stack trace are not lines that could possibly generate errors. I would suggest removing the addon files (you don't need to clear your settings) and re-installing.

**Comment by wheatbread** [comment]
Hi, 

Thank you for the response!

I did a complete clean reinstall (removed the files and reinstalled), and am still getting the error.  

I'm not sure if it is relevant, but I regularly swap between specs for m+ and raid (outlaw, assassination, and a little sub), and seem to only get the error on outlaw.  

Might you have any further ideas on how to fix this?

**Comment by Cilraaz** [comment]
Please post a new copy of the lua error. The line numbers simply don't make sense from the one originally posted. It's possible it was a corrupted stack trace or some other issue that gave incorrect information in the error that was previously posted. Also, please post an export string of the talent build that you are using.
