### ISSUE TITLE
[Bug]: monk lua bug

### ISSUE THREAD

**Issue by J603** [herotc/hero-rotation#1118]
### What version of HeroRotation are you using?

Latest 

### What version of HeroLib are you using?

Latest 

### What version of HeroDBC are you using?

Latest 

### What is the issue?

![IMG_20240925_100351](https://github.com/user-attachments/assets/3e8f0faf-940d-4526-ae87-a502cc6f560b)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/165a886ce9c29b328b507409d63e6ab67ebdd490

**Comment by J603** [comment]
Thanks guys
