### ISSUE TITLE
[Bug]: [Shadow] Kaheti Shadeweaver's Emblem trinket

### ISSUE THREAD

**Issue by Ragowit** [herotc/hero-rotation#1122]
### What version of HeroRotation are you using?

11.0.2.51

### What version of HeroLib are you using?

11.0.2.16

### What version of HeroDBC are you using?

11.0.2.04

### What is the issue?

HeroRotation tells me to use the trinket, when I can't. This is probably because I don't have any stacks of Kaheti Shadeweaver's Dark Ritual at the time.

Trinket: https://www.wowhead.com/item=225651/kaheti-shadeweavers-emblem
Stack: https://www.wowhead.com/spell=455464/kaheti-shadeweavers-dark-ritual

Great comment that explains the trinket more in-depth: https://www.wowhead.com/item=225651/kaheti-shadeweavers-emblem#comments:id=5957440

### Icon Behavior

None

**Comment by Cilraaz** [comment]
I added logic to HeroLib in commit https://github.com/herotc/hero-lib/commit/0923a520f30d7778860227f93c3d20e9669baea0

This should stop suggestions when:
- Less than 4 stacks of the buff exist, unless the buff will expire in the next 3 seconds
- The buff doesn't exist at all

Please let me know if the change doesn't work as expected.
