### ISSUE TITLE
[Bug]: [Rogue] GCD Icon Overlapping with Adrenaline Rush

### ISSUE THREAD

**Issue by Thestral12** [herotc/hero-rotation#1124]
### What version of HeroRotation are you using?

11.0.2.52

### What version of HeroLib are you using?

11.0.2.17

### What version of HeroDBC are you using?

11.0.2.04

### What is the issue?

I have show off GCD checked.  It will appear off the GCD until combat starts. 
![Screenshot 2024-10-03 093115](https://github.com/user-attachments/assets/bcff2b7c-a639-4152-9202-b6884c19fe20)
![Screenshot 2024-10-03 092457](https://github.com/user-attachments/assets/b0a6269f-eb6e-4b17-97fd-200ff8062fbb)
![Screenshot 2024-10-03 092450](https://github.com/user-attachments/assets/c4d7fa92-3ce9-4e8a-aa6e-29e38d1a83c8)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
That is a cast queue and is the intended behavior, regardless of your OffGCD setting.

**Comment by Seny951** [comment]
To turn this off disable these options:

![image](https://github.com/user-attachments/assets/75518e6a-6081-429a-9e26-3363ed2e3a0e)

They are showing you what your next suggestion will be after pressing an off gcd ability by acting as if you're already in that state i.e. stealth from using vanish / have full CPs from using improved AR.

**Comment by Thestral12** [comment]
I assumed it was a bug because it was showing vanish and bte when I only had one cp. Sent from my iPhoneOn Oct 3, 2024, at 10:18, James Sen ***@***.***> wrote:﻿
To turn this off disable these options:
image.png (view on web)
They are showing you what your next suggestion will be after pressing an off gcd ability by acting as if you're already in that state i.e. stealth from using vanish / have full CPs from using improved AR.
