### ISSUE TITLE
[Bug]: Augmentation Evoker Lua Error

### ISSUE THREAD

**Issue by shinyisme** [herotc/hero-rotation#1130]
### What version of HeroRotation are you using?

11.0.2.66

### What version of HeroLib are you using?

11.02.22

### What version of HeroDBC are you using?

11.02.04

### What is the issue?

Lua Error after casting any channeling spell:

Message: ...nterface/AddOns/HeroRotation_Evoker/Augmentation.lua:671: attempt to index field 'TomorrowToday' (a nil value)
Time: Mon Oct 21 15:20:35 2024
Count: 190
Stack: ...nterface/AddOns/HeroRotation_Evoker/Augmentation.lua:671: attempt to index field 'TomorrowToday' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroRotation_Evoker/Augmentation.lua"]:671: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:476: in function <Interface/AddOns/HeroRotation/Main.lua:455>

Locals: 

### Icon Behavior

None

**Comment by shinyisme** [comment]
*Upheaval cast not all channeling spells

**Comment by Cilraaz** [comment]
This should be fixed now, as of commit https://github.com/herotc/hero-rotation/commit/8ee2d044d0dba1cc12abb51da028c263f5e476d8
