### ISSUE TITLE
[Bug]: Lua Errors for Rogue

### ISSUE THREAD

**Issue by wheatbread** [herotc/hero-rotation#1132]
### What version of HeroRotation are you using?

11.0.5.04

### What version of HeroLib are you using?

11.0.5.02

### What version of HeroDBC are you using?

11.0.5.01

### What is the issue?

Hi, it's me again!

I previously reported this error being spammed as outlaw.  I stopped playing outlaw and fully committed to assassin, so I stopped seeing the error. 

However, today after updating HeroRotation, I am seeing the error (that says "outlaw") as assassin.  I did a full uninstall and deleted all saved variables for HeroRotation, Herolib, etc. then reinstalled.  Still getting the error when I dps.  

This is the error:

`736x HeroRotation/Core.lua:229: attempt to index field '?' (a string value)
[string "@HeroRotation/Core.lua"]:229: in function <HeroRotation/Core.lua:222>
[string "@HeroRotation/Core.lua"]:240: in function <HeroRotation/Core.lua:239>
[string "@HeroRotation_Rogue/Outlaw.lua"]:420: in function <HeroRotation_Rogue/Outlaw.lua:388>
[string "@HeroRotation_Rogue/Outlaw.lua"]:499: in function <HeroRotation_Rogue/Outlaw.lua:491>
[string "@HeroRotation_Rogue/Outlaw.lua"]:816: in function `?'
[string "@HeroRotation/Main.lua"]:476: in function <HeroRotation/Main.lua:455>

Locals:
Skipped (In Encounter)`

This is the build I'm using:  CMQAA0tw2gAD7pPTLoW5IGZDeMjZmZGmhHYAAAAAAY2gtZAAAAAAottZmhZmxYmZWmlxYwMzMzgZmZbbZMDwmZZgBsEsMMBGWA

(It's basically the Wowhead m+ build, except with Blackjack instead of Tricks.)

P. S. Tested outlaw just now on the dummy and haven't reproduced the error in that spec. 

### Icon Behavior

None

**Comment by wheatbread** [comment]
Thank you for the update!  I tested with assassin and outlaw on the dummy and the error hasn't resurfaced so far.  

Have keys later, so I can test there and report back if that changes.

**Comment by wheatbread** [comment]
No error in keys, cheers!

**Comment by Seny951** [comment]
No Problem & thanks for the report.
