### ISSUE TITLE
[Enhancement]: Add Show GCD as Off GCD toggle for Demolish

### ISSUE THREAD

**Issue by daturst** [herotc/hero-rotation#1143]
### What feature would you like to have added?

I am running Warlords Torment and sometimes I'm just a few globals away from Avatar coming off cooldown. I'd like Demolish to be in the smaller uper icons instead, so I can continue with the regular rotation for a few globals, until Avatar comes off cooldown.

**Comment by Cilraaz** [comment]
Added a DisplayStyle setting for Demolish in commit https://github.com/herotc/hero-rotation/commit/3e093b93fb59c650c27a95ccd9184c9feb098114

You can grab the update from github or it will be included in future version 11.0.5.24.

**Comment by daturst** [comment]
I'm a total noob. How can I manually update this?

**Comment by daturst** [comment]
Thanks for adding this. However, I do appreciate that there are people out there, who'd like Demolish in the big main box. I'd suggest adding it as a toggle-able option under HR->Warrior->Arms->

**Comment by Cilraaz** [comment]
It's a DisplayStyle option. You can put it in whichever icon area you like. There's no need for a secondary option.
