### ISSUE TITLE
[BM Hunter] Pets

### ISSUE THREAD

**Issue by Spedwards** [herotc/hero-rotation#126]
If it can be done, it may be a good idea to add in Revive/Call Pet, or at the very least, not return Kill Command when you have no active pet.

**Comment by nicolede** [comment]
i have added
`	CallPet						  = Spell(883),`
and 

`    if Everyone.TargetIsValid() then
	  if not IsPetActive() then
		if AR.Cast(S.CallPet) then return ""; end
	  end`
 need to find for revive

**Comment by aethys256** [comment]
Has been added in https://github.com/herotc/hero-rotation/commit/9c4f7c4b2167af305fc3608fa281c5ee9fba0e0a :)
