### ISSUE TITLE
[UI] Highlight the suggested ability on action bars

### ISSUE THREAD

**Issue by mspykerez** [herotc/hero-rotation#133]
Can you add an option to highlight the suggested ability to use on our action bar icons like a border color, an overlay or spell flash of some kind? I would prefer if you used the blizzard default highlight but with different colors for different abilities if possible.

**Comment by yoshimo** [comment]
using default might be misleading because sometimes abilities "proc" and glow in the default ui, for example when tiger palm makes blackout kick free of charge.

**Comment by mspykerez** [comment]
Heres what I suggest the highlights to look like https://media.wago.io/screenshots/dnSI1JGDv/5c311eaa2f97872c09791a2e.gif from here https://wago.io/dnSI1JGDv

**Comment by mspykerez** [comment]
Relevant ? https://wow.curseforge.com/projects/libcustomglow

**Comment by dMopp** [comment]
Push, this is my personal missing keyfeature :D (Maybe look at conro)

**Comment by SulpherStaer** [comment]
I am aware the focus is currently on getting the specs ready for the pre-release and shadowlands, but am I allowed to put a bounty on this? This is a feature I'd really really want! :D

**Comment by ArcticLatent** [comment]
Is this an upcoming feature?

**Comment by codengine** [comment]
Any updates here? I'd also like to have that feature.

**Comment by Cilraaz** [comment]
SpellFlashCore support was added in early August 2023
