### ISSUE TITLE
[Arcane Mage] Rotation drops out

### ISSUE THREAD

**Issue by Barleduq** [herotc/hero-rotation#145]
Not sure how to phrase it.  I'm a relatively new 110 on this toon, opening up argus. Before I came down here, I turned on Solo mode (sacrifice dps for survivability).  

As I was facing the mobs in the area around where Talestra the Vile spawns in the building, it would suggest the following:  Arcane Blast, sometimes 2 or three times, then Mark of Aluneth, Mirror Image, Arcane Power, and then... nothing.  I'm trying to train myself to watch the suggestions, so I end up button mashing at this point because I'm not watching what pops up when. I *think* it might start back with Arcane Blast when I have a new target, but I'm not sure. My talents are Arcane Familiar, Slipstream, Mirror Image, Supernova, Chrono Shift, Unstable Magic, and Arcane Orb. (I think that's one of the builds Icy Veins suggests, or close to it.)  I'll note that I had Arcane power as ticked to be off gcd, yet it was suggesting it in the main icon. 

It is also, only very rarely, suggesting Presence of Mind, which I would think would make sense to use in front of Arcane Blast? Also had it ticked as off gcd, and only being suggested in the main button. 

ETA: I turned solo mode off, and it was still doing it.

**Comment by tristangreeno** [comment]
I would suspect it has something to do with Arcane Familiar?

**Comment by aethys256** [comment]
Closing since BfA is around the corner and the discussion is no longer relevant.
