### ISSUE TITLE
[Havoc / BM / Mages] Interrupt / with stun not showing up?

### ISSUE THREAD

**Issue by Barleduq** [herotc/hero-rotation#147]
So far I've used this on Havoc DH, BM hunter, and all three mage specs, doing world quests and heroic dungeon pugs. I haven't yet seen any suggestion of interrupts show up, even when DBM was telling me to interrupt things.

**Comment by Kutikuti** [comment]
Some specs don't have interrupt included in their rotations. They have to be updated

**Comment by Cilraaz** [comment]
All specs have now had interrupts added.
