### ISSUE TITLE
[UI] When addon is unlocked main icon to move does not show

### ISSUE THREAD

**Issue by mspykerez** [herotc/hero-rotation#154]
As you can see here https://imgur.com/a/BdwLD the main icon is not shown when we unlock the Addon...

**Comment by aethys256** [comment]
I've never experienced this, might it be related to masque @ghr74 ?

**Comment by abura101** [comment]
I have this exact issue, even tried disabling most of my addons, like elvui etc

**Comment by ghr74** [comment]
Should hopefully be fixed in https://github.com/herotc/hero-rotation/commit/320725a61389cba9be0a90282d2f51facc1a811c
