### ISSUE TITLE
[DM Warlock] Doom

### ISSUE THREAD

**Issue by drugexe** [herotc/hero-rotation#162]
Is there a reason Doom isn't in the rotation? instead its replaced with Demonwrath

**Comment by drugexe** [comment]
It’s not currently showing on my rotations.

**Comment by isugimpy** [comment]
Perhaps it's to do with your spec?  If you have Hand of Doom, casting Doom itself is pointless, so it doesn't offer it.  I'm currently 1212123 and Doom is offered as a suggestion when I'm moving if it's within the pandemic window, if I'm short on shards and in the pandemic window, or when it's expired, from what I've seen.

**Comment by aethys256** [comment]
Closing since BfA is around the corner and the discussion is no longer relevant.
