### ISSUE TITLE
[Elemental] Not Showing Next Spell to Cast

### ISSUE THREAD

**Issue by tristangreeno** [herotc/hero-rotation#165]
When playing Elemental, Aethys is not accurately displaying the next spell to cast while casting another spell. The current spell being cast has to finish casting before correctly displaying the next spell to cast (behaving more like a melee than a spell-casting class).

**Comment by swaj** [comment]
I'm encountering this issue too.  Tried to take a stab at fixing it, but no luck yet.

**Comment by lithium720** [comment]
We're working on it, it's likely we'll have something before BfA. We'll keep you updated :)

**Comment by Cilraaz** [comment]
This is no longer an issue. The profile currently suggests the next spell correctly while a spell is being cast.
