### ISSUE TITLE
[Balance Druid] Moon spells sometimes shows the wrong icon

### ISSUE THREAD

**Issue by mspykerez** [herotc/hero-rotation#169]
Sometimes moon spells shows the wrong icon, it often occurs when we have full moon or half moon available to use and it shows the new moon icon instead. 

I'm not sure but I think it happens more often when we have half moon or full moon available to use and we start combat with moonfire/sunfire and follow the normal rotation from there... at one point it will suggest to use a moon spell and that spells will always have the new moon icon regardless of us only having available half moon or full moon.

**Comment by aethys256** [comment]
Closing since BfA is around the corner and the discussion is no longer relevant.
