### ISSUE TITLE
[UI] Always show a spell icon to use when in combat regardless of not having any target selected

### ISSUE THREAD

**Issue by mspykerez** [herotc/hero-rotation#170]
As the title says it would be great if we have an option to enable this. 

In some cases it would be helpful if we always have a predictive spell icon to use when no target is selected. For example when mobs are dying fast and you lose your target but you still have other mobs around but no icon is shown which makes you think that the fight is over when its not. 
Most useful in aoe situations with spells that do not require any target to be selected (starfall comes to mind and AFAIK the addon should know if there is any target in range to use it if you have enough resources). Or when you are single targeting and your target dies and you want to move to the next one without the need to selecting it since your next predictive spell should do that for you when you use it.

**Comment by aethys256** [comment]
AoE spell should be displayed whether or not you have a target, at least for melee.
Due to API limitations, it's not really possible to implement it nicely for ranged.
Blame Blizzard :/
