### ISSUE TITLE
Shown as OFF GCD & Keybindings

### ISSUE THREAD

**Issue by sparkiespaark** [herotc/hero-rotation#174]
Hey, I was wondering how can I make an ability show as toggle for example "Show as OFF GCD: Dark Arbiter" that is in the ingame settings? (these are just examples)

I have added in settings Death Coil as a OFF GCD:
    Unholy = {
		= {
        -- Abilities
        ArmyOfDead     = true,
        SummonGargoyle = true,
        DarkArbiter    = true,
	DeathCoil      = true
      },

Shows in game as a toggle, but the toggle doesn't do anything. What else do I need to change? 
Also is there a way to make a keybind for these toggles? Like keybind to toggle CD on and off, like that?

**Comment by aethys256** [comment]
You need to implement that in the rotation file aswell.
Nowadays we try to use a generator to do it, so you should also add it there: https://github.com/herotc/hero-rotation-generator
