### ISSUE TITLE
Frost mage - Blizzard being suggested when AoE is off

### ISSUE THREAD

**Issue by waynesteiner** [herotc/hero-rotation#180]
Also, Time warp and other CDs are not showing up as the smaller icons above the main suggestion

**Comment by roclo** [comment]
Im having the same problem.

**Comment by ghr74** [comment]
Are the blizzards that get suggested instant cast? If so, that seems to be in line with the APL and not an issue.

**Comment by roclo** [comment]
It isn’t instant. Takes several seconds.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by roclo** [comment]
Also can’t cast anything else, or move around while blizzard is dropping, in my experience.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EvanMichaels** [comment]
I fixed the AoE issue in https://github.com/herotc/hero-rotation/commit/2a142e53df6a2b5b46056a4739732991a642883e last night.

**Comment by roclo** [comment]
Thank you. Also a problem is frost mage counterspell.  Would appreciate help with that as well. Again, thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Phoebie** [comment]
Blizzard showing up with AOE rotation unselected seems to be persisting. Is this an issue in the APL?
