### ISSUE TITLE
[WIP] [Deathknight] new simulationcraft APL is out

### ISSUE THREAD

**Issue by FluffyDK** [herotc/hero-rotation#186]
https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/Tier21/T21_Death_Knight_Frost.simc

i'm working atm on the implementation.
I already created a PR for healing in solo mode.

in the current version there are also some issues, i'll try to fix.
for example:
- if you get out of melee range while BoS is ticking, it will suggest FrostStrike which is not a good idea :)
- "show off GCD" for some abilities are not working.
- make use of the switches for AoE and CDs
- add interrupts

**Comment by chrislopez24** [comment]
Thanks for open the issue, im already on both uh and frost update, have been busy with irl stuff
