### ISSUE TITLE
[Fury Warrior] Recklessness as option 

### ISSUE THREAD

**Issue by chubbyzz** [herotc/hero-rotation#192]
Hi, as a fury warrior the Recklessness should be a little icon like it was on 7.3.5, it should be an option, becouse sometimes i want to hold the Recklessness, if it is a lock Rotation skill, i cant see the normal rotation.
If i can set this on HeroRotation, please tell me how, i try to google it, but i dont find how to do it

**Comment by Nianel** [comment]
Hi, it's already an option. Interface > Addons > HeroRotation > Warrior > Fury > Show as Off GCD: Recklessness.

**Comment by chubbyzz** [comment]
tnx
