### ISSUE TITLE
Fire mage

### ISSUE THREAD

**Issue by S4B3R4** [herotc/hero-rotation#194]
Rotation suggests Pyro then it goes blank.

**Comment by Ankhy** [comment]
Date: 2018-07-23 15:28:39
ID: 1
Error occured in: Global
Count: 45
Message: ..\AddOns\HeroRotation_Mage\Fire.lua line 345:
   attempt to index global 'firestarter' (a nil value)
Debug:
   HeroRotation_Mage\Fire.lua:345: ?()
   HeroRotation\Main.lua:432:
      HeroRotation\Main.lua:410
Locals:
Precombat = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:94
ActiveTalents = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:116
CombustionPhase = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:134
RopPhase = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:200
StandardRotation = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:258
(*temporary) = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:86
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'firestarter' (a nil value)"
Everyone = <table> {
 TargetIsValid = <function> defined @Interface\AddOns\HeroRotation\Commons.lua:24
 AoEToggleEnemiesUpdate = <function> defined @Interface\AddOns\HeroRotation\Commons.lua:36
 UnitIsCycleValid = <function> defined @Interface\AddOns\HeroRotation\Commons.lua:45
 Interrupt = <function> defined @Interface\AddOns\HeroRotation\Commons.lua:55
 CanDoTUnit = <function> defined @Interface\AddOns\HeroRotation\Commons.lua:50
}
UpdateRanges = <function> defined @Interface\AddOns\HeroRotation_Mage\Fire.lua:76
S = <table> {
 Fireball = <table> {
 }
 ArcaneIntellect = <table> {
 }
 Kindling = <table> {
 }
 HotStreakBuff = <table> {
 }
 Firestarter = <table> {
 }
 MirrorImage = <table> {
 }
 Pyroblast = <table> {
 }
 CombustionBuff = <table> {
 }
 KaelthasUltimateAbilityBuff = <table> {
 }
 Flamestrike = <table> {
 }
 AlexstraszasFury = <table> {
 }
 TimeWarp = <table> {
 }
 Meteor = <table> {
 }
 BloodFury = <table> {
 }
 IncantersFlowBuff = <table> {
 }
 Scorch = <table> {
 }
 HeatingUpBuff = <table> {
 }
 Combustion = <table> {
 }
 FlamePatch = <table> {
 }
 EruptingInfernalCoreBuff = <table> {
 }
 FireBlast = <table> {
 }
 RuneofPower = <table> {
 }
 LivingBomb = <table> {
 }
 Berserking = <table> {
 }
 Counterspell = <table> {
 }
 DragonsBreath = <table> {
 }
 RuneofPowerBuff = <table> {
 }
 BlastWave = <table> {
 }
}
Player = <table> {
 AttackPowerDamageMod = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:61
 RunicPowerDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:362
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:599
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:219
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:668
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:95
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:257
 Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:645
 InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:68
 RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:98
 ArcaneChargesDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:630
 MaelstromPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:510
 ArcaneCharges = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:615
 ActiveMitigationNeeded = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Tank.lua:61
 SoulShardsDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:427
 IsInWhitelistedVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:124
 PainDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:686
 AttackPower = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:57
 ChiDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:544
 PainDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Playe
AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  AskMrRobot, v59
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  DBMCore, v8.0.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.75
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  HandyNotes, vv1.5.1
  HeroCache, v8.0.1.02
  HeroLib, v8.0.1.02
  HeroRotation, v8.0.1.02
  HeroRotationMage, v
  Informant, v7.7.6000 (SwimmingSeadragon)
  MasterPlanA, vA
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  Stubby, v7.7.6000 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=514)

**Comment by aethys256** [comment]
Same as https://github.com/herotc/hero-rotation/issues/202, will move the discussion there, it's because it's not fully supported yet.
