### ISSUE TITLE
Frost Mage

### ISSUE THREAD

**Issue by roclo** [herotc/hero-rotation#198]
Counterspell is part of rotation and blocks progression to next dpell unless used

**Comment by lordthete** [comment]
I had the same problem, deleting settings and reinstalling addon fixed it for me.

**Comment by roclo** [comment]
Thanks. But what settings are you referring to?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Glynnyx** [comment]
@roclo 

> I had the same problem, deleting settings and reinstalling addon fixed it for me.

Can you confirm if this works please? I never found this issue when I reinstalled the addon from fresh.

**Comment by roclo** [comment]
The only thing that worked for me was downloading the update previously to the last one. It seems that the last update caused the problem.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aethys256** [comment]
@Glynnyx @ghr74 might want to add a check for interrupt setting there and then disabling interrupt would remove it.

**Comment by ghr74** [comment]
this is fixed for frost already in https://github.com/herotc/hero-rotation/commit/1d20ce6e1a5f8870f33763dc01f58cb8ed9b20d9
