### ISSUE TITLE
Fire Mage Alpha [8.0.1.03] lua Error>>  bool(firestarter.active) 

### ISSUE THREAD

**Issue by Darkmoded** [herotc/hero-rotation#202]
`121x HeroRotation_Mage\Fire.lua:352: attempt to index global 'firestarter' (a nil value) 
HeroRotation_Mage\Fire.lua:352: in function `?' 
HeroRotation\Main.lua:432: in function <HeroRotation\Main.lua:410> 
Locals: 
InCombatSkipped `

`  -- call_action_list,name=combustion_phase,if=cooldown.combustion.remains<=action.rune_of_power.cast_time+(!talent.kindling.enabled*gcd)&(!talent.firestarter.enabled|!firestarter.active|active_enemies>=4|active_enemies>=2&talent.flame_patch.enabled)|buff.combustion.up
  if (S.Combustion:CooldownRemainsP() <= S.RuneofPower:CastTime() + (num(not S.Kindling:IsAvailable()) * Player:GCD()) and (not S.Firestarter:IsAvailable() or not bool(firestarter.active) or Cache.EnemiesCount[40] >= 4 or Cache.EnemiesCount[40] >= 2 and S.FlamePatch:IsAvailable()) or Player:BuffP(S.CombustionBuff)) then
    local ShouldReturn = CombustionPhase(); if ShouldReturn then return ShouldReturn; end
  end`

 bool(firestarter.active)  <<

**Comment by aethys256** [comment]
Related to https://github.com/herotc/hero-rotation-generator not handling firestarter

**Comment by ghr74** [comment]
Hello,

this was already fixed 4 days ago in https://github.com/herotc/hero-rotation/commit/e9c2c224fc5f4472627361ad5a848d155d6b982b

Please make sure to update before reporting issues, especially for WIP specs, thank you.
