### ISSUE TITLE
Unholy DK

### ISSUE THREAD

**Issue by Ankhy** [herotc/hero-rotation#204]
Rotation stops if I turn CD's off.

**Comment by chrislopez24** [comment]
More info please, version? Talents? Gear?

**Comment by chrislopez24** [comment]
And If lua errors

**Comment by Ankhy** [comment]
This; 
and S.Apocalypse:CooldownRemainsP() > 5) or Target:DebuffStack(S.FesteringWound) > 4) and S.ArmyOfTheDead:CooldownRemainsP() > 5 
needs to be changed to:
and S.Apocalypse:CooldownRemainsP() > 5 and (HR.CDsON() or not HR.CDsON()) or Target:DebuffStack(S.FesteringWound) > 4) and (S.ArmyOfTheDead:CooldownRemainsP() > 5 and (HR.CDsON() or not HR.CDsON())  or something like that in the generic section

**Comment by Ankhy** [comment]
Sorry went to sleep and is currently at work. Will make the changes and a PR when I get back home, unless you've sorted it out 👍

**Comment by aethys256** [comment]
#207
