### ISSUE TITLE
[UI] Add alpha/transparency setting

### ISSUE THREAD

**Issue by Ruby437** [herotc/hero-rotation#205]
I'd love to make it partially transparent, but sadly, there is no option to.

**Comment by kots33** [comment]
i would also love to make all the icons black, and only show keybindings. is this able to do?

**Comment by aethys256** [comment]
That's a good idea, flagging it as enhancement.
No ETA tho.

**Comment by Kutikuti** [comment]
Done in https://github.com/herotc/hero-rotation/commit/7d70e06034ea63d7b6eb63d93f004761b9c88776
