### ISSUE TITLE
Frost Mage 

### ISSUE THREAD

**Issue by phantom1004** [herotc/hero-rotation#208]
Something i noticed with the latest update is in the frost mage rotation its saying "Counterspell" should be used, regardless of the mob, i don't really know what causes it to replicate it, but it should be easy to see when using the addon as a frost mage

**Comment by Gnoma69** [comment]
I had that issue too on the various specs.
I changed all of them to this:

  -- counterspell,if=target.debuff.casting.react
  if S.Counterspell:IsCastableP() and Settings.General.InterruptEnabled and Target:IsInterruptible() and (true) then
    if HR.CastAnnotated(S.Counterspell, false, "Interrupt") then return ""; end
  end

**Comment by ghr74** [comment]
This was fixed in https://github.com/herotc/hero-rotation/commit/dac240f63d793b037ab1750c4ed47b7e7e1f4e78 . Please ensure you have the most recent version, especially when reporting issues with WIP builds.
