### ISSUE TITLE
how to only show keybindings

### ISSUE THREAD

**Issue by kots33** [herotc/hero-rotation#212]
hello. what i want to do is to alter the ui file, because i only want to see keybindings in front of a black font. can you please tell me what line do i have to alter in order to see only the keybinding? thank you in advance

**Comment by ghr74** [comment]
Hello,
this change is not in the scope of the addon. What would you need this for anyways? Thanks for the suggestion but we'll have to respectfully decline.

**Comment by kots33** [comment]
hello again. i know that this is not the scope of this addon, but
unfortunately, i have a misfunction in my eyes, and i am confusing the 3
basic colours. i don't know the english word for my eyes desease. i have
this discolouration 6 months now, and it's very hard for me to understand
the abilities icon, in my wow interface. this is why i want everything to
be shown as black and white. no other reason. anyway i thought that a
simple change in the coding files would be easy to fulfil my request.
didn't know that this is a hard one. thank you anyways.

2018-07-29 6:50 GMT+03:00 ghr74 <notifications@github.com>:

**Comment by skasch** [comment]
For color blindness, Blizzard developed a colorblind mode allowing the game to display colors with improved contrast. You probably want to check that out, as this will probably solve your issues.

https://worldofwarcraft.com/en-us/news/17964863/new-colorblind-support-in-patch-6-1
