### ISSUE TITLE
Feral Druid

### ISSUE THREAD

**Issue by cerravox** [herotc/hero-rotation#214]
Its all wrong. Redo.

**Comment by cerravox** [comment]
Just try it. Tells u to regrowth but it’s not even proc

**Comment by ghr74** [comment]
Hello, precasting regrowth is correct pre-combat. If you refer to it being stuck on that OOC, this was already fixed in https://github.com/herotc/hero-rotation/commit/5ca84519cc2629ea1b835f6764665db3c4a33798
