### ISSUE TITLE
Retribution Paladin

### ISSUE THREAD

**Issue by SemperYoda** [herotc/hero-rotation#215]
Just wanted to say great addon.  I have just recently started using this one and have found that I like it very much.  I noticed that Divine Storm recommends at 2 targets.  Everything I have read says to cast Templar's Verdict at 2 targets and below, while DS at 3+ targets unless you have Divine Judgement talent.  Also Wake of Ashes talent and Hammer of Wrath don't seem to be included in the rotation if these talents are selected.  Not sure if it is an issue or I am just doing something wrong.

**Comment by chrislopez24** [comment]
Hi! Thanks for the love, unfortunately, retribution is not updated for BfA yet.
