### ISSUE TITLE
Fearl Druid [alpha] - precombat bugs

### ISSUE THREAD

**Issue by Darkmoded** [herotc/hero-rotation#216]
**Regrowth is allways returns true**:   when talented with bloodtalons –  
needs >> and not Player:Buff(S.BloodtalonsBuff) 

**Cat form called when in Cat form**: 
Player:BuffDownP(S.CatForm)  returns true while in cat form.   
There is a bug/Problem with BuffDownP out of combat? 
not Player:Buff(S.CatForm) <<< works! 

**Prowl shown when prowling**: 
Player:BuffDownP(S.Prowl) should be using S.ProwlBuff + BuffDownP bug? 
not Player:Buff(S.ProwlBuff ) <<< works! 

The rotation works good BTW!

Cheers

**Comment by ghr74** [comment]
Precombat regrowth fixed in https://github.com/herotc/hero-rotation/commit/5ca84519cc2629ea1b835f6764665db3c4a33798

Other two are not issues, tested ingame. Buff checks are already corrected in overrides.

Thanks for the report.

**Comment by Darkmoded** [comment]
Player:BuffDownP(S.Prowl) 

Prowl vrs Prowlbuff?

**Comment by ghr74** [comment]
They both have the same ID so it doesn't matter at all, just an artifact of auto-generating.
