### ISSUE TITLE
Fire mage [8.0.1.05]

### ISSUE THREAD

**Issue by Solanis** [herotc/hero-rotation#221]
HeroRotation_Mage\Fire.lua:135: attempt to index field 'LightsJudgment' (a nil value)
HeroRotation_Mage\Fire.lua:135: in function `CombustionPhase'
HeroRotation_Mage\Fire.lua:353: in function `?'
HeroRotation\Main.lua:432: in function <HeroRotation\Main.lua:410>

**Comment by ghr74** [comment]
This issue should already be fixed in the most current version, try the Alpha version on the twitch client (for HeroRotation and HeroLib) or wait for the next release to receive the fix.
