### ISSUE TITLE
Enhancement Rotation

### ISSUE THREAD

**Issue by xxchuoxx** [herotc/hero-rotation#229]
enhancement rotation calls a lots of rockbiter, give rockbiter more priority above stromstrike procs, keeps calling rockbiter with max resources, low or non existent lava lash to clean resources.

**Comment by lithium720** [comment]
Hello,

I double checked the Rockbiter casts, they are in line with the SimC T21 APL. Rockbiter is used as a filler when there isn't anything else that can be cast either. Seems like it's working as intended.
