### ISSUE TITLE
Arcan Mage [8.0] Arcan-Charge will allways return 0

### ISSUE THREAD

**Issue by Darkmoded** [herotc/hero-rotation#231]
Playing around with the Arcane Mage / hero-gen
Player:BuffStackP(S.ArcaneChargeBuff) << wrong call will always return 0
Player:ArcaneCharges() >> is the correct call
cheers!

**Comment by ghr74** [comment]
Thanks for the report, this is now fixed with https://github.com/herotc/hero-rotation-generator/commit/b1bbf316df9cf87f372e5ba6f3ad1906f57390a8 and https://github.com/herotc/hero-rotation/commit/b42e8445281a30b77644c8ed95569333af576c72 .
