### ISSUE TITLE
[Arcane] Shows Counterspell Whenever Enemy Casts

### ISSUE THREAD

**Issue by tristangreeno** [herotc/hero-rotation#234]
Even though I have interrupts turned off, the rotation suggests casting Counterspell every time the enemy casts, even if it's not interruptible.

**Comment by Glynnyx** [comment]
@tristangreeno for now, I have commented out Counterspell for all 3 specs, this is a enduring solution I understand but it will work in the interim. I have swamped with IRL work sadly. I committed the changes just now https://github.com/herotc/hero-rotation/commit/05083a73ab41b219293c151557f2a820d7538bc5

**Comment by Glynnyx** [comment]
I'll close this for now and create a task to remind myself
