### ISSUE TITLE
MM Hunter recommends aimed shot when focus starved

### ISSUE THREAD

**Issue by Zeldern** [herotc/hero-rotation#235]
It seems the MM Hunter rotation is recommending aimed shot when focus starved and at least 1 charge.

Sometimes I don't have the focus for 5+ seconds but it still shows.

**Comment by fyatre** [comment]
Having this same problem too as MM.
Not sure if related, but sometimes when my focus is capped I will be recommended steady shot over and over again.

If it helps, https://worldofwarcraft.com/en-us/character/arathor/Fyatre

**Comment by Vexiaa** [comment]
I can confirm that this problem is still an issue for MM spec. Sadly until this is fixed I have disabled this addon for my hunter. Thank you for your assistance in trying to resolve this matter.

**Comment by injustice4all** [comment]
Has there been any development on this?

Still recommending Aimed Shot while focus starved.

**Comment by Cilraaz** [comment]
MM Hunter profile was recreated from the latest SimC APL on Jan 17, 2019. This should no longer be an issue.
