### ISSUE TITLE
Hide while out of combat

### ISSUE THREAD

**Issue by Hinalover** [herotc/hero-rotation#236]
Add an option to only show while in combat or while targeting a target. I like a minimalist UI, and just like not having things show up while not in combat.

**Comment by Cilraaz** [comment]
Manually changed every spec to include Everyone.TargetIsValid() around opener spells (buffs, pet summons, etc will still be suggested with no target) to hide the icon when out of combat and no attackable target selected. Commit: https://github.com/herotc/hero-rotation/commit/9597a679308e591ade495766f70262a998ef24e8

Leaving this issue open, in case we want to add a toggle option or add this to HRGen.

**Comment by Cilraaz** [comment]
Going to mark this one duplicate to #128. The current TargetIsValid wrapper works, but I think we're looking for a longer-term solution.
