### ISSUE TITLE
Problem with Vol`Kall @Atal`Dazar, suggesting Charge all the time. Fury warrior

### ISSUE THREAD

**Issue by botelho11** [herotc/hero-rotation#238]
During the fight, even if you are at melee range the rotation keep suggesting the use of Charge.  And can you add an option to show Charge as Off GCD? Thanks and great work.

**Comment by dimatter** [comment]
+1

probably something with range cache

**Comment by Trelander84** [comment]
Same happens for the last boss of Grim Batol - and agree with the Charge as off GCD.

**Comment by itsbuddyman** [comment]
this is still and issue for me, any word on it? or are we stuck?

**Comment by Cilraaz** [comment]
No longer appears to be an issue.
