### ISSUE TITLE
[Priest|Shadow] Shadow Word Death gets recommended even if not chosen

### ISSUE THREAD

**Issue by AISORTH** [herotc/hero-rotation#241]
I assume because this line:

    if S.ShadowWordDeath:IsCastableP() and (not Player:BuffP(S.VoidformBuff) or 
    **(S.ShadowWordDeath:ChargesP() == 2 and Player:BuffStackP(S.VoidformBuff) < 15))** 
     and Target:HealthPercentage() < ExecuteRange()  then

       if HR.Cast(S.ShadowWordDeath) then return ""; end
        end

Shadow Word Death still gets recommended as a Shadow Priest even though the spell now became a talent choice on 75. *And even if it's not chosen as the talent of that tier.

Edit: Oh sorry, didn't see that you're not supposed to open issues for shadow. My bad :)!

**Comment by AISORTH** [comment]
Proposed Change:

    if S.ShadowWordDeath:IsCastableP() then
      if (not Player:BuffP(S.VoidformBuff) or (S.ShadowWordDeath:ChargesP() == 2 
      and Player:BuffStackP(S.VoidformBuff) < 15)) and Target:HealthPercentage() < ExecuteRange()  then
        if HR.Cast(S.ShadowWordDeath) then return ""; end
    end

**Comment by Kutikuti** [comment]
Fixed in https://github.com/herotc/hero-rotation/commit/59184f5d75ee224c7de131efae3b12f4800014ae
