### ISSUE TITLE
Frost Mage Summon Water Elemental

### ISSUE THREAD

**Issue by Satirica** [herotc/hero-rotation#242]
When the Water Elemental talent is taken the rotation calls for casting Summon Water Elemental when it is already active and at 100% health.  This is a new bug, within the last 2? days.  Today it was persistent in recommending SWE after each boss and each mob in a dungeon.  Thanks for all your hard work.

**Comment by towicode** [comment]
Can confirm, the issues stops when combat starts however.

**Comment by ghr74** [comment]
Please make sure you have both HeroLib and HeroRotation updated to twitch alpha / current github version. I haven't heard any reports of this issue after https://github.com/herotc/hero-lib/commit/59a6bcaa1b120ba409df28ddc1ea24e86b36badb.
