### ISSUE TITLE
Balance Druid Bug

### ISSUE THREAD

**Issue by tinyrage** [herotc/hero-rotation#245]
Message: Interface\AddOns\HeroRotation_Druid\Balance-Balance.lua:173: attempt to index field 'GCDasOffGcd' (a nil value)
Time: Sat Aug 18 14:27:35 2018
Count: 371
Stack: Interface\AddOns\HeroRotation_Druid\Balance-Balance.lua:173: attempt to index field 'GCDasOffGcd' (a nil value)

Getting this constantly when using the addon. Thanks!

**Comment by knoxz** [comment]
Did you look at the supported specs page?

**Comment by tinyrage** [comment]
Ah, nope, I'm a little new to this bug reporting thing, just trying to help out because I love this addon so much. No worries, I'll keep an eye peeled for an update! Thanks for the response. :)
