### ISSUE TITLE
Balance Druid

### ISSUE THREAD

**Issue by victorscones** [herotc/hero-rotation#247]
```
562x HeroRotation_Druid\Balance-Balance.lua:177: attempt to index field 'GCDasOffGcd' (a nil value)
HeroRotation_Druid\Balance-Balance.lua:177: in function <HeroRotation_Druid\Balance.lua:150>
HeroRotation_Druid\Balance-Balance.lua:334: in function `?'
HeroRotation\Main.lua:432: in function <HeroRotation\Main.lua:410>

Locals:
InCombatSkipped
```

I'm getting this error whenever I enter combat as a Balance Druid. I'm not seeing any icons for spells after entering combat, but they show up again as soon as I exit combat.

**Comment by ghr74** [comment]
Typo fixed in https://github.com/herotc/hero-rotation/commit/957986834e82e9d0c82ce8b3d750509833c3cd11, thanks for the report.
