### ISSUE TITLE
[General] Hide out of combat/hide until ability is ready options. 

### ISSUE THREAD

**Issue by lukeyboy89** [herotc/hero-rotation#250]
I really enjoy minimalist UIs and currently abilities are showing outside of combat.

Also, it would be nice to have an option to only show the icon when it's ready to be pressed. As someone who is using this add on to "learn" a new spec instead of becoming reliant on the add on to do well, it's nice to be able to play yourself and work out what you've done wrong after the fact

Just an idea.

**Comment by Mystler** [comment]
As I already mentioned in DMs, the addon always shows what to do next. If you want to "play yourself" and hide during GCD this still makes it (and thus the requested feature) completely useless. There is no history mode or something like that which you can actually use to evaluate your performance, atm.
