### ISSUE TITLE
Remove Small CD Box

### ISSUE THREAD

**Issue by Snichy** [herotc/hero-rotation#252]
Is there a way to remove the small 1 or 2 boxes above the main icon that show cooldowns?  I can tick the "Show as Off GCD" for that abilitybox and they disappear, but then the ability appears in the main rotation which I want to avoid.  I basically want to blacklist an ability (Ironskin Brew) so it appears nowhere as I decide when to use it or not.

**Comment by aethys256** [comment]
Until such option is added on a per-ability basis, it is not possible.
Considering Brewmaster is not supported coming into SL yet, I'm closing the issue.
