### ISSUE TITLE
Please add DK Death Strike and Pally Inquisition to rotation for all specs that use it. 

### ISSUE THREAD

**Issue by zaberwookie** [herotc/hero-rotation#255]
And Wake of Ashes, Hammer of Wrath for ret pallies. Pretty please with a cherry on top! <3

**Comment by Cilraaz** [comment]
Death Strike has been in the Frost and Blood profiles for a while. I added it to Unholy as well. It will only function in solo mode for Frost and Unholy.

Ret Paladin was updated on Feb 7, 2019. It should be in good shape now.
