### ISSUE TITLE
Unholy Death knight Dark Transformation and Control Undead

### ISSUE THREAD

**Issue by DLSauron** [herotc/hero-rotation#256]
With a lot of the new BFA dungeons having undead I have noticed with using Control Undead that HR gets stuck on wanting to cast Dark Transformation even though you are unable to cast it as you do not have out your normal pet.

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/cbed9f5dae0fb1024ffbf62079d48f7d834f3383
