### ISSUE TITLE
Hunter: BM LUA error

### ISSUE THREAD

**Issue by OlCiFr** [herotc/hero-rotation#257]
Go this one and it seems to correlate when I move my toon during a fight - not 100% sure

Message: ...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:203: attempt to index global 'AR' (a nil value)
Time: Fri Aug 31 08:47:49 2018
Count: 17
Stack: ...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:203: attempt to index global 'AR' (a nil value)
...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:203: in function `?'
Interface\AddOns\HeroRotation\Main.lua:432: in function <Interface\AddOns\HeroRotation\Main.lua:410>

Locals: (*temporary) = nil
(*temporary) = <table> {
 LastRemovedFromPlayerTime = 405507.197
 LastAppliedOnPlayerTime = 405492.257
 SpellType = "Player"
 LastHitTime = 405492.257
 LastCastTime = 405492.257
 LastDisplayTime = 405492.099
 SpellID = 19574
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'AR' (a nil value)"
HL = <table> {
 UnregisterForCombatPrefixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:198
 Tier21_2Pc = false
 LoadRestores = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:300
 MythicDungeon = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\MythicDungeon.lua:47
 RegisterForCombatPrefixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:109
 LiveRealm = <function> defined @Interface\AddOns\HeroLib\Core.lua:36
 GetEnemies = <function> defined @Interface\AddOns\HeroLib\Misc\Enemies.lua:28
 CombatEnded = 0
 RangeTracker = <table> {
 }
 GetInstanceInfo = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:32
 RegisterForCombatSuffixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:124
 MainFrame = HeroLib_MainFrame {
 }
 OutOfCombatTime = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:94
 UnregisterForSelfCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:170
 Latency = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:73
 Utils = <table> {
 }
 LoadOverrides = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:306
 Pulse = <function> defined @Interface\AddOns\HeroLib\Main.lua:29
 UnregisterForCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:156
 TTDRefresh = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:49
 SpecID_ClassesSpecs = <table> {
 }
 GUI = <table> {
 }
 UnregisterForCombatSuffixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:212
 Timer = <table> {
 }
 OffsetRemains = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:116
 MAXIMUM = 40
 FindKeyBinding = <function> defined @Interface\AddOns\HeroLib\Events\KeyBinding.lua:142
 UnitNotInFront = <table> {
 }
 RegisterForPetCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:94
 CacheHasBeenReset = false
 LastUnitCycledTime = 0
 BetaRealm = <function> defined @Interface\AddOns\HeroLib\Core.lua:46
 GetInstanceDifficulty = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:67
 HasTier = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Equipment.lua:113
 Tier19_2Pc = false
 Equipment = <table> {
 }
 Tier20_2Pc = false
 RegisterForCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:64
 LastUnitCycled = <table> {
 }
 UnitNotInFrontTime = 0
 PulseInitialized = true
 WhitelistKeyBinding = <function> defined @Interface\AddOns\HeroLib\Events\KeyBinding.lua:138
 Tier21_4Pc = false
 Print = <function> defined @Interface\AddOns\HeroLib\Core.lua:60
 CombatStarted = 405505.168
 TTD = <table> {
 }
 RegisterForEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:48
 BuildVersion = <function> defined @Interface\AddOns\HeroLib\Core.lua:31
 RegisterForSelfCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:79
 CombatTime = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:89
 Tier20_4Pc = false
 GetEquipment = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Equipment.lua:24
 BMPullTime = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:99

**Comment by Kutikuti** [comment]
Fixed in 7565ae24a9f8bfb3b9262ebb2f39134478b6770d
