### ISSUE TITLE
[Assassin] Vendetta not showing up in pulls

### ISSUE THREAD

**Issue by Gyudon47** [herotc/hero-rotation#262]
I think after the recent update, Vendetta is not being suggested to use when pulling if i have my cd's turn on

**Comment by Mystler** [comment]
Do you have Shrouded Suffocation powers? I do not have one ready to test atm. Also please try again with the latest version (set Release Type to Alpha if you use Curse/Twitch App).

**Comment by Gyudon47** [comment]
Yes, i have two of the  Shrouded Suffocation traits. Will give the new version a go once im home for work. Thanks for all the hard work!

**Comment by Gyudon47** [comment]
Ok, so it does show up but for like a half a second and its kinda un castable during that time because still have gcd.

**Comment by Gyudon47** [comment]
Works perfectly now!
