### ISSUE TITLE
isStealthedP missing currently?

### ISSUE THREAD

**Issue by murx** [herotc/hero-rotation#263]
Hi there,
thanks for your work.
Currently there is a problem in Outlaw/Sub Rogue

Message: Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:465: attempt to call method 'IsStealthedP' (a nil value)
Time: Fri Sep  7 20:25:21 2018
Count: 101
Stack: Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:465: attempt to call method 'IsStealthedP' (a nil value)
[C]: in function `IsStealthedP'
Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:465: in function `?'
Interface\AddOns\HeroRotation\Main.lua:433: in function <Interface\AddOns\HeroRotation\Main.lua:411>

Locals:

**Comment by Mystler** [comment]
Please make sure you use the latest version of HeroLib. If you have set HeroRotation to Alpha, make sure HeroLib is set that way as well.

**Comment by murx** [comment]
You were right, didn't saw the hero-lib repo.
The lib I used was from twitch-loader
Thank you!
