### ISSUE TITLE
Frost mage should not shatter Ebonbolt. Unless (specific condition)

### ISSUE THREAD

**Issue by towicode** [herotc/hero-rotation#265]
This part fixed on 9/13/2018 release

```
The current addon is incorrectly recommending shattering Ebonbolts.


Here is what should happen:


EbonBolt should be used to generate BrainFreze Proc if we are at 5 Icicles and we don't have BrainFreeze.
However... this EbonBolt should not be shattered. As the BrainFreze generated should be used for GS.


it should go:

 **5 Icicles > Ebon bolt > GS > Flurry > Ice Lance.**


This is what the addon suggests now:


5 Icicles > **Ebon bolt > Flurry > Ice Lance > (wait for another brain freeze) > GS > Flurry > Ice Lance**


Now I know what you might be thinking... but it clearly says
`flurry,if=talent.glacial_spike.enabled&buff.brain_freeze.react&(prev_gcd.1.frostbolt&buff.icicles.stack<4|prev_gcd.1.glacial_spike|prev_gcd.1.ebonbolt)`

And this is the part I don't really understand... (probably because i'm new to simcraft language)


**However**,  you look at the (Sample Sequence Table) you'll see the above is true, even inside of SimCraft.

https://i.imgur.com/f0tGl8i.png


https://i.imgur.com/McGQMOX.png


https://i.imgur.com/zJfEMOo.png

```

__________________________________________________________________________________

**There is only 1 case** where you should shatter EbonBolt.

That is if you get a BrainFreze proc on the 4th Icicle. In this case you should do

**Frost Bolt x 4 > Ebon Bolt > Flurry > Ice Lance > GS > Flurry > Ice Lance**

You can see that this also happens in the SIMC sample table.

https://i.imgur.com/fR9YIDX.png

_________________________________________________________________________________

I understand this might be confusingly worded and could gladly discuss it in discord if you want. 

(assumes talents 1213223)

**Comment by towicode** [comment]
btw, it seems the upper issue was fixed with latest release.

The bottom issue where it should shatter ebonbolt on 4x icicles still persists, but it's way less of an issue.

**Comment by Cilraaz** [comment]
This should be resolved over the last few commits. 

Line 251 of the current file will cover Flurry after Ebonbolt if GS is not spec'd, there are less than 4 icicles (before the one from Ebonbolt), or there's already a Brain Freeze proc.
Line 255 of the current file will cover Flurry after GS.
Line 259 of the current file will cover Flurry after Frostbolt if GS is not spec'd or there are less than 4 icicles (before the one from Frostbolt).

Please let us know if there is still a problem.
