### ISSUE TITLE
Assassination Rogue AOE using FOK @ 2 targets instead of 3+

### ISSUE THREAD

**Issue by bordot** [herotc/hero-rotation#272]
I've noticed that the rotation is suggesting using FOK at 2 targets instead of 3+. I was just wondering if this is intentional or if there is a way to set an AOE threshold? 

Thanks!

**Comment by Mystler** [comment]
Yes it is intended and how the APL uses it. However, in terms of DPS output it does not really seem matter if you FoK at 2+ or 3+.
