### ISSUE TITLE
LUA error on attack

### ISSUE THREAD

**Issue by KJanos1396** [herotc/hero-rotation#275]
I attack simple MOBS and the following LUA error occoured:

Message: ...nterface\AddOns\HeroRotation_Paladin\Retribution.lua:212: attempt to perform arithmetic on a nil value
Time: Thu Sep 13 21:35:06 2018
Count: 1932
Stack: ...nterface\AddOns\HeroRotation_Paladin\Retribution.lua:212: attempt to perform arithmetic on a nil value

Locals: 

Message: Interface\AddOns\HeroLib\Events\Main.lua:387: attempt to call method 'AzeriteScan' (a nil value)
Time: Thu Sep 13 21:21:52 2018
Count: 5
Stack: Interface\AddOns\HeroLib\Events\Main.lua:387: attempt to call method 'AzeriteScan' (a nil value)

Locals: 

Message: Error loading Interface\AddOns\HeroLib\Class\Spell\Azerite.lua
Time: Thu Sep 13 21:13:46 2018
Count: 3
Stack: Error loading Interface\AddOns\HeroLib\Class\Spell\Azerite.lua

Locals: <none>

**Comment by ghr74** [comment]
It seems your HeroLib was outdated. Additionally, Retribution is currently "Outdated" so issues are to be expected.
