### ISSUE TITLE
SV Hunter Rotation Wildfire Infusion

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#277]
The bombs are not really on the way to what is on the Actionbar.
![svhunter](https://user-images.githubusercontent.com/43277089/45563387-7cc3cf00-b84d-11e8-891e-de8e60ca579f.png)

**Comment by ghr74** [comment]
Should be fixed with https://github.com/herotc/hero-rotation/commit/5bc04912fc77c886cc4718b1bb5b702785991dda#diff-1ccbc06209c41a7931b88b2828bfd914, thanks for the report.
