### ISSUE TITLE
Arms Warrior: "Show as off GCD" option not working

### ISSUE THREAD

**Issue by tommerg** [herotc/hero-rotation#279]
Spells are still being kept in the main rotation even with specific "Show as off GCD" or "Enable Warbreaker" options enabled.

**Comment by ghr74** [comment]
Thanks for the report, should be fixed as of https://github.com/herotc/hero-rotation/commit/dd7c9ae5f76d6b63094393411d78026b334fc793#diff-9ed8a6f75147a3d8b722d9e42e180ac1.
