### ISSUE TITLE
@Nia - Make an inquiry for an automatic range check 

### ISSUE THREAD

**Issue by Shashlic** [herotc/hero-rotation#280]
Yesterday we talked about 2 things and you asked me to leave a post here with pictures. At the moment I do not see any possibility to upload the 3 pictures. But I'll give you the link to the addon "Ovale".

https://wow.curseforge.com/projects/ovale

![wowscrnshot_091518_172759](https://user-images.githubusercontent.com/42533719/45594221-485c2a00-b997-11e8-998a-dabd34b3d04c.jpg)
![wowscrnshot_091518_172839](https://user-images.githubusercontent.com/42533719/45594222-485c2a00-b997-11e8-9d48-bb095b8bb5fa.jpg)
![wowscrnshot_091518_172803](https://user-images.githubusercontent.com/42533719/45594223-48f4c080-b997-11e8-897b-c4aa39918047.jpg)

- Rangecheck
The addon "ovale" has already implemented this function, so you could look there how it works and possibly with little effort (if it is also desired) also integrate with HeroRotation. You can see 3 pictures.

1 in range (small white point in the right corner of the spellicon)
2 options (rangecheck)
3 out of range (small red point in the right corner of the spellicon)

One little update: Prepot (new)

Thank you for your time invested. The addon is really great!
Have a beautiful Sunday!

Shashlic

**Comment by Cilraaz** [comment]
The preliminary code for this has been added in commit https://github.com/herotc/hero-rotation/commit/3bd3567ac1f2d0f6a045269527dc43ca5644c492

The individual profiles will need to be re-written accordingly. I'll be working on those over the next week or so.

**Comment by Cilraaz** [comment]
Range checking has (finally) been added for all specs. Closing this issue.
