### ISSUE TITLE
Hotkeys other than the main bar no longer show keybind

### ISSUE THREAD

**Issue by Barleduq** [herotc/hero-rotation#289]
I have the option to show the keybind toggled on.  For a while now - I think before BfA dropped but I'm no longer sure - any ability that isn't on the 1st row of hotkeys does not display the keybind. I use the generic UI, and before BfA screwed with it, my main bar was 1-2-3 etc, the bar over that was control-shift-1-2-3 etc, and the bar over the right side of the UI was control-alt-1-2-3-etc. 

For example: my windwalker has the chi-producer (tiger palm strike?) on the #2 button on the first row.  When that is displayed as what I should use, it has a 2 on it.  She has the ability that bounces back and forth between foe and friend, harming and healing, on the row that displays directly over row 1, #3.  I have everything in that row keybound to be control-shift and the appropriate key - 1, 2, 3...=.  When that ability is displayed as what I should use, it FORMERLY showed C-S-3 as the keybind. It now shows nothing.  I have not moved those keybinds between the two xpacs. 

Let me know if you want screenshots.

-Barleduq

**Comment by ghr74** [comment]
I did manage to find an issue with macro keybind detection in the default UI, fixed here: https://github.com/herotc/hero-lib/commit/814887928f1d432cfce77e8fce90acdd70dcefc6

No issues with the rows though, let me know if the macro change fixed your issue.

**Comment by Barleduq** [comment]
I'm not sure how to dl single files from github - I have no problem
replacing single files to test, I'm just not seeing anything on that
page that says 'click here to dl'.  Or should I C&P the contents of
the code (with the toggle diff off)?

-Barleduq

**Comment by ghr74** [comment]
This fix should be in the release version now, so just update HeroLib to receive it. Let me know if that fixes your issue.

**Comment by ghr74** [comment]
Closing since there has been no update.
