### ISSUE TITLE
Murder of Crows

### ISSUE THREAD

**Issue by Aldwew** [herotc/hero-rotation#290]
Is there anyway to make the addon not consider it as a cd? Thanks

**Comment by nurbzz1** [comment]
Edit 
	    -- actions+=/a_murder_of_crows
    if HR.CDsON() and Target:IsInRange(40) and S.AMurderofCrows:IsCastable() then
      if HR.Cast(S.AMurderofCrows, Settings.BeastMastery.GCDasOffGCD.AMurderofCrows) then return ""; end

To

	    -- actions+=/a_murder_of_crows
    if Target:IsInRange(40) and S.AMurderofCrows:IsCastable() then
      if HR.Cast(S.AMurderofCrows, Settings.BeastMastery.GCDasOffGCD.AMurderofCrows) then return ""; end
Should work

**Comment by Cilraaz** [comment]
This was changed in the Jan 17, 2019 update.
