### ISSUE TITLE
Assassin rogue with Exsanguinate.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#292]
When cooldowns are off and you're running exsanguinate, it gets stuck on mutilate at full combo points showing the "pools" icon, then telling you to use mutilate instead of evenom/rupture. Also having a problem with it not showing crimson tempest properly in various situations.

**Comment by azzi1103** [comment]
If exsanguinate is on cooldown, this does not happen.

**Comment by Mystler** [comment]
Fixed the issue that it wanted to hold onto finishers when Exsg was ready but CDs disabled.
For Toxic Blade I do not see an issue, right now. That it is pooling for quite a bit of energy when at finishing threshold (outside cooldowns) is normal and intended.
For Crimson Tempest, I'd also like more specific information of when you think it is wrong.

**Comment by azzi1103** [comment]
The issue with crimson tempest is probably the range check, sometimes after fan of knives it would choose Rupture before Crimson
