### ISSUE TITLE
Afflic Warlock error

### ISSUE THREAD

**Issue by Petetsmisc** [herotc/hero-rotation#294]
Message: Interface\AddOns\HeroLib\Events\InFlight.lua:78: 
You forgot to register Seed of Corruption for InFlight tracking.
Time: Fri Oct  5 20:29:57 2018
Count: 294
Stack: 
Interface\AddOns\HeroLib\Events\InFlight.lua:78:
You forgot to register Seed of Corruption for InFlight tracking.
Locals:

**Comment by Petetsmisc** [comment]
The above is nasty as a big LUA error box pops up blocking all view and I cant dismiss it till the mobs are dead.

**Comment by ghr74** [comment]
Fixed in https://github.com/herotc/hero-rotation/commit/b884e5574ca146ae5224f74b317ca24a7fcb6d24, should be included in release update.
