### ISSUE TITLE
Windwalker doesn't prompt for Whirling Dragon Punch under AOE scenario

### ISSUE THREAD

**Issue by DNLMow** [herotc/hero-rotation#296]
It will prompt for Spinning Crane Kick but not Whirling Dragon Punch occasionally, which is mandatory in both AOE and single target. This is pretty reproducible.

**Comment by Cilraaz** [comment]
Windwalker was updated on Feb 8, 2019. WDP is the 2nd spell suggested in the AoE rotation. This should now be fixed.
