### ISSUE TITLE
Killingspree and outlaw.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#297]
Killingspree is being shown in the times of energy pooling or during down time. It would be really great to have the option of having ks as AOE+CD only, so it doesnt show up at bad times when it's only singeltarget and not multiple enemies. Would be lovely if you guys could do something about this.

**Comment by EvanMichaels** [comment]
Going to close this since we added an option to move Killing Spree to the Suggested or Cooldown sections instead of the main icon if desired. Thanks!
