### ISSUE TITLE
Enhancement Shaman: Berserking Racial not following SimC

### ISSUE THREAD

**Issue by lukeyboy89** [herotc/hero-rotation#298]
actions.cds+=/berserking,if=(talent.ascendance.enabled&buff.ascendance.up)|(talent.elemental_spirits.enabled&feral_spirit.remains>5)|(!talent.ascendance.enabled&!talent.elemental_spirits.enabled)

This line is not being followed, It's asking to use Berserking on CD and not to hold it for any of the above lines.

**Comment by Cilraaz** [comment]
The SimC APL has since been modified, and the HR profile has been adjusted accordingly. Closing this issue, as it's no longer valid.
