### ISSUE TITLE
Windwalker occasionally will stuck in pooling when energy bar is full

### ISSUE THREAD

**Issue by DNLMow** [herotc/hero-rotation#303]

**Comment by kycan** [comment]
Single target logic is definitely not utilizing the energy. In code the late priority is to cast tiger palm but only if chi deficit is >= 2. If this isn't the case then energy will sit a full:

if S.TigerPalm:IsReadyP() and not Player:PrevGCD(1, S.TigerPalm) and Player:ChiDeficit() >= 2 and (Player:BuffDownP(S.RushingJadeWind) or Player:EnergyPredicted() > 56) then

**Comment by Cilraaz** [comment]
The profile has been updated multiple times since this issue was reported. I'm currently unable to replicate this issue, so I assume one of the APL changes eliminated it. Will re-open if the issue is reported again.
