### ISSUE TITLE
Shadow Priest: :Lua error with OFFGCDasOffGCD with Alpha

### ISSUE THREAD

**Issue by Fraktyl** [herotc/hero-rotation#304]
Version: 8.0.1.08-14-gfbe7b95-alpha

Line 313: 
if HR.Cast(S.Berserking, Settings.Common.OffGCDasOffGCD.Racials) then return ""; end

throws an error.  Looking at the settings.lua file for ShadowPriest all the racial checks are part of the Settings.Shadow table.

Changing the above line to:
if HR.Cast(S.Berserking, Settings.Shadow.OffGCDasOffGCD.Racials) then return ""; end

Stops the Lua error, not sure if the original table needs to be updated or if the change above is the correct fix.  Changing to the above stops the error and allows the addon to display recommended skills again.

**Comment by ghr74** [comment]
Hi,
thanks for the report. Should be fixed in https://github.com/herotc/hero-rotation/commit/e148ae74809e6133a7f0e5652a5d61697cef654b.
