### ISSUE TITLE
DH Havoc not using Blade Dance

### ISSUE THREAD

**Issue by tamedbeast** [herotc/hero-rotation#305]
Havoc Demon Hunter not using Blade dance when up, only showing death sweep, this in on single and multi-target training dummy scenarios.

**Comment by Spuffeld** [comment]
I have not had this problem, but either way both are the same skill and button. Death sweep becomes available in demon form, blade dance is available when not in demon form.

**Comment by Cilraaz** [comment]
Havoc's profile was updated on Dec 31, 2018. That should have fixed any issue with Blade Dance. If it is still not working, please submit a new issue.
