### ISSUE TITLE
Affliction Warlock Siphon Life not tracking

### ISSUE THREAD

**Issue by Natakeu** [herotc/hero-rotation#306]
As the title suggests when I use hero rotation it never tells me to use siphon life. From what I can tell it acts like it isn't even there. The addon will tell me to use all other abilities and talented items just fine. I really appreciate your addon and hope to see this issue fixed soon. Thank you for your time reading this.

**Comment by Natakeu** [comment]
After further playtesting, it seems to be working. My only issue with it is that hero rotation does not suggest using siphon life as part of an opening sequence. Typically I start off with Haunt, then Siphon Life, Agony, Corruption, then Unstable Affliction in that order. But usually, hero rotation skips suggesting the use of siphon life until later down the line after applying and maintaining my dots for about thirty seconds. I am left to ask if this is something intended or am I needing to learn to play my class better?

**Comment by Cilraaz** [comment]
The Affliction profile has been updated recently. Please try the new profile and let us know if there are any issues.
