### ISSUE TITLE
Icon Size goes from small to Huge and no in between

### ISSUE THREAD

**Issue by zion563** [herotc/hero-rotation#309]
Playing Arms warrior-Icons set to lowest size is a small size-the next "notch" is literally 4 times larger-I'm hoping for something in between a bit more granular, or a number to change instead of/in addition to a slider.

**Comment by Aenwyn** [comment]
Yeah not super pleased about this recent change. :(

**Comment by Cilraaz** [comment]
Changed in commit https://github.com/herotc/hero-rotation/commit/13fc2c8f499777a1e204d6af8e672518a4f5229d
