### ISSUE TITLE
Survival hunter rotation last update

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#312]
Be the last update I can no longer put aspect of the eagle as a small symbol. 
It stands as a large main symbol in the middle although it does not belong to the rotation. 
And without me using it, the rotation doesn't go any further either.
Thx

**Comment by ghr74** [comment]
Fixed in https://github.com/herotc/hero-rotation/commit/0efd1e5740e4f2621c8e031b23f28653f1a9fe82.
Thanks for the report!
