### ISSUE TITLE
Survival hunter rotation not fixed

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#313]
the problem ist not fixing......
same problem.
You have to use aspect of the eagle to continue rotating the symbols.

_Originally posted by @cyberbook78 in https://github.com/herotc/hero-rotation/issues/312#issuecomment-439844633_

**Comment by ghr74** [comment]
Hello,

please make sure you updated to the most recent alpha/github version. After the fix, I am unable to replicate the issue:

https://gfycat.com/SparseWebbedGalapagospenguin

**Comment by cyberbook78** [comment]
thx works good :D
