### ISSUE TITLE
[Warlock Demonology] Pet Tracking. Here ya go

### ISSUE THREAD

**Issue by Darkmoded** [herotc/hero-rotation#314]
I don't know who s working on the Demo lock.. but i added my own pet tracking to the Events.lua.
Just thought i would share it. clean/chop it up if needed. :)

https://pastebin.com/rMThjbQb

Cheers!

**Comment by Darkmoded** [comment]
Added Imp Energy tracking
Added 15 sec to demons time when Demonic Tyrant is spawned + Freezes Wild imp energy for 15 sec.

https://pastebin.com/YKUr1jdk

**Comment by Cilraaz** [comment]
Out of curiosity, why did you add the imp energy tracking? The SimC APL doesn't reference imp energy at all.

Also, thank you for the initial tracking code. It got me over a huge hurdle.

**Comment by Darkmoded** [comment]
I use Energy tracking for a custom condition when using "Demonic Consumption". Energy adds damage gain to your Demonic Tyrant.  This method is just a bit more accurate than just getting a Wild Imp Count.  
6 Imps can have more energy than 9 imps at times. And the sim does not make really good use of Demonic Consumption it needs a build Wild Imp Sate.  Using the Wild Imp Count works fine. I just want a more accurate call.
