### ISSUE TITLE
[HAVOC] It does not offer to press Blade Dance in AOE without metamorphosis.

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#317]
Found a bug or maybe not in the rotation for Havoc. When there are 3+ goals and no metamorphosis, he does not suggest pressing Blade Dance, but only when there is a metamorphosis and then he always suggests using Death Sweep. I want to know this is a bug or is it normal that he in AOE pack does not say to press Blade Dance on cd. Just if I use my hands on the CD Blade Dance top DPS in AOE grows

**Comment by narvell3** [comment]
https://imgur.com/a/qcgjfyX Dear developers, please pay attention to what I wrote. I indicated to you on the screenshot the readiness of the blades and your rotation does not show them. Please fix it.

**Comment by EvanMichaels** [comment]
Yes, this is correct as per the APL. It does not use Blade Dance if Metamorphosis is off cooldown, instead opting to save it to use as Death Sweep after using Metamorphosis.

If you want it to ignore this, you can turn CDs off in the configuration.
