### ISSUE TITLE
Fire Mage Rotation

### ISSUE THREAD

**Issue by Aenwyn** [herotc/hero-rotation#341]
Living Bomb isn't being suggested in rotation (at all, in raids or in open world, nameplates enabled).

**Comment by Aenwyn** [comment]
Also Flamestrike not showing up correctly (aoe enabled)

**Comment by ghr74** [comment]
Seems to have been fixed in a previous update, I got both Living Bomb and Flamestrike to show. Do keep in mind that Flamestrike has a fairly high target count requirement if you don't have the talent for it.
