### ISSUE TITLE
[Shaman] [Restoration] Please do this rotation

### ISSUE THREAD

**Issue by Trypholusion** [herotc/hero-rotation#344]
Hi, I will love see Shaman Restoration's Rotation on this addon. 

Thanks in advance.

**Comment by Kutikuti** [comment]
You mean the DPS rotation ?
ATM HR can't do healing rotation and it probably won't be added.

**Comment by Cilraaz** [comment]
No response from the issue creator in 2 months. At this time, we still don't support healing rotations. Closing issue.
