### ISSUE TITLE
Frost Mage - Suggesting Summon Water Elemental

### ISSUE THREAD

**Issue by victorscones** [herotc/hero-rotation#346]
Since 8.0.1.08-49-gdef7b5b-alpha, Hero Rotation is suggesting Summon Water Elemental (while out of combat), even if the Water Elemental is summoned.

**Comment by ghr74** [comment]
Thanks for the report, fixed in https://github.com/herotc/hero-rotation/commit/6a7ec4ebb476463719271b29c5ab806b1f0355d0
