### ISSUE TITLE
Icon Bugged

### ISSUE THREAD

**Issue by smol-wisteria** [herotc/hero-rotation#348]
I am unable to get the icon above the "C" "A" and "O" buttons to move along with the buttons. I can change the size, but I can not drag it to where I'd like it to be. 

Is there any chance I am simply forgetting how to move it?

**Comment by Cilraaz** [comment]
Unable to duplicate this issue. Either it's been fixed in core changes or was an issue with interactions with user's other addons.

To move, issue '/hr unlock' command. All icons and buttons then move.
