### ISSUE TITLE
Outlaw Rogue - rolling the bones during blade flurry AOE

### ISSUE THREAD

**Issue by aesbr** [herotc/hero-rotation#350]
Not sure if this is correct behavior, but during Blade Flurry up and mobs in AOE range, the addon suggests to reroll for correct buffs rather than using dispatch. I believe with a certain threshhold of mobs, we should be dispatching instead when Blade Flurry is up?

**Comment by EvanMichaels** [comment]
This is more of an APL issue in general (HR is doing the 'right' thing here) but you are probably right that it is worth investigating.

**Comment by EvanMichaels** [comment]
Never found any gain from doing this. If someone finds an APL that makes sense, it would be good to know. But currently it doesn't appear to be the case.
