### ISSUE TITLE
Ret Pally rotation

### ISSUE THREAD

**Issue by petesmisc** [herotc/hero-rotation#351]
After the recent update (a day or two ago), my rotation is showing "Inquisition" but I am NOT talented for Inquisition! This was NOT showing up prior to the update (and it should not be showing up unless I select that talent)

So, we have a bug.

**Comment by ithappenedagain** [comment]
I added a check ` and S.Inquisition:IsAvailable() ` around the ifs for Cast Inquistion checks and this helped.
[RetributionINQ.txt](https://github.com/herotc/hero-rotation/files/2733095/RetributionINQ.txt)

**Comment by MrCleanX** [comment]
> 
> 
> I added a check `and S.Inquisition:IsAvailable()` around the ifs for Cast Inquistion checks and this helped.
> [RetributionINQ.txt](https://github.com/herotc/hero-rotation/files/2733095/RetributionINQ.txt)

I just made this change and it appears to have fixed the problem. Thank you!!!
