### ISSUE TITLE
[Vengeance] Please watch the rotation

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#352]
Hello. Yesterday I uploaded my logs to the wowanalyzer website and noticed that it swears at most of the abilities that are not compressed, although I strictly follow your addon, click everything that it shows me. But as practice has shown, the rotation is not quite good. I suppose at the moment of idle time, I don’t throw the blade, as soon as the moment approaches the fire shield, it also doesn’t show it immediately to pass by cd, etc. I would like you to revise the rotation and correct it. Since the rotation of Hekilli on Vengeance is fine. And you have a lot of downtime in the rotation.

**Comment by Cilraaz** [comment]
HR's Vengeance profile currently matches the SimC APL. I haven't had any problems with VDH, personally. Wowanalyzer is not great at dealing with tank specs and is currently out of date, as they still have VDH based on 8.0.1. If you still have issues with the profile, please log a new issue.
