### ISSUE TITLE
Marksmanship Hunter Interrupt no spell in rotation

### ISSUE THREAD

**Issue by Aum280** [herotc/hero-rotation#353]
Counter Shot doesnt appear in rotation, when Interrupt checked in.

**Comment by Glynnyx** [comment]
Hello,

Thank you very much for your continued feedback, it's very much appreciated. The purpose of HeroRotation is provide the most optimal DPS output for each class. As Counter Shot does not provide any damage bonus and isn't a key part of the rotation it is not added here. 

Thanks again for raising these "issues"!

**Comment by Aum280** [comment]
Thank you very much, however there is an option in the General tab of the addon for Interrupt spells. Paladin/Warrior interrupts work pretty well, showing in the rotation when an enemy is casting an interruptable spell, and also with the option to have the Pummel/Rebuke spells shown as OffGCD. Paladin's stun spell even works for the Use stun for Interrupt option in the addon. Hunter should be no different. I am aware that Counter Shot is OffGCD and allows to interrupt a player's ongoing cast, unlike Arcane Shot, which even if GCD is over, when pressed, will not interrupt a player's Aimed/Rapid/Steady shots (for example Aimed Shot/Steady Shot/Rapid Fire all could be interrupted before the cast has ended if the player presses Counter Shot). This should be addressed, making it something like:

IF enemy cast, will end before Player's cast(Aumed Shot/Rapid Fire/Steady shot) then show Counter Shot in the rotation.
IF enemy cast will end after Player's cast(Aimed Shot/Rapid Fire/Steady Shot) then show Counter Shot only after current player's cast has ended.

Please, help me with this, I don't know how to implement it.
