### ISSUE TITLE
Update Conflict with Titan

### ISSUE THREAD

**Issue by Aidenrhys** [herotc/hero-rotation#357]
After the latest HeroRotation update, the Reputation aspect of TitanPanel will no longer show when both are enabled.  Below is the error I receive.

Date: 2019-01-08 10:19:15
ID: 1
Error occured in: Global
Count: 1
Message: ...\HeroLib\Lib\LibUIDropDownMenu\LibUIDropDownMenu.lua line 110:
   attempt to index field '?' (a nil value)
Debug:
   ...\HeroLib\Lib\LibUIDropDownMenu\LibUIDropDownMenu.lua:110: L_UIDropDownMenu_Initialize()
   Titan\TitanUtils.lua:1569:
      Titan\TitanUtils.lua:1557
   Titan\TitanUtils.lua:1664: TitanPanelDisplayRightClickMenu_Toggle()
   Titan\TitanPanel.lua:581: TitanPanelBarButton_OnClick()
   TitanReputation\TitanReputation.lua:190: TitanPanelReputationButton_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
frame = Titan_Bar__Display_BarRightClickMenu {
 0 = <userdata>
 Icon = Titan_Bar__Display_BarRightClickMenuIcon {
 }
 Text = Titan_Bar__Display_BarRightClickMenuText {
 }
 initialize = <function> defined @Interface\AddOns\Titan\TitanPanel.lua:2106
 Button = Titan_Bar__Display_BarRightClickMenuButton {
 }
 Right = Titan_Bar__Display_BarRightClickMenuRight {
 }
 Left = Titan_Bar__Display_BarRightClickMenuLeft {
 }
 Middle = Titan_Bar__Display_BarRightClickMenuMiddle {
 }
}
initFunction = <function> defined @Interface\AddOns\Titan\TitanPanel.lua:2106
displayMode = "MENU"
level = 1
menuList = nil
dropDownList = L_DropDownList1 {
 0 = <userdata>
 dropdown = Titan_Bar__Display_BarRightClickMenu {
 }
 shouldRefresh = true
 Button1 = L_DropDownList1Button1 {
 }
 MenuBackdrop = L_DropDownList1MenuBackdrop {
 }
 numButtons = 16
 Backdrop = L_DropDownList1Backdrop {
 }
 maxWidth = 132.891426
}
name = "Titan_Bar__Display_BarRightClickMenu"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "ButtonNormalTexture"
(*temporary) = <function> defined @Interface\AddOns\Titan\TitanPanel.lua:1688
(*temporary) = <table> {
 value = "Use Global Profile"
 text = "Use Global Profile"
 func = <function> defined @Interface\AddOns\Titan\TitanPanel.lua:1766
}
(*temporary) = nil
(*temporary) = "<>"
(*temporary) = ""
(*temporary) = "attempt to index field '?' (a nil value)"
securecall = <function> defined =[C]:-1
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:74
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 Recount_MainWindow_Bar6 = Recount_MainWindow_Bar6 {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 StoreMicroButtonAlertGlowBottom = StoreMicroButtonAlertGlowBottom {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 398
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 HealBot_Options_CrashProt_OnClick = <function> defined @Interface\AddOns\HealBot\HealBot_Options.lua:1350
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 BOOKTYPE_PROFESSION = "professions"
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:794
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2372
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid =
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  WorldFlightMapLoader, v8.0.0.3
  Ace3, v
  Altoholic, vr190
  AltoholicCountHider, v1.06
  AskMrRobot, v71
  Atlas, vv1.44.06
  AtlasBattlegrounds, vv1.44.01
  AtlasBurningCrusade, vv1.44.01
  AtlasCataclysm, vv1.44.01
  AtlasClassicWoW, vv1.44.01
  AtlasClassOrderHalls, vv1.44.01
  AtlasDungeonLocs, vv1.44.01
  AtlasLegion, vv1.44.01
  AtlasMistsofPandaria, vv1.44.01
  AtlasOutdoorRaids, vv1.44.01
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.01
  AtlasWarlordsofDraenor, vv1.44.01
  AtlasWorldEvents, vv3.25
  AtlasWrathoftheLichKing, vv1.44.01
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.0.7
  BagSaver, v0.8.0
  Bartender4, v4.8.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.1
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  EasyMail, v7.3
  FishingBuddy, v1.9.25p1
  Grail, v099
  GrailQuestsenUS, v27178
  HandyNotes, vv1.5.3
  HandyNotesArgus, vv0.12
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBoralusRP, v0.331
  HandyNotesBrokenShore, vv1.30
  HandyNotesDungeonLocations, v1.45
  HandyNotesLegionClassOrderHalls, vv1.30
  HandyNotesLegionInstanceWorldQuests, vv1.17
  HealBot, v8.1.0.1
  HeroCache, v8.0.1.09
  HeroLib, v8.0.1.09
  HeroRotation, v8.0.1.09
  LibSharedMedia30, v3.0-104
  LibWindow11, v1.1.15
  Mappy, v3.8.5
  Omen, v3.2.0
  OpenAll, v1
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  PetBattleTeams, v3.3.11
  Recount, vv8.1.0b
  Stubby, v8.0.6161 (SwimmingSeadragon)
  Titan, v5.16.0.80100
  TitanClock, v5.16.0.80100
  TitanGold, v5.16.0.80100
  TitanLocation, v5.16.0.80100
  TitanRepair, v5.16.0.80100
  TitanReputation, v3.9.5
  TomTom, vv80001-1.0.2
  WorldFlightMap, v8.0.0.10b
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=9b9)

**Comment by ghr74** [comment]
Hey. I was unable to reproduce the bug with HeroRotation and Titan Panel + Titan Panel [Reputation]. Could you try narrowing your addon list down to find out which combination is causing it?

**Comment by Cilraaz** [comment]
No further reports of issues in over 4 months. No response to request for further information. Please create a new issue if this is still a problem
