### ISSUE TITLE
Marksmanship Hunter Rotation - Steady Focus

### ISSUE THREAD

**Issue by Aum280** [herotc/hero-rotation#358]
There is something terribly wrong with the Marksmanship Hunter rotation, either a mistake by the guy who wrote it in HeroRotation addon or the one provided from SimCraft.

Right now, when you have specd into Steady Focus, when Precise Shots procs(Marksmanship default Passive spell) HeroRotation suggests casting Steady Shot, while at 100 Focus. The addon ignores Lock & Load procs, which is not fatal, but Jesus Christ. Fix your addon.

Thank you

**Comment by Cilraaz** [comment]
The SimC APL does not reference Lock and Load procs. They get used just by following the general rotation. 

The only line in the profile referencing Steady Focus is:
`if S.ArcaneShot:IsCastableP() and (Player:Focus() > 60 and not S.SteadyFocus:IsAvailable() or Player:BuffP(S.PreciseShotsBuff) and Player:BuffDownP(S.TrueshotBuff) or Player:Focus() > 85) then`

At 100 energy, this would trigger before Steady Shot, causing Arcane Shot to be suggested. I can't duplicate your issue. Try the latest profile. If this is still an issue, please enable debug output and let us know exactly what is being suggested.
