### ISSUE TITLE
[Fury] Lua Error

### ISSUE THREAD

**Issue by Fraktyl** [herotc/hero-rotation#364]
Version: 8.0.1.09-29-ge31d275-alpha

Fury Warrior throws the following LUA errors whenever you are in combat:

`164x HeroRotation_Warrior\Fury-Fury.lua:172: attempt to index global 'movement' (a nil value)
HeroRotation_Warrior\Fury-Fury.lua:172: in function `?'
HeroRotation\Main.lua:433: in function <HeroRotation\Main.lua:411>

Locals:
InCombatSkipped
`

**Comment by Cilraaz** [comment]
That was my fault. I forgot to replace the movement calls when I regenerated the profile. I just submitted a PR to fix this.
