### ISSUE TITLE
Sv hunter multitaget

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#368]
Multitarget rotation after update is broken

![wowscrnshot_012519_090341](https://user-images.githubusercontent.com/43277089/51733104-976e4600-2080-11e9-9b11-03672ef78cb0.jpg)

**Comment by ghr74** [comment]
should be fixed in https://github.com/herotc/hero-rotation/commit/3f9453de4b16c33e2027cf3717d1c67454891734. thanks for the report.
