### ISSUE TITLE
Elemental Shaman only getting Lightning bolt

### ISSUE THREAD

**Issue by Gopher697** [herotc/hero-rotation#370]
Not sure if this is the right place to ask about it, but the HR addon only tells me to use lightning bolt once when on my Elemental Shaman, and then gives me nothing. I can't even find the elemental shaman options in the interface menu. I know very little about how this addon works, so if anyone could maybe point out something I'm missing that would get it to work, that would be lovely! Is it maybe because I am trying to use it on a level 40 Shaman? Are the abilities the mod looks for higher level things?

**Comment by Cilraaz** [comment]
Issue was due to low level character. Closing issue.
