### ISSUE TITLE
Retribution, does not work with Divine Purpose talent. Minor Inquisition issue.

### ISSUE THREAD

**Issue by Flitzekatze** [herotc/hero-rotation#371]
Crusade works perfectly fine, there are some small issues with Inquisition. For example if you accidently extend the duration of Inquisition, it sometimes tells you to use Inquisition again even if you have 40 seconds left on the buff. It can be solved by fully deplete your Holy Power
, forcing it to tell you to use a Generator.

Divine Purpose doesn't work at all. My talents with DP are: 2313131

Thank you.

**Comment by ghr74** [comment]
Thanks for the report, divine purpose should be fixed in https://github.com/herotc/hero-rotation/commit/d63e9c0a646e484dfad6d55f3d3390b81748dae0 and inquisition in https://github.com/herotc/hero-rotation/commit/39cd898cbc063932fe46b2a5efe05c4a20f127df.
