### ISSUE TITLE
Fury Warrior AoE rotation

### ISSUE THREAD

**Issue by Maradea** [herotc/hero-rotation#372]
After the Update, the AoE rotation stopped working. It shows you need to cast whirlwind until you reach enough rage to use Rampage. Doesn't show the usage of Bloodthirst and Raging Blow inbetween

**Comment by Mirado12** [comment]
Having the same exact issues as above.

**Comment by endersgone** [comment]
Same issue

**Comment by itsbuddyman** [comment]
I'm playing with AOE turned off for now because of this issue. Love the addon.

**Comment by nurbzz1** [comment]
https://pastebin.com/xnZGyL1u

**Comment by mwojtkowski** [comment]
I've run SimulationCraft with 3 targets to see APL Sample Sequence Table and it looks like SimulationCraft use old buff name (meat_cleaver) for whirlwind buff

so this is the problem
```
-- whirlwind,if=spell_targets.whirlwind>1&!buff.meat_cleaver.up
if S.Whirlwind:IsCastableP() and (Cache.EnemiesCount[8] > 1 and not Player:BuffP(S.MeatCleaverBuff)) then
    if HR.Cast(S.Whirlwind) then return "whirlwind 114"; end
end
```
in ```HeroRotation_Warrior\Fury.lua``` you need to change
```MeatCleaverBuff                       = Spell(280392),```
to whirlwind buff spell id
```MeatCleaverBuff                       = Spell(85739),```
