### ISSUE TITLE
Ret Pally Inquisition 

### ISSUE THREAD

**Issue by GravixGotcha** [herotc/hero-rotation#375]
I'm being asked to refresh my Inquisition with 40 seconds left. For most trash fights I only use 1-2 holy power on Inquisition so my rotation is just constantly reminding me to refresh Inquisition. Seems this change came with the last update.

**Comment by ghr74** [comment]
Thanks for the report, should be fixed in https://github.com/herotc/hero-rotation/compare/d63e9c0a646e...9d86c74a01ee.
