### ISSUE TITLE
hero rota interface probs

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#376]
buttons scale to big
![wowscrnshot_020719_212501](https://user-images.githubusercontent.com/43277089/52440864-7d704100-2b1f-11e9-8b7b-68c9a36ec97e.jpg)

**Comment by ghr74** [comment]
Thanks for the report, fixed in https://github.com/herotc/hero-lib/commit/36fd2710e518626eb961996f7495d7c98687fba9.
