### ISSUE TITLE
Gronk trinket to the rotation

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#379]
Hello. Can you please tell me if there is an opportunity to add a Gronk trinket to the rotation for Unholy DK? Simply, there are conditions that are necessary to comply with when the character is both Triket RAGE and Triket Gronk at the same time. Here I have thrown off below under what conditions can I add them to the rotation.

What do I do when I have both the RAGE trinket (Mekkatorque) and the Grong's trinket?
Use RAGE on pull and Grong's 20 sec later. Then just use on Cooldown, saving Unholy Frenzy for RAGE.

When should I use the Grongs trinket?
Pretty much off Cooldown. Use it in the opener after you've popped Unholy Frenzy (wounds will still be applied).

How do I use the RAGE trinket (Mekkatorque) correctly?
Use it in opener and use Unholy Frenzy as you usually do. Then save Unholy Frenzy for your other uses, popping Unholy Frenzy 6 seconds after using the trinket.

I hope you can make it happen. For a class like Unholy DK. Thanks in advance for your help.

**Comment by Uranium2** [comment]
You just have the 2 worst Trinket. I don't think you should even use them.
It breaks so many rules in our rotation. Keep it if you don't have anything else, but even a 370 ilvl item is better than Gronk trinket.

**Comment by narvell3** [comment]
When was the last time you watched the logs on unholy dk? Have you looked at all who needs this class? I think not, if you say so. In a simcraft, a trinket with gronk is very strong. The rotation should start so that the RAGE tricent will immediately go away, then with a full 30 seconds on the CD we return the Gronk trinket. And if one of these trinkets is wearing a character, then it should be synchronized with Unholy Frenzy. On this please ask the logs of people. P.S. If you do not know how it works, this does not mean that they are the worst.

**Comment by narvell3** [comment]
Cheked this https://www.warcraftlogs.com/zone/rankings/21#metric=dps&class=DeathKnight&spec=Unholy and you see

**Comment by narvell3** [comment]
And watch this https://www.herodamage.com/death-knight/combinations-3a/1t-t23-unholy for bis gear

**Comment by narvell3** [comment]
And last watch http://www.simulationcraft.org/reports/T23_Raid.html

**Comment by Cilraaz** [comment]
Grong's trinket was added to the Unholy DK APL with the April 13th update, as was the RAGE trinket.
