### ISSUE TITLE
[PALADIN] Retribution opener

### ISSUE THREAD

**Issue by Nmxsz** [herotc/hero-rotation#386]
This updated Retri Rotation is bugged for the opener Rotations. When in Opener Rotation and you are in combat with 2 or more mobs it tells you to cast Templers Verdict instead of casting Divine Storm

BTW sorry but this Rotation is really crap i would recommand you to use my rotation it is 100% coded like simcraft do and it works

**Comment by Cilraaz** [comment]
The current profile matches the SimC APL, which only references Templar's Verdict in the opener.

Other than TV vs DS in the opener, what specific problems do you have with the rotation?

**Comment by Cilraaz** [comment]
4 days with no response. If this is still a problem with the latest version, please re-submit an issue.
