### ISSUE TITLE
Windwalker AOE

### ISSUE THREAD

**Issue by Snichy** [herotc/hero-rotation#388]
Under AOE conditions, the addon recommends Fists of Fury abd Spinning Crane Kick under most situations.  However a priority should be Whirling Dragon Kick under all circumstances, but this is not recommended because it is only available AFTER Rising Sun Kick (and FoF) is on CD but because RSK is very low on the action list for AOE situations it wont recommend it.

I believe it is simply a coding issue in the addon as even according to Simc although RSK quite rightly shouldn't be recommended for AOE, it should be high on the list in order make WDK available which is the highest possible priority.

**Comment by Cilraaz** [comment]
The AoE part of the profile was just updated 10 days prior to your issue being logged. Whirling Dragon Punch is very high in priority. Please make sure you have the latest version of the profile.

**Comment by Cilraaz** [comment]
4 days with no response. If this is still a problem with the latest version, please re-submit an issue.
