### ISSUE TITLE
[DEMONOLOGY} Action after Tyrant

### ISSUE THREAD

**Issue by Tamashi** [herotc/hero-rotation#390]
Demonology Warlock. It shows you to summon the Tyrant, but does not show you what to cast next until the Tyrant is already summoned. If 5 soulshards it should be Hand of Guldan, if lower than 5 Shards, Shadowbolt. It does show correctly what to cast, but only once the cast of the Tyrant is finished, which makes you need to track your soulshards manually to predict the next spell. It would be great if while casting the tyrant, HeroRotations would already show the next action rather than having to finish the cast to find out.

**Comment by Cilraaz** [comment]
Added a fix for this in pull request #389. Should be fixed after review/merge.

**Comment by Cilraaz** [comment]
This should be fixed as of commit https://github.com/herotc/hero-rotation/commit/c7a139c49aee229eaf00434456e3a52c1c93a825
