### ISSUE TITLE
hunter‘s GCDasOffGCD Setting  is unavailable

### ISSUE THREAD

**Issue by ayuanbro** [herotc/hero-rotation#400]

**Comment by Cilraaz** [comment]
What spec and what spells? I pushed a fix for Marksmanship to fix Trueshot's GCDasOffGCD setting and add SummonPet. Please let us know if this is what was being referenced or if it was something else.

**Comment by ayuanbro** [comment]
Can you add ‘’Hunter's Mark‘’ and ‘’Double Tap‘’？

**Comment by Cilraaz** [comment]
Added in the following commit: https://github.com/herotc/hero-rotation/commit/e9a41d83725ee045c0e1f08c0647b6783f2d0a38
