### ISSUE TITLE
Retri paladin

### ISSUE THREAD

**Issue by Tobbelainen** [herotc/hero-rotation#403]
Why cant we choose to not have shield of vengeance in the rotation and some more tweaks as outlaw rogue have not much settings on Retri side of this addon, except this is a great addon for other Spec and classes more love to Retri paladins.

**Comment by Cilraaz** [comment]
Added a toggle setting for using Shield of Vengeance in the normal DPS rotation. Commit: https://github.com/herotc/hero-rotation/commit/544d3e01250938c3ffec656d2df3f237ece64e24
