### ISSUE TITLE
Army of the Dead 

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#404]
hi

Army of the dead is called as the main spell in the middle. Please let it be displayed as off gcd.
i have no option for this.

unholy dk

**Comment by Cilraaz** [comment]
Army of the Dead has to be used in order for the rotation to proceed, as per the SimC profile. When it was made OffGCD, it simply left a blank main icon. As such, for now, we're leaving it as a main icon ability. This may change in the future, though.
