### ISSUE TITLE
Wake of ashes talent bug

### ISSUE THREAD

**Issue by allenguest** [herotc/hero-rotation#406]
When spec'd into wake of ashes, the first couple of recommendations such as Blade of Justice and Judgement show up then it goes blank. No more recommendations., When I switch out of Wake of ashes it works fine.

**Comment by Cilraaz** [comment]
What talents are you using, other than Wake of Ashes? There may be a condition in the opener that doesn't cover your specific talent setup.

**Comment by allenguest** [comment]
Toon is Ammertyme (paladin) on Kel'thazud-US. Character is not 120 yet,
perhaps is part of the issue?
The addon stops recommending abilities after suggesting "Shield of
Vengeance", "Judgement", and "Blade of Justice".

[image: image.png]

**Comment by Cilraaz** [comment]
We technically don't support classes under max level, however, I added a check in commit https://github.com/herotc/hero-rotation/commit/0a01e69ecfa6e93d4015be0545fd158b9812cb98 to skip the opener rotation if no level 100 talent is selected. This should fix your issue.

**Comment by allenguest** [comment]
Great job
