### ISSUE TITLE
[Warlock][Demonology] ImpCount is not updated when Wild Imp disappear. 

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#407]
If Imp if not consumed by Implosion such as imps disappear when out of combat, ImpCount is not updated.

please try summoning Imps and let it disappear and:

/dump HeroLib.GuardiansTable.ImpCount

to see the results.

**Comment by Cilraaz** [comment]
Fixed in commit: https://github.com/herotc/hero-rotation/commit/913cfcb31dab53600dfe269e04f2c5abf5ab99d8

**Comment by jo32** [comment]
Appreciate the quick fix!
