### ISSUE TITLE
MM hunter rotation showing use of pet

### ISSUE THREAD

**Issue by Remokizz** [herotc/hero-rotation#410]
can you please add a button on the settings too remove the call pet action as its anoying cuse MM hunter dont use pet cuse of Lone wolf 10% more dmg and i cant use the dps actions cuse of it

**Comment by Cilraaz** [comment]
This option was already added (Lone Wolf in settings). If you update the addon via the Twitch client, please set the release type for Hero Rotation to Alpha to receive the latest updates.

**Comment by Remokizz** [comment]
allright il try that
