### ISSUE TITLE
Possible to make "pooling" optional for assassin rogue?

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#411]
Could you fix an option for pooling being optional for assassin rogue? It would be really good to be able to maintain 10% dmg increase by using evenom earlier when the pooling icon is up. Would be a helpful 👍

**Comment by Cilraaz** [comment]
Pooling is an essential part of the Assassination rotation. The Rogue profiles are some of the best maintained and match the SimC APLs. Closing this issue.
