### ISSUE TITLE
[WindWalker] Sometimes idle when has 4 chi and energy approaching maximum

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#412]

**Comment by ar1a** [comment]
I get this too.

**Comment by Hinalover** [comment]
Yea I am getting it myself once in a blue moon. I'll need to figure out what is going on, but from what I could tell, is that it happens after Tiger Palming and everything is on cooldown. It should Blackout Kick (or something along those lines) but it is not.

**Comment by jo32** [comment]
Casting any other spell should make it work again. Usually I cast Tiger Palm to prevent wasting energy.

I think one part of the problem is every casting of Tiger Palm in the logic must meet "Player:ChiDeficit() >= 2", which overlook some situations like having 4 chi.

**Comment by ar1a** [comment]
Also possibly related, it sometimes asks me to cast tiger palm twice in a row. I think it's when it swaps from the single target to the AOE rotation!

**Comment by Cilraaz** [comment]
Duplicate to #303.
