### ISSUE TITLE
[Protection War] Should not use shield block when is not currently tanking.

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#415]
```
    if S.ShieldBlock:IsReadyP() and (S.ShieldSlam:CooldownUpP() and Player:BuffDownP(S.ShieldBlockBuff)) then
      if HR.Cast(S.ShieldBlock, Settings.Protection.OffGCDasOffGCD.ShieldBlock) then return "shield_block 64"; end
    end
```

consider adding isCurrentlyTanking() to codes mentioned above.

**Comment by Cilraaz** [comment]
SimC uses Shield Block for the dps increase to Shield Slam. I'll add a toggle option to only use Shield Block defensively.

**Comment by jo32** [comment]
@Cilraaz I think casting ignore pain should also consider if currently tanking.

**Comment by Cilraaz** [comment]
Changed in commit https://github.com/herotc/hero-rotation/commit/efaa6de08a5cad238a004504769d777aa05bcc62

Shield Block now has a "defensive use only" option toggle. Usage within the Aoe and St functions will obey the toggle option. Within the Defensive function, it will be suggested regardless.

I also added isCurrentlyTanking to Ignore Pain.
