### ISSUE TITLE
[Protection War] LastStandBuff is not declared

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#416]
In Protection.lua line 146

**Comment by jo32** [comment]
gcdTime is also not declared

**Comment by Cilraaz** [comment]
Both should be fixed in commit https://github.com/herotc/hero-rotation/commit/a98bd910e273f93196369b7b3774dcacf3b61bbe

**Comment by nurbzz1** [comment]
Seems to have very very low uptime of ignore pain.
