### ISSUE TITLE
Rotation Unholy DK

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#418]
in this Version 8.0.1.10-87-g482e4d4-alpha is the unholy DK rotation brocken.
 Scourge Strike & Festering Strike missing!

**Comment by Dimmn** [comment]
seeing the same issue

**Comment by domingosnovo** [comment]
Same here, addon is now broken for Unholy DKs.

**Comment by Cilraaz** [comment]
Update to the latest version. Easiest way to tell is to check your settings. If you have more OffGCD options than just Dark Transformation, you're on an old version.

**Comment by domingosnovo** [comment]
Thanks for the quick response. I tested against the version available on Twitch (which I assume is 8.0.1.11). Just noticed you pushed a couple fixes to the master branch a few days ago. Will test it tonight and report back.

**Comment by domingosnovo** [comment]
Thanks @Cilraaz , I can confirm the latest version fixes the issue for me.
