### ISSUE TITLE
Army of the dead icon not removable

### ISSUE THREAD

**Issue by Dimmn** [herotc/hero-rotation#421]
I am unable to remove the Army of the Dead Icon from the Hub. There is no option to remove it anywhere I can see.

Screenshot of the icon.
https://gyazo.com/1ed5e0263efb7e89a53e42320ae65f0b

**Comment by Dimmn** [comment]
So there seems to be more issues with Unholy When i start my attacks I do not get Scourge Strike icon or the pool for resource like it use to show when you are to hold your abilities

**Comment by Cilraaz** [comment]
Army of the Dead has to be used for the rotation to continue, as per the SimC APL. I changed AotD from CastSuggested to a normal Cast so that it will be a main icon instead of a smaller icon off to the left. Please update your profile and let me know if this fixes your problem.

**Comment by Dimmn** [comment]
How do I update the profile?

**Comment by Cilraaz** [comment]
If you're updating via the Twitch app, right click Hero Rotation and set its type to alpha. Then you'll always get the latest updates.

**Comment by Dimmn** [comment]
Two things that are happening 
**First is Festering Strike, and Scourge Strike are not being displayed when to use them the rotation helper disappears during those abilities ques.**

**Second is on log in I'm getting this LUA error.**
```
Message: Interface\AddOns\HeroLib\Events\KeyBinding.lua:100: attempt to index field 'db' (a nil value)
Time: Tue Apr  9 11:05:54 2019
Count: 5
Stack: Interface\AddOns\HeroLib\Events\KeyBinding.lua:100: attempt to index field 'db' (a nil value)
[C]: ?
Interface\AddOns\HeroLib\Events\KeyBinding.lua:100: in function <Interface\AddOns\HeroLib\Events\KeyBinding.lua:62>
Interface\AddOns\HeroLib\Events\KeyBinding.lua:133: in function `Handler'
Interface\AddOns\HeroLib\Events\Main.lua:227: in function <Interface\AddOns\HeroLib\Events\Main.lua:225>

Locals: 
```
Maybe this part is the cause for the first issue.

**Comment by Cilraaz** [comment]
The second is a completely separate issue. There is already an issue logged in the HeroLib git.

For the first, this has been resolved in commit https://github.com/herotc/hero-rotation/commit/0c15e34655d747c67cfbb84a99b0a0dc0714845d

**Comment by Cilraaz** [comment]
No further reports of the problem. If the issue still exists or re-occurs, please open a new issue.
