### ISSUE TITLE
Outlaw Rogue: After WOW Hotfix 8.1.5.29981 No Rotation is highlights are showing anymore

### ISSUE THREAD

**Issue by Dravion** [herotc/hero-rotation#422]
Hi thee,
First of all, a verry nice Addon! Keep up the good work!
Today i logged into WOW, a 74 MBytes Patch came down and was applied to WOW.
Restart, logged in Herorotation doesnt work anymore. The HUD was showing but not
the highlights on the main Combat spells. I hate Blizz

**Comment by Cilraaz** [comment]
Not sure if this was a short-term patch issue, but HeroRotation is working as intended at this time.
