### ISSUE TITLE
Unholy Trinket/summon ghoul icon issue (wont disable)

### ISSUE THREAD

**Issue by Dimmn** [herotc/hero-rotation#427]
I am unable to disable the summon ghoul/trinket icon in the top left part of the Hero Rotation system. See image https://i.gyazo.com/1284b7d44914746828b5cddac1ccb998.png
 
I have went into the settings and unchecked everything that sounds like it has something to do with those icons reloaded my UI and the icons  still show up. See image https://i.gyazo.com/6713b404fc05d0f2bc72f3617bbcd846.png

**Comment by Cilraaz** [comment]
They're not able to be disabled, as they're a core part of the rotation. They are all called via CastSuggested, which is why they're on the left side of the main icon.

**Comment by Dimmn** [comment]
So no way of removing it to just show the main icon?

**Comment by Cilraaz** [comment]
Remove them entirely? 

No. It would be possible to move them above the main icon by recoding the profile to make them GCDasOffGCD abilities, but as there are already a good number of those, it would likely become cluttered and not always properly show icons that should been shown. So I don't know if we want to go in that direction. 

The current configuration is pretty much the best balance of icon location usage. I'm not sure there would be benefit in changing it. Always open to input, though.
