### ISSUE TITLE
Enh Shaman - Move Sundering ability to off-gcd icons?

### ISSUE THREAD

**Issue by Herdrage** [herotc/hero-rotation#430]
It's important to get the most out of Sundering so a lot of times especially in m+ it would be better to hold on to it a little longer such as if a pack is about to die, or if finishing a single mob right before pulling an aoe pack. Can it be moved from the main icons to off-gcd icons for when called as both filler and even for the aoe rotation?

**Comment by Cilraaz** [comment]
Added a toggle for Sundering to be GCDasOffGCD in commit https://github.com/herotc/hero-rotation/commit/82e6340a07508b2ae89d77cafb1509bb1da325cc
