### ISSUE TITLE
Outlaw Ruthless Precision Reroll Priority Wrong

### ISSUE THREAD

**Issue by Scathic** [herotc/hero-rotation#431]
Reroll logic for Outlaw in Single Target and AOE rotation suggestion using the SimC profile has an error. If you have a  single buff of Ruthless Precision, the sequence suggests a reroll at 16 seconds or less remaining on the buff once you have 5+ cps with Deeper and 4+ with Vigor.

**Comment by EvanMichaels** [comment]
This is correct in terms of the APL. The APL will reroll a single RP buff if Between the Eyes is on cooldown and won't come back up before the duration remaining on the buff. If you see otherwise, please reopen but this is correct in that specific case.

**Comment by GoHahl** [comment]
But it seems like it does not consider the cooldown reduction from finishers. 

As an example: 
RP got 20 seconds left and BtE is on 30 seconds CD. With the 1 second cooldown reduction for each CP BtE will probably off CD before RP runs out.

**Comment by Mystler** [comment]
Yes, it's more an APL "issue" than a HR issue. However, attempts by both Koji and me to account for this CDR have not resulted in any noticeable gain.

**Comment by GoHahl** [comment]
Yeah, I think it is very situational and hard to write some logic for this case. 
But maybe it's better to just don't reroll RP at all? For me it was a bit confusing to see HR tell me that I should reroll RP with about 30 seconds left.

**Comment by EvanMichaels** [comment]
APL logic that attempted to wait out the duration just for the CDR was a DPS loss when tested. It is still better to use that time in order to try to fish for a 2 buff, essentially, since it is a period of very limited value.
