### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#432]
my error 
Message: Interface\AddOns\HeroRotation\UI.lua:392: attempt to index local 'HealthBar' (a nil value)
Time: Mon May 20 19:28:29 2019
Count: 50
Stack: Interface\AddOns\HeroRotation\UI.lua:392: attempt to index local 'HealthBar' (a nil value)
[C]: ?
Interface\AddOns\HeroRotation\UI.lua:392: in function `AddIcon'
Interface\AddOns\HeroRotation\Core.lua:147: in function `CastLeftNameplate'
Interface\AddOns\HeroRotation\Core.lua:185: in function `CastTargetIf'
Interface\AddOns\HeroRotation_Hunter\Survival.lua:327: in function `Cleave'
Interface\AddOns\HeroRotation_Hunter\Survival.lua:543: in function `?'
Interface\AddOns\HeroRotation\Main.lua:433: in function <Interface\AddOns\HeroRotation\Main.lua:411>

Locals:

**Comment by ghr74** [comment]
Hi,
thanks for the report. Should hopefully be fixed in https://github.com/herotc/hero-rotation/commit/9174bfa9c14fa785371c21066b68981c49c58d57.
