### ISSUE TITLE
Survival hunter rotation doesnt reccomend to maintain serpent sting?

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#433]
Barely uses serpent sting in rotation, even when it has procced Viper's Venom. Can you guys please fix this?

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/dd2c21ff553234f2599dd0dbfbeb45a8f71c3efa

Please let me know if there are any further issues.

**Comment by azzi1103** [comment]
Is the possible to add instant use on proc? The initial dmg is great. Ofc this is if you use Viper's Venom
