### ISSUE TITLE
Multishot really low prio on both BM hunter and MM hunter?

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#434]
Does it have a low prio, or is it difficulty of detecting mobs?

**Comment by Cilraaz** [comment]
There's a setting toggle for whether or not to use SplashData. SplashData will create a table of data from mobs that have been hit by your (and your pet's) AoE abilities to determine a count of enemies that you are fighting.

If you are using SplashData for AoE, then you have to use an AoE ability before any AoE ability will be suggested. 

If you are not using SplashData for AoE, then the profile will suggest AoE abilities when multiple mobs are within 40 yards, which is pretty much constantly when in the wild.

**Comment by azzi1103** [comment]
that option is only available for BM and not MM?

**Comment by Cilraaz** [comment]
It's available to both.

**Comment by azzi1103** [comment]
https://i.gyazo.com/a9ef5c0d154043050168ce76e936ec10.png BM is showing here. But not on MM ---->https://i.gyazo.com/41993d0f40278f08da35c09d583c678e.png

**Comment by Cilraaz** [comment]
Make sure you have the latest version of all files: https://i.imgur.com/hfyD8Te.png

**Comment by azzi1103** [comment]
Yeah it's all updated, im not getting it up for some reason

**Comment by azzi1103** [comment]
just reinstalled it, and it's still not there :/ is the one on the twitch client older?

**Comment by azzi1103** [comment]
installed from the github and got it now. Rotation doesn't use multishot correctly. Should be used before rapid fire if 3+ targets. But it recommends the rapid fire before the multishot. Also sometimes it goes crazy and tells to spam multishot when adds are a bit spread

**Comment by nurbzz1** [comment]
https://pastebin.com/LAYvTrBx should deal with most of your issues, as for multi shit spam you should just use a hot key to toggle aoe on when you know it will hit 3 or more targets

**Comment by azzi1103** [comment]
I know that, but what I mean is that DURING AOE rotation, it sometimes prefers Rapidfire BEFORE multishot, which means the rapidfire won't hit other targets. In aoe rotation Multishots should be prio before rapid fire, so you can maximize AOE dmg

**Comment by nurbzz1** [comment]
what i posted will fix that issue

**Comment by azzi1103** [comment]
thanks mate.
