### ISSUE TITLE
[Feral] Ferocious Bite w/no combo points

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#435]
Version: 8.0.1.12-27-g5dffee9-alpha
Character: https://worldofwarcraft.com/en-us/character/us/silvermoon/solitha

HR is sometimes suggesting Ferocious Bite with no combo points. From what I've experienced, and my screenshot attempts, I think there are three factors here:
1. Savage Roar was just used, using all combo points
2. Tiger's Fury is still active
3. Brutal Slash is recharging

This isn't a new problem, but it's been hard to pin down.
![WoWScrnShot_060119_153237](https://user-images.githubusercontent.com/14163320/58767291-e69c1a00-853d-11e9-9b6a-49abea77a6b6.jpg)

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/7a1fa5c5306ec9dd994a91903b9c658600495728

I changed Ferocious Bite to use IsReadyP instead of IsCastableP and, just to be safe, added a check to only suggest it at above 0 combo points.
