### ISSUE TITLE
Demonology: Option to have Nether Portal Off GCD

### ISSUE THREAD

**Issue by DLSauron** [herotc/hero-rotation#436]
Can we please have the option to move Nether Portal off GCD? Also if you turn off cool downs in the HR UI Nether Portal still shows up in the rotation.

**Comment by Cilraaz** [comment]
Added an option to move Nether Portal to OffGCD in commit https://github.com/herotc/hero-rotation/commit/cf2cd8d388f0857a9697cd84f06cf9a5888e4812
