### ISSUE TITLE
Enhancement - Ascendance CD missing off-gcd option

### ISSUE THREAD

**Issue by Herdrage** [herotc/hero-rotation#437]
Can someone implement this when able?

**Comment by Cilraaz** [comment]
Added toggle option to move Ascendance to OffGCD area in commit https://github.com/herotc/hero-rotation/commit/7b9be5d12c42d8d380701d8c936d32e7a28dc903

**Comment by Herdrage** [comment]
Thanks for being so fast, I tried it though and it's not working right. It's not showing anything at a certain point, I believe it's at the point where it recommends ascendance in the rotation. It doesn't show anything in the main icon or off-gcd.

**Comment by Cilraaz** [comment]
The only change I made was adding the GCDasOffGCD option. It's disabled by default, however, so make sure you enable it in the settings.

**Comment by Herdrage** [comment]
Here I'll show you what it's doing since that change. It shows all the other abilities fine but once it gets to ascendance it doesn't show anything and that's with the option on or off now. Before the change it did work fine as part of the main rotation icon. I noticed the elemental spec already had the off-gcd toggle option for it's ascendance, maybe that could be interfering with it somehow? I did try all combinations with both the ele and enh ascendance toggle just to see if that would change anything but it didn't.

![WoWScrnShot_060419_142632](https://user-images.githubusercontent.com/50458490/58908445-37467b00-86d6-11e9-807d-ab7c1dda9513.jpg)

![WoWScrnShot_060419_142647](https://user-images.githubusercontent.com/50458490/58908455-3c0b2f00-86d6-11e9-8ee1-9ce8ac0284a0.jpg)

**Comment by Cilraaz** [comment]
It looks like it was throwing a LUA error because Enhancement settings weren't defined as a variable, like spec settings usually are. It should be fixed in commit https://github.com/herotc/hero-rotation/commit/d3aa52667939e76dc0c489a148bad89b68cb02c9

**Comment by Herdrage** [comment]
Thanks it works perfect now.
