### ISSUE TITLE
errors in guardian spec

### ISSUE THREAD

**Issue by antisocialian** [herotc/hero-rotation#440]
Getting 

> 3031x HeroRotation\Core.lua:160: bad argument #1 to 'pairs' (table expected, got nil)
> [C]: in function `pairs'
> HeroRotation\Core.lua:160: in function `CastCycle'
> HeroRotation_Druid\Guardian.lua:265: in function `?'
> HeroRotation\Main.lua:433: in function <HeroRotation\Main.lua:411>
> 
> Locals:
> InCombatSkipped

while in combat with the alpha version, 8.0.1.12-50-g589ac07-alpha

it repeats until i leave combat but continues when i go back in again. it has been a while since i played guardian so i'm not sure when the issue started, but it doesn't give errors when using version 8.0.1.12(release) of the addon. 

Since i'm not sure what the alpha versions would give me i guess i'll stick to the release version for now?

**Comment by Cilraaz** [comment]
What talents are you using? I'm tanking as Guardian in BoD currently and have gotten no lua errors.

**Comment by antisocialian** [comment]
not sure why i chose them, haven't used guardian in a while, but 

> Blood Frenzy
> Wild Charge
> Balance Affinity
> Typhoon
> Soul of the Forest
> Guardian of Elune
> Rend and Tear

probly not the most efficient talents, but i don't really know how to be a bear

**Comment by Cilraaz** [comment]
It might be Balance Affinity, since that changes your ability ranges. I'll test that once I'm done in raid.

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/90ae8ed0139913c2a750b455207e009fd069737d
