### ISSUE TITLE
Brewmaster Tools

### ISSUE THREAD

**Issue by KrazyMainer** [herotc/hero-rotation#441]
I get this message every  time I go in game. Brewmaster tools is on curseforge but file has been removed. Do I need this and if so where can I find it?
![Brewmaster](https://user-images.githubusercontent.com/39057407/59552518-168fe800-8f56-11e9-995c-2911527a6d05.jpg)

**Comment by Cilraaz** [comment]
This has been updated in the latest profile. You can download it from here on github or, if you use the Twitch client, set the addon type to Alpha for Hero Rotation. You can do this by right clicking Hero Rotation,  going to Release Type, and selecting Alpha.
