### ISSUE TITLE
Beast Mastery seems broken after recent changes

### ISSUE THREAD

**Issue by p4nchez** [herotc/hero-rotation#442]
Hi
it seems beast mastery is broken after one of the recent changes in the splash AOE thing or something other
"0cd6841 [Beast Mastery] Convert to HL Splash Data System - EvanMichaels"

the only suggesten i get is summon pet
nothing else

Survivel and MM work and show icons

**Comment by EvanMichaels** [comment]
If you are syncing to latest on HR you will also need to sync to latest on the Hero Lib core.

**Comment by p4nchez** [comment]
i have both latest alpha from twitch client (hero lib and hero rotation) 

http://wanna.see.my.p4nda.de/ShareX/2019-06-16_17-04-17.png

**Comment by EvanMichaels** [comment]
That issue was fixed almost immediately in https://github.com/herotc/hero-lib/commit/d8097715140052b81f842a22241bd50a6229147b so that change seems to be missing from your local version.

**Comment by p4nchez** [comment]
ok if i download both from latest master here on github no errors and working
but if i install latest alpha from twitch client i get this error
is twitch hero lib alpha not up2date?

**Comment by p4nchez** [comment]
ok i guess i know whats the problem is
twitch client maybe has some thing of delay or something

in twitch client latest alpha looks old


  end

  HL:RegisterForSelfCombatEvent(UpdateAbilityCache, "SPELL_DAMAGE");
  HL:RegisterForPetCombatEvent(UpdateAbilityCache, "SPELL_DAMAGE");
end

but latest alpha from
https://wow.curseforge.com/projects/herolib/files

looks this

  HL:RegisterForSelfCombatEvent(UpdateAbilityCache, "SPELL_DAMAGE", "SPELL_PERIODIC_DAMAGE");
  HL:RegisterForPetCombatEvent(UpdateAbilityCache, "SPELL_DAMAGE");


so i guess you can close this because i didnt know that twitch client hast some kind of delay
but very strange twitch shows name of the latest working alpha

http://wanna.see.my.p4nda.de/ShareX/2019-06-16_17-30-03.png

**Comment by EvanMichaels** [comment]
Huh, yeah that's pretty odd that the checksum shows the same as latest but the files don't mind. I wonder if it is some caching issue on the client or something like that. I will close this, but thanks for the report!
