### ISSUE TITLE
[Feral] Error breaking addon

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#443]
HR 8.0.1.12-79-g2982601-alpha
HL 8.0.1.12-3-gd809771-alpha

https://worldofwarcraft.com/en-us/character/us/silvermoon/solitha

67x HeroRotation\Core.lua:160: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
HeroRotation\Core.lua:160: in function `CastCycle'
HeroRotation_Druid\Feral.lua:342: in function <HeroRotation_Druid\Feral.lua:299>
(tail call): ?
HeroRotation\Main.lua:433: in function <HeroRotation\Main.lua:411>

Locals:
InCombatSkipped

**Comment by Cilraaz** [comment]
Should be fixed after commit https://github.com/herotc/hero-rotation/commit/7f9a173b9a36d8aee19a019897db490b634d2d48

We reverted the new SplashData update for melee specs.
