### ISSUE TITLE
LibUIDropDownMenu and "XML Node object already exists"

### ISSUE THREAD

**Issue by d87** [herotc/hero-rotation#446]
On /reload i'm getting these 3 errors:

Deferred XML Node object named L_UIDropDownMenuButtonTemplate already exists
Deferred XML Node object named L_UIDropDownListTemplate already exists
Deferred XML Node object named L_UIDropDownMenuTemplate already exists

The problem is that LibUIDropDownMenu is using xml and since 8.0 you get these errors when something is defined twice in xml. In my case it's Method Dungeon Tools that's also using it.
I think people switched to https://github.com/p3lim-wow/LibDropDown to fix this

**Comment by Cilraaz** [comment]
I believe this issue has been fixed for quite some time.
