### ISSUE TITLE
[Hunter] error on login

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#447]
I've got a Beastmaster hunter and logged in to this.
Edit: Sorry, only half-awake
HL 8.0.1.12-7-g7e04c07-alpha
HR 8.0.1.12-131-gf246b82-alpha

```
4x HeroRotation_Hunter\Survival.lua:63: '}' expected (to close '{' at line 24) near 'Carve'
[C]: ?
[C]: in function `LoadAddOn'
HeroRotation\Main.lua:373: in function `PulseInit'
HeroRotation\Main.lua:285: in function <HeroRotation\Main.lua:282>

Locals:
(*temporary) = "HeroRotation_Hunter"

```

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/128b5d283c224f015ae085c3abb81444599ec108
