### ISSUE TITLE
Ret Paladin Avenging Wrath + Templars Verdict

### ISSUE THREAD

**Issue by Fuzzygrakk** [herotc/hero-rotation#451]
8.0.1.12-146-g1b58557-alpha

Talents Zeal - BoW - FoJ - WoA - US - WoG - DP

Avenging Wrath is set to show as cool down and not main display.

If Avenging Wrath is off cool down, the main rotation will be blank when it wants to suggest Templar's Verdict.  Templar's Verdict will become visible like normal when Avenging Wrath has been caste and is while it is on cool down.

**Comment by Cilraaz** [comment]
The SimC APL will only use TV if AW/Crusade is on CD, as it assumes AW would be used on CD. I'm currently looking for a good way to change it without completely going against the intent of the APL.

**Comment by Cilraaz** [comment]
A quick fix was issued in commit https://github.com/herotc/hero-rotation/commit/cbe91d474e878e56d83dce3e4ecedeb504ed2943

I added a second Templar's Verdict check that will suggest it when there's enough Holy Power and CDs are disabled. So long as CDs are enabled, TV will require AW/Crusade/ES to be on cooldown before being suggested.

We are looking for a better long-term fix.

**Comment by Gundor** [comment]
With the new version posted today, the bug come back. Blanck when the rotation don't use AW. But Works fine with AW or AW on CD.

**Comment by Cilraaz** [comment]
There was no change that would have affected this. The quick fix line still exists. The only reason it would potentially be an issue is if CDs are enabled in the settings, but AW still isn't being used.

**Comment by solitha** [comment]
I dislike this kind of forced choice. You don't always want to use a cooldown immediately. There are always fights where you want to hold your c/ds for certain moments, phases, targets, etc. Patchwerks are rare.

Even just playing open world like I tend to be doing... I use c/ds on rares and elites or if I get unexpectedly mobbed. Knowing if they're ready is important. But so is being able to judge when to use them.

**Comment by GTBlueGold** [comment]
I apologize for making my post. I thought this one was closed. I am new to the Hub

**Comment by Cilraaz** [comment]
No worries. I haven't really spent any time working on this, as I don't play my Paladin. I'll see if I can squeeze in some time to look at it again.

**Comment by GTBlueGold** [comment]
Thanks. You do great work. For me its not game breaking anyway...if i have a blank spot that pretty much means its time to use 1 of those 2 moves :D

**Comment by Cilraaz** [comment]
Added a toggle option allowing for TV to be suggested when delaying AW/Crusade in commit https://github.com/herotc/hero-rotation/commit/8c4305314ba4c2c94af1657dd0c66f606ced54f2

**Comment by GTBlueGold** [comment]
You’re awesome. Much appreciated.
