### ISSUE TITLE
Essence icon coming on GCD icon [ROGUE]?

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#452]
It used to come on the main GCD icon, and now it's on off GCD, could you atleast make this an option for people who like having them on the main icon?

**Comment by Cilraaz** [comment]
What class/spec?

**Comment by azzi1103** [comment]
For rogue, it would be really great to have this as an option since im used to it from previous versions

**Comment by azzi1103** [comment]
haven't tested on sub, but atleast on outlaw and assassin it only shows as OFF GCD and not on main icon

**Comment by Mystler** [comment]
In the latest version from GitHub or Twitch (via Alpha setting), this is a customizable option in the settings.

**Comment by azzi1103** [comment]
okay thanks! :)
