### ISSUE TITLE
[Shadow] Chat log spam

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#453]
https://worldofwarcraft.com/en-us/character/us/silvermoon/talililis
HR 8.0.1.12-172-g5da5f5f-alpha
HL 8.0.1.12-7-g7e04c07-alpha

When targeting anything attackable, HR sends a constant stream of "Insanity Drain: x" messages to chat, like maybe 10 per second.

**Comment by Cilraaz** [comment]
Sorry about that. Spam has been removed in commit https://github.com/herotc/hero-rotation/commit/8bd92d4783d13e2d308046e54bdf1e12ad02fa40
