### ISSUE TITLE
[Druid]? Runaway error on spec switch

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#454]
Sometimes when I change to Restoration I get an error that just keeps spamming until I reload.

`59x HeroRotation\Main.lua:433: attempt to call field '?' (a nil value)
HeroRotation\Main.lua:433: in function <HeroRotation\Main.lua:411>

Locals:
SpecID = 105
(*temporary) = nil
(*temporary) = "attempt to call field '?' (a nil value)"
HL = <table> {
 UnregisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:198
 Tier21_2Pc = false
 LoadRestores = <function> defined @HeroLib\Events\Main.lua:300
 MythicDungeon = <function> defined @HeroLib\Class\Unit\Player\MythicDungeon.lua:47
 RegisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:109
 GetSplashCount = <function> defined @HeroLib\Misc\Enemies.lua:207
 LiveRealm = <function> defined @HeroLib\Core.lua:36
 UnregisterForEvent = <function> defined @HeroLib\Events\Main.lua:139
 CombatEnded = 2009644.621000
 RangeTracker = <table> {
 }
 GetInstanceInfo = <function> defined @HeroLib\Misc\ToSort.lua:32
 RegisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:124
 MainFrame = HeroLib_MainFrame {
 }
 OutOfCombatTime = <function> defined @HeroLib\Misc\ToSort.lua:94
 UnregisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:170
 Latency = <function> defined @HeroLib\Misc\ToSort.lua:73
 Utils = <table> {
 }
 LoadOverrides = <function> defined @HeroLib\Events\Main.lua:306
 Pulse = <function> defined @HeroLib\Main.lua:29
 UnregisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:156
 TTDRefresh = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:49
 SpecID_ClassesSpecs = <table> {
 }
 GUI = <table> {
 }
 UnregisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:212
 Timer = <table> {
 }
 OffsetRemains = <function> defined @HeroLib\Misc\ToSort.lua:116
 MAXIMUM = 40
 FindKeyBinding = <function> defined @HeroLib\Events\KeyBinding.lua:142
 UnitNotInFront = <table> {
 }
 RegisterForPetCombatEvent = <function> defined @HeroLib\Events\Main.lua:94
 CacheHasBeenReset = false
 LastUnitCycledTime = 0
 BetaRealm = <function> defined @HeroLib\Core.lua:46
 Spell = <table> {
 }
 HasTier = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:113
 Tier19_2Pc = false
 Equipment = <table> {
 }
 RegisterNucleusAbility = <function> defined @HeroLib\Misc\Enemies.lua:225
 Tier20_2Pc = false
 RegisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:64
 PulseInitialized = true
 LastUnitCycled = <table> {
 }
 Tier21_4Pc = false
 UnitNotInFrontTime = 0
 Tier20_4Pc = false
 WhitelistKeyBinding = <function> defined @HeroLib\Events\KeyBinding.lua:138
 Tier19_4Pc = false
 Print = <function> defined @HeroLib\Core.lua:60
 GetInstanceDifficulty = <function> defined @HeroLib\Misc\ToSort.lua:67
 TTD = <table> {
 }
 RegisterForEvent = <function> defined @HeroLib\Events\Main.lua:48
 BuildVersion = <function> defined @HeroLib\Core.lua:31
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @HeroLib\Misc\ToSort.lua:89
 RegisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:79
 GetEquipment = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:24
 BMPullTime = <function> defined @HeroLib\Misc\ToSort.lua:99
 GetEnemies = <function> defined @HeroLib\Misc\Enemies.lua:265
 BuildInfo = <table> {
 }
 Debug = <function> defined @HeroLib\Core.lua:67
 RecoveryOffset = <function> defined @HeroLib\Misc\ToSort.lua:84
 UnregisterForPetCombatEvent = <function> defined @HeroLib\Events\Main.lua:184
 Unit = <table> {
 }
 Item = <table> {
 }
 ValidateSplashCache = <function> defined @HeroLib\Misc\Enemies.lua:218
 ManuallyFilterItemRanges = <function> defined @HeroLib\Class\Unit`

**Comment by Cilraaz** [comment]
I never was able to replicate this issue, but there is now a Resto profile, so this error should no longer occur.
