### ISSUE TITLE
[Rogue] Previous rotation was doing better.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#456]
Previous rotation was doing alot better than current one in singletarget with lucid dreams trait, can you please look into that?

**Comment by Mystler** [comment]
Could you give details and specify what previous/new rotation? There was almost no change.

**Comment by azzi1103** [comment]
the usage on the lucid dreams was better, and the opening was different, my opening is a bit different now and lucid dreams is being suggest too early

**Comment by azzi1103** [comment]
and instead of garrote, it recommends to open with mutilate now. It happened after update

**Comment by EvanMichaels** [comment]
Do you have MA? If so, I think it's intentional to open with Mutilate now to take advantage of the crit out of stealth and it applies Garrote once MA has dropped.

**Comment by azzi1103** [comment]
Might be, it is performing worse rn, from the last version, it must be something. Maybe it's just the lucid dream recommendation being off.

**Comment by azzi1103** [comment]
also is it possible to add trinkets to main icon? would be nice to have that option especially with cyclotronic blast

**Comment by azzi1103** [comment]
The cyclonic blast trinket should probably recommended together with vanish if "Master assassin" is used.

**Comment by EvanMichaels** [comment]
MA does not affect trinkets, it only affects Rogue abilities.

**Comment by azzi1103** [comment]
ahhh okay, would you guys mind adding the option to put trinket on main icon atleast? I never notice the smaller icon on the side

**Comment by Mystler** [comment]
If you are running DS or so, you may have run into a Lucid APL bug. Pushed a fix. The opener change for MA should otherwise not have any noticeable impact. I am taking the liberty of closing this and consider trinket display not a part of it.

**Comment by azzi1103** [comment]
okay thanks for fixing the Lucid dream bug mate. I hope you guys can add the optional button for main icon or "suggested" for tinkets. Again thanks for your time!

**Comment by EvanMichaels** [comment]
Sure, that’s a good suggestion. I will look into that.
