### ISSUE TITLE
3x HeroRotation_Rogue\Outlaw.lua:97: attempt to call local 'MultiSpell' (a nil value)

### ISSUE THREAD

**Issue by erxx** [herotc/hero-rotation#457]
Same error for Assa

3x HeroRotation_Rogue\Outlaw.lua:97: attempt to call local 'MultiSpell' (a nil value)
HeroRotation_Rogue\Outlaw.lua:97: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
HeroRotation\Main.lua:373: in function `PulseInit'
HeroRotation\Main.lua:285: in function <HeroRotation\Main.lua:282>

Locals:
addonName = "HeroRotation_Rogue"
addonTable = <table> {
}
HL = <table> {
 UnregisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:198
 Tier21_2Pc = false
 LoadRestores = <function> defined @HeroLib\Events\Main.lua:300
 MythicDungeon = <function> defined @HeroLib\Class\Unit\Player\MythicDungeon.lua:47
 RegisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:109
 LiveRealm = <function> defined @HeroLib\Core.lua:36
 GetEnemies = <function> defined @HeroLib\Misc\Enemies.lua:28
 CombatEnded = 1
 GetInstanceInfo = <function> defined @HeroLib\Misc\ToSort.lua:32

**Comment by EvanMichaels** [comment]
This sound like you are not synced up to latest on HeroLib

**Comment by erxx** [comment]
Downloaded the files from GitHub
