### ISSUE TITLE
No rotation found for this/class spec

### ISSUE THREAD

**Issue by waveydude** [herotc/hero-rotation#461]
Just installed the addon and my addons show each rotation but once in game it tells me no rotation found. not sure what i could be doing wrong.

**Comment by Cilraaz** [comment]
What class and spec?

**Comment by waveydude** [comment]
i get the same results with every character, rogue,warlock,druid.

**Comment by Cilraaz** [comment]
You have Hero Lib, Hero Cache, and Hero Rotation installed?

**Comment by waveydude** [comment]
![image](https://user-images.githubusercontent.com/23585435/61197393-7b3f7f00-a689-11e9-8848-0b86df834351.png)


Yes i do

**Comment by Cilraaz** [comment]
At that point, it should be working for you. If you're installing from the Twitch app, please make sure both HeroLib and HeroRotation are set to addon type Alpha, then try again.

**Comment by waveydude** [comment]
well thank you. i was able to get it working once installed with the twitch app. unsure why it wasnt working when installing the manual way.
