### ISSUE TITLE
Affliction LUA Error with 8.0.1.12-250-g09d8b04-alpha

### ISSUE THREAD

**Issue by Fraktyl** [herotc/hero-rotation#462]
Current ALPHA throws this error:
464x HeroRotation_Warlock\Affliction.lua:686: attempt to perform arithmetic on a boolean value
HeroRotation_Warlock\Affliction.lua:686: in function `?'
HeroRotation\Main.lua:433: in function <HeroRotation\Main.lua:411>

Locals:
InCombatSkipped

If you wrap the S.DreadfulCalling:AzeriteEnabled() inside a num() call it stops throwing the error.  So the line would look like:

if S.DarkSoul:IsCastableP() and HR.CDsON() and (S.SummonDarkglare:CooldownRemainsP() < 15 + Player:SoulShardsP() * num(S.DreadfulCalling:AzeriteEnabled()) and (Target:DebuffP(S.PhantomSingularityDebuff) or Target:DebuffP(S.PhantomSingularityDebuff) or not S.PhantomSingularity:IsAvailable() and not S.VileTaint:IsAvailable()) or Target:TimeToDie() < 20 + Player:GCD() or EnemiesCount > 1) then

Line 682 looks like it would throw the same LUA error if we had GuardianOfAzeroth castable.

**Comment by Cilraaz** [comment]
Thanks for the report. Fixed in commit https://github.com/herotc/hero-rotation/commit/93fdfffcc9f6644ba315c66752a3fc9bd0210c96
