### ISSUE TITLE
[Fury Warrior] Fury warrior range problems?

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#463]
I've usually used hero with my rogue, but I notice that the fury warrior rotation shows up even though you're not in range. Is there no range check? It's very annoying because when I'm out of range, the icons still show up making me think I'm in range.

**Comment by Cilraaz** [comment]
Added range checks in commit https://github.com/herotc/hero-rotation/commit/b2cd8660579cdd3bfe7f2a14af12326bb56b2bdb
