### ISSUE TITLE
[Protection Warrior] Lua error related to Ashvane's Razor Coral

### ISSUE THREAD

**Issue by kisatan** [herotc/hero-rotation#464]
> HeroRotation_Warrior\Protection.lua:265: attempt to call method 'IsCastableP' (a nil value)
> HeroRotation_Warrior\Protection.lua:265: in function `St'
> HeroRotation_Warrior\Protection.lua:382: in function `?'
> HeroRotation\Main.lua:433: in function <HeroRotation\Main.lua:411>
> 
> Locals:
> InCombatSkipped

This error keeps popping up. I don't have the trinket that line is about.
Version: 8.0.1.12-281-g1d9d624-alpha

**Comment by Cilraaz** [comment]
My mistake. Items should call IsReady, not IsCastableP. This has been resolved in commit https://github.com/herotc/hero-rotation/commit/e4c052ff360b9eac80df1b0a522304e5a304b1da
