### ISSUE TITLE
[Arms] Update APL?

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#466]
Rotation seems to be off, also execute procs from "sudden death" not being prefered at all even though they hit like truck.

**Comment by Cilraaz** [comment]
The HeroRotation Arms profile currently matches the Simulationcraft APL.

**Comment by azzi1103** [comment]
Then there's something wrong with the execute proc from sudden death, because it doesn't recommend execute at all unless target is on executing phase. The execute proc should be in rotation when it procs?

**Comment by Cilraaz** [comment]
What situation are you seeing problems? Single target? AoE? In all three functions (single target, 2-4 target cleave, and 5+ target cleave), it's set to be suggested when Sudden Death is up. It's just not the highest priority spell.

**Comment by azzi1103** [comment]
problem persists in both modes. When execute procs from the talent, it does not suggest at all

**Comment by Cilraaz** [comment]
Not sure why it wasn't working, but it should be fixed as of commit https://github.com/herotc/hero-rotation/commit/04b7a48fba79e53897680c40c08ba72b3756742a

Please let me know if you have any further problems with it.

**Comment by azzi1103** [comment]
I will let you know after checking! thanks mate
