### ISSUE TITLE
SV hunter interrupt symbol lost

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#468]
Hi

if you have a mob that acts a interruptible spell, the symbol where the rotation is shown disappears for the cast duration. no further rotation will be displayed in the magic time until you have interrupted or the magic has been cast. #

thank you in advance

https://www.directupload.net/file/d/5528/yxebcqoz_jpg.htm

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/36007f6e35050804a54bc77d367924518375611a
