### ISSUE TITLE
[War Fury] bug of execute 34

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#470]
if S.Execute:IsReadyP("Melee") then
      if HR.Cast(S.Execute) then return "execute 34"; end
    end

not able to cast Execute, sth wrong here

**Comment by jo32** [comment]
I has sth to do with override.lua, I recover the change like this, it works again:

      if self == SpellFury.Execute then
        return BaseCheck and self:IsUsable()
      elseif self == SpellFury.Charge then
        return (not Target:IsInRange(8) and Target:IsInRange(25))
      else
        return BaseCheck
      end

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/660ed4fbf17f5bcbc1018807626049451acc35a9
