### ISSUE TITLE
BM Hunter Essence toggle not working

### ISSUE THREAD

**Issue by InvalidTheory** [herotc/hero-rotation#479]
When selecting "Show as Off GCD: Essences" on BM hunter, there is no change in the rotation, it still shows the Essence in the same spot as before instead of at the top where Off GCD skills usually go.

**Comment by Cilraaz** [comment]
Placement of both Trinkets and Essences is now in the class settings section. The "Show as Off GCD: Essences" option is completely vestigial and was not removed as an oversight. Please use the dropdown setting under your class. I will remove the extraneous settings.

**Comment by Cilraaz** [comment]
The Hunter settings were messed up from the changeover to the new display options. The class dropdown did nothing, nor did the spec checkbox. This has been fixed in commit https://github.com/herotc/hero-rotation/commit/297bb7a4c12411b7a408ab48ba2e7ad3f5d92dd8
