### ISSUE TITLE
Enh Shaman - Totem mastery keeps getting suggested

### ISSUE THREAD

**Issue by TzachDana** [herotc/hero-rotation#480]
When using this build :https://www.wowhead.com/enhancement-shaman-talent-guide#azerite-builds-primal-primer 
I keep getting Totem in my rotation with the occasional Crash Lightning or Rockbiter.

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/e8ebfa1a2c92e58bb9cdda146f868f67decfdc0c

Please test and let us know if it works as expected now.

**Comment by TzachDana** [comment]
works perfectly thank you :)
