### ISSUE TITLE
There are some problems with ADK and FDK.

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#485]
Hello, I'll probably start in order.

[ADK]
1. Playing as an ADK, I saw that there was no support for [Azshara's Font of Power](https://www.wowhead.com/item=169314/azsharas-font-of-power&bonus=4798:1487). Please add it to the ADK rotation. Since now they are taking [Azshara's Font of Power](https://www.wowhead.com/item=169314/azsharas-font-of-power&bonus=4798:1487) and [Ashvane Razor Coral.](https://www.wowhead.com/item=169311/ashvanes-razor-coral&bonus=4798:1487)
2. After that I tried AOE rotation and saw that we do not use [Dark Transformatio](https://www.wowhead.com/spell=63560/dark-transformation)n in AOE rotation, we just rotate the rotation but without using [Dark Transformation](https://www.wowhead.com/spell=63560/dark-transformation) in AOE.

[FDK]
1. FDK lacks full [Ashvane's Razor Coral](https://www.wowhead.com/item=169311/ashvanes-razor-coral&bonus=4798:1487) support. He uses it only when the [breath of sindragosa](https://www.wowhead.com/spell=152279/breath-of-sindragosa) is working. But he does not look at whether he is inserted or not. It just shows that just click on [Ashvane's Razor Cora](https://www.wowhead.com/item=169311/ashvanes-razor-coral&bonus=4798:1487)l and that’s it. Please revise this moment and also make simultaneous support for [Ashvane's Razor Cora](https://www.wowhead.com/item=169311/ashvanes-razor-coral&bonus=4798:1487)l and [Azshara's Font of Power](https://www.wowhead.com/item=169314/azsharas-font-of-power&bonus=4798:1487).
2. When taking [Frostscythe](https://www.wowhead.com/spell=207230/frostscythe) talent, he works only for AOE but does not want to use it for Solo purpose. As we know that we can use [Frostscythe](https://www.wowhead.com/spell=207230/frostscythe) in Solo target only under one condition when the [Killing Machine](https://www.wowhead.com/spell=51124/killing-machine) buff worked. But he does not do this and simply offers to press [Obliterate](https://www.wowhead.com/spell=49020/obliterate). Please, please also pay attention to this.

P.S. I would like to know if it is possible in the add-on to turn on and off using the key combination? I would like to apply this method to the Pillar of Frost spell? Suppose, at the beginning of rotation, we checked that [Pillar of Frost](https://www.wowhead.com/spell=51271/pillar-of-frost) will be off gkd. Further, when the rotation with [breath of sindragosa](https://www.wowhead.com/spell=152279/breath-of-sindragosa) took place, I press the combination key shift + ctrl + n and [Pillar of Fros](https://www.wowhead.com/spell=51271/pillar-of-frost)t will be displayed already in the Main icon in the rotation, and then to prepare for Sindragosa again in off gkd. Is this possible to do? Thank.

**Comment by Cilraaz** [comment]
[ADK]
1. Azshara's Font of Power is only in the SimulationCraft APL during Precombat. As we match the SimC APL, that's the only entry in HeroRotation. If the SimC APL is updated, HR will be as well.
2. The SimC APL specifically states to not use Dark Transformation during AoE:
`actions.cooldowns+=/dark_transformation,if=!raid_event.adds.exists|raid_event.adds.in>15`
As such, HR replicates this.

[FDK]
1. Ashvane's usage matches the current SimC APL.
2. Frostscythe has been updated to remove the multi-target requirement in several places. This has occurred in commit https://github.com/herotc/hero-rotation/commit/9f72a5cbb06d0c4c79d8b9336e2019d372518eff

**Comment by Cilraaz** [comment]
Also, I don't understand your P.S. request. Please elaborate.

**Comment by narvell3** [comment]
Regarding the update of ashvane's razor coral. He does not want to embed him in the target. It turns out if we do the openner rotation, everything is fine there, but during the fight itself until the moment of syndragosa, he does not insert the coral so that it starts to stack. Here is a screenshot of an example where Hekilli offers me to insert coral so that it starts to stack, and in your rotation it is silent and Weakauras shows that you can insert coral into the target. That's what I wanted you to fix with FDK. [IMG Bug](https://imgur.com/a/UofWEhg)

Regarding P.S. I would like to have a toggle switch ON and OFF in your program by key combinations. So that you can turn it off and on during the battle simply using the keyboard shortcuts. [Img](https://imgur.com/a/6mWhWDP)

**Comment by narvell3** [comment]
I noticed another problem. Playing for ADK, taking control of another rather than a rotation, suggests using a dark transformation. And it should not be so. It is necessary to make a condition that will check whether we have our pet or not.

**Comment by narvell3** [comment]
Thanks for the edits. Regarding the dark transformation, I would like to say that Control undead is absolutely not a pet. And the dark transformation should not be applied to him at all, since we cannot transform other creatures except ours.

Regarding the combination key, it’s a pity that you don’t think of this kind of adding, it would be very convenient to even switch from AOE to ST rotation instead of clicking the panel)

**Comment by narvell3** [comment]
Well, I hope that in Mythic + during the Control Undead the dark transformation will not appear in rotation.
