### ISSUE TITLE
Lua-error by targeting a mob

### ISSUE THREAD

**Issue by Shashlic** [herotc/hero-rotation#486]
Message: ...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:244: attempt to perform arithmetic on a nil value
Time: Sat Aug 24 10:42:06 2019
Count: 132
Stack: ...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:244: attempt to perform arithmetic on a nil value
...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:244: in function `Cds'
...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:441: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals: (*temporary) = 2.013923
(*temporary) = nil
(*temporary) = 0
(*temporary) = <table> {
 LastRemovedFromPlayerTime = 839774.006000
 SpellTable = <table> {
 }
 LastHitTime = 839743.895000
 LastCastTime = 839743.895000
 LastDisplayTime = 840601.252000
 LastAppliedOnPlayerTime = 839743.895000
}
(*temporary) = "attempt to perform arithmetic on a nil value"
S = <table> {
 KillCommand = <table> {
 }
 DanceofDeathBuff = <table> {
 }
 AncestralCall = <table> {
 }
 LightsJudgment = <table> {
 }
 AspectoftheWild = <table> {
 }
 Multishot = <table> {
 }
 GuardianofAzeroth = <table> {
 }
 DanceofDeath = <table> {
 }
 PurifyingBlast = <table> {
 }
 BloodFury = <table> {
 }
 CobraShot = <table> {
 }
 PrimalInstincts = <table> {
 }
 Fireblood = <table> {
 }
 BerserkingBuff = <table> {
 }
 AspectoftheWildBuff = <table> {
 }
 BloodFuryBuff = <table> {
 }
 BloodoftheEnemy = <table> {
 }
 Barrage = <table> {
 }
 RippleInSpace = <table> {
 }
 ConcentratedFlameBurn = <table> {
 }
 PoolFocus = <table> {
 }
 RecklessForceBuff = <table> {
 }
 BestialWrathBuff = <table> {
 }
 SummonPet = <table> {
 }
 PrimalInstinctsBuff = <table> {
 }
 RecklessForceCounter = <table> {
 }
 AMurderofCrows = <table> {
 }
 BeastCleaveBuff = <table> {
 }
 BarbedShot = <table> {
 }
 RapidReload = <table> {
 }
 SpittingCobra = <table> {
 }
 FrenzyBuff = <table> {
 }
 BestialWrath = <table> {
 }
 DireBeast = <table> {
 }
 OneWithThePack = <table> {
 }
 LifebloodBuff = <table> {
 }
 FocusedAzeriteBeam = <table> {
 }
 WorldveinResonance = <table> {
 }
 KillerInstinct = <table> {
 }
 TheUnboundForce = <table> {
 }
 Intimidation = <table> {
 }
 CounterShot = <table> {
 }
 MemoryofLucidDreams = <table> {
 }
 Exhilaration = <table> {
 }
 Berserking = <table> {
 }
 RazorCoralDebuff = <table> {
 }
 ConcentratedFlame = <table> {
 }
 ChimaeraShot = <table> {
 }
 Stampede = <table> {
 }
}
HR = <table> {
 MaxQueuedCasts = 3
 CmdHandler = <function> defined @Interface\AddOns\HeroRotation\Core.lua:208
 PulseInit = <function> defined @Interface\AddOns\HeroRotation\Main.lua:348
 GetTexture = <function> defined @Interface\AddOns\HeroRotation\Core.lua:46
 APLInits = <table> {
 }
 CastSuggested = <function> defined @Interface\AddOns\HeroRotation\Core.lua:197
 CastAnnotated = <function> defined @Interface\AddOns\HeroRotation\Core.lua:110
 PulsePreInit = <function> defined @Interface\AddOns\HeroRotation\Main.lua:294
 LeftIconFrame = HeroRotation_LeftIconFrame {
 }
 MainFrame = HeroRotation_MainFrame {
 }
 GUISettings = <table> {
 }
 AoEON = <function> defined @Interface\AddOns\HeroRotation\Core.lua:284
 NameplateIconFrame = HeroRotation_NameplateIconFrame {
 }
 CreateBackdrop = <function> defined @Interface\AddOns\HeroRotation\UI.lua:61
 ToggleIconFrame = HeroRotation_ToggleIconFrame {
 }
 ChangePulseTimer = <function> defined @Interface\AddOns\HeroRotation\Main.lua:457
 Commons = <table> {
 }
 Print = <function> defined @Interface\AddOns\HeroRotation\Core.lua:31
 CastCycle = <function> defined @Interface\AddOns\HeroRotation\Core.lua:157
 Cast = <function> defined @Interface\AddOns\HeroRotation\Core.lua:87
 Pulse = <function> defined @Interface\AddOns\HeroRotation\Main.lua:417
 CastTargetIf = <function> defined @Interface\AddOns\HeroRotation\Core.lua:173
 Timer = <table> {
 }
 Locked = <function> defined @Interface\AddOns\HeroRotation\Core.lua:294
 Nameplate = <table> {
 }
 CastLeftCommon = <function> defined @Interface\AddOns\HeroRotation\Core.lua:139
 Ready = <function>

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/631c332f6b39f9b46ea34972a08a948239a87e91
