### ISSUE TITLE
[ADK] Have troubles with razor coral ashwane

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#490]
Hello. Yesterday in the raid I noticed that the coral does not work as it should in rotation. In short and in fact. It turns out that we pull out the coral very often, preventing it from pushing on. If we look at the rotation of simcraft, then he pulls it out very rarely and try to use it as efficiently as possible so there are a lot of stacks. And it turns out that I stuck in the coral, and pulled out when I have 2-4 stacks. When should I pull it out on 10+ stacks at least. I also know such a moment that coral is not a predictable thing in terms of stacks. But to insert and pull out the coral very often on 2-4 stacks is not effective, I think. Please look at this moment. Thank. 

By the way, such a moment was noticed and was at FDK, not always but manifested.

**Comment by Cilraaz** [comment]
Current HeroRotation usage matches SimulationCraft's suggested usage. There are multiple conditions that will trigger its suggestion, but none rely on the number of stacks.
