### ISSUE TITLE
Enhancement Shaman ERROR

### ISSUE THREAD

**Issue by DKong86** [herotc/hero-rotation#496]
I have deleted all my addons and reinstalled HeroRotation yet I keep getting this error message but only for Enhancement Shaman the other Shaman specs work fine for me.
Message: Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:173: attempt to index global 'feral_spirit' (a nil value)
Time: Tue Sep  3 22:13:10 2019
Count: 503
Stack: Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:173: attempt to index global 'feral_spirit' (a nil value)
Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:173: in function <Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:171>
Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:548: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals: (*temporary) = <function> defined @Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:163
(*temporary) = nil
(*temporary) = <table> {
 LastRemovedFromPlayerTime = 0
 LastAppliedOnPlayerTime = 0
 SpellType = "Player"
 LastHitTime = 0
 LastCastTime = 0
 LastDisplayTime = 0
 SpellID = 114051
}
(*temporary) = nil
(*temporary) = false
(*temporary) = "attempt to index global 'feral_spirit' (a nil value)"
VarCooldownSync = 0
num = <function> defined @Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:163
S = <table> {
 StrengthofEarth = <table> {
 }
 Frostbrand = <table> {
 }
 ForcefulWinds = <table> {
 }
 GuardianofAzeroth = <table> {
 }
 LandslideBuff = <table> {
 }
 FeralSpirit = <table> {
 }
 BloodFury = <table> {
 }
 ResonanceTotemBuff = <table> {
 }
 NaturalHarmonyNatureBuff = <table> {
 }
 PrimalPrimer = <table> {
 }
 WorldveinResonance = <table> {
 }
 CrashLightningBuff = <table> {
 }
 FuryofAirBuff = <table> {
 }
 BloodoftheEnemy = <table> {
 }
 RazorCoralDebuff = <table> {
 }
 WindShear = <table> {
 }
 SearingAssault = <table> {
 }
 LightningConduitDebuff = <table> {
 }
 CrashLightning = <table> {
 }
 StormbringerBuff = <table> {
 }
 SeethingRageBuff = <table> {
 }
 EarthenSpikeDebuff = <table> {
 }
 EarthenSpike = <table> {
 }
 LavaLash = <table> {
 }
 FuryofAir = <table> {
 }
 Landslide = <table> {
 }
 AscendanceBuff = <table> {
 }
 StrengthofEarthBuff = <table> {
 }
 AncestralCall = <table> {
 }
 LightningConduit = <table> {
 }
 CapacitorTotem = <table> {
 }
 Stormstrike = <table> {
 }
 PrimalPrimerDebuff = <table> {
 }
 LightningShield = <table> {
 }
 Fireblood = <table> {
 }
 MoltenWeaponBuff = <table> {
 }
 HotHandBuff = <table> {
 }
 Sundering = <table> {
 }
 TotemMastery = <table> {
 }
 RecklessForceCounter = <table> {
 }
 ConcentratedFlameBurn = <table> {
 }
 RecklessForceBuff = <table> {
 }
 Rockbiter = <table> {
 }
 LifebloodBuff = <table> {
 }
 Hailstorm = <table> {
 }
 FocusedAzeriteBeam = <table> {
 }
 TheUnboundForce = <table> {
 }
 ConcentratedFlame = <table> {
 }
 RippleInSpace = <table> {
 }
 Flametongue = <table> {
 }
 PurifyingBlast = <table> {
 }
 MemoryofLucidDreams = <table> {
 }
 ConductiveInkDebuff = <table> {
 }
 Boulderfist = <table> {
 }
 NaturalHarmonyFireBuff = <table> {
 }
 NaturalHarmonyFrostBuff = <table> {
 }
 HotHand = <table> {
 }
 CracklingSurgeBuff = <table> {
 }
 SunderingDebuff = <table> {
 }
 FrostbrandBuff = <table> {
 }
 GatheringStormsBuff = <table> {
 }
 LightningBolt = <table> {
 }
 FlametongueBuff = <table> {
 }
 Thundercharge = <table> {
 }
 CrashingStorm = <table> {
 }
 NaturalHarmony = <table> {
 }
 Berserking = <table> {
 }
 Overcharge = <table> {
 }
 Ascendance = <table> {
 }
 Windstrike = <table> {
 }
 IcyEdgeBuff = <table> {
 }
}
Player = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:581
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:632
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:218
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:706
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:92
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Playe

**Comment by Cilraaz** [comment]
Update to the latest alpha if updating via Twitch.

**Comment by DKong86** [comment]
I have the latest update 8.0.2.00 this is issue is not resolved but thx for just dismissing my error report like u did

**Comment by Cilraaz** [comment]
It was fixed in a commit after the release of 8.0.2.00, which is why I said to get the latest alpha.
