### ISSUE TITLE
lightforged draenei warrior racial issue

### ISSUE THREAD

**Issue by madmons** [herotc/hero-rotation#498]
Hi,

when i use your addon as a lightforged draenei warrior, the Light's Judgment racial trait always appears in the middle icon, even with the "Show as Off GCD: Racials" option selected. Am I doing something wrong?

Thanks

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/6593edc2fded69cd3d359e2b6d64266998ea5e38

**Comment by madmons** [comment]
ty !
