### ISSUE TITLE
fix epedemic adk

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#499]
Can I fix the epidemic? the ad epidemic does not work correctly, but rather an aoe mode. when we are close in the radius, then the epidemic works for several purposes, and if we just hang out the plague, then the epidemic does not offer long distances, although the work of the epidemic is not limited by the radius, the main thing is that there is one condition, there was a plague on the target and the epidemic will to bear the damage in no dependence at what distance. please fix this moment.

**Comment by Cilraaz** [comment]
Epidemic has two conditions, both within the AoE rotation. First, it will be suggested if Death and Decay is active, you have less than 2 runes, and you shouldn't be pooling for Gargoyle. Second, lower in priority, it will be suggested simply if you shouldn't be pooling for Gargoyle.

I'm unsure of what the problem is.

**Comment by narvell3** [comment]
I may not put it correctly apologize. I will explain in more detail.
When the battle is on, let's say with 2 goals. how your rotation works, if the goals are nearby, then he suggests pouring a puddle, and reaping an epidemic. but if the second goal is far from us, then the rotation does not offer to reap an epidemic, but simply put the death coil in the rotation. it turns out so we just hung out the plague for both purposes, the addon should offer me an epidemic for the death coil place but it doesn’t. but if the target is close within the radius of my cleave then everything works correctly.

**Comment by narvell3** [comment]
just test it yourself. 1 target will be close to you and you beat it. and the second goal is far away, but it is possible to reach it with the plague and see that for two purposes the epidemic will not work.

**Comment by narvell3** [comment]
https://imgur.com/a/URv70I6 
Here is a good example of what I am writing about. I hit the main target, and the other 3 goals are infected with the plague, and the epidemic is not offered in rotation. and it should be.

**Comment by Cilraaz** [comment]
It won't be suggested because the targets are not nearby. The AoE rotation is only suggested if there are 2+ targets within 8 yards of you.

**Comment by narvell3** [comment]
https://www.wowhead.com/spell=207317/epidemic
so if you read the spell and see, there is no indication of how many yards it works. The only condition is that there is a plague on the target, and it doesn’t matter where it stands, but if we push the epidemic, the damage will go through the target even if it is 1000+ yards away from us and is out of our sight. I think this is not correct if the epidemic is offered only when the target is within a radius of 8m. An epidemic should be offered when there are two targets infected with the plague.

**Comment by Cilraaz** [comment]
As posted in the Discord:
`The addon currently can't determine something like Epidemic's usage. At most, I could convert Unholy to use SplashData, but then it wouldn't check to ensure that all of the targets have plague. It's an edge case scenario at best.`

I'll keep this issue open as a possible future enhancement.

**Comment by narvell3** [comment]
ok thank.

**Comment by Cilraaz** [comment]
I made a change in commit https://github.com/herotc/hero-rotation/commit/97b97f4a4754d5d7af7070a7d66555b1063d638c

This should give you the usage you're expecting. Please let me know.

**Comment by narvell3** [comment]
works great. I am very grateful for the fix. everything works well, the epidemic works at any distance. and it’s not attached to the radius. The only thing I noticed was that the goals were in the field of view of my character and that’s all, but these are trifles. thanks again for the cool implementation.
