### ISSUE TITLE
Fix outlaw rogue 3+ target RTB priority & SS spam @ Proper wits stacks

### ISSUE THREAD

**Issue by Buddhaman1** [herotc/hero-rotation#500]
Currently not updating for 3+ target cleave RTB priority. 

Also, not updating rotation @ 14 wits stacks to ignore opportunity procs when >45 energy

**Comment by Mystler** [comment]
Can you specify? The addon is updated to the latest SimC APL research state which includes BF RtB rerolling and the 14 stacks you mention. Are you using the latest version?
