### ISSUE TITLE
Splash Damage not working for SPriest/Mages

### ISSUE THREAD

**Issue by CoilDomain** [herotc/hero-rotation#501]
Splash damage seems to work fine for BM Hunter, but for some reason these class/specs seem to not. Let me know what info you might need, I'm running the latest alpha.

**Comment by Cilraaz** [comment]
All 4 profiles are configured to use SplashData. What seems to not be working for you?

**Comment by CoilDomain** [comment]
For spriest Mindsear is never recommended, same with FlameStrike on Fire mage.

**Comment by Cilraaz** [comment]
I'm unable to replicate the issue. For SplashData, you must first damage the targets with an AoE ability for them to be counted among available targets. 

In Shadow's case, this would be Void Eruption, Mind Sear, Dark Void, or Shadow Crash. 
In Fire's case, this would be Blast Wave, Meteor, Dragon's Breath, Living Bomb, Flamestrike, or Phoenix Flames.

**Comment by CoilDomain** [comment]
Not sure what else I can give, I just deleted the addon, reinstalled it from Twitch, updated it to alpha and went on my priest to the dummies in Zuldazar, precasting mindsear or void eruption did not change that mind flay was suggested. Ran into Darkshore just to make sure it wasn't an issue with neutral mobs and the same thing happened.

**Comment by Cilraaz** [comment]
I logged into my Priest and hit the dummies in Boralus. I casted Mind Blast, VT, and Mind Sear. The result was Mind Sear being suggested going forward as expected.
![mindsear](https://user-images.githubusercontent.com/12204132/64483092-f1b0b700-d1ca-11e9-9d97-7a7cea6f06fd.png)

**Comment by CoilDomain** [comment]
Here's the debug log. 
![image](https://user-images.githubusercontent.com/2592475/64483121-74397680-d1cb-11e9-953a-7feef5fe0408.png)

**Comment by Cilraaz** [comment]
What talents are you using? I can try to test with the same setup to see if it's a talent issue.

**Comment by CoilDomain** [comment]
3111111

**Comment by Cilraaz** [comment]
Spec'd 3111111, I still have Mind Sear suggested as expected. What version of HeroLib are you using?

**Comment by CoilDomain** [comment]
![image](https://user-images.githubusercontent.com/2592475/64483200-2ec97900-d1cc-11e9-86bc-4b92eb3861ec.png)

**Comment by elmurjfudd** [comment]
![image](https://user-images.githubusercontent.com/55065713/64495033-a0540680-d262-11e9-9be3-85cd7a35d4d0.png)
 have u tried unchecking this box in settings ?

**Comment by CoilDomain** [comment]
Thanks but this is about splash damage, so that's pointless.

**Comment by nurbzz1** [comment]
I had a lot of issues with Splash damage too on bm, it would nto register multitarget for like 4-5 secs after pull. I ended up just pulling the unit count around pet  from a weak aura and it works perfectly, not sure if you could apply this to other specs tho.

**Comment by Cilraaz** [comment]
SplashData doesn't register targets until they're hit by an AoE ability, at which point they're counted immediately.

Ideally, Blizzard could just give us an API call for number of targets we're currently in combat with. Unfortunately, they haven't, so we have to find our own workarounds.
