### ISSUE TITLE
BeastMastery.lua:432 - Trinket Razor Coral?

### ISSUE THREAD

**Issue by Shashlic** [herotc/hero-rotation#503]
Hi guys, 

_8.0.2.00-74-gb9b343c-alpha works without this LUA:432_

with the newest Alpha:
**when Trinket Razor Coral ist rdy to use + a target**. LUA: can you have a look at: 

Message: ...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:432: attempt to call method 'CooldownRemainsP' (a nil value)
Time: Mon Sep 23 10:25:28 2019
**Count: 880**
Stack: ...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:432: attempt to call method 'CooldownRemainsP' (a nil value)
...nterface\AddOns\HeroRotation_Hunter\BeastMastery.lua:432: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals: Precombat = <function> defined @Interface\AddOns\HeroRotation_Hunter\BeastMastery.lua:165
Cds = <function> defined @Interface\AddOns\HeroRotation_Hunter\BeastMastery.lua:214
Cleave = <function> defined @Interface\AddOns\HeroRotation_Hunter\BeastMastery.lua:256
St = <function> defined @Interface\AddOns\HeroRotation_Hunter\BeastMastery.lua:338
(*temporary) = 8888
(*temporary) = <function> defined @Interface\AddOns\HeroRotation_Hunter\BeastMastery.lua:131
(*temporary) = nil
(*temporary) = <table> {
 ItemID = 167555
 LastHitTime = 0
 LastCastTime = 0
 LastDisplayTime = 0
 ItemSlotID = <table> {
 }
}
(*temporary) = "attempt to call method 'CooldownRemainsP' (a nil value)"
GCDMax = 1.418184
Player = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:581
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:632
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:218
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:706
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:92
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:271
 Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:680
 InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:69
 RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:131
 VersatilityDmgPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:98
 ArcaneChargesDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:664
 MaelstromPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:541
 ArcaneCharges = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:649
 ActiveMitigationNeeded = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Tank.lua:57
 SoulShardsDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:459
 IsInWhitelistedVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:121
 PainDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:721
 AttackPower = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:57
 FocusCastRegen = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:200
 PainDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:726
 PrevOffGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:150
 MasteryPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:93
 InsanityPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:617
 ManaDeficitPercentageP = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:105
 FuryDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:690
 PrevGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:128
 AstralPowerMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:470
 IsMounted = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:23
 EnergyRegenPercentage = <function> defined @Interface\Ad

Thx 4 support,
Shashlic

**Comment by Cilraaz** [comment]
This should be fixed as of commit https://github.com/herotc/hero-rotation/commit/a153a0b5dd572b824607a40dbc91a674e3264461
