### ISSUE TITLE
[FDK] fix Chains of Ice with the coral interaction.

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#504]
Hello. After the update, I noticed a couple of bugs.

1. The bug is that the addon offers us to use Chains of Ice not on 20 stacks when we use coral to take critical damage. He just thinks that we are using the ice pillar and as a result the addon is buggy and every time offers to beat Chains of Ice when the coral is active and when the ice pillar is active. View this moment please.

2. And the second bug is that at the beginning of the battle when we do Oppener, the addon does not offer to insert coral into the target. If I myself do not press it myself then the rotation is again violated all. He will just insert coral but not pick up stacks. And when we lived at the beginning of the azshara trinket, we have 30 seconds of cd per coral, and in fact we should activate it, but the addon does not say that we need to click on the coral as it became ready, and only when it is ready for the second time BoS.

Please return as it was before, because the rotation all flew into the trash.

**Comment by Cilraaz** [comment]
1. Chains of Ice does not interact with Ashvane's Razor Coral, as per the SimC APL. The profile suggests Chains of Ice in accordance with the SimC APL.
2. There was an APL line missing that suggested Ashvane's Razor Coral when the target does not have the Razor Coral debuff. That has been added in commit https://github.com/herotc/hero-rotation/commit/33f9651419c623d3038685bc611eb6c4ffc537c8
