### ISSUE TITLE
Error visual in the interfaz and I can`t use the addon

### ISSUE THREAD

**Issue by Royking89** [herotc/hero-rotation#505]
Message: Interface\AddOns\HeroRotation\Main.lua:153: Frame HeroRotation_MainFrame is not movable
Time: Sun Sep 29 17:09:40 2019
Count: 7
Stack: Interface\AddOns\HeroRotation\Main.lua:153: Frame HeroRotation_MainFrame is not movable
[C]: ?
[C]: in function `StartMoving'
Interface\AddOns\HeroRotation\Main.lua:153: in function <Interface\AddOns\HeroRotation\Main.lua:152>

Locals:

**Comment by Royking89** [comment]
Message: Interface\AddOns\HeroRotation\Main.lua:30: attempt to index field '__MSQ_NormalTexture' (a nil value)
Time: Sun Sep 29 17:17:56 2019
Count: 1
Stack: Interface\AddOns\HeroRotation\Main.lua:30: attempt to index field '__MSQ_NormalTexture' (a nil value)
Interface\AddOns\HeroRotation\Main.lua:30: in function <Interface\AddOns\HeroRotation\Main.lua:28>
Interface\AddOns\HeroRotation\Main.lua:54: in function `func'
Interface\AddOns\Masque\Core\Callback.lua:42: in function <Interface\AddOns\Masque\Core\Callback.lua:37>
Interface\AddOns\Masque\Core\Group.lua:60: in function <Interface\AddOns\Masque\Core\Group.lua:54>
Interface\AddOns\Masque\Core\Group.lua:179: in function `ReSkin'
Interface\AddOns\HeroRotation\Main.lua:254: in function <Interface\AddOns\HeroRotation\Main.lua:179>

Locals: Frame = HeroRotation_LeftIconFrame {
 ChangeIcon = <function> defined @Interface\AddOns\HeroRotation\UI.lua:360
 __MSQ_Shape = "Square"
 GetNormalTexture = <function> defined @Interface\AddOns\HeroRotation\Main.lua:239
 __MSQ_NormalHook = true
 __MSQ_bType = "Legacy"
 __MSQ_Enabled = true
 __MSQ_oType = "Frame"
 __MSQ_NormalColor = <table> {
 }
 __MSQ_Normal = <unnamed> {
 }
 __MSQ_ChargeSkin = <table> {
 }
 Texture = <unnamed> {
 }
 Init = <function> defined @Interface\AddOns\HeroRotation\UI.lua:342
 Backdrop = <unnamed> {
 }
 __MSQ_Addon = "HeroRotation"
 0 = <userdata>
 __MSQ_NormalSkin = <table> {
 }
 __MSQ_Backdrop = <unnamed> {
 }
 __MSQ_Icon = <unnamed> {
 }
 SetNormalTexture = <function> defined =[C]:-1
}
Disabled = <table> {
 Normal = <table> {
 }
 Checked = <table> {
 }
 Backdrop = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '__MSQ_NormalTexture' (a nil value)"
mathmin = <function> defined =[C]:-1

**Comment by Royking89** [comment]
I add image about the error we have -> https://ibb.co/SRGnqmH

**Comment by Cilraaz** [comment]
This error was due to an update in Masque. It was fixed several versions ago. If you update via the Twitch client, please set your release type to alpha to receive the latest updates.
