### ISSUE TITLE
Many syntax error in Unholy.lua

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#508]
Please check it

**Comment by Cilraaz** [comment]
I'm unable to duplicate any errors with Unholy. Please ensure that you have updated to the latest profile. If you update via the Twitch app, please set the Release Type to Alpha.

If you are still having problems after this, please reply with a copy of the error message, your azerite essences, your azerite traits, and your talent selections.

**Comment by Cilraaz** [comment]
No reply in 5 days. Closing this issue. If it re-occurs, please open a new issue.
