### ISSUE TITLE
Problem with Monk Windwalker

### ISSUE THREAD

**Issue by Mikhael85** [herotc/hero-rotation#512]
With new version of addon, i have some problem with monk dps,...only tiger palm is in rotarion.

**Comment by Hinalover** [comment]
I've been meaning to update the monk module since the revamp to the SimC APL. I'll take a look over the next few days.

**Comment by yoshimo** [comment]
I sometimes get this:

`Message: ..\AddOns\HeroRotation_Monk\Windwalker.lua line 520:
   attempt to call method 'CooldownRemainsP' (a nil value)
Debug:
   [C]: CooldownRemainsP()
   HeroRotation_Monk\Windwalker.lua:520:
      HeroRotation_Monk\Windwalker.lua:518
   HeroRotation_Monk\Windwalker.lua:339: Cooldowns()
   HeroRotation_Monk\Windwalker.lua:570: ?()
   HeroRotation\Main.lua:439:
      HeroRotation\Main.lua:417`

**Comment by Cilraaz** [comment]
That error should be fixed in commit https://github.com/herotc/hero-rotation/commit/61a21dffd86f3e3f5655130cffc464c281a594dc

I accidentally used CooldownRemainsP, which isn't available for items. It's now changed to CooldownRemains.
