### ISSUE TITLE
[ADK] Bugged Epidemic solo target.

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#513]
Hello, I updated HeroRotation and after the update my epidemic began to work incorrectly. A bug appears when we hit 1 target, or else there is 1 target next to us, but there is no dot.

Please check the correct operation of the epidemic. By logic, it should work only when there are 2+ goals, and there is a plague.

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/440d8a13bce12968f407f5b2ef584ec63271c75b

I added a check to the AoE Epidemic suggestions. It will not only suggest Epidemic during AoE if 2+ targets are afflicted with Virulent Plague.
