### ISSUE TITLE
lua warnings

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#516]
Message: Interface\AddOns\HeroRotation\Commons.lua:62: attempt to index field '?' (a nil value)
Time: Sat Oct 26 12:35:54 2019
Count: 36
Stack: Interface\AddOns\HeroRotation\Commons.lua:62: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\HeroRotation\Commons.lua:62: in function `Interrupt'
Interface\AddOns\HeroRotation_Hunter\Survival.lua:652: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals:

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/c23b47957da6db875f6733498324928140141e4b
