### ISSUE TITLE
Issue with Pocket-Sized Computation Device

### ISSUE THREAD

**Issue by johnnyops** [herotc/hero-rotation#518]
Char: Monk / Windwalker (120)

Issue: Generating numerous LUA errors and ability button will randomly disappear

Cause: I do not have the Cyclotronic Blast punchcard on my Pocket-Sized Computation Device and this appears to be the problem as it errors out looking for a cooldown time ("CooldownRemainsP")

See attached lua error message
[lua_error.txt](https://github.com/herotc/hero-rotation/files/3797011/lua_error.txt)

**Comment by Cilraaz** [comment]
This issue was resolved in a prior commit. Please update to the latest alpha version to obtain the fix.
