### ISSUE TITLE
marksman hunter issues happens more in dungeons than target dummy 

### ISSUE THREAD

**Issue by elmurjfudd** [herotc/hero-rotation#519]
talents r 1123231     here the lua error i get

 Message: ...nterface\AddOns\HeroRotation_Hunter\Marksmanship.lua:221: attempt to perform arithmetic on a nil value
Time: Sun Nov  3 01:29:13 2019
Count: 71
Stack: ...nterface\AddOns\HeroRotation_Hunter\Marksmanship.lua:221: attempt to perform arithmetic on a nil value
[C]: ?
...nterface\AddOns\HeroRotation_Hunter\Marksmanship.lua:221: in function `Cds'
...nterface\AddOns\HeroRotation_Hunter\Marksmanship.lua:400: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

not sure whats happening i tried checking and unchecking options i tried using release alpha and beta and nothing

**Comment by elmurjfudd** [comment]
mainly seems only on mutli traget it happens even with aoe rotation turn off also happens with splash data turned on or off

**Comment by Cilraaz** [comment]
I believe this was an issue with the BaseDuration check on Guardian of Azeroth. I've instead hard-coded the duration, as it's 30 seconds with all levels of the essence. Please re-test the latest alpha update and let me know if the issue is resolved. Thanks!

Fixed(?) in commit https://github.com/herotc/hero-rotation/commit/fbfd80d81c65f2552fc225c01047decb717c717e

**Comment by elmurjfudd** [comment]
ok still pops up if i hold GOA when its off cd i get the error like trash before a boss but if u use it on pull no issues at all so basically i cant hold essence cd at all just switched to marks ths does happen with surv

**Comment by elmurjfudd** [comment]
anyone know which version this started so maybe i can use an old version to avoid this issue?

**Comment by Cilraaz** [comment]
Try the latest version after commit https://github.com/herotc/hero-rotation/commit/424b9341a73ecefc76b9923362befc590327c12c

**Comment by elmurjfudd** [comment]
ty kindly working great now ill close this appreciate all u guys do
