### ISSUE TITLE
[Balance] A bug with AOE rotation in ST

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#520]
Hello. Yesterday I decided to play for Balance Druid, and a bug was noticed in the raid on 1 boss and on subsequent other bosses and just adds. The problem is that when we start our rotation in the beginning everything is fine until the moment where we gained astral power to press the Starsurge ability, but he thinks that we have more than 4+ goals, and suggests instead of Starsurge to press Starfall. I thought maybe the addon sees some more goals but no. And so it turns out that in our ST rotation, Starfall goes for the Starsurge place. Fix it please. There is a possibility that this is due to the new Splash AOE function.

**Comment by narvell3** [comment]
will you fix the problem? Or will it be in ST to show the goal in Starfire rotation? or do you think it works well? here is a screenshot. https://imgur.com/a/IjDzKds

**Comment by narvell3** [comment]
Is tech support alive at all? Or can I close the balance rotation? You have a bug in determining ST and AOE. Correct enough to ignore this. You have a serious bug and you care.

**Comment by Cilraaz** [comment]
Please provide the following information:
- Talent Build
- Azerite Essences in use
- Azerite Traits in use, specifically ranks of Arcanic Pulsar and Streaking Stars)

**Comment by narvell3** [comment]
Talent Build - https://imgur.com/a/gVHW4kt
Azerite Essences in use - (Vision of Perfection LVL2 Major) (Focused Azerite Beam LVL2 Minor) https://imgur.com/a/atQbQXy
Azerite Traits - Head (Power of the Moon, Streaking Stars) Shoulder (Arcanic Pulsar, Arcane Heart) Chest (Streaking Stars, Dawning Sun) https://imgur.com/a/Ttr49uD

**Comment by Cilraaz** [comment]
Do you have SplashData enabled or disabled?

**Comment by narvell3** [comment]
enabled SplashData

**Comment by Cilraaz** [comment]
I ran a quick test on the dummies in Boralus and couldn't replicate the issue. I'll do a bit of testing on some World Quests when I get home this evening and see if I can get the issue to occur.

**Comment by narvell3** [comment]
The bug appears on ST bosses. 
I think it works because of the large radius of recognition. I repeated it either on the bosses, or simply in the open world, or something else.

**Comment by Cilraaz** [comment]
There is no "radius of recognition" when SplashData is enabled. SplashData will only count targets hit by an AoE ability. The 40 yard radius is only used when SplashData is disabled.

**Comment by Cilraaz** [comment]
I've tested in a few world quests, including the weekly Nazjatar world boss, as that's a good single target with tons of other targets around the player. I matched your talent spec, had a rank of Arcanic Pulsar, and less than 2 ranks of Streaking Stars. This would put the Starfall target variable to 6 for both of us. I was not able to get the addon to suggest Starfall at all while attacking single target.

**Comment by narvell3** [comment]
So I have attached screenshots again. That the bug is repeated. As I understand it, there is a certain delay when adds die and the addon does not have time to calculate how many goals, or the radius is very large, I do not know what the problem is. Also, even when there is a battle with active enemy units, for some reason he nevertheless offers to use Starfall. When they didn’t even fight with us. It turns out somewhere a problem but I do not know where. Img (https://imgur.com/a/9fPW2lt)

**Comment by narvell3** [comment]
We still have not resolved this issue regarding a bug with Starfal.
Because in rotation it appears in ST rotation Starfall. Not always, but there are moments on the same azshara. When we kill the kiran and the Einer, and then the azshara appears, then Starfall always appears for the place of starsurge, as if we are fighting with AOE 7+ targets. And so on until the end. But try yourself in such a condition to test. It’s just not good to leave it as it is.

**Comment by Buddhaman1** [comment]
I just wanted to respnd and say that I also have experienced this. Starfall  is effectively taking the place of starsurge in ST. Obviously it's not a huge deal as you just ignore the starfall suggestion but it def. is odd

**Comment by aethys256** [comment]
Closed since Balance is not supported coming into SL yet.
