### ISSUE TITLE
Criteria for SnD

### ISSUE THREAD

**Issue by illion20** [herotc/hero-rotation#521]
Is there anyone who would be so kind to explain why this is a criteria for SnD for Rogue Outlaw? Where does the value 1.8 come from?
https://github.com/herotc/hero-rotation/blob/1f7598e2fa0198e498ae9c9a2c8570523aaf32f6/HeroRotation_Rogue/Outlaw.lua#L498

**Comment by Cilraaz** [comment]
This is more of a question for the SimC team, as these values come from their APL.
