### ISSUE TITLE
Same issue as #451 (closed topic)

### ISSUE THREAD

**Issue by GTBlueGold** [herotc/hero-rotation#522]
I have loved this addon for quite some time. My paladin also doesnt suggest to use TV or divine storm unless wrath is on cooldown. It did not used to be like this. I have made no changes other than to update with twitch addon updater. just thought I would make it known that the issue that the other person had..I am having as well. works perfectly when wrath is on cooldown...has blank spots when it isnt. Everything else for me is pretty well flawless across most accounts.

**Comment by Cilraaz** [comment]
Closing duplicate to issue #451, which is still open at this time.
