### ISSUE TITLE
[Enhancement Shaman] Crash Lightning

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#526]
HR: 8.2.5.01-32-g9031d8b-alpha
HL: 8.2.5.01-3-gc006615-alpha
Character: https://worldofwarcraft.com/en-us/character/us/earthen-ring/skarai

I last quested with this character within the last week or two. Today, though, I'm noticing Crash Lightning coming up in the rotation even when I'm only fighting one thing, where it was specifically a multi-target spell before. It feels like it's really disrupting the rotation.

Edit: It's even being suggested with AoE off.

**Comment by Cilraaz** [comment]
Crash Lightning is properly being suggested as a filler for single target when Forceful Winds is talented, as per the December 31st change to the SimulationCraft APLs.
