### ISSUE TITLE
HeroRotation_Hunter/Survival.lua CastTargetIf error

### ISSUE THREAD

**Issue by Darkmoded** [herotc/hero-rotation#527]
if HR.CastTargetIf(S.KillCommand, 50

range 50 is not defined 

need to add 50 to range check
local EnemyRanges = {8,50}

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/afc8e44caea28fd04e48bdb8eb16f04edc644656
