### ISSUE TITLE
Can I modify the BDK rotation?

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#528]
Hello. I decided to try the addon rotation on BDK. And I saw that there are a lot of downtime, because of this we have a small survival rate and a small DPS. Plus, there are absolutely no ligaments with the heart of Azeroth. Could you make a rotation either to bias in survival or to bias dps rotation. Because BDK rotation is disgusting right now.

**Comment by Cilraaz** [comment]
As discussed in the Discord channel, Blood is handled about as well as possible at the moment. If you have specific suggestions, we will gladly accept them. Overall, the profile functions fairly well.
