### ISSUE TITLE
[Feral] Request for HoA modification

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#530]
HR: 8.2.5.01-132-g25495ea-alpha

I know HR is not meant to optimize lower level characters, but generally it does pretty well at it anyway. A recent update to the Feral module, though, has made it inoperable without the BfA neck. The addon throws errors upon entering combat until the game throttles it.

`88x HeroRotation_Druid\Feral.lua:282: attempt to index field 'HeartEssence' (a nil value)
[string "@HeroRotation_Druid\Feral.lua"]:282: in function `Cooldowns'
[string "@HeroRotation_Druid\Feral.lua"]:510: in function `?'
[string "@HeroRotation\Main.lua"]:439: in function <HeroRotation\Main.lua:417>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'HeartEssence' (a nil value)"
S = <table> {
 JungleFury = <table> {
 }
 SavageRoarBuff = <table> {
 }
 ThrashCatDebuff = <table> {
 }
 PrimalWrath = <table> {
 }
 ProwlBuff = <table> {
 }
 RakeDebuff = <table> {
 }
 MoonfireCat = <table> {
 }
 MoonfireCatDebuff = <table> {
 }
 Sabertooth = <table> {
 }
 Thorns = <table> {
 }
 ConcentratedFlameBurn = <table> {
 }
 PurifyingBlast = <table> {
 }
 RecklessForceBuff = <table> {
 }
 Shred = <table> {
 }
 GuardianofAzeroth = <table> {
 }
 IncarnationBuff = <table> {
 }
 FocusedAzeriteBeam = <table> {
 }
 WorldveinResonance = <table> {
 }
 IronJawsBuff = <table> {
 }
 TheUnboundForce = <table> {
 }
 TigersFury = <table> {
 }
 Incarnation = <table> {
 }
 PredatorySwiftnessBuff = <table> {
 }
 RippleInSpace = <table> {
 }
 MemoryofLucidDreams = <table> {
 }
 BloodoftheEnemy = <table> {
 }
 RazorCoralDebuff = <table> {
 }
 CatForm = <table> {
 }
 Prowl = <table> {
 }
 SavageRoar = <table> {
 }
 Regrowth = <table> {
 }
 ShadowmeldBuff = <table> {
 }
 CatFormBuff = <table> {
 }
 SkullBash = <table> {
 }
 ScentofBlood = <table> {
 }
 ClearcastingBuff = <table> {
 }
 PoolResource = <table> {
 }
 SwipeCat = <table> {
 }
 BrutalSlash = <table> {
 }
 ThrashCat = <table> {
 }
 RipDebuff = <table> {
 }
 ScentofBloodBuff = <table> {
 }
 LunarInspiration = <table> {
 }
 Bloodtalons = <table> {
 }
 TigersFuryBuff = <table> {
 }
 Rake = <table> {
 }
 Rip = <table> {
 }
 FerociousBiteMaxEnergy = <table> {
 }
 WildFleshrending = <table> {
 }
 Berserk = <table> {
 }
 FeralFrenzy = <table> {
 }
 FerociousBite = <table> {
 }
 Maim = <table> {
 }
 ConductiveInkDebuff = <table> {
 }
 Berserking = <table> {
 }
 Shadowmeld = <table> {
 }
 ConcentratedFlame = <table> {
 }
 BloodtalonsBuff = <table> {
 }
 BerserkBuff = <table> {
 }
}
HR = <table> {
 MaxQueuedCasts = 3
 CmdHandler = <function> defined @HeroRotation\Core.lua:216
 PulseInit = <function> defined @HeroRotation\Main.lua:348
 GetTexture = <function> defined @HeroRotation\Core.lua:46
 APLInits = <table> {
 }
 CastSuggested = <function> defined @HeroRotation\Core.lua:205
 CastAnnotated = <function> defined @HeroRotation\Core.lua:118
 PulsePreInit = <function> defined @HeroRotation\Main.lua:294
 LeftIconFrame = HeroRotation_LeftIconFrame {
 }
 MainFrame = HeroRotation_MainFrame {
 }
 GUISettings = <table> {
 }
 AoEON = <function> defined @HeroRotation\Core.lua:292
 NameplateIconFrame = HeroRotation_NameplateIconFrame {
 }
 CreateBackdrop = <function> defined @HeroRotation\UI.lua:61
 ToggleIconFrame = HeroRotation_ToggleIconFrame {
 }
 ChangePulseTimer = <function> defined @HeroRotation\Main.lua:457
 Commons = <table> {
 }
 Print = <function> defined @HeroRotation\Core.lua:31
 CastCycle = <function> defined @HeroRotation\Core.lua:165
 Cast = <function> defined @HeroRotation\Core.lua:87
 Pulse = <function> defined @HeroRotation\Main.lua:417
 CastTargetIf = <function> defined @HeroRotation\Core.lua:181
 Timer = <table> {
 }
 Locked = <function> defined @HeroRotation\Core.lua:302
 Nameplate = <table> {
 }
 CastLeftCommon = <function> defined @HeroRotation\Core.lua:147
 Ready = <function> defined @HeroRotation\Main.lua:452
 APLs = <table> {
 }
 ResetIcons = <function> defined @HeroRotation\UI.lua:36
 CastLeftOffset = 1
 SuggestedIconFrame = HeroRotation_SuggestedIconFrame {
 }
 CastLeftNameplate = <function> defined @HeroRotation\Core.lua:158
 CastQueue = <function> defined @HeroRotation\Core.lua:129
 SmallIconFrame = HeroRotation_SmallIconFrame {
 }
 MainIconPartOverlayFrame = HeroRotation_MainIconPartOverlayFrame {
 }
 MainIconFrame = HeroRotation_MainIconFrame {
 }
 CastSuggestedOffse`

**Comment by Cilraaz** [comment]
This should be fixed by commit https://github.com/herotc/hero-rotation/commit/0ea4c6088d076941d135de9deafb544ff6a92c84

Please let me know if this fixes your issue or if you continue to have the issue.

**Comment by solitha** [comment]
Updated to 8.2.5.01-133-g4c18b70-alpha but it's still there. Did your commit make it into that update or am I waiting for another one?

**Comment by Cilraaz** [comment]
That is the update prior to the one with the above commit.

**Comment by solitha** [comment]
Fixed! Thanks so much!
