### ISSUE TITLE
Beast Mastery Aspect of the wild

### ISSUE THREAD

**Issue by darydaryd** [herotc/hero-rotation#532]
Take it out of the rotation please. or add a feature to let the user decide.
In mythic + I want to decide where to use it. I don't want it to be basically the only thing it tells me to use next. Its so annoying I disabled the add on its completely useless in mythic + .
Let the user know its off cd but dont make it part of the rotation.

**Comment by nurbzz1** [comment]
You can set hotkeys to turn on and off cool downs being suggested

**Comment by Cilraaz** [comment]
You can either disable cooldowns entirely or use the previously added option to move the Aspect of the Wild icon to the OffGCD area, which will allow you to delay it while the main icon still shows other abilities. This option is found in the Beast Mastery section as "Show as Off GCD: Aspect of the Wild".
