### ISSUE TITLE
[Feral] Request to add Balance Affinity support

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#533]
It looks like Balance Affinity is the suggested talent for the tier, and I've been using it anyway and enjoying the extended range it gives me.

I know there were fights in EP specifically where you had to run off by yourself for disgustingly extended amounts of time. That's when I'd try my Balance cooldown just because I had nothing else I could do. But the addon doesn't support it so I was just blindly throwing spells.

Not sure how this would be done... perhaps suggest the moonkin cooldown when out of range as a radial option; if the cooldown is invoked, switch to Balance spells with cat form as a radial option (to suggest you get your butt back into melee if possible). You can probably come up with better ideas, but at least having a Balance rotation while using the Affinity c/d would be awesome.

**Comment by solitha** [comment]
In addition and related... I also see you've added range detection with red shading, which I am all for! But with Balance Affinity, your range is extended. I don't know if it's possible for the addon to read that adjusted range straight from the tooltip or not.

**Comment by Cilraaz** [comment]
Added Balance Affinity handling in commit https://github.com/herotc/hero-rotation/commit/f7b9be558ec8a94f179171b77eba33f98ca8681b

**Comment by Cilraaz** [comment]
Re-opening issue. The Balance Affinity handling that was added was for the additional range, not any out of melee range/Moonkin Form handling.

**Comment by aethys256** [comment]
Closed since Feral is not supported coming into SL yet.
