### ISSUE TITLE
version mismatch between Twitch and Blizzard

### ISSUE THREAD

**Issue by Sericus** [herotc/hero-rotation#534]
Greetings all. Is anyone else getting an error message in game, when Twitch calls the version up to date? Blizzard and Twitch disagree. If I'm the idiot, please tell me, am I doing something wrong?

edit: specifically, Twitch has version 8.2.5 marked as current, and Blizzard is expecting 8.3, and won't load the addon, and it doesn't work in game even if you force load it.

**Comment by Cilraaz** [comment]
What version of the addon are you running? Checking the "Load Out-of-Date Addons" option in WoW should fix the issue.

**Comment by Cilraaz** [comment]
Please ignore the above. I went ahead and pushed an updated 8.3.0 version of the addon. It should show in the updater shortly. If you still have any problems with the addon, please let us know.

**Comment by Sericus** [comment]
Thank you Cilraaz! That did the trick. I was pretty helpless in game without this addon! lol
