### ISSUE TITLE
Arms Warrior CDsOn/CDsOFF issue

### ISSUE THREAD

**Issue by InvalidTheory** [herotc/hero-rotation#535]
Currently, when CDs are off, the Arms rotation still recommends using Warbreaker and Memory of Lucid Dreams.  I fixed it by modifying line 352:

`if S.Warbreaker:IsCastableP("Melee") and HR.CDsON() then`

and line 498:

`if S.MemoryofLucidDreams:IsCastableP() and HR.CDsON() and (S.Warbreaker:IsAvailable() and S.Warbreaker:CooldownRemainsP() < Player:GCD() and (Target:TimeToDie() > 150 or Target:HealthPercentage() < 20)) then`

Also, 

There might be some other issues with Arms.lua, it wasn't recommending to reuse Memory of Lucid Dreams after the first use, and a few of the OGCD/Main/Suggested options weren't working.  Thank you.

**Comment by Cilraaz** [comment]
I fixed the missed HR.CDsON() check for the one Warbreaker line. I've also added HR.CDsON() checks for Colossus Smash, as well as adding an OffGCD option for Colossus Smash.

We haven't used CDsON for any of the azerite essences. Rather, they have an option of how they are displayed (main icon, offgcd, or "suggested").

I see no reason Memory of Lucid Dreams wouldn't be suggested after first use or any OffGCD settings that wouldn't be working. If you can provide any further information, it would be appreciated.

The Colossus Smash/Warbreaker updates are included in commit https://github.com/herotc/hero-rotation/commit/4a0062d3814256c1c8000c40da0b2d0f2c44f335
