### ISSUE TITLE
Problem with paladin spenders

### ISSUE THREAD

**Issue by Gankedit** [herotc/hero-rotation#536]
HeroRotation will not suggest a holy spender unless avenging wrath is activated. When it comes to holy spender on AoE or Single target the addon deactivates until a spender has been pressed.

**Comment by Cilraaz** [comment]
That matches the expected result from the SimC APL. We added an option a while ago called "Allow Delayed Avenging Wrath" to allow for the use of finishers while delaying AW/Crusade.
