### ISSUE TITLE
Havoc DH error

### ISSUE THREAD

**Issue by IAmAGitNewbie** [herotc/hero-rotation#537]
Simply targeting anything (hostile or not) with v8.3.0.00 results in this error:

Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:255: attempt to compare number with boolean
Time: Sun Mar  8 11:23:13 2020
Count: 206
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:255: attempt to compare number with boolean
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:255: in function `Cooldown'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:462: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals:

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/ae59b49847718656c18a1c34fb2e87f69722add9

Thanks for the report!
