### ISSUE TITLE
Havoc DH Error on use of Eye Beam

### ISSUE THREAD

**Issue by Markiv3** [herotc/hero-rotation#538]
Message: Interface\AddOns\HeroRotation\Core.lua:48: attempt to index local 'Object' (a number value)
Time: Mon Mar  9 20:55:29 2020
Count: 130
Stack: Interface\AddOns\HeroRotation\Core.lua:48: attempt to index local 'Object' (a number value)
[string "@Interface\AddOns\HeroRotation\Core.lua"]:48: in function `GetTexture'
[string "@Interface\AddOns\HeroRotation\Core.lua"]:88: in function `Cast'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:288: in function `Cooldown'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:472: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals: Object = 159617
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Object' (a number value)"
Cache = <table> {
 GUIDInfo = <table> {
 }
 Set = <function> defined @Interface\AddOns\HeroCache\Main.lua:270
 WipeTableRecursively = <function> defined @Interface\AddOns\HeroCache\Main.lua:276
 Get = <function> defined @Interface\AddOns\HeroCache\Main.lua:254
 APLVar = <table> {
 }
 Enemies = <table> {
 }
 Reset = <function> defined @Interface\AddOns\HeroCache\Main.lua:41
 HasBeenReset = true
 SpellInfo = <table> {
 }
 UnitInfo = <table> {
 }
 Persistent = <table> {
 }
 MiscInfo = <table> {
 }
 ItemInfo = <table> {
 }
 EnemiesCount = <table> {
 }
}
tostring = <function> defined =[C]:-1

I believe changing line 288 in HeroRotation_DemonHunter\Havoc.lua  to the below will fix it. It at least stopped throwing the error for me.

if HR.Cast(Item(TrinketToUse), nil, Settings.Commons.TrinketDisplayStyle) then return "Generic use_items for " .. TrinketToUse:Name(); end

**Comment by Cilraaz** [comment]
Make sure you've updated both HeroRotation and HeroLib. It looks like you do not have the latest HeroLib update.
