### ISSUE TITLE
[Affliction] Error on login

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#539]
HR 8.3.0.00-35-g323f18f-alpha
HL 8.3.0.00-5-g9bd74c7-alpha
Character https://worldofwarcraft.com/en-us/character/us/silvermoon/kayonnoruva

There's a third error, but it only says (null).

Error 1
`1x HeroRotation_Warlock\Overrides.lua:19: attempt to index local 'SpellAffli' (a nil value)
[string "@HeroRotation_Warlock\Overrides.lua"]:19: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@HeroRotation\Main.lua"]:373: in function `PulseInit'
[string "@HeroRotation\Main.lua"]:285: in function <HeroRotation\Main.lua:282>

Locals:
HL = <table> {
 UnregisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:198
 Tier21_2Pc = false
 LoadRestores = <function> defined @HeroLib\Events\Main.lua:300
 MythicDungeon = <function> defined @HeroLib\Class\Unit\Player\MythicDungeon.lua:47
 RegisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:109
 GetSplashCount = <function> defined @HeroLib\Misc\Enemies.lua:207
 LiveRealm = <function> defined @HeroLib\Core.lua:36
 GetTime = <function> defined @HeroLib\Core.lua:51
 CombatEnded = 1
 RangeTracker = <table> {
 }
 GetInstanceInfo = <function> defined @HeroLib\Misc\ToSort.lua:32
 RegisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:124
 MainFrame = HeroLib_MainFrame {
 }
 OutOfCombatTime = <function> defined @HeroLib\Misc\ToSort.lua:94
 UnregisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:170
 Latency = <function> defined @HeroLib\Misc\ToSort.lua:73
 Utils = <table> {
 }
 UseTrinkets = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:140
 LoadOverrides = <function> defined @HeroLib\Events\Main.lua:306
 Pulse = <function> defined @HeroLib\Main.lua:29
 UnregisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:156
 TTDRefresh = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:49
 SpecID_ClassesSpecs = <table> {
 }
 GuardiansTable = <table> {
 }
 GUI = <table> {
 }
 UnregisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:212
 Timer = <table> {
 }
 OffsetRemains = <function> defined @HeroLib\Misc\ToSort.lua:116
 ImmolationTable = <table> {
 }
 UnregisterNucleusAbilities = <function> defined @HeroLib\Misc\Enemies.lua:263
 MAXIMUM = 40
 FindKeyBinding = <function> defined @HeroLib\Events\KeyBinding.lua:142
 BuildInfo = <table> {
 }
 RegisterForPetCombatEvent = <function> defined @HeroLib\Events\Main.lua:94
 LastUnitCycledTime = 0
 BetaRealm = <function> defined @HeroLib\Core.lua:46
 GetInstanceDifficulty = <function> defined @HeroLib\Misc\ToSort.lua:67
 HasTier = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:119
 Tier19_2Pc = false
 Equipment = <table> {
 }
 RegisterNucleusAbility = <function> defined @HeroLib\Misc\Enemies.lua:225
 Tier20_2Pc = false
 RegisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:64
 Tier21_4Pc = false
 Tier20_4Pc = false
 Tier19_4Pc = false
 LastUnitCycled = <table> {
 }
 OnUseTrinkets = <table> {
 }
 UnitNotInFrontTime = 0
 GetEnemies = <function> defined @HeroLib\Misc\Enemies.lua:274
 WhitelistKeyBinding = <function> defined @HeroLib\Events\KeyBinding.lua:138
 UnitNotInFront = <table> {
 }
 Print = <function> defined @HeroLib\Core.lua:60
 RegisterForEvent = <function> defined @HeroLib\Events\Main.lua:48
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @HeroLib\Core.lua:31
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @HeroLib\Misc\ToSort.lua:89
 RegisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:79
 GetEquipment = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:23
 BMPullTime = <function> defined @HeroLib\Misc\ToSort.lua:99
 ValidateSplashCache = <function> defined @HeroLib\Misc\Enemies.lua:218
 Item = <table> {
 }
 Debug = <function> defined @HeroLib\Core.lua:67
 RecoveryOffset = <function> defined @HeroLib\Misc\ToSort.lua:84
 UnregisterForPetCombatEvent = <function> defined @HeroLib\Events`

Error 2
`4x HeroRotation_Warlock\Affliction.lua:383: 'then' expected near ','
[string "=[C]"]: in function `LoadAddOn'
[string "@HeroRotation\Main.lua"]:373: in function `PulseInit'
[string "@HeroRotation\Main.lua"]:285: in function <HeroRotation\Main.lua:282>

Locals:
(*temporary) = "HeroRotation_Warlock"
`

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/ca0c5153f4d68037890a2827fe62eac919bc43a5
