### ISSUE TITLE
[Feral] Breaks after dots

### ISSUE THREAD

**Issue by solitha** [herotc/hero-rotation#540]
The addon just stops after Rip and Rake are applied. I'm not sure what version; I was using the latest alpha, but currently backtracking through alphas trying to find one that works because my raid group is going on without me :(

`6604x HeroRotation_Druid\Feral.lua:407: attempt to call method 'buffP' (a nil value)
[string "@HeroRotation_Druid\Feral.lua"]:407: in function `Cooldowns'
[string "@HeroRotation_Druid\Feral.lua"]:616: in function `?'
[string "@HeroRotation\Main.lua"]:439: in function <HeroRotation\Main.lua:417>

Locals:
Skipped (In Encounter)`

**Comment by EvanMichaels** [comment]
Should be fixed with https://github.com/herotc/hero-rotation/commit/dc7d9661e7a37606a09a8331657da4328e44b8a7

**Comment by solitha** [comment]
Thanks for that. Since I suck at github and that commit isn't on Curse yet, do you know what version I can downgrade it back to, offhand?
