### ISSUE TITLE
Ret Pali Buggy Suggested Rotation

### ISSUE THREAD

**Issue by dcodom** [herotc/hero-rotation#541]
When I target the mob, it works just fine, however once I do 1 or 2 suggested attacks, it displays nothing at all. Then after a while of me attacking with my manual suggestions (in my head suggestions), it will finally start displaying suggestions again. I dont know when this started, as I dont keep up with all my toons. It was working. I am running the latest update to the rotation addon, which I update always.

I do not know what else I can provide to help troubleshoot this issue. Please let me know.

**Comment by Cilraaz** [comment]
I was unable to replicate your issue. Please be sure that you either use Avenging Wrath or Crusade when suggested or check the option to "Allow Delayed Avenging Wrath".

If you do not see this option under the options for Retribution, be sure that you have the latest version of the addon. If you use the Twitch app to update, be sure the addon type is set to alpha.

**Comment by dcodom** [comment]
I wasnt running with the alpha version. That took care of the issue. 

Thanks!
