### ISSUE TITLE
Can I speed up the next spell on RDD?

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#542]
Hello. I am using your addon for MDD. And there he does an excellent job, for which many thanks to you. But he decided to try it on Destro warlock and noticed that if I pressed the spell button, then he would not show the next spell until he reached the end. Can I make it so that when I click on the spell, it immediately shows the following? or highlighted the one we clicked? Because I get confused and don’t understand whether it’s worth further to continue to press this spell or not, since the add-on happens that after the end shows that use it, and sometimes it says continue to use it further.

**Comment by aethys256** [comment]
This is due to not optimal implementation of the cast prediction in destruction rotation. With Shadowlands, we will try to release only optimal rotation rather than as much as possible, focusing on quality rather than quantity.
