### ISSUE TITLE
Demon Hunter Rotation Error

### ISSUE THREAD

**Issue by Kungfujo** [herotc/hero-rotation#543]
I've tried to reload, Uninstalled and reinstalled. Nothing is working.

Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:255: attempt to compare number with boolean
Time: Sun Mar 22 12:31:28 2020
Count: 262
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:255: attempt to compare number with boolean
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:255: in function `Cooldown'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:462: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Locals: (*temporary) = false
(*temporary) = <table> {
 LastRemovedFromPlayerTime = 0
 LastAppliedOnPlayerTime = 0
 SpellType = "Player"
 LastHitTime = 0
 LastCastTime = 0
 LastDisplayTime = 0
 SpellID = 206491
}
(*temporary) = 50
(*temporary) = nil
(*temporary) = "attempt to compare number with boolean"
S = <table> {
 ThrowGlaive = <table> {
 }
 RevolvingBlades = <table> {
 }
 DarkSlashDebuff = <table> {
 }
 FelBarrage = <table> {
 }
 PreparedBuff = <table> {
 }
 FelRush = <table> {
 }
 TrailofRuin = <table> {
 }
 EyeBeam = <table> {
 }
 MetamorphosisBuff = <table> {
 }
 BladeDance = <table> {
 }
 RecklessForceCounter = <table> {
 }
 WorldveinResonance = <table> {
 }
 ConcentratedFlameBurn = <table> {
 }
 RecklessForceBuff = <table> {
 }
 FelEruption = <table> {
 }
 RazorCoralDebuff = <table> {
 }
 RippleInSpace = <table> {
 }
 ChaosStrike = <table> {
 }
 LifebloodBuff = <table> {
 }
 ReapingFlames = <table> {
 }
 GuardianofAzeroth = <table> {
 }
 DemonBlades = <table> {
 }
 ChaoticTransformation = <table> {
 }
 DarkSlash = <table> {
 }
 DeathSweep = <table> {
 }
 Metamorphosis = <table> {
 }
 FocusedAzeriteBeam = <table> {
 }
 TheUnboundForce = <table> {
 }
 FelMastery = <table> {
 }
 DemonsBite = <table> {
 }
 PurifyingBlast = <table> {
 }
 MemoryofLucidDreams = <table> {
 }
 BloodoftheEnemy = <table> {
 }
 BlindFury = <table> {
 }
 VengefulRetreat = <table> {
 }
 Demonic = <table> {
 }
 Disrupt = <table> {
 }
 Felblade = <table> {
 }
 ChaosNova = <table> {
 }
 MomentumBuff = <table> {
 }
 Annihilation = <table> {
 }
 FirstBlood = <table> {
 }
 ConductiveInkDebuff = <table> {
 }
 Nemesis = <table> {
 }
 Momentum = <table> {
 }
 ConcentratedFlame = <table> {
 }
 NemesisDebuff = <table> {
 }
 ImmolationAura = <table> {
 }
}
Player = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:581
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:632
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:218
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:706
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:92
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:271
 Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:680
 InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:69
 RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:131
 VersatilityDmgPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:98
 ArcaneChargesDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:664
 MaelstromPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:541
 ArcaneCharges = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:649
 ActiveMitigationNeeded = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Tank.lua:57
 SoulShardsDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:459
 IsInWhitelistedVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:121
 PainDeficit = <function> defined @Interface\Ad

**Comment by Cilraaz** [comment]
If you're installing from the Twitch client, please be sure to set the release type to Alpha for both HeroRotation and HeroLib. It appears you have an older version, as line 255, referenced in your error, does not contain any comparisons.
