### ISSUE TITLE
Is it possible to hide something like an addon when streaming a game?

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#545]
I want to stream the game, but I do not want users to see that I am using the addon. Can you somehow hide it from the audience? So that I can see the addon in the game, and not see my rotation addon on the stream? I just know what the creators of add-ons have been practicing for a long time and it seems to be possible to do this. Please, please do not ignore my question.

**Comment by Cilraaz** [comment]
It seems this would have more to do with your streaming configuration than the addon. There's no way to have an addon somehow display to you within the game and not display on a capture of the game.
