### ISSUE TITLE
[Havoc Demon Hunter] Removing Throw glaive from main icon.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#546]
Would be an amazing option to have. So annoying to have throw glaive pop up all the time on main icon when you move a little bit. Ruins it pretty much for me. Possible to have it as an option to be off and on main icon? Since it's pretty much something barely used in a PVE rotation

**Comment by Cilraaz** [comment]
Your wish is granted.

Added in commit https://github.com/herotc/hero-rotation/commit/c15c46cc1c1cc9d3eb76ab19fd1114d7082eceb1
