### ISSUE TITLE
BM Hunter - Recommending AOTW on ST even during an active VOP proc

### ISSUE THREAD

**Issue by gac21116** [herotc/hero-rotation#549]
The BM Hunter rotation helper doesn't seem to interact with VOP procs, as it still recommends AOTW when a VOP proc is currently active., despite the ST apl stating: actions.st+=/aspect_of_the_wild,if=buff.aspect_of_the_wild.down&(cooldown.barbed_shot.charges<1|!azerite.primal_instincts.enabled)

This is of course avoidable by switching both aotw and wrath to off gcd and having a WA or something similar that shows when you have VOP procs but figured I'd point this out in case it's something worth fixing

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/bb54f843bb7d3bde6855da0bea315bb7cc9b7da8
