### ISSUE TITLE
Request: Add optoin to take summon infernal off of GCD

### ISSUE THREAD

**Issue by gac21116** [herotc/hero-rotation#550]

**Comment by Cilraaz** [comment]
Unfortunately, moving Summon Infernal to the OffGCD location stalls the remainder of the profile. When Summon Infernal is not used, it creates a cascade effect. If also spec'd into Grimoire of Supremacy, the profile stalls completely, suggesting only Incinerate, Conflagrate, and Immolate until Infernal is eventually used. When not spec'd into Grimoire, it's slightly more usable, but still does not operate correctly. As such, we will not be adding the OffGCD option at this time.
