### ISSUE TITLE
[Assassination] Bug: Rupture with no combo point

### ISSUE THREAD

**Issue by beati** [herotc/hero-rotation#552]
Hi,

While playing I noticed that rupture was sometimes suggested with no combo point which is a problem because we can't cast rupture without combo point.

I think 3ec3c9855f861d31d23755df15216dd05f456467 introduced the bug. It's also probably a bug in simcraft apl but not sure.

Here rupture can be cast with 0 combo point if HL.CombatTime() > 10 :
https://github.com/herotc/hero-rotation/blob/ae30163c32f6d57d724c7cfc362194498f377a8e/HeroRotation_Rogue/Assassination.lua#L748-L751

The corresponding APL line is :
https://github.com/herotc/hero-rotation/blob/ae30163c32f6d57d724c7cfc362194498f377a8e/HeroRotation_Rogue/Assassination.lua#L737
which is not consistent with the one at the end of the file
https://github.com/herotc/hero-rotation/blob/ae30163c32f6d57d724c7cfc362194498f377a8e/HeroRotation_Rogue/Assassination.lua#L1075
There is an extra 
`&(time>10|combo_points>=2)`
as far as I understand this condition can't be correct for rupture because it can be true with 0 combo point.
The condition is also present in this APL line :
https://github.com/herotc/hero-rotation/blob/ae30163c32f6d57d724c7cfc362194498f377a8e/HeroRotation_Rogue/Assassination.lua#L1066
which is probably a bug in simcraft.

**Comment by Mystler** [comment]
Thanks for the report. SimC knows that Rupture cannot be used without CP so this has no effect on it. However, in HR we have to manually add a check for CP even if the amount does not matter to avoid these 0CP bugs. So, yeah, I think this is a simple oversight and easy to fix, but I'll wait for @EvanMichaels input as he was fiddling with that.
