### ISSUE TITLE
Error with MM hunter rotation resulting in addon to stop working and alot of lua errors.

### ISSUE THREAD

**Issue by crusnikssin** [herotc/hero-rotation#553]
Hello i just started messing around with MM hunter the other day but noticed that the icon disappears and addon stops working. I have attached below the lua error that I am getting.

Message: ...nterface\AddOns\HeroRotation_Hunter\Marksmanship.lua:241: attempt to call method 'CooldownRemainsP' (a nil value)
Time: Sat Jun  6 10:22:36 2020
Count: 64
Stack: ...nterface\AddOns\HeroRotation_Hunter\Marksmanship.lua:241: attempt to call method 'CooldownRemainsP' (a nil value)
[string "=[C]"]: in function `CooldownRemainsP'
[string "@Interface\AddOns\HeroRotation_Hunter\Marksmanship.lua"]:241: in function `Cds'
[string "@Interface\AddOns\HeroRotation_Hunter\Marksmanship.lua"]:436: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:439: in function <Interface\AddOns\HeroRotation\Main.lua:417>

Love the addon keep up the good work.

**Comment by Cilraaz** [comment]
Line 241 is not a line that references CooldownRemainsP in the most recent version. If you're updating the addon via the Twitch app, please set the release type to alpha to get the latest updates.
