### ISSUE TITLE
Problem with Fire Mage rotation

### ISSUE THREAD

**Issue by Tensewicz** [herotc/hero-rotation#554]
Hello,

I'm having a problem with fire mage rotation.

All the time im opening my rotation it points me to cast schorch, and it doesn't matter what - it is always scorch. I've noticed it is something wrong with Combustion since whenever im setting combustion on main window and im using it in rotation it works fine, otherwise it just spam schorch without a reason (no 30% and no combustion). I've read some1 had a problem with it some time ago but couldn't find an answer for that.

**Comment by Cilraaz** [comment]
There is a line in the APL for Scorch that checks against the cooldown remaining on Combustion. If Combustion is not used (making the remaining cooldown 0), the line will return true, which is causing the Scorch loop.

If you wish to delay Combustion usage, you can enable the "Disable Combustion" option, which will allow the rotation to continue without forcing Combustion usage.
