### ISSUE TITLE
 Please make Outbreak be used on the boss when there are other targets nearby.

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#555]
Hello. I’ve written many times in discord, but they don’t want to hear me, or ignore this, I duplicate here the question, the problem. Please make sure that Outbreak during the battle with the boss and 2+ targets nearby, so that the addon does not offer to use Outbreak for nearby targets, but simply uses Outbreak on the boss so that the ability infects nearby targets. So it will be more correct. This can be done if FDK with its wind.

**Comment by Cilraaz** [comment]
The logic of Outbreak is to be suggested on any target whose Virulent Plague will wear off within a GCD. This usage will spread VP to all nearby targets. If the player wishes to use Outbreak on the primary target instead of the suggested target, they're welcome to do so.
