### ISSUE TITLE
Error with Rogue Outlaw Rotation

### ISSUE THREAD

**Issue by lectrcsprx** [herotc/hero-rotation#556]
Im getting this error ingame.

Message: Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:307: bad argument #1 to 'pairs' (table expected, got nil)
Time: Thu Jun 18 06:23:08 2020
Count: 1368
Stack: Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:307: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua"]:307: in function `FightRemains'
[string "@Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua"]:332: in function `FilteredFightRemains'
[string "@Interface\AddOns\HeroRotation_Rogue\Outlaw.lua"]:474: in function <Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:374>
[string "@Interface\AddOns\HeroRotation_Rogue\Outlaw.lua"]:642: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:446: in function <Interface\AddOns\HeroRotation\Main.lua:424>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by lectrcsprx** [comment]
I use Twitch to update and would love it if you put new patch for addon there!  :)

**Comment by Cilraaz** [comment]
If you are using the alpha version of HeroRotation, it requires that you also use the alpha version of HeroLib.

**Comment by lectrcsprx** [comment]
Where can I get the Alpha version of HeroLib?

**Comment by Cilraaz** [comment]
If you update via the Twitch app, right click the addon, go to Release Type, and select alpha.

Otherwise, you can download the alpha versions here:
[HeroLib](https://www.curseforge.com/wow/addons/herolib/files/all)
[HeroRotation](https://www.curseforge.com/wow/addons/herorotation/files/all)

**Comment by solitha** [comment]
This still appears to be an issue. I appear to be up to date with both alphas on the Twitch client.
HeroLib-8.3.0.00-17-g95b5dbe-alpha.zip
HeroRotation-8.3.0.00-171-g06585e2-alpha.zip

I'm not getting it on every fight... running a lvl 99 at the moment.

**Comment by Cilraaz** [comment]
The addon isn't guaranteed to work for characters under max level. If you provide an exact error, we can take a look at it, however.

**Comment by solitha** [comment]
1783x HeroLib\Class\Unit\TimeToDie.lua:307: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@HeroLib\Class\Unit\TimeToDie.lua"]:307: in function `FightRemains'
[string "@HeroLib\Class\Unit\TimeToDie.lua"]:332: in function `FilteredFightRemains'
[string "@HeroRotation_Rogue\Outlaw.lua"]:474: in function <HeroRotation_Rogue\Outlaw.lua:374>
[string "@HeroRotation_Rogue\Outlaw.lua"]:643: in function `?'
[string "@HeroRotation\Main.lua"]:446: in function <HeroRotation\Main.lua:424>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by solitha** [comment]
Took one of my rogues out yesterday with no problems. After a while, though, I swapped to Asn because I'm so tired of Roll the Bones RNG. Thanks for checking into it!

**Comment by lectrcsprx** [comment]
Its fixed, ty Kathy
    On Friday, July 10, 2020, 05:18:28 PM CDT, Kathy Clifford <notifications@github.com> wrote:  
 
 


Took one of my rogues out yesterday with no problems. After a while, though, I swapped to Asn because I'm so tired of Roll the Bones RNG. Thanks for checking into it!
