### ISSUE TITLE
Retribution Paladin Not Showing Finishers

### ISSUE THREAD

**Issue by Bipolarized** [herotc/hero-rotation#558]
When I use this for my retribution paladin, it does not show either Templars Verdict or Divine Purpose.  It does recommend inquisition when the talent is selected.

**Comment by Cilraaz** [comment]
Please see issues #536, #522, and #451. 

This is due to delaying use of Avenging Wrath. If you are using the alpha version of the addon, you can enable the "Allow Delayed Avenging Wrath" option.
