### ISSUE TITLE
Vendetta not showing at all

### ISSUE THREAD

**Issue by Noogii** [herotc/hero-rotation#559]
Hello i'm doing few tests and i realized that my vendetta is not showing as suggested spell to use, why? i tried with 0 Nothing personal and with 3 nothing personal, just doesn't show on the rotation

**Comment by EvanMichaels** [comment]
I would need a bit more information about that. Do you have the cooldowns "C" button unchecked?

Vendetta works fine for me, I use HR every day for Assassination. So unclear where that would have come from.

**Comment by Cilraaz** [comment]
Unable to replicate issue and no response in three weeks. Will gladly re-open the issue if the reporter eventually replies.
