### ISSUE TITLE
[Restoration] attempt to compare bool with number

### ISSUE THREAD

**Issue by illion20** [herotc/hero-rotation#560]
1x HeroRotation_Druid\Restoration.lua:147: attempt to compare boolean with number

`TargetUnit:DebuffRefreshableCP(S.RakeDebuff) < 1`

TargetUnit:DebuffRefreshableCP(S.RakeDebuff) is a bool so this will fail

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/baa666de2cc32248c809d2a74ae188a5406f1965
