### ISSUE TITLE
Rogue - Sublety - No Skill Recommendations presented visually or in debug

### ISSUE THREAD

**Issue by mhunk** [herotc/hero-rotation#561]
"Debug Output Checked"
-----

""Stealthed Cast or Pool (OOC): Shadowstrike""

------

It is recommending Reaping Flames & Shadowblades, but nothing else, no follow up shadow strikes, no backstabs, no eviserates, etc.

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/a996d8f3b508d21d5a21f90fa5effe060cc181f7
