### ISSUE TITLE
ADK rotation is not working well.

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#564]
Hello. None, in the rotation of the Soul Reaper addon ignores it. Also during the AoE rotation, until you use Death and Decay, the AoE rotation does not start working on 4+ targets. Plus, there is no support for essences in the rotation.

**Comment by chrislopez24** [comment]
Hello!

- Soul Reaper is an execute from 9.0.1 so no longer does damage if the target is not below 35%: https://www.wowhead.com/spell=343294/soul-reaper

- AOE -> Thats how its currently working in the APL: First it tries to build fwound around active enemies (cycling Festering Strike), then burst them all -> Repeat

- Theres no Essence support into the APL

**Comment by chrislopez24** [comment]
Soul Reaper had an obsolete id, should be fixed now

**Comment by Dragonfo** [comment]
Thanks for the fix. The problem with the AoE is that I was standing next to the manikins with 4 targets. And he offered to hang Festermight on each one, and after I hung Festermight on each target, he also suggested that I also put Festermight on another totem, which is far from me, although I think this is not correct. After all, I will not be able to hit this target, and my Death and decay will also not be able to hit it. Can I somehow fix this moment so that the nearest targets to which I can reach, he immediately offered to use Death and decay? so that Festermight does not offer to set up on goals that are out of reach.

**Comment by chrislopez24** [comment]
By Festermight you mean Festering Strike, right?

Just pushed https://github.com/herotc/hero-rotation/commit/985b85f802a0ba906978c8e77db4af3ea2804a39 that hopefully fix the problem

**Comment by Dragonfo** [comment]
Hello again. I noticed a bug or not a bug. That in the AoE rotation, for some reason, the apocalypse is ignored.

**Comment by chrislopez24** [comment]
debuff.festering_wound.stack>=4&active_enemies>=2&!death_and_decay.ticking

APL uses APOC when a enemy has more or equal to 4 fwounds, and death and decay is not ticket
