### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Finnschdk** [herotc/hero-rotation#565]
The addon screen on Wow also tells me i'm missing the HeroRotation dependency even though it is in my addon folder.

**Comment by Cilraaz** [comment]
It's most likely that you're missing the new HeroDBC addon, which is now a dependency of HeroRotation. If that's not the case, please supply a screenshot of your addon window showing the missing dependency error.

**Comment by cthulhu93** [comment]
Having the same issue:
![WoWScrnShot_101420_142122](https://user-images.githubusercontent.com/72886283/96029462-b8fcfb80-0e28-11eb-8d9d-9fe25014557f.jpg)

**Comment by cthulhu93** [comment]
additionally the HeroDBC version installed is 9.0.1.02

**Comment by Cilraaz** [comment]
You're missing HeroLib, cthulu93.

**Comment by cthulhu93** [comment]
Thank you.
