### ISSUE TITLE
Sub - Rotation 

### ISSUE THREAD

**Issue by RoguedEnyo** [herotc/hero-rotation#568]
The rotation for sub isn't displaying dance windows/opportunities. It did produce one time after I turned CDs and AOE off. Can't replicate the shadow dance again.

**Comment by Cilraaz** [comment]
Please update to the latest alpha. A bug was found earlier today that manifested when Razor Coral was equipped. If updating to the latest alpha does not fix your issue, please reply with your:

- Talents selected
- Primary neck essence
- lua error, if any

**Comment by RoguedEnyo** [comment]
Afternoon,

Looks like the issue is fixed when I activate my coral it works
beautifully, once coral is back off CD it goes blank again. I did switch
the channels to "ALPHA" in wowio to avial.


Talents -

Weapon master
Shadow Focus
Deeper
Cheat Death
Prey on Weak
Enveloping Shadows
Master of Shadows.

Essences -
Crucible
Memory of lucid dreams
Breath of the dying
Conflict and strife.

103x AngryKeystones\Schedule.lua:112: attempt to index field 'RunStatus' (a
nil value)
[string "@AngryKeystones\Schedule.lua"]:112: in function
<AngryKeystones\Schedule.lua:101>
[string "=[C]"]: in function `ChallengesFrame_Update'
[string "@Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:154: in
function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:138>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\PVEFrame.lua"]:138: in function `PVEFrame_ShowFrame'
[string "@FrameXML\PVEFrame.lua"]:88: in function `PVEFrame_ToggleFrame'
[string "@MythicDungeonTools\MythicDungeonTools-3.2.0.lua"]:202: in
function <...aceMythicDungeonTools\MythicDungeonTools.lua:201>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "LEFT"
(*temporary) = 50
(*temporary) = -30
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = 12
(*temporary) = 13
(*temporary) = nil
(*temporary) = 4
(*temporary) = nil
(*temporary) = nil
(*temporary) = 4
(*temporary) = 5
(*temporary) = "attempt to index field 'RunStatus' (a nil value)"
Mod = <table> {
 CHALLENGE_MODE_UPDATED = <function> defined
@AngryKeystones\Schedule.lua:430
 CHALLENGE_MODE_START = <function> defined @AngryKeystones\Schedule.lua:418
 AffixFrame = <unnamed> {
 }
 CheckCurrentKeystone = <function> defined @AngryKeystones\Schedule.lua:365
 SetPartyKeystoneRequest = <function> defined
@AngryKeystones\Schedule.lua:351
 Blizzard_ChallengesUI = <function> defined @AngryKeystones\Schedule.lua:168
 KeystoneText = <unnamed> {
 }
 CheckAffixes = <function> defined @AngryKeystones\Schedule.lua:310
 SendCurrentKeystone = <function> defined @AngryKeystones\Schedule.lua:385
 PartyFrame = <unnamed> {
 }
 Startup = <function> defined @AngryKeystones\Schedule.lua:434
 GetInventoryKeystone = <function> defined @AngryKeystones\Schedule.lua:297
 CHALLENGE_MODE_COMPLETED = <function> defined
@AngryKeystones\Schedule.lua:424
 CHAT_MSG_LOOT = <function> defined @AngryKeystones\Schedule.lua:340
 BAG_UPDATE = <function> defined @AngryKeystones\Schedule.lua:330
 SendPartyKeystonesRequest = <function> defined
@AngryKeystones\Schedule.lua:359
 Name = "Schedule"
 ReceiveAddOnComm = <function> defined @AngryKeystones\Schedule.lua:397
}
GetNameForKeystone = <function> defined @AngryKeystones\Schedule.lua:35
Addon = <table> {
 ADDON_LOADED = <function> defined @AngryKeystones\Core.lua:47
 PLAYER_ENTERING_WORLD = <function> defined @AngryKeystones\Core.lua:218
 ForAllModules = <function> defined @AngryKeystones\Core.lua:209
 Modules = <table> {
 }
 ShortName = "AngryKeystones"
 CHAT_MSG_ADDON = <function> defined @AngryKeystones\Core.lua:156
 UnregisterAddOnComm = <function> defined @AngryKeystones\Core.lua:129
 RegisterEvent = <function> defined @AngryKeystones\Core.lua:18
 Version = "v0.18.4"
 RegisterAddOnLoaded = <function> defined @AngryKeystones\Core.lua:59
 UnregisterAddOnLoaded = <function> defined @AngryKeystones\Core.lua:77
 Name = "Angry Keystones"
 NewModule = <function> defined @AngryKeystones\Core.lua:199
 SendAddOnComm = <function> defined @AngryKeystones\Core.lua:146
 ModulePrototype = <table> {
 }
 UnregisterEvent = <function> defined @AngryKeystones\Core.lua:94
 RegisterAddOnComm = <function> defined @AngryKeystones\Core.lua:114
}
currentWeek = 7
affixScheduleUnknown = false
rowCount = 3
affixSchedule = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}
UpdatePartyKeystones = <function> defined @AngryKeystones\Schedule.lua:42


Respectfully,


Joseph

**Comment by RoguedEnyo** [comment]
There is the correct string. Sorry about that

137x HeroRotation_Rogue\Subtlety.lua:508: attempt to call method
'ActiveCount' (a nil value)
[string "@HeroRotation_Rogue\Subtlety.lua"]:508: in function
<HeroRotation_Rogue\Subtlety.lua:385>
[string "@HeroRotation_Rogue\Subtlety.lua"]:722: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function
<HeroRotation\Main.lua:423>

Locals:
DefaultTrinketCondition = false
*CastRazorCoral = nil*
(*temporary) = nil
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 34453.868000
 LastRemovedFromPlayerTime = 0
 SpellName = "Razor Coral"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 35
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 303568
}
(*temporary) = "attempt to call method 'ActiveCount' (a nil value)"
Target = <table> {
 UnitCanBeAttacked = true
 IsSpellInActionRange = <function> defined @HeroLib\Events\Action.lua:406
 IsItemInActionRange = <function> defined @HeroLib\Events\Action.lua:396
 UnitID = "target"
 UseCache = true
 UnitExists = true
 IsActionInRange = <function> defined
@HeroLib\Class\Unit\Target\Range.lua:23
 UnitGUID = "Creature-0-3134-1643-320-131983-0000070984"
 UnitName = "Raider's Training Dummy"
 UnitNPCID = 131983
}
Player = <table> {
 UseCache = true
 RunicPowerDeficitPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:394
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:104
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined
@HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined
@HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 ActiveMitigationNeeded = <function> defined
@HeroLib\Class\Unit\Player\Tank.lua:57
 SoulShardsDeficit = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined
@HeroLib\Class\Unit\Player\Enemies.lua:51
 IsInWhitelistedVehicle = <function> defined
@HeroLib\Class\Unit\Player\Main.lua:133
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 ChiDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:591
 PainDeficitPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:482
 FocusDeficitPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:180
 EnergyRegenPercentage = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:389
 FuryP

**Comment by Cilraaz** [comment]
That error is the one that was fixed in the latest alpha.

**Comment by RoguedEnyo** [comment]
Awesome, I'll figure out how to get it updated. I appreciate your time and
effort.

Respectfully,

Joseph
