### ISSUE TITLE
Outlaw Rogue

### ISSUE THREAD

**Issue by boognish619** [herotc/hero-rotation#571]
getting this error also rotation is not asking for slice and dice, between the eyes or dispatch.  Pretty much just sinister strike roll the bones and blade flurry 

essage: Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:402: attempt to call method 'HasHeroism' (a nil value)
Time: Fri Oct 16 09:01:14 2020
Count: 1051
Stack: Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:402: attempt to call method 'HasHeroism' (a nil value)
[string "=[C]"]: in function `HasHeroism'
[string "@Interface\AddOns\HeroRotation_Rogue\Outlaw.lua"]:402: in function <Interface\AddOns\HeroRotation_Rogue\Outlaw.lua:264>
[string "@Interface\AddOns\HeroRotation_Rogue\Outlaw.lua"]:573: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

**Comment by Cilraaz** [comment]
This should be fixed as of commit https://github.com/herotc/hero-rotation/commit/fc9993184f0c4568a48f47d5bdf395cfadd028a3
