### ISSUE TITLE
[DK] Deathknight Use Stun for Interupt not using (available) stun

### ISSUE THREAD

**Issue by SulpherStaer** [herotc/hero-rotation#572]
I am aware the Deathknight is WIP, but I checked the 8.3 release, and asphyxiate isn't used either there. (It is a talent)

This means when mindfreeze is on cooldown, it doesn't suggest asphyxiate, it just tells me to get hit.

**Comment by Cilraaz** [comment]
Added Asphyxiate as a stun interrupt in commit https://github.com/herotc/hero-rotation/commit/2ce75350a96dfedc1f58d89e5530dcbfbdbfe5cb
