### ISSUE TITLE
[DK] There are still questions and problems with the AOE rotation of the ADK

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#573]
I apologize in advance for the importunity and persistence. But I would like to clarify that when taking the talents 1,1, x, 1, x, 2,3, the rotation in AoE starts perfectly. BUT there is a problem that the addon makes a huge delay in rotation and adjusts all abilities to hit. But the allotment turns out so that we can stand for 5-10 seconds or even more and just watch what is happening. I attached a screenshot https://imgur.com/a/4C6KLBu on the mannequins where you can clearly see that I have all the runes, but there are no ready-made spells, and we are just waiting for something. Of course, I don’t know again, I don’t understand many of the nuances, but somehow it costs 5-10 seconds to do nothing with a full margin is also not good.

**Comment by Dragonfo** [comment]
Plus, it was also noticed that between switching modes on the AOE or ST panel, it does not work, it ignores it the same way. Plus, as it was implemented in the bfa release, that at long distances he used the Death coil and now for some reason he offers to hit with any other ability, but not the Death coil. The same is with the epidemic, if the plague acts on the targets, then the epidemic is also offered, but it turns out that we are fighting with additional targets with the boss, and he does not offer an epidemic in the rotation. So far, such bugs are still seen in rotation.

**Comment by chrislopez24** [comment]
Hello!

Ill add the CD and AOE conditionals later tonight or tomorrow

For the rest of your issues, remember DK is WIP, so its not optimized. If i find free time time in the coming weeks i'll have a look at it

**Comment by Dragonfo** [comment]
I am extremely grateful for your work. I am just describing the problems that have appeared. I apologize if I offended you somehow.

**Comment by chrislopez24** [comment]
https://github.com/herotc/hero-rotation/commit/d1f1a5e53d83b3bc4bfa5e290142d4dead307958 Fixed support for both CD and AOE switches, have in mind disabling Cooldowns will stop Apocalypse for being suggested, same for Dark Transformation. Thats how APL is made.

https://github.com/herotc/hero-rotation/commit/e3e9849159dea325c199f98c58c07823c3f6f200 has basic support for an oor rotation (Epidemic/DC depending of number of targets)

I couldnt replicate the issue you had in the screenshot, sorry

**Comment by Dragonfo** [comment]
Thank you for your quick help. About reproduce as in the screenshot. The bottom line is that look. The addon strives to do the following every time before starting. He offers to make sure that all targets have Virulent Plague, if not, he immediately resets the icon on the target, and asks me to use Virulent Plague, since further rotation will also be stopped. After making sure that all targets with Virulent Plague as an addon, he immediately suggests using a combination of festering strike and epidemic on targets. And again this bug can be repeated, if another goal is added to my goals, it will again offer them to use Virulent Plague festering strike and epidemic. And he will not suggest using Death and Decay on old targets. Because the new targets have just approached the old ones and he will try to capture them in my AOE as well. Here is a very interesting situation with AOE rotation. That addon, before starting it, he wants to first work out all the scenarios that I indicated above, and only after he makes sure that there is Festering everywhere and there is no runic power for the epidemic, then he will advise me to use Death and decay. And yes, one more not pleasant moment, the addon also advises to use AOE rotation on any shields, build-ups, etc. which cannot be killed.

**Comment by chrislopez24** [comment]
https://github.com/herotc/hero-rotation/commit/78003c1f37bc694bf204e6b114fd728340a5a296 try with this version

**Comment by Dragonfo** [comment]
I tried the version. It still does not offer an epidemic when we fight a boss and additional targets that are found in the distance.

**Comment by Dragonfo** [comment]
Is it possible to do that when the addon offers to use Festering strike on other targets in the AOE rotation so that it takes into account the amount of HP of the targets? Perhaps this is an absurd request, but I come across such interesting moments where there are additional targets, very fragile, and I just kill them with one blow of Festering strike, and it turns out so that in the end I do not inflict damage in the area, but simply spend 2 runes per hit Festering strike. If it would be possible to somehow beat this scenario where fragile targets that I can kill with 1 hit were not offered in the AoE rotation, but just the usual ST rotation.

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
