### ISSUE TITLE
Outlaw Rogue Error

### ISSUE THREAD

**Issue by wheatbread** [herotc/hero-rotation#577]
Hello!

I'm getting the following error on my outlaw rogue.  It seems to pop up when the Writhing Segment of Drest'agath trinket is off CD.  

> 49x HeroRotation_Rogue\Outlaw.lua:402: attempt to call method 'HasHeroism' (a nil value)
> [string "@HeroRotation_Rogue\Outlaw.lua"]:402: in function <HeroRotation_Rogue\Outlaw.lua:264>
> [string "@HeroRotation_Rogue\Outlaw.lua"]:573: in function `?'
> [string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>
> 
> Locals:
> TrinketToUse = <table> {
>  ItemName = "Writhing Segment of Drest'agath"
>  ItemSlotIDs = <table> {
>  }
>  LastCastTime = 0
>  ItemRarity = 4
>  ItemMinLevel = 50
>  ItemID = 173946
>  ItemLevel = 85
>  LastDisplayTime = 0
>  LastHitTime = 0
> }
> (*temporary) = nil
> (*temporary) = <table> {
>  UseCache = true
>  RunicPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:394
>  GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
>  Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:34
>  Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
>  FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
>  PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
>  IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:104
>  EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
>  Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
>  InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
>  RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
>  VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
>  ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:681
>  MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
>  ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
>  ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
>  SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
>  GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:51
>  IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:133
>  PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
>  AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
>  ChiDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:591
>  PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
>  PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
>  MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
>  InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
>  ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
>  FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
>  PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
>  AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
>  FocusDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:180
>  EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:289
>  RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:389
>  FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:703
>  Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:628
>  EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Unit\Player\Power.lua:336
>  ArcaneChargesPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:671
>  AstralPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:503
>  MaelstromDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:564
>  FuryDeficitPercentage = <function> defined @

**Comment by Cilraaz** [comment]
This was fixed in commit fc9993184f0c4568a48f47d5bdf395cfadd028a3

CurseForge is having some issues packaging our alpha versions, but this fix was included in release version 9.0.1.04.
