### ISSUE TITLE
[DH] Lua Error

### ISSUE THREAD

**Issue by Arkanis81** [herotc/hero-rotation#580]
Looks to be a misspelling of "return" on line 353

Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:353: attempt to call global 'reutrn' (a nil value)
Time: Wed Oct 21 12:37:12 2020
Count: 18
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:353: attempt to call global 'reutrn' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `reutrn'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:353: in function <Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:306>
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:514: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals: errMsg = "Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:353: attempt to call global 'reutrn' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/f9ae91e17e0802c58a026f150a4db948d39dfb9e

Thanks for the report!
