### ISSUE TITLE
Hunter shows a lot errors

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#585]
1139x HeroRotation_Hunter\BeastMastery.lua:378: attempt to index field 'SplashEnemies' (a nil value)
[string "@HeroRotation_Hunter\BeastMastery.lua"]:378: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>

**Comment by Cilraaz** [comment]
Ensure that you have the latest version of HeroLib, as the Splash system was updated recently.

**Comment by ReglohPri** [comment]
Thanks a lot for this info. I will test it if the servers online again.
Then i will close this issue.
