### ISSUE TITLE
not a bug just a suggestion

### ISSUE THREAD

**Issue by Nmxsz** [herotc/hero-rotation#593]
Can we have a discord? So we can communicate who's working on which APL?

**Comment by Nmxsz** [comment]
Im doing this because i love WoW and i love programming in my leisure and i dont know who's feels the same and already works on new APL's

**Comment by Kutikuti** [comment]
It's on the project page : https://discord.com/invite/tFR2uvK
As for APLs, if it's not stated as WIP or OK on the project page, nobody is working on it
