### ISSUE TITLE
[Hunter-MM] - make best use of [Explosive Shot] & [Rapid fire] in mythic+ 

### ISSUE THREAD

**Issue by Ohemx** [herotc/hero-rotation#594]
In mythic plus situations, 
- when a pack of mobs is almost dead (only 1-2 no-boss targets are about to die), An option to save [[Explosive Shot]](https://www.wowhead.com/spell=212431/explosive-shot) [[Rapid Fire]](https://www.wowhead.com/spell=257044/rapid-fire) may be also [[Double Tap]](https://www.wowhead.com/spell=260402/double-tap) [[Resonating Arrow]](https://www.wowhead.com/spell=308491/resonating-arrow) for the next pack (usually a full pack) so don't waist AOE dmg. 
- when dealing with [[Manifestation of Pride]](https://www.wowhead.com/npc=173729/manifestation-of-pride) a special rotation to make sure you have full CDs when we get the [[Prideful]](https://www.wowhead.com/spell=340880/prideful) buff (for example when the [[Manifestation of Pride]](https://www.wowhead.com/npc=173729/manifestation-of-pride) is about to die, stop showing [[Explosive Shot]](https://www.wowhead.com/spell=212431/explosive-shot) [[Rapid Fire]](https://www.wowhead.com/spell=257044/rapid-fire)) so you can use these spells with the [[Prideful]](https://www.wowhead.com/spell=340880/prideful) buff on the next pack.

**Comment by Nmxsz** [comment]
may we can add these spells to the cooldown list and then u can manually turn off the CDs Button in your Addon i binded the Cooldown and Aoe Button

**Comment by Ohemx** [comment]
I did that by adding `if HR.CDsON() and` in the code, However most of the time you want to save [Double Tap] [Resonating Arrow] and use [Explosive Shot] [Rapid Fire] since the last 2 have short CDs. ( making 2 different CDs list is not optimal) 
its would be way better to be automatic for the [Explosive Shot] [Rapid Fire] and use the CDs Keybind for the longer CDs

**Comment by Ohemx** [comment]
Been running mythic+ all day with the addon, where I experienced this issue. 
`for example ([High Adjudicator Aleez] 3rd boss of [Halls of Atonement], the addon displayed [Explosive Shot],[Rapid Fire] and [Volley] at 2% of the boss health, and right after it we pulled an entire room, which these spells could make huge DPS `

So I thought if we had an option, while in mythic keystone, similar to the (Exhilaration HP threshold bar) on the addon that could be set to a certain target health % to stop displaying [Explosive Shot],[Rapid Fire] and [Volley], therefore can be adjusted depends on the key level (health scaling), which only excludes the last boss's in mythic+ where saving the CDs is a waist
Additionally, a sub adjustable bar under the [suggested: target health % threshold bar] that can also set the number of targets around the main target.
```
for example, by adjusting these 2 bars for each spell we can have very good control when it's worth it using these spells 
- the target health is at 5%ish and the targets around it are<2, is better to hold the spells 
- the target health is at 5%ish and the targets around it are>4, it's ok to use the spells 
- the target health is at 90%ish and the targets around it are<2, it's ok to use the spells
- the target health is at 90%ish and the targets around it are>2, it's ok to use the spells
```

**Comment by Ohemx** [comment]
[suggested: target health % threshold bar] should be set to actual health, the not % so you don't waist dmg on minions or spawns since their 100% health is 3-5% regular elite

**Comment by Nmxsz** [comment]
You can also check Target time to die

**Comment by Ohemx** [comment]
true, although the Target time to die fluctuate a lot  depends on the entire grp using their CDs or not, still really helpful to determine its worth it to save these spell for next pull

**Comment by Yaooti** [comment]
I just added an extra button to the UI as a toggle for Volley and Exp Shot. Not ideal but it works.

**Comment by Ohemx** [comment]
i will give it a try and report

**Comment by Cilraaz** [comment]
Marksmanship profile has long since been updated. Closing this issue.
