### ISSUE TITLE
[Hunter-MM] - Disable cast spells when moving option

### ISSUE THREAD

**Issue by Ohemx** [herotc/hero-rotation#595]
The frost mages have an option to  (Disable cast abelites when moving ) it's very useful in heavy movement situation like mythic+, would be very handy for hunters, it's true one castability that requires to stay still (Aimed Shot), however, when dodging shit on the ground I lose a lot of DPS

**Comment by Cilraaz** [comment]
Added in commit https://github.com/herotc/hero-rotation/commit/2a3f30c20b842d33e58d06b9c3ec8a5a20f49d1e

**Comment by Ohemx** [comment]
thanks work very well
