### ISSUE TITLE
[Hunter-MM] Rapid Fire without Trick Shots in AOE

### ISSUE THREAD

**Issue by Ohemx** [herotc/hero-rotation#596]
On may, AOE occasion [Rapid Fire] get displayed without having the [Trick Shots] buff since it gets consumed with [Aimed Shot], without refreshing it [Rapid Fire] lose all the AOE damage, I compare my damage with other hunters, their [Rapid Fire] is the top damage with x2-3 greater than mine, which is a big drawback, not sure if the problem is in the rotation itself or can tell if I am in an AOE situation.

**Comment by Cilraaz** [comment]
I added a check so Rapid Fire will not be suggested within the Trick Shots function if Aimed Shot is currently being casted. This should stop situations where Rapid Fire is suggested directly after Aimed Shot, where Aimed Shot eats the Trick Shots buff.
