### ISSUE TITLE
Make GitHub Releases compatible with WoWUp

### ISSUE THREAD

**Issue by SulpherStaer** [herotc/hero-rotation#597]
https://github.com/WowUp/WowUp/issues/397#issuecomment-728674242

To be compatible with WowUp.io the releases must contain an aditional zip that is the addon, not just source.zip.
https://wowup.io/guide/section/get-addons/install-from-url

I am asking, because curseforge is going out during launch week.
https://www.wowhead.com/news=319169/curseforge-suspending-addon-updates-during-shadowlands-launch-week

Edit:
So, whilst this add-on _is_ available on WowUp, it is through curse, which will not allow proper updates being released during the first week of shadowlands.

**Comment by fludotlove** [comment]
I'm using WowUp.io and this addon works fine with it... you just need to install the dependencies separately, HeroLib and HeroDBC. 

![image](https://user-images.githubusercontent.com/4395975/99425817-4685ac80-28fb-11eb-9523-346d3a0adfb3.png)

**Comment by Cilraaz** [comment]
We've been including the addon in zip format for many releases now. Closing this issue.
