### ISSUE TITLE
Warrior rotation within the Wow Addon List shows as purple instead of brown

### ISSUE THREAD

**Issue by nate8282** [herotc/hero-rotation#600]
Warrior rotation within the Wow Addon List shows as purple instead of brown. Not sure if this is just me.

![image](https://user-images.githubusercontent.com/52011990/99470375-e0505800-2901-11eb-9dd1-d743df087a45.png)

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/5b1acdf1cb2f12de9d2f23ed5fab8aff429bd130
