### ISSUE TITLE
Pally issues

### ISSUE THREAD

**Issue by Giki42** [herotc/hero-rotation#602]
Not sure why, but I have a blood elf pally that this won't come up for.  I have a dranai pally that it works for properly, but for some reason, it just won't work on the blood elf and I'm not sure if there's something I've done to break it or something.  When I go into the addons while on the pally, it says "Only loadable on demand" and I can't get it to load on this specific toon.  I have tried only loading the addon, I've also tried deleting my UI and rebuilding it.  I'm not sure what's wrong.
![WoWScrnShot_111920_213348](https://user-images.githubusercontent.com/74749230/99750757-f3545b00-2aae-11eb-8057-f133ba9aa6d1.jpg)

**Comment by Cilraaz** [comment]
1. There is currently no profile for Retribution. The only working Paladin profile at the moment is Protection.
2. Please try changing to Protection spec on your Blood Elf Paladin and see if the same issue occurs.
3. If number 2 does not work, what version of the addon do you have?

**Comment by Cilraaz** [comment]
Ticket open 9 days without response. Closing this ticket. Also, a proper Retribution profile has been added since this ticket's creation date.
