### ISSUE TITLE
[Sub Rogue] Error

### ISSUE THREAD

**Issue by wheatbread** [herotc/hero-rotation#609]
Getting the following error.  (Still getting it at level 60)

> 48x HeroRotation\Core.lua:48: attempt to index local 'Object' (a boolean value)
> [string "@HeroRotation\Core.lua"]:48: in function `GetTexture'
> [string "@HeroRotation\Core.lua"]:183: in function <HeroRotation\Core.lua:177>
> [string "@HeroRotation\Core.lua"]:199: in function `CastQueuePooling'
> [string "@HeroRotation_Rogue\Subtlety.lua"]:876: in function `?'
> [string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>
> 
> Locals:
> Object = false
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index local 'Object' (a boolean value)"
> Cache = <table> {
>  GUIDInfo = <table> {
>  }
>  Set = <function> defined @HeroCache\Main.lua:266
>  APLVar = <table> {
>  }
>  Enemies = <table> {
>  }
>  Get = <function> defined @HeroCache\Main.lua:250
>  HasBeenReset = true
>  SpellInfo = <table> {
>  }
>  UnitInfo = <table> {
>  }
>  MiscInfo = <table> {
>  }
>  Persistent = <table> {
>  }
>  ItemInfo = <table> {
>  }
>  Reset = <function> defined @HeroCache\Main.lua:41
> }
> tostring = <function> defined =[C]:-1
>

**Comment by EvanMichaels** [comment]
Should be fixed in https://github.com/herotc/hero-rotation/commit/400a2800e15b7e60283cbed162f2fe8d56d3f565

**Comment by wheatbread** [comment]
Thank you so much!
