### ISSUE TITLE
Lot errors by using arcane mage

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#611]
446x HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "@HeroLib\Class\Unit\Aura.lua"]:32: in function <HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@HeroLib\Class\Unit\Aura.lua"]:148: in function `DebuffRemains'
[string "@HeroLib\Class\Unit\Aura.lua"]:159: in function `DebuffUp'
[string "@HeroLib\Class\Unit\Aura.lua"]:164: in function `DebuffDown'
[string "@HeroLib\Class\Unit\Aura.lua"]:132: in function `DebuffStack'
[string "@HeroRotation_Mage\Arcane.lua"]:607: in function <HeroRotation_Mage\Arcane.lua:561>
[string "@HeroRotation_Mage\Arcane.lua"]:907: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/59b055b03c3c3b1fd888a142c10b58077914dadc
