### ISSUE TITLE
[Sub Rouge]  attempt to index local 'Object'

### ISSUE THREAD

**Issue by VitalijSelynin** [herotc/hero-rotation#612]
Getting an error sporadically

Message: Interface\AddOns\HeroRotation\Core.lua:48: attempt to index local 'Object' (a boolean value)
Time: Thu Nov 26 20:40:08 2020
Count: 31
Stack: Interface\AddOns\HeroRotation\Core.lua:48: attempt to index local 'Object' (a boolean value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation\Core.lua"]:48: in function `GetTexture'
[string "@Interface\AddOns\HeroRotation\Core.lua"]:183: in function <Interface\AddOns\HeroRotation\Core.lua:177>
[string "@Interface\AddOns\HeroRotation\Core.lua"]:193: in function <Interface\AddOns\HeroRotation\Core.lua:192>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroRotation_Rogue\Subtlety.lua"]:623: in function <Interface\AddOns\HeroRotation_Rogue\Subtlety.lua:608>
[string "@Interface\AddOns\HeroRotation_Rogue\Subtlety.lua"]:848: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

**Comment by VitalijSelynin** [comment]
I use HeroRotation 9.0.2.04 with HeroLib 9.0.2.03 and HeroDBC 9.0.2.02

**Comment by EvanMichaels** [comment]
Should be fixed in https://github.com/herotc/hero-rotation/commit/400a2800e15b7e60283cbed162f2fe8d56d3f565
