### ISSUE TITLE
[Frost DK] Issue when fighting multiple targets

### ISSUE THREAD

**Issue by Rotorhead** [herotc/hero-rotation#614]
Getting the following error when fighting groups of mobs:

Message: Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:418: attempt to index field 'GCDasOffGCD' (a nil value)
Time: Fri Nov 27 17:18:35 2020
Count: 95
Stack: Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:418: attempt to index field 'GCDasOffGCD' (a nil value)
[string "@Interface\AddOns\HeroRotation_DeathKnight\Frost.lua"]:418: in function <Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:371>
[string "@Interface\AddOns\HeroRotation_DeathKnight\Frost.lua"]:605: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals: (*temporary) = <function> defined @Interface\AddOns\HeroRotation\Core.lua:132
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Sacrificial Pact"
 IsMelee = true
 SpellType = "Player"
 MaximumRange = 0
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 327574
}
(*temporary) = nil
(*temporary) = "Player-1171-086F8237"
(*temporary) = <table> {
 GCD = 1.207052
}
(*temporary) = "attempt to index field 'GCDasOffGCD' (a nil value)"
S = <table> {
 FrostFeverDebuff = <table> {
 }
 ColdHeart = <table> {
 }
 FrostStrike = <table> {
 }
 UnholyStrengthBuff = <table> {
 }
 ArcaneTorrent = <table> {
 }
 EmpowerRuneWeapon = <table> {
 }
 ColdHeartBuff = <table> {
 }
 PoolRange = <table> {
 }
 ArcanePulse = <table> {
 }
 UnleashedFrenzyBuff = <table> {
 }
 BloodFury = <table> {
 }
 BitingCold = <table> {
 }
 MindFreeze = <table> {
 }
 Obliterate = <table> {
 }
 DeathStrike = <table> {
 }
 DeathStrikeBuff = <table> {
 }
 HowlingBlast = <table> {
 }
 BagofTricks = <table> {
 }
 AncestralCall = <table> {
 }
 ChainsofIce = <table> {
 }
 SacrificialPact = <table> {
 }
 FrostwyrmsFury = <table> {
 }
 DeathAndDecay = <table> {
 }
 Fireblood = <table> {
 }
 LightsJudgment = <table> {
 }
 RunicAttenuation = <table> {
 }
 HypothermicPresence = <table> {
 }
 EradicatingBlowBuff = <table> {
 }
 SwarmingMist = <table> {
 }
 RaiseDead = <table> {
 }
 RazoriceDebuff = <table> {
 }
 ShackleTheUnworthy = <table> {
 }
 IcyTalonsBuff = <table> {
 }
 DeathsDue = <table> {
 }
 Icecap = <table> {
 }
 RimeBuff = <table> {
 }
 UnleashedFrenzy = <table> {
 }
 GlacialAdvance = <table> {
 }
 BreathofSindragosa = <table> {
 }
 PillarofFrostBuff = <table> {
 }
 KillingMachineBuff = <table> {
 }
 Obliteration = <table> {
 }
 FrozenPulseBuff = <table> {
 }
 Frostscythe = <table> {
 }
 EradicatingBlow = <table> {
 }
 RemorselessWinter = <table> {
 }
 AbominationLimb = <table> {
 }
 EmpowerRuneWeaponBuff = <table> {
 }
 HornofWinter = <table> {
 }
 GatheringStorm = <table> {
 }
 Berserking = <table> {
 }
 Asphyxiate = <table> {
 }
 IcyTalons = <table> {
 }
 FrozenPulse = <table> {
 }
 PillarofFrost = <table> {
 }
}
Player = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:116
 IsInParty = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @Interface\AddOns\

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/d88b56062d343c802954399dc5535203191b53a4
