### ISSUE TITLE
[Hunter MM] - Trueshot suggested when CDs are off.

### ISSUE THREAD

**Issue by munkafan** [herotc/hero-rotation#615]
When toggling CDs off, Trueshot still is suggested. 
With Trueshot being a 2min CD it should be included to the same type of CDs as covenant ability Wild Spirits that is working correct and not firing while CDs are off.

**Comment by Cilraaz** [comment]
Added a CDs check in commit https://github.com/herotc/hero-rotation/commit/ea6cc707c6a7c71edc24a03b8011ee9909633abd
