### ISSUE TITLE
A lot errors in dungeon with arcane mage

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#616]
823x HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "@HeroLib\Class\Unit\Aura.lua"]:32: in function <HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@HeroLib\Class\Unit\Aura.lua"]:148: in function `DebuffRemains'
[string "@HeroLib\Class\Unit\Aura.lua"]:159: in function `DebuffUp'
[string "@HeroLib\Class\Unit\Aura.lua"]:164: in function `DebuffDown'
[string "@HeroLib\Class\Unit\Aura.lua"]:132: in function `DebuffStack'
[string "@HeroRotation_Mage\Arcane.lua"]:671: in function <HeroRotation_Mage\Arcane.lua:645>
[string "@HeroRotation_Mage\Arcane.lua"]:919: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>

i think the line 671 must be changed from:
if S.ArcaneBarrage:IsCastable() and Target:DebuffStack(S.RadiantSparlVulnerability) == 4 and (Player:BuffDown(S.ArcanePower) or Player:BuffRemains(S.ArcanePower) <= Player:GCDRemains()) and (Player:BuffDown(S.RuneofPowerBuff) or Player:BuffRemains(S.RuneofPowerBuff) <= Player:GCDRemains()) then

to:
if S.ArcaneBarrage:IsCastable() and Target:DebuffStack(S.RadiantSparkVulnerability) == 4 and (Player:BuffDown(S.ArcanePower) or Player:BuffRemains(S.ArcanePower) <= Player:GCDRemains()) and (Player:BuffDown(S.RuneofPowerBuff) or Player:BuffRemains(S.RuneofPowerBuff) <= Player:GCDRemains()) then

**Comment by Cilraaz** [comment]
Duplicate of issue #611

**Comment by ReglohPri** [comment]
Thats not correct with duplicate, is another line with this error!!!!!

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/6066cd97eabc67adf73c904a751c8b1bfcfc9e2e
