### ISSUE TITLE
[Shaman-Enh] Nothing is showing up for enhancement shaman unless Ascendance is used

### ISSUE THREAD

**Issue by bchinfoon** [herotc/hero-rotation#617]
This just started happening recently, but I no longer get a rotation unless I pop Ascendance and have the buff.  Otherwise it just shows as blank.

**Comment by bchinfoon** [comment]
I seem to have the same issue with elemental shaman as well.  Once I cast flame shock on a target dummy nothing shows up.

**Comment by Nmxsz** [comment]
please check if the nameplate is showing. if there are no nameplates the addon will show nothing. I just tested enhancement and elemental in its latest version and it works for me.

**Comment by bchinfoon** [comment]
I always have nameplates enabled and I tried on my hunter that was working fine.  Like I mentioned for enhancement it only works if I pop Ascendance which is really weird.  Not sure what the problem is as it was working perfecly a few days ago.

**Comment by Nmxsz** [comment]
may you can upload an image while fighting target dummy?

**Comment by Cilraaz** [comment]
Profile was long since updated. Closing this issue.
