### ISSUE TITLE
[DK FROST] Error causing Hero rotation to stop working.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#620]
Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
Time: Mon Nov 30 00:15:07 2020
Count: 74
Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:81: in function `BuffRemains'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:99: in function `BuffUp'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:104: in function `BuffDown'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:65: in function `BuffStack'
[string "@Interface\AddOns\HeroRotation_DeathKnight\Frost.lua"]:500: in function <Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:485>
[string "@Interface\AddOns\HeroRotation_DeathKnight\Frost.lua"]:629: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals:

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/afbd9a700857536abb84f74592a42a47773aec2f
