### ISSUE TITLE
[Monk - Windwalker] attempt to index field 'ConcentratedFlame' (a nil value)

### ISSUE THREAD

**Issue by Delution** [herotc/hero-rotation#623]
4x HeroRotation_Monk\Windwalker.lua:82: attempt to index field 'ConcentratedFlame' (a nil value)
[string "@HeroRotation_Monk\Windwalker.lua"]:82: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@HeroRotation\Main.lua"]:380: in function `PulseInit'
[string "@HeroRotation\Main.lua"]:292: in function <HeroRotation\Main.lua:289>

Locals:
addonName = "HeroRotation_Monk"
addonTable = <table> {
}
DBC = <table> {
 ItemRange = <table> {
 }
 AzeriteEssences = <table> {
 }
 SpellTickTime = <table> {
 }
 AzeriteEssenceSpellIDs = <table> {
 }
 SpellRPPM = <table> {
 }
 AzeriteEssenceScaling = <table> {
 }
 ItemSpell = <table> {
 }
 SpellProjectileSpeed = <table> {
 }
 metaTime = "2020-11-22T22:22:18.037730"
 SpellMeleeRange = <table> {
 }
 SpellDuration = <table> {
 }
 SpellEnchants = <table> {
 }
 metaVersion = "9.0.2.36710"
 SpellGCD = <table> {
 }
 SpellConduits = <table> {
 }
}
HL = <table> {
 RegisterForEvent = <function> defined @HeroLib\Events\Main.lua:46
 MAXIMUM = 40
 BossFilteredFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:348
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 Item = <table> {
 }
 Pulse = <function> defined @HeroLib\Main.lua:29
 LiveRealm = <function> defined @HeroLib\Core.lua:34
 RegisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:133
 UnregisterForEvent = <function> defined @HeroLib\Events\Main.lua:62
 AddCoreOverride = <function> defined @HeroLib\Misc\Overrides.lua:26
 BetaRealm = <function> defined @HeroLib\Core.lua:44
 Spell = <table> {
 }
 BossFightRemainsIsNotValid = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:333
 GetInstanceInfo = <function> defined @HeroLib\Misc\ToSort.lua:37
 Action = <table> {
 }
 LoadRestores = <function> defined @HeroLib\Misc\Overrides.lua:42
 RegisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:148
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 1
 RecoveryTimer = <function> defined @HeroLib\Misc\ToSort.lua:116
 BMPullTime = <function> defined @HeroLib\Misc\ToSort.lua:87
 RegisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:88
 OutOfCombatTime = <function> defined @HeroLib\Misc\ToSort.lua:82
 UnregisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:177
 Latency = <function> defined @HeroLib\Misc\ToSort.lua:111
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 GetInstanceDifficulty = <function> defined @HeroLib\Misc\ToSort.lua:72
 LoadOverrides = <function> defined @HeroLib\Misc\Overrides.lua:48
 Print = <function> defined @HeroLib\Core.lua:49
 UnregisterAuraTracking = <function> defined @HeroLib\Events\Aura.lua:37
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @HeroLib\Core.lua:29
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @HeroLib\Misc\ToSort.lua:77
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 UnregisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:163
 BossFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:328
 FightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:296
 TTDRefresh = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:53
 RecoveryOffset = <function> defined @HeroLib\Misc\ToSort.lua:124
 FilteredFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:338
 CombatStarted = 0
 SpecID_ClassesSpecs = <table> {
 }
 RegisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:103
 UnregisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:205
 GUI = <table> {
 }
 UnregisterForPetCombatEvent = <function> defined @HeroLib\Events\Main.lua:191
 UnregisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:219
 Timer = <table> {
 }
 PTRRealm = <function> defined @Ad

**Comment by Delution** [comment]
Hero Rotation Version 9.0.2.05
Hero Lib Version 9.0.2.04

**Comment by Cilraaz** [comment]
Fixed in commits https://github.com/herotc/hero-rotation/commit/5d133ac8c7f38fe715c56a6af40316f47aad2a5b and https://github.com/herotc/hero-rotation/commit/3b39628b5c7df9a0de210caab9f11878ab7fe777

You can pull the fix from github, or it will go live in the next version.

Edit: Helps if I post the right commits.
