### ISSUE TITLE
There are minor problems with the FDK.

### ISSUE THREAD

**Issue by geraint425** [herotc/hero-rotation#631]
Hello. In rotation, I noticed that the trinket is always located in OffGCD. But I specifically set it to show in the Main icon ([screenshot](https://imgur.com/HSm65F5)) in the settings, but it still shows it in OffCGD. The same problem is with the covenant ability. All of them are in OffCGD, regardless of whether the ability is checked or not in the addon settings. I also found such a moment that the addon in different ways offers to use the ability of the Sacrificial Pact, it can offer to use it when my pet is not there, then it does not offer it when the pet is nearby. Also, when taking the Obliteration talent, we have an easy rotation when the rune power mark reaches 100, he simply does not offer to use Frost Strike. And he waits for the pillar of frost to end and only then he offers to use the Frost Strike ability, and again it manifests itself in different ways, it may or may not work. Plus, there is no Frostscythe in the rotation when the talent is taken. I did all these tests both on mannequin and in the open world and in dungeons.

**Comment by chrislopez24** [comment]
fixed in https://github.com/herotc/hero-rotation/commit/8703f1cda4dca6efc6fd608b068900b95fd59280
