### ISSUE TITLE
Druid missing from rotations

### ISSUE THREAD

**Issue by N6REJ** [herotc/hero-rotation#632]
For some reason druid is missing completely.
![image](https://user-images.githubusercontent.com/1850089/100738340-0adaf000-339b-11eb-8c14-e28db89b8d9d.png)

**Comment by p4nchez** [comment]
at the moment there is no supported druid spec released
look at https://github.com/herotc/hero-rotation you see every supported spec with status

**Comment by N6REJ** [comment]
*gets on knee's and begs*

**Comment by p4nchez** [comment]
i also waiting for feral :D

**Comment by Kutikuti** [comment]
As stated above, druid is not yet supported for 9.0
