### ISSUE TITLE
[FROST DK] Pooling for BoS even when CDS off.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#633]
Hey even when CDS are off, the addon shows "pooling" constantly either way. Can you guys add so that it only pools when cds are active?

**Comment by chrislopez24** [comment]
Hello!

Will have a look at this issues (and some other related to frost dk) probably this weekend!

**Comment by chrislopez24** [comment]
Hello again!

You have an option to Disable BoS Pooling under Settings (Deathknight -> Frost -> Check Disable BoS Pooling)

**Comment by azzi1103** [comment]
What if I want to keep pooling on when i want to burst, but wanna keep it off when I wanna save my cd for big pack or boss fight? I can't go in and disable and enable it while im running through dung/raid

**Comment by chrislopez24** [comment]
The module is meant to be a ported ingame version of the simc apl. the simc robot doesnt hold cds, just use skills when conditions are met.

I'm okay with an option to disable bos pooling, but apart from that I doubt if I want to add support for those scenarios that could become somewhat complex

Anyway, you can bind the toggle to cds on/off from the WoW keybind menu if it helps

**Comment by azzi1103** [comment]
It is bound, but if I turn off CD, it STILL pools for BoS, and it's hella annoying if I'm just clearing trash before boss. Which means I have to physically go in and change "pooling" on and off for BoS. All I'm asking is for pooling to be ignored when CDS are off, because then BoS is not included in the rotation, but the rotation is still pooling up for a BoS for no reason.
