### ISSUE TITLE
[Rogue] when CDs off, no shadowdance, no KillingSpree

### ISSUE THREAD

**Issue by mizone** [herotc/hero-rotation#637]
Hi , when turn off CDs,

Sub: no shadow dance recommend any more. is it right?
Outlaw: seems some thing wrong with  RTB logical when use Conduits:Count the Odds, please check. also, when turn off CDS, no KillingSpree recommend when do AOE

**Comment by Mystler** [comment]
Regarding Shadow Dance with CDs off, this is coming from the Eco Charge option in the settings. If you used the addon in BfA it might still have the former default value of 2.55 which can never happen in SL. Try lowering it manually to sth like 1.7.

**Comment by mizone** [comment]
> Regarding Shadow Dance with CDs off, this is coming from the Eco Charge option in the settings. If you used the addon in BfA it might still have the former default value of 2.55 which can never happen in SL. Try lowering it manually to sth like 1.7.

That's it. Thanks.

any solution for recommending KillingSpree when CDs off?
