### ISSUE TITLE
Rogue - Serrated Bone Spike invisible in rotation (Video)

### ISSUE THREAD

**Issue by ferrius94** [herotc/hero-rotation#638]
Greetings, and thanks for your hard work.

**Spec: Assassin**
**Race: Human
Covenant: Necrolord**

[Sim for talents and such, if needed.](https://www.raidbots.com/simbot/report/gRsLu86gvuRgw68mRsfCMb)

Since having reached level 60, and chosen Necrolord, everytime HR wants to suggest the use of the coventant ability, no icon is loaded in any location - having also attempted to change its appearance between main-icon, suggested, and CD. The rotation is appearing blank, and upon then using the ability once or twice, the rotation suggestions continue as normal.

I know for (almost) a fact, that this is not related to any other addon or the type of bar the spell is located in, as it in the previous week worked perfectly during the levelling process, and first being introduced to the Necrolord covenant abilities. I only had the issue after reaching 60 and updating my addons on the 1st of December (Tuesday) - and rediscovering the ability then.

Attached is a video of my experience.

Hero DBC, LIB, and Rotation are all up to date and downloaded manually off the Git repostiry. 

Let me know if you need any further information...

To re-itterate, this worked fine in an earlier version, latest used a day after release of Shadowlands.

Please see [this video](https://www.youtube.com/watch?v=Hx2yUosmanI), hosted on youtube.

Thank you

**Comment by Mystler** [comment]
If it doesn't show anything, then there's likely an error. I can check if I see something odd later, but if you have an addon to collect bugs (like BugSack) it would help if you can post the error.

**Comment by ferrius94** [comment]
**Thank you for your reply, here's a bug it grabbed in combat (and the only one):
(Let me know if there's a more complete place I can get it, other than chat output such as this one, it looks to be cut off?)**



`[17:18:07] 73x HeroRotation_Rogue\Assassination.lua:528: attempt to call method 'Buff' (a nil value)
[string "@HeroRotation_Rogue\Assassination.lua"]:528: in function <HeroRotation_Rogue\Assassination.lua:519>
[string "@HeroRotation_Rogue\Assassination.lua"]:689: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:116
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
 FocusTimeToXPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:202
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:110
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:145
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @HeroLib\Class\Unit\Player\Main.lua:28
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:389
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:703
 Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:628
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Unit\Player\Power.lua:336
 ArcaneChargesPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:671
 AstralPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:503
 MaelstromDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:564
 FuryDe 
[17:18:17] Usage: /buggrabber <1-1>. `

**Comment by Mystler** [comment]
Nice, thanks. Pushed a fix in f1500b7 that should be in the next release.
