### ISSUE TITLE
[Warrior-Arms] "this spell missing"

### ISSUE THREAD

**Issue by batchyy** [herotc/hero-rotation#639]
Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
Time: Fri Dec  4 16:41:26 2020
Count: 97
Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:81: in function `BuffRemains'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:99: in function `BuffUp'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:104: in function `BuffDown'
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:262: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals:

**Comment by Kutikuti** [comment]
should be fixed with latest PR

**Comment by Melocide** [comment]
still not fixed still recieving the LUA Error

**Comment by Cilraaz** [comment]
Please provide the entire lua error.

**Comment by dmillerlx** [comment]
I am seeing the same error.  I disabled all other addons and no joy.  I went to the maw and tried on the first mob I saw.  I received icons for:
1 - charge
2 - avatar
3 - warbreaker
4 - overpower
Then the LUA error popup appeared with message below.

`Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
Time: Tue Jan 12 20:24:05 2021
Count: 5
Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:148: in function `DebuffRemains'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:159: in function `DebuffUp'
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:248: in function <Interface\AddOns\HeroRotation_Warrior\Arms.lua:222>
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:378: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals: self = <table> {
 UnitExists = true
 UnitNPCID = 170157
 UnitGUID = "Creature-0-3782-2222-199-170157-00007E7581"
 UnitID = "target"
 UseCache = true
 UnitName = "Stygian Runesmith"
 UnitCanBeAttacked = true
}
ThisSpell = nil
Filter = "HARMFUL|PLAYER"
Full = nil
GUID = "Creature-0-3782-2222-199-170157-00007E7581"
UnitID = "target"
(*temporary) = <table> {
 UnitExists = true
 UnitNPCID = 170157
 UnitGUID = "Creature-0-3782-2222-199-170157-00007E7581"
 UnitID = "target"
 UseCache = true
 UnitName = "Stygian Runesmith"
 UnitCanBeAttacked = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'ThisSpell' (a nil value)"
UnitAura = <function> defined =[C]:-1
`

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/b7151f82b4cd3eb84eaf7b5d92c3a61df9842057
