### ISSUE TITLE
[Shaman-Enhancement] WindFury Totem

### ISSUE THREAD

**Issue by Myrkana** [herotc/hero-rotation#641]
Hero Rotation works fine until you equip the Doom winds legendary on enhancement shaman. Then it only wants you to put down your windfury totem constantly unless frost shock or elemental wolves is usable. IF you place windfury totem and it is able to use the ability from the Doom Winds the rotation will then work fine. But while the ability is not usable (only usable once per minute)  the addon sticks to thinking windfury totem should be placed. 

You do get a debuff from the Doom Winds during the period you cannot activate the ability again.

**Comment by lithium720** [comment]
Should be fixed in https://github.com/herotc/hero-rotation/commit/dd291fe0b347c206904659bde87e10c037d3371a
