### ISSUE TITLE
[MM hunter] Rotation issues

### ISSUE THREAD

**Issue by Ohemx** [herotc/hero-rotation#645]
Been using the addon and comparing the cast sequence with that of raid bot quick sim and I've noticed that the addon suggests Wild Spirits when Explosive Shot is up, while Explosive Shot have a higher priority over Wild Spirits, also while Volley buff is up it suggests using Multi-shots (https://imgur.com/a/pQcSf3f)

**Comment by Cilraaz** [comment]
Marksmanship has since been updated to match the latest APL.
