### ISSUE TITLE
[Unholy DK] Sacrificial Pact OffGCDasOffGCD vs GCDasOffGCD mismatch

### ISSUE THREAD

**Issue by wlfman57** [herotc/hero-rotation#648]
Line 293 tries to reference the GCDasOffGCD setting for sacrificial pact when it should reference OffGCDasOffGCD. This periodically causes errors and the rotation to disappear temporarily.

The Error Generated:
Message: Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua:293: attempt to index field 'GCDasOffGCD' (a nil value)
Time: Tue Dec  8 20:54:05 2020
Count: 396
Stack: Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua:293: attempt to index field 'GCDasOffGCD' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua"]:293: in function <Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua:238>
[string "@Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua"]:434: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Line 293 in Unholy.lua:
if HR.Cast(S.SacrificialPact, Settings.Commons.GCDasOffGCD.SacrificialPact, nil, not TargetIsInRange[8]) then return "sacrificial_pact cooldown 13"; end

Commons Section in Settings.lua:
 Commons = {
    UseDeathStrikeHP = 60, -- % HP threshold to try to heal with Death Strike
    UseDarkSuccorHP = 80, -- % HP threshold to use Dark Succor's free Death Strike
    UsePotions = true,
    UseTrinkets = true,
    TrinketDisplayStyle = "Suggested",
    EssenceDisplayStyle = "Suggested",
    CovenantDisplayStyle = "Suggested",
    RaiseDeadDisplayStyle = "Suggested",
    OffGCDasOffGCD = {
      Trinkets = true,
      Potions = true,
      Racials = true,
      MindFreeze = true,
      DeathAndDecay = false,
      SacrificialPact = true,
      ArcaneTorrent = true
    }

**Comment by azzi1103** [comment]
Bump

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/073fcbdeec35ff17129e18b3cbfa6de3ae333a82
