### ISSUE TITLE
[Rogue][Outlaw] Count the odds and rerolling

### ISSUE THREAD

**Issue by mztikk** [herotc/hero-rotation#655]
Hi hi,

when a roll buff from the Count the Odds is lower than 3s it suggests rerolling, which leads to it pretty much rerolling all the time since they only last 5s, even though the original buff from the Roll the Bones cast still lasts for much longer or you even have multiple buffs up.

**Comment by mrdmnd** [comment]
Yes, I've noticed this too; I think it's arguably a real bug in the SIMC APL possibly.

**Comment by EvanMichaels** [comment]
No, this has nothing to do with the APL. It's a difference in how the core RtB buff is tracked.

**Comment by mrdmnd** [comment]
Ah, okay, noted. If you get to it first, feel free to tackle @EvanMichaels ; otherwise I'll probably handle it later tonight.
