### ISSUE TITLE
Poor Demon Spikes usage and Addon Threshold issues.

### ISSUE THREAD

**Issue by tamedbeast** [herotc/hero-rotation#658]
Demon Spikes health Threshold not working on the set value on the adjuster in the addon settings, it just blows both charges on full health, I would suggest having two thresholds for this since Demon spikes are used usually first charge 80% and second 40% approx for good measure.

**Comment by Cilraaz** [comment]
Demon Spikes is currently suggested when there are greater than 1.9 charges (1 charge and 90% of the way through the 2nd charge's cooldown) or if the player's health is under the configurable threshold. It will not use both charges at full health.

**Comment by tamedbeast** [comment]
> Demon Spikes is currently suggested when there are greater than 1.9 charges (1 charge and 90% of the way through the 2nd charge's cooldown) or if the player's health is under the configurable threshold. It will not use both charges at full health.

That is wrong, it does use both demon spikes at 100% health, go test it on the test dummy, also demon spikes should not be called in till there is incoming damage, it would be a waste to use is anything above 90% health.

**Comment by Cilraaz** [comment]
I main Vengeance. It does not.

**Comment by tamedbeast** [comment]
> I main Vengeance. It does not.

I also main vengeance, and using 2 charges of demons spikes on full health is pointless.

**Comment by Cilraaz** [comment]
Please provide the conditions under which this phenomenon occurs. I've never seen it, and the code should not allow for it.

**Comment by tamedbeast** [comment]
Go to a test dummy in Stormwind and you can see if will recommend it while fighting the dummy that is literally doing no damage to you.

**Comment by Cilraaz** [comment]
I have Demon Spikes set to OffGCD, so they're above the main icon. Here's 21 seconds on a dummy in Stormwind. It is suggested one time when at full or near-full charges.

![VDH-DemonSpikes](https://user-images.githubusercontent.com/12204132/102442900-79eb5200-3ff3-11eb-9ee2-96830846cd8b.gif)

**Comment by tamedbeast** [comment]
You can see from mine the first ability it wanted to cast was demon spikes, then after it casts it still calls for it to be used, and this is at a training dummy at 100% health with no incoming dmg. 

https://i.gyazo.com/9b349e3e3a703b636237e3d5beed71ff.mp4

**Comment by Cilraaz** [comment]
I see the exact same behavior: Suggesting DS when at full or near-full stacks. You originally stated that it suggested dumping both charges. Suggesting the one charge when it shouldn't is a very different potential issue.

Any defensives being suggested while not actively tanking should be resolved in commit https://github.com/herotc/hero-rotation/commit/8965c989d8cd62e36629d113c6f6b82fc9ae7716
