### ISSUE TITLE
[Warlock] Affliction: where is the function of Cooldowns()

### ISSUE THREAD

**Issue by mizone** [herotc/hero-rotation#659]
Hi, 

there are no cooldowns() found in the profile. can you fix it?

**Comment by Kutikuti** [comment]
there is plenty. What APL action do you want to translate ?

**Comment by mizone** [comment]
affliction:
local function Aoe()

line 260 :      local ShouldReturn = Cooldowns(); if ShouldReturn then return ShouldReturn; end

**Comment by Kutikuti** [comment]
I see, i fixed it temporarily until someone take a look at the profile completely
https://github.com/herotc/hero-rotation/commit/fe119400f34fd2f0d8bbe24032d5b68b5d61c8ed

**Comment by mizone** [comment]
Thank you!
