### ISSUE TITLE
Arm Warrior speel is missing

### ISSUE THREAD

**Issue by KeelMD** [herotc/hero-rotation#660]
Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
Time: Thu Dec 17 11:43:29 2020
Count: 304
Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:81: in function `BuffRemains'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:99: in function `BuffUp'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:104: in function `BuffDown'
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:262: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals: 

Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
Time: Thu Dec 17 11:44:13 2020
Count: 67
Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:81: in function `BuffRemains'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:99: in function `BuffUp'
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:104: in function `BuffDown'
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:262: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:439: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals:

**Comment by Kutikuti** [comment]
fixed in https://github.com/herotc/hero-rotation/commit/3ba91ae62c4123985e6b9349cc1047141f5d8c8c
