### ISSUE TITLE
[Warrior-Arms] Execute(Condemn) missing as Venthyr !

### ISSUE THREAD

**Issue by Samsemilia1** [herotc/hero-rotation#664]
If you choose venthyr as faction, your Execute is replaced by "Condemn".
Actualy the helper completely ignores them, what is a big big lost of dps.

**Comment by Cilraaz** [comment]
What version of the addon are you running? This should have been fixed in version 9.0.2.14.

**Comment by Samsemilia1** [comment]
I am using 9.0.2.14.

**Comment by Cilraaz** [comment]
Does your UI allow you to view spell IDs on the tooltip (some like ElvUI do this)? If so, can you let me know what ID shows for Condemn?

**Comment by Samsemilia1** [comment]
Have fast installed an extra addon to check ist. The ID is 330334

**Comment by Cilraaz** [comment]
Awesome! Thank you. It looks like Blizz is using multiple spell IDs for Condemn. It's probably different IDs based on Massacre and non-Massacre, at minimum. I've added ID 330334 in commit https://github.com/herotc/hero-rotation/commit/2a8c01d04c287ea583eb1371a04599f9c3ae5a2f

**Comment by Samsemilia1** [comment]
is there need of edit something other? I get the following lua error if Condemn should be usable:


> Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
> Time: Mon Dec 21 00:21:31 2020
> Count: 131
> Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
> [string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
> [string "=(tail call)"]: ?
> [string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:81: in function `BuffRemains'
> [string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:99: in function `BuffUp'
> [string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:272: in function <Interface\AddOns\HeroRotation_Warrior\Arms.lua:222>
> [string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:378: in function `?'
> [string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>
> 
> Locals: self = <table> {
>  UseCache = true
>  ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:596
>  GCDStartTime = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:70
>  Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:46
>  Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:648
>  FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:226
>  PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:725
>  IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:118
>  IsInParty = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:33
>  EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:279
>  Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:698
>  InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:22
>  RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:139
>  VersatilityDmgPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:119
>  FocusTimeToXPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:202
>  MaelstromPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:554
>  ArcaneCharges = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:666
>  IsInDungeonArea = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:53
>  ActiveMitigationNeeded = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Tank.lua:57
>  UpdateActiveLegendaryEffects = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Equipment.lua:117
>  SoulShardsDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:470
>  GetEnemiesInRange = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Enemies.lua:53
>  IsInWhitelistedVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:154
>  PainDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:740
>  AttackPower = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:78
>  FocusCastRegen = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:208
>  PainDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:745
>  PrevOffGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:236
>  MasteryPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:114
>  InsanityPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:633
>  ManaDeficitPercentageP = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:113
>  FuryDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:708
>  PrevGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:202
>  AstralPowerMax = <function

**Comment by Cilraaz** [comment]
Line 272 uses a BuffUp check on Sudden Death's buff. I'll have to do some testing after raid to see that we have the correct Sudden Death buff spell ID, and see if there's some issue with handling the Sudden Death buff.

**Comment by tflo** [comment]
Could you please also add Condemn with ID 317349 ?

This is Condemn on my Arms _without_ Massacre. (With Massacre, and on Fury, it already shows up correctly.)

My Condemn IDs (9.0.5):

- Arms
  - With Massacre: 330334
  - Without Massacre: 317349
- Fury
  - With Massacre: 330325
  - Without Massacre: 317485
- Protection: 317349

**Comment by Cilraaz** [comment]
Condemn IDs were updated on March 11th and should no longer be an issue.

**Comment by tflo** [comment]
Thanks.
