### ISSUE TITLE
[Outlaw Rogue]  Suggesting RTB and overwriting conduit buffs. SnD issue as well.

### ISSUE THREAD

**Issue by darttribal** [herotc/hero-rotation#665]
BiS conduit for rogue gives dispatch/ambush chance to give you a Roll the Bones buff you don't currently have for 5 seconds. If you cast normal RTB it gives you the new buffs from RTB, and you lose your buffs from the conduit procs. 

So if you have 1 energy buff for 15 seconds, and a crit buff for 5, a atk buff for 3 and you cast RTB and gain CDR, you will just have CDR and lose the others.

The addon is suggesting to cast RTB based on your baseline RTB buff and not taking the extra buffs into consideration causing you to cancel them early resulting in DPS loss.

Also it is suggesting to use Slice and Dice on Anima Charged combo points when Slice and Dice is in pandemic, you should only SnD at 4+, and if you have an anima charge at 2, it is suggesting SnD at 2 CP if you are in pandemic for SnD.

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
