### ISSUE TITLE
[DK-UH] Only showing pool on aoe

### ISSUE THREAD

**Issue by Skarpety** [herotc/hero-rotation#666]
I have a problem with aoe on m+. It is showing "pool" all the time after using outbreak and Dark transformation. It doesn't even recommend to use   epidemic.

**Comment by Cilraaz** [comment]
Profile has been updated to current as of commit https://github.com/herotc/hero-rotation/commit/22d588a244cc9b94e40e0ccd0b5979ae41250318

This should no longer be a problem.
