### ISSUE TITLE
[MM-HUNTER] Steady Focus buff before using CD

### ISSUE THREAD

**Issue by Ohemx** [herotc/hero-rotation#668]
I've been using HR in the raid setting past 2 weeks, and after analyzing/comparing my logs to top world hunters, I've noticed that when [[Steady Focus]](https://www.wowhead.com/spell=193533/steady-focus) talent is picked, RH never suggest casting 2 Steady Shot at the opener to get the 7% Hast buff the [[Steady Focus]](https://www.wowhead.com/spell=193533/steady-focus) offers that synergizes very well with the CD's, Which I believe it will increase the DPS substantively and can be easily fixed, Thanks for the good work btw

**Comment by Yaooti** [comment]
Add to the top line of the ST function.

https://pastebin.com/hq4t7exR

**Comment by Ohemx** [comment]
thanks for the help I will give it a try

**Comment by Ohemx** [comment]
now it somehow cast 3 aimed shot at the pull instead of 2, perhaps its overlap with this 
`  -- steady_shot,if=talent.steady_focus.enabled&prev_gcd.1.steady_shot&buff.steady_focus.remains<5
  if S.SteadyShot:IsReady() and (S.SteadyFocus:IsAvailable() and Player:PrevGCDP(1, S.SteadyShot) and Player:BuffRemains(S.SteadyFocusBuff) < 5) then
    if HR.Cast(S.SteadyShot, nil, nil, not TargetInRange40y) then return "steady_shot st 1"; end
  end`

**Comment by Yaooti** [comment]
Oh yea sorry remove the steady shot at top of St function . Forgot to say.

**Comment by Yaooti** [comment]
Here is the full version https://pastebin.com/EXyfzarn

**Comment by Ohemx** [comment]
So replacing 
`-- steady_shot,if=talent.steady_focus.enabled&prev_gcd.1.steady_shot&buff.steady_focus.remains<5 if S.SteadyShot:IsReady() and (S.SteadyFocus:IsAvailable() and Player:PrevGCDP(1, S.SteadyShot) and Player:BuffRemains(S.SteadyFocusBuff) < 5) then if HR.Cast(S.SteadyShot, nil, nil, not TargetInRange40y) then return "steady_shot st 1"; end end` with the code you sent me right ?

**Comment by Ohemx** [comment]
works perfectly thanks

**Comment by Ohemx** [comment]
sometimes casts  3 steady shots in a row not sure why

**Comment by Cilraaz** [comment]
Marksmanship profile has been re-written multiple time since this issue was logged. Closing this issue.
