### ISSUE TITLE
[Hunter-BM] Barbed Shot not showing before bestial wrath

### ISSUE THREAD

**Issue by Telkine** [herotc/hero-rotation#669]
When ever I'm opening in a fight or on a dummy Bestial wrath always is show first before barbed shot.  This seems counter to all high level hunter parsed logs and Simcrafts BM sample sequence which shows barbshot should be shot before bestial wrath when opening.

I assume this is to both build to 3 stacks of frenzy/thrill as quickly as possible and because the barbed shot charges will be back to full as soon as bestial wrath is activated.  Currently Hero rotation seems to ignore that I have no frenzy/thrill built up before using bestial wrath, wasting any charges that exist for barbed shot before using it if I were to follow hero rotations suggestion.

When reviewing the highest dps parses on warcraft logs, it seems BM hunters are building 2 stacks of frenzy before using bestial wrath when they open.  I wonder pretend to be able to read the expressions in the lua for BM but it does seem like bestial wrath is higher in priority order in the BM lua even though in the simcraft priority barbshot should be in the expression:

  | barbed_shot,if=cooldown.bestial_wrath.remains<12*charges_fractional+gcd&talent.scent_of_blood\|full_recharge_time<gcd&cooldown.bestial_wrath.remains\|target.time_to_die<9

**Comment by Cilraaz** [comment]
The profile has been re-written multiple time since this issue was logged. Currently, the APL suggests Bestial Wrath be casted pre-combat (1.5s before pull). Closing this issue.
