### ISSUE TITLE
Keybind Not Displayed For Abilities in Stealth

### ISSUE THREAD

**Issue by AndreiTapai** [herotc/hero-rotation#670]
![image](https://user-images.githubusercontent.com/7092405/103030136-2dd76a80-4529-11eb-8e57-0d99b104dced.png)

See attached imaged

**Comment by MrSmurfy** [comment]
Can confirm, I also have this issue.

**Comment by Cilraaz** [comment]
This should be resolved as of version 9.0.2.29. Closing this issue. If it's still a problem, please comment and I'll reopen it.
