### ISSUE TITLE
Enhancement: Next Ability in Queu

### ISSUE THREAD

**Issue by thegreedyturtle** [herotc/hero-rotation#671]
Could you please add an icon showing the next ability in the rotation queue?

An older rotation helper I used had this feature, and it is extremely useful for maintaining a rotation when you want to skip certain abilities.

For example, a Prot Paladin usually uses Avenger's Shield in the rotation, but AS also has an interrupt function. So if the paladin were in a heavy interrupt fight, they might want to hold their shield back instead of using it in rotation.

With the runner-up ability visible, you can still maintain the 'second best' rotation with what's available.

There's many of these on other classes, such as Vengance DH's jump ability, that they might want to hold back for mobility.

Hopefully it's not extremely challenging to add!

Edit: Misspelled queue...

**Comment by Kutikuti** [comment]
There is no current plan to add next spell in queue because it's way too situatuonal. Some spells are required to be launch in a certain order and that would result in a dps lost or require rotation maintainer to make big modifications to the rotation and add unnecessary cluter
