### ISSUE TITLE
[FROST DK] Error during rotation.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#672]
Message: Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:320: attempt to index field 'GCDasOffGCD' (a nil value)
Time: Sat Dec 26 22:23:58 2020
Count: 27
Stack: Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:320: attempt to index field 'GCDasOffGCD' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation_DeathKnight\Frost.lua"]:320: in function <Interface\AddOns\HeroRotation_DeathKnight\Frost.lua:285>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals:

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/d58246fb52ddffc1f435bad22bb822c47d2cfe60
