### ISSUE TITLE
[Rogue-sub] bug aoe

### ISSUE THREAD

**Issue by sventraxx** [herotc/hero-rotation#674]
today a bug appeared, it does not make me do more aoe in the pulls with the rogue I tried to change everything equip, activate and deactivate the aoe but nothing what can I do?

**Comment by Kutikuti** [comment]
Do you have any lua error poping up ? What is the "bug" ?
Could you provide your talent/conduit/soulbind/legendary setup ?

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
