### ISSUE TITLE
Enhancement Shaman (Windfury Totem)

### ISSUE THREAD

**Issue by Enyaluis** [herotc/hero-rotation#675]
I'm having an issue that seems to be coming from having the legendary "Doom Winds". Before I made the legendary the add on was working really well. With the addition to the legendary the rotation gets stuck on Windfury Totem as if it's not in my range. Even after setting it down again it remains stuck until the doom winds effect wears off. Totems have always been a little weird with the add on for me. I was wondering if there could be a box to check to just disable totems in the shaman selection menu. Thanks for all you do! keep up the hard work!

**Comment by lithium720** [comment]
I have noticed it sometimes without the DW legendary, I will fix it probably on Monday or Tuesday when I get a minute

**Comment by Enyaluis** [comment]
thank you @lithium720 it seems to be working really well now.
