### ISSUE TITLE
[Arms Warrior] AoE bug

### ISSUE THREAD

**Issue by Zekke** [herotc/hero-rotation#677]
AoE suggested spells (cleave and sweeping strikes) always appear faded like if we have not enough rage to use them.
Lvl : 50
Talents : 2-1-2-2-3-3-2

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/c1b4c7452f09546b4b8b9dccc43a1bcdbda402a9
