### ISSUE TITLE
dh havoc

### ISSUE THREAD

**Issue by Tyriion** [herotc/hero-rotation#682]
Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:406: attempt to index field 'Blur' (a nil value)
Time: Tue Jan  5 11:12:17 2021
Count: 97
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:406: attempt to index field 'Blur' (a nil value)
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:406: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals: ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:118
 IsInParty = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:119
 FocusTimeToXPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:202
 MaelstromPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Equipment.lua:121
 SoulShardsDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:154
 PainDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:28
 EnergyRegenPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:389
 FuryPercentage =

**Comment by Tyriion** [comment]
bekomme seit heute diesen lua fehler was kann ich dagegen tun?

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/d46e923aae373a855bd7d4ab122ce2ec66da1983
