### ISSUE TITLE
[Paladin-Ret] Final Verdict legendary power

### ISSUE THREAD

**Issue by VSmoL** [herotc/hero-rotation#684]
Addon doesn't show Final Verdict in rotation when you are using Final Verdict legendary power. Seems like that addon doesn't recognize Final Verdict and skips it from rotation.

**Comment by guardabassi** [comment]
Still bugged as of april 12 , written as pool when final verdict is available

**Comment by guardabassi** [comment]
Still bugged as of april 12 , written as pool when final verdict is available

**Comment by Atlentys** [comment]
Still bugged as of april 12 , written as pool when final verdict is available
And when empyrean power is selected as a talent it doesn't show up on the rotation

**Comment by Cilraaz** [comment]
The profile was completely re-written for 9.2. If any problems persist, please open a new issue.
