### ISSUE TITLE
Monk - Windwalker_EXPERIMENTAL.lua - about usage

### ISSUE THREAD

**Issue by jo32** [herotc/hero-rotation#688]
Can I use a macro to switch to next suggested target?

**Comment by mrdmnd** [comment]
I have mouseover macros for all of the suggested abilities; and that works pretty well for me. You cannot directly control targeting from in game addons or macros, though, so you'll have to do it manually.

**Comment by Kutikuti** [comment]
As @mrdmnd said, you can't control which target to switch with a macro

**Comment by jo32** [comment]
@mrdmnd got it. btw, rotation works very very well, thank you.

**Comment by mrdmnd** [comment]
Thanks @jo32 - a labor of love <3
