### ISSUE TITLE
Remove trinkets from PVP rotation [FDK]

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#691]
I was randomly wearing a PVP trinket that removes all negative effects, and it was offered in rotation. please remove it.
And if possible, see if there is still this kind of rotation in the rotation so that there are no problems. Thank you.

**Comment by Cilraaz** [comment]
What trinket were you using? We can look at adding it to the blacklist. It's simply a function that will suggest any non-blacklisted on-use trinket at that point in the rotation.

**Comment by Dragonfo** [comment]
https://www.wowhead.com/item=184052/sinful-aspirants-medallion?bonus=6793 This trinket is displayed in rotation.

**Comment by Cilraaz** [comment]
The Sinful Aspirant's Medallion was already blacklisted (change is in the github, but not in current release version 9.0.2.07), as was the Sinful Gladiator's Medallion. I've added the Corrupted versions to the blacklist. Please let me know if this is still a problem after the next release version of HeroLib, which will be 9.0.2.08.
