### ISSUE TITLE
Affliction Warlock issues

### ISSUE THREAD

**Issue by MrSmurfy** [herotc/hero-rotation#694]
With the latest release the affliction warlock rotation isn't working correctly, it keeps wanting to cast Unstable Affliction.
I noticed a lot of changes were made to the rotation, but I am guessing the logic for if the debuff is refreshable is not working correctly.

Another thing I noticed is that with cooldowns off, it wants me to use my trinket, I don't think that should be happening.

**Comment by Cilraaz** [comment]
I've been unable to replicate this issue. Can you please provide the following:
- Your HeroRotation version
- Your HeroLib version
- Your talent selections
- Is War mode enabled?
- If yes, your PvP talent selections
- Soulbind in use
- Conduits in use

Thanks!

**Comment by MrSmurfy** [comment]
Hey Cilraaz,

HeroRotation version 9.0.2.21
HeroLib version 9.0.2.08

Talents:
Drain Soul
Siphon Life
Burning Rush
Phantom Singularity
Mortal Coil
Haunt
Dark Soul: Misery

Warmode is disabled.
I don't use any Affliction Conduits at the time of testing.

I could make a recording of it if that helps you troubleshoot it better. Just let me know.
Thanks for making Affliction up-to-date for SL :)

**Comment by MrSmurfy** [comment]
Can't replicate it anymore. Thanks for all your work.
Only QoL thing I could suggest is the night fae spell, Soul Rot while casting shows for the whole duration of the cast, instead of switching to the next recommendation.
All in all a very good update, thanks @Cilraaz !

**Comment by Cilraaz** [comment]
I'm going to re-open this issue. I noticed it on the world boss this week. I believe it has something to do with the function we're using to determine which unit has Unstable Affliction. I've added some debug code to my local copy and will see if I can find out why this is randomly happening.

**Comment by MrSmurfy** [comment]
Yes it's rather weird. It was happening consistently on target dummies for me when I initially reported this but after reloading I couldn't reproduce it.
Thanks for looking into it.

**Comment by Cilraaz** [comment]
I'm hoping this is fixed in commit https://github.com/herotc/hero-rotation/commit/ad23014f38e4412ba9e198fe7b74dc2aea1613c5

**Comment by Cilraaz** [comment]
I'm changing the tag on this to Blizzard Issue. The reason it's seemingly randomly occurring is that we can only track enemies by their nameplates. On larger mobs, such as the world bosses, the nameplates can leave the screen. When they do, they're no longer counted in the enemy table. The workaround from the previous commit should work, but a better fix would be to clamp the nameplates to the screen. This is achievable via UI package settings (for ElvUI, for instance, under NamePlates you can check the option "Clamp Nameplates") or via CVar.
