### ISSUE TITLE
[DK - UH] Errors Only on Dark Iron Dwarf DK

### ISSUE THREAD

**Issue by vcorruptc** [herotc/hero-rotation#699]
This one is kind of weird.  My horde DK works fine, but my Alliance DK's scourge strike and festering strike doesn't show up.  Error below:
2309x HeroRotation_DeathKnight\Unholy.lua:324: attempt to index global 'ArmyoftheDead' (a nil value)
[string "@HeroRotation_DeathKnight\Unholy.lua"]:324: in function <HeroRotation_DeathKnight\Unholy.lua:297>
[string "@HeroRotation_DeathKnight\Unholy.lua"]:438: in function `?'
[string "@HeroRotation\Main.lua"]:445: in function <HeroRotation\Main.lua:423>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = 276837
(*temporary) = "attempt to index global 'ArmyoftheDead' (a nil value)"
HR = <table> {
 CastPooling = <function> defined @HeroRotation\Core.lua:170
 MaxQueuedCasts = 3
 CmdHandler = <function> defined @HeroRotation\Core.lua:264
 PulseInit = <function> defined @HeroRotation\Main.lua:355
 GetTexture = <function> defined @HeroRotation\Core.lua:46
 APLInits = <table> {
 }
 LastUnitCycledTime = 183389.240000
 CastSuggested = <function> defined @HeroRotation\Core.lua:241
 CastQueuePooling = <function> defined @HeroRotation\Core.lua:198
 CastAnnotated = <function> defined @HeroRotation\Core.lua:161
 PulsePreInit = <function> defined @HeroRotation\Main.lua:301
 LeftIconFrame = HeroRotation_LeftIconFrame {
 }
 CastRightSuggested = <function> defined @HeroRotation\Core.lua:252
 GUISettings = <table> {
 }
 LastUnitCycled = <table> {
 }
 ChangePulseTimer = <function> defined @HeroRotation\Main.lua:463
 AoEON = <function> defined @HeroRotation\Core.lua:349
 NameplateIconFrame = HeroRotation_NameplateIconFrame {
 }
 CreateBackdrop = <function> defined @HeroRotation\UI.lua:67
 ToggleIconFrame = HeroRotation_ToggleIconFrame {
 }
 RightSuggestedIconFrame = HeroRotation_RightSuggestedIconFrame {
 }
 Commons = <table> {
 }
 Print = <function> defined @HeroRotation\Core.lua:31
 ResetIcons = <function> defined @HeroRotation\UI.lua:37
 Cast = <function> defined @HeroRotation\Core.lua:132
 Pulse = <function> defined @HeroRotation\Main.lua:423
 Timer = <table> {
 }
 MainFrame = HeroRotation_MainFrame {
 }
 Locked = <function> defined @HeroRotation\Core.lua:360
 Nameplate = <table> {
 }
 CastLeftCommon = <function> defined @HeroRotation\Core.lua:221
 Ready = <function> defined @HeroRotation\Main.lua:458
 APLs = <table> {
 }
 SuggestedIconFrame = HeroRotation_SuggestedIconFrame {
 }
 CastLeftOffset = 1
 SmallIconFrame = HeroRotation_SmallIconFrame {
 }
 SetAPL = <function> defined @HeroRotation\Core.lua:38
 CastRightSuggestedOffset = 1
 CastQueue = <function> defined @HeroRotation\Core.lua:192
 MainIconPartOverlayFrame = HeroRotation_MainIconPartOverlayFrame {
 }
 MainIconFrame = HeroRotation_MainIconFrame {
 }
 CastSuggestedOffset = 1
 CastLeft = <function> defined @HeroRotation\Core.lua:226
 CastLeftNameplate = <function> defined @HeroRotation\Core.lua:232
 CastOffGCDOffset = 2
 GUI = <table> {
 }
 ON = <function> defined @HeroRotation\Core.lua:355
 CDsON = <function> defined @HeroRotation\Core.lua:335
}
S = <table> {
 UnholyStrengthBuff = <table> {
 }
 UnholyAssault = <table> {
 }
 LightsJudgment = <table> {
 }
 UnholyBlightDebuff = <table> {
 }
 PoolResources = <table> {
 }
 UnholyAssaultBuff = <table> {
 }
 ArcanePulse = <table> {
 }
 DeathCoil = <table> {
 }
 ScourgeStrike = <table> {
 }
 ArmyoftheDamned = <table> {
 }
 ArmyoftheDead = <table> {
 }
 FesteringStrike = <table> {
 }
 Fireblood = <table> {
 }
 DeathStrike = <table> {
 }
 DeathStrikeBuff = <table> {
 }
 ConvocationOfTheDead = <table> {
 }
 DarkTransformation = <table> {
 }
 SoulReaper = <table> {
 }
 SacrificialPact = <table> {
 }
 SummonGargoyle = <table> {
 }
 DeathAndDecay = <table> {
 }
 UnholyPact = <table> {
 }
 Epidemic = <table> {
 }
 RaiseDead = <table> {
 }
 ClawingShadows = <table> {
 }
 Defile = <table> {
 }
 DeathsDue = <table> {
 }
 DeathAndDecayBuff = <table> {
 }
 SuddenDoomBuff = <table> {
 }
 UnholyBlight = <table> {
 }
 MindFreeze = <table> {
 }
 Pestilence = <table> {
 }
 AncestralCall = <table> {
 }
 BagofTricks = <table> {
 }
 BloodFury = <table> {
 }
 ArcaneTorrent = <table> {
 }
 VirulentPlagueDebuff = <table> {
 }
 FesteringWoundDebuff = <t

**Comment by CrusaderJohnny** [comment]
Can confirm, my dark iron dwarf is having the same error. Keeps saying armyofthedead a nil value, same error you are getting. But It is very rare. It does not have to do with Army being on CD or off as I have the error both ways. I am wondering if my dark iron racial is what is causing this issue as I notice it mainly after it tells me to do dark transformation and I have that macrod for Fireblood too.

Message: Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua:324: attempt to index global 'ArmyoftheDead' (a nil value)
Time: Sat Jan 23 10:07:19 2021
Count: 161
Stack: Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua:324: attempt to index global 'ArmyoftheDead' (a nil value)
[string "@Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua"]:324: in function <Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua:297>
[string "@Interface\AddOns\HeroRotation_DeathKnight\Unholy.lua"]:438: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = 276837
(*temporary) = "attempt to index global 'ArmyoftheDead' (a nil value)"
HR = <table> {
 CastPooling = <function> defined @Interface\AddOns\HeroRotation\Core.lua:170
 MaxQueuedCasts = 3
 CmdHandler = <function> defined @Interface\AddOns\HeroRotation\Core.lua:264
 PulseInit = <function> defined @Interface\AddOns\HeroRotation\Main.lua:355
 GetTexture = <function> defined @Interface\AddOns\HeroRotation\Core.lua:46
 APLInits = <table> {
 }
 LastUnitCycledTime = 526095.082000
 CastSuggested = <function> defined @Interface\AddOns\HeroRotation\Core.lua:241
 CastQueuePooling = <function> defined @Interface\AddOns\HeroRotation\Core.lua:198
 CastAnnotated = <function> defined @Interface\AddOns\HeroRotation\Core.lua:161
 PulsePreInit = <function> defined @Interface\AddOns\HeroRotation\Main.lua:301
 LeftIconFrame = HeroRotation_LeftIconFrame {
 }
 CastRightSuggested = <function> defined @Interface\AddOns\HeroRotation\Core.lua:252
 GUISettings = <table> {
 }
 LastUnitCycled = <table> {
 }
 ChangePulseTimer = <function> defined @Interface\AddOns\HeroRotation\Main.lua:463
 AoEON = <function> defined @Interface\AddOns\HeroRotation\Core.lua:349
 NameplateIconFrame = HeroRotation_NameplateIconFrame {
 }
 CreateBackdrop = <function> defined @Interface\AddOns\HeroRotation\UI.lua:67
 ToggleIconFrame = HeroRotation_ToggleIconFrame {
 }
 RightSuggestedIconFrame = HeroRotation_RightSuggestedIconFrame {
 }
 Commons = <table> {
 }
 Print = <function> defined @Interface\AddOns\HeroRotation\Core.lua:31
 ResetIcons = <function> defined @Interface\AddOns\HeroRotation\UI.lua:37
 Cast = <function> defined @Interface\AddOns\HeroRotation\Core.lua:132
 Pulse = <function> defined @Interface\AddOns\HeroRotation\Main.lua:423
 Timer = <table> {
 }
 MainFrame = HeroRotation_MainFrame {
 }
 Locked = <function> defined @Interface\AddOns\HeroRotation\Core.lua:360
 Nameplate = <table> {
 }
 CastLeftCommon = <function> defined @Interface\AddOns\HeroRotation\Core.lua:221
 Ready = <function> defined @Interface\AddOns\HeroRotation\Main.lua:458
 APLs = <table> {
 }
 SuggestedIconFrame = HeroRotation_SuggestedIconFrame {
 }
 CastLeftOffset = 1
 SmallIconFrame = HeroRotation_SmallIconFrame {
 }
 SetAPL = <function> defined @Interface\AddOns\HeroRotation\Core.lua:38
 CastRightSuggestedOffset = 1
 CastQueue = <function> defined @Interface\AddOns\HeroRotation\Core.lua:192
 MainIconPartOverlayFrame = HeroRotation_MainIconPartOverlayFrame {
 }
 MainIconFrame = HeroRotation_MainIconFrame {
 }
 CastSuggestedOffset = 1
 CastLeft = <function> defined @Interface\AddOns\HeroRotation\Core.lua:226
 CastLeftNameplate = <function> defined @Interface\AddOns\HeroRotation\Core.lua:232
 CastOffGCDOffset = 1
 GUI = <table> {
 }
 ON = <function> defined @Interface\AddOns\HeroRotation\Core.lua:355
 CDsON = <function> defined @Interface\AddOns\HeroRotation\Core.lua:335
}
S = <table> {
 UnholyStrengthBuff = <table> {
 }
 UnholyAssault = <table> {
 }
 LightsJudgment = <table> {
 }
 UnholyBlightDebuff = <table> {
 }
 PoolResources = <table> {
 }
 UnholyAssaultBuff = <table> {
 }
 ArcanePulse = <table> {
 }
 DeathCoil = <table> {
 }
 ScourgeStrike = <table> {
 }
 ArmyoftheDamned = <table> {
 }
 ArmyoftheDead = <table> {
 }
 FesteringStrike = <table> {
 }
 Fireblood = <table> {
 }
 DeathStr

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/d3e9444307ca54ee343a86fff6d3dd48ad82d1da
