### ISSUE TITLE
[Warrior - Arms] Ravager bug (Venthyr)

### ISSUE THREAD

**Issue by Zekke** [herotc/hero-rotation#701]
Addon stop suggesting spells when ravager is ready while out of execution phase (80 -> 35%). It starts suggesting spells again once you cast ravager.
Talents : 2-1-1-3-2-2-3
Covenant : Venthyr

**Comment by Cilraaz** [comment]
Arms has been re-written since this issue was raised. I just tested and it appears to no longer be a problem at this time. If you are still having an issue, please let us know.
