### ISSUE TITLE
[Suggestion] Option to show next 3 actions instead of just 1

### ISSUE THREAD

**Issue by wheatbread** [herotc/hero-rotation#706]
It would be great if we had the option to show the next 3 actions instead of 1, similar to Ovale or Hekili.  It means you can plan ahead just a bit more, or go to the next one if the first one suggested isn't what you want to do (ex. it suggests rolling the bones when I still have a few seconds of a 5-stack buff left).

**Comment by Herdrage** [comment]
Certain abilities you can go in the settings to have them show in the top icon as a suggestion, including roll the bones, blade dash, blade flurry etc. It's usually an option for long cd abilities or st+aoe (frozen orb, eye beam, blade dash etc) abilities. 

Many times I've also requested some abilities to have the option to be in the suggested icon and the devs were happy to add it if it made sense to. It's usually stuff you may want to hold for certain boss phases or especially in m+. 

However sometimes the APLs are written very strict where if you don't follow them perfectly the entire rotation could go out of whack, but sometimes HR will deviate a little bit to fix those issues if it's not too much work.

**Comment by wheatbread** [comment]
Huh, I actually specifically looked for an option to move Roll the Bones to a suggestion instead of a required action before coming to suggest this, and I couldn't find it.  Looking now, I still don't see it.  The most I see is an option for Killing Spree to be a suggestion.

At any rate, I still think being able to foresee the next 3 abilities instead of just 1 is an advantage as it removes that tiny hesitation in between casts.

**Comment by Herdrage** [comment]
oh sorry. It used to have that option in BFA. I haven't minded it this expac since they made it into a 45 sec cd. You can put in a request to have it as an option. Or if there's a certain buff you always want you can change the roll the bones logic in the options.

**Comment by Kutikuti** [comment]
Same answer as https://github.com/herotc/hero-rotation/issues/37
