### ISSUE TITLE
[Monk - Windwalker] EXPERIMENTAL.lua - Suggestive spells on AOE

### ISSUE THREAD

**Issue by Ankhy** [herotc/hero-rotation#709]
It ruins aoe if there is a main target and only small ads to burn, cause it stops showing rotation in main window and tries to force you to change target to apply mark of the crane, but that can be highly inefficient in many situations. Maybe keep the rotation in the main window while suggesting other targets?

**Comment by Cilraaz** [comment]
The profile was completely re-written for 9.2. If any problems persist, please open a new issue.
