### ISSUE TITLE
[Monk-Windwalker] Priority is broken in latest build.

### ISSUE THREAD

**Issue by chimikoo** [herotc/hero-rotation#711]
As stated as of build 9.0.2.24 windwalker monk's priority is pretty broken. It recommends spamming blackout kick during WOO.
Its sorted by using Experimental lua instead but that has some questionable pooling going on, like pooling energy while being at 100 energy and only having 2 chi.

**Comment by Cilraaz** [comment]
This profile has since been completely rewritten for 9.2. If any issue still exists, please open a new issue.
