### ISSUE TITLE
Warrior: Bladestorm shows as 'Main' icon even when 'show as off gcd' checked

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#712]
Bladestorm shows on the main icon even when 'show as off gcd' is checked on both fury and arms. Would appreciate a fix!

**Comment by Cilraaz** [comment]
Fury is fixed in commit https://github.com/herotc/hero-rotation/commit/74c66287824943b8539de102058d5995cfc7f48a

Arms was fixed in a previous commit.
