### ISSUE TITLE
[UH-DK] Fix epidemic with disabled AOE option

### ISSUE THREAD

**Issue by geraint425** [herotc/hero-rotation#718]
Yesterday I was in a raid, and at the Sludgefest boss, I noticed a bug. It manifests itself in the fact that when I run away from the target at a long distance, he offers me to use the Death coil, but if the radius of the Death coil ends, then Epidemic is used. Yesterday I turned off the AOE rotation on purpose, and in the rotation it was still offered Epidemic at the farthest distance. And it should work like that. If we run away from the target, and we can use the Death coil, we use it, if we move away from the target by more than 40m, then nothing should be offered in the rotation. And the epidemic ability should only work when there are 4+ targets, and it shouldn't be in ST rotation at all. For good, even up to 3 targets, for simcraft we should use the Death coil, and the epidemic only when 4+ targets. Please correct that the epidemic works only when the AOE option is enabled, and only when there are 2+ targets, but please do not remove the function when we run away from targets at a very long distance and use the epidemic when 4+ targets.

**Comment by Cilraaz** [comment]
Added an AoEON check for the out-of-range Epidemic suggestion.
