### ISSUE TITLE
[UH-DK] Bug using an epidemic on the boss Denathrius.

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#720]
Hello. On the boss Denathrius and not only, I noticed that in the rotation it is proposed to use the epidemic without an outbreak on the targets. Here is a screenshot https://imgur.com/vYr4BZW of the sequence on the boss itself when many targets appear around it. The addon immediately suggests using an epidemic rather than an outbreak on the main target, and then an epidemic. I also noticed this and it works on other bosses where there is an additional target around the main one.
If this is not a bug, then you can tell me how it should work in such scenarios. Because I see it should work like this. There is a fight with the boss, after an additional target appears, and the addon must check the readiness of Unholy Blight if this ability is CD then use the main target of the outbreak to infect other nearby targets, and update the outbreak on the main one. And only after we used the outbreak through the main target, we are already using the epidemic.

**Comment by Cilraaz** [comment]
This should be resolve in commit https://github.com/herotc/hero-rotation/commit/273f3b1fa0e682d530e6c3737a397ccfe292d811
