### ISSUE TITLE
[Enhancement]: [Rogue] Add OffGCD Option for Slice and Dice

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#722]
Please move slice and dice to the smaller cooldown panels above the main rotation. There are numerous scenarios where we do not want to burn combo points for slice and dice. even disabling AoE does not remove slice and dice from the main rotation. please, fix this.  it literally will stay as the spell to press no matter what else we press and are forced to use it. To make matters worse is the fact that if we burn 1 combo point to just get it out of the main window, it returns back in a few seconds forcing us to use it on a 5 combo point just to have it not appear.  Make it function like you have Blade furry appears for Outlaw, that way we determine if the current circumstance warrants using slice and dice or not.

**Comment by EvanMichaels** [comment]
Are you actually sure there are numerous scenarios where you don't want to use SnD? This seems more harmful than useful in a general sense. SnD is almost always worth casting even if the fight is ridiculously short. It is extremely strong.

**Comment by Soulsmacka** [comment]
I know the importance of it, but it can be set to the side like Blade furry and we can use it on cd, but sometimes you get engaged in PvP and it's just more of a nuisance than anything plus it's not necessary to take priority over everything else when a target has less than 20% health and 1 evis can drop them.

**Comment by Soulsmacka** [comment]
I hoped back onto a rogue and this still exist. Can you please consider adding the option to put Slice n Dice to the Global CD window. Thanks

**Comment by Seny951** [comment]
Slice & Dice is no longer manually casted
