### ISSUE TITLE
[Balance Druid] Celestial Alignment Missing with Trinket

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#723]
Celestial alignment does not show up on the rotation when empyreal ordinance is equipped.

**Comment by Cilraaz** [comment]
Celestial Alignment/Incarnation relies on a variable. That variable contains the condition that Empyreal Ordinance is not equipped _or_ it's on cooldown with less than 160 second remaining. If the trinket is ready to use, that would cause this variable to be false, causing CA/Inc to not be suggested.

**Comment by RussellAnas** [comment]
That's the thing. Even when the trinket is on cooldown, it doesn't suggest CA/Inc. No matter when I cast the trinket, it's like the spell has gotten disabled.

**Comment by Lespindagger** [comment]
I moved the trinket display to the "SuggestedRight" and now the trinket displays properly and when off CD, but the CA/Inc is not display suggested when off CD

**Comment by Lespindagger** [comment]
Seems the CA/Inc and the Trinket keybind are on the same CD and also on the same location on HeroRotation. When one or the other is used, HeroRotation sees it as on or off CD for both.

**Comment by Lespindagger** [comment]
Regardless of suggested or suggested right location both CA/Inc or Trinket are both either off or on CD instead of either or.

**Comment by Lespindagger** [comment]
Found the issue with CA/inc, Trinket and or Convoke. If one places trinket to SuggestedRight HeroRotation works properly. The issue is when using it on Training Dummies. I tested trinket placed on SuggestedRight slot on different mobs and it works. HeroRotation will not work properly between Trinket, CA/inc or Convoke when testing Dps on Training Dummies.

**Comment by RussellAnas** [comment]
Should this have gotten fixed in the latest release or still open?

**Comment by Lespindagger** [comment]
This is still pending. It came back after the last release. It doesn't display while on any mob, regardless if Training dummy or not

**Comment by Cilraaz** [comment]
Balance has been re-written to be in line with the 9.1 APL. This should be working as expected now.
