### ISSUE TITLE
[FROST MAGE] Error on login

### ISSUE THREAD

**Issue by Caynn** [herotc/hero-rotation#727]
8x HeroRotation_Mage\Frost.lua:240: ')' expected near 'then'
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@HeroRotation\Main.lua"]:381: in function `PulseInit'
[string "@HeroRotation\Main.lua"]:293: in function <HeroRotation\Main.lua:290>

Locals:
(*temporary) = "HeroRotation_Mage"

**Comment by Cilraaz** [comment]
This was previously fixed in commit 728a2f19dfb45a430aca830436654b7fc4ee7e5a

You can grab the update from the github files or it will be included in the next release.
