### ISSUE TITLE
[FDK] BoS cannot last long in rotation

### ISSUE THREAD

**Issue by geraint425** [herotc/hero-rotation#728]
Yesterday in a raid I decided to test Frost DK in the BoS build, and saw that the addon could not hold BoS. At the beginning of the battle, we are gaining 50 runic power, and the addon suggests using BoS. And I noticed that in the middle of the battle, when the BoS build is offered to be pressed, he calmly holds it for 45sec +. Is it possible to somehow correct the beginning of the rotation so that the addon gains more runic power? And make obliterate priority higher during BoS, so that we ignore Rime when we have little rune power.

**Comment by geraint425** [comment]
I just noticed. That the rotation does not correspond to the apple on which the rotation is going. Here is a screenshot of the raidbots of my rotation simcraft. https://imgur.com/a/oloesCh and it is directly radically different from the rotation that is now in the addon. Please correct. Since there is an assumption that the error is due to the fact that BoS does not work correctly in this particular rotation.

**Comment by Cilraaz** [comment]
Frost DK has been re-written to be in line with the 9.1 APL. This should be better now.
