### ISSUE TITLE
Dragon roar warrior fury solo rotation

### ISSUE THREAD

**Issue by alexmr06** [herotc/hero-rotation#729]
Hi :) is it possible to put in the mono rotation the dragon roar ? What if some people don't prefer to have it, put it in the addon's menu, and be able to activate/deactivate it at any time ? Thank you for the work you do like every time :). ( and if you do it, don't forget that it's used in the rage period and adds 10 more rage ).

**Comment by Cilraaz** [comment]
Dragon Roar is only suggested with more than one target, as per the SimC APL.
