### ISSUE TITLE
[Unholy DK] Latest release broke AoE rotation

### ISSUE THREAD

**Issue by n3rdninja** [herotc/hero-rotation#734]
The rotation sticks on pooling: Outbreak > Unholy Blight > stuck on pooling.

**Comment by Cilraaz** [comment]
I'm unable to replicate this. Please try the 9.0.5.01 version of the addon.

**Comment by n3rdninja** [comment]
Same issue with 9.0.5.01. The only abilities ever prompted are Outbreak, Unholy Blight, and Death Coil (forgot to mention that last time). Epidemic, Festering Strike, and Scourge Strike are never prompted.

I have tried re-installing the add-on (and dependencies). If I go back to the version before you made the Epidemic changes, it works fine. I am not sure why though, those changes LGTM.

**Comment by Cilraaz** [comment]
Please provide the following:

- Your talent build
- Your Covenant
- Your Soulbind
- Your active conduits
- Your trinkets (if they are on-use trinkets)

**Comment by n3rdninja** [comment]
talents=1333221
covenant=necrolord
soulbind=plague_deviser_marileth:4,323074/124:5/323091/108:1/323081

Neither trinket is on-use.

**Comment by Cilraaz** [comment]
With the same talent build, I'm unable to replicate the issue. For me, the addon suggests Army and Outbreak pre-combat, then Unholy Blight -> Dark Transformation -> Festering Strike and so on.

What settings are you using for the Display Styles for Trinkets, Raise Dead, and Covenant? Also, which abilities do you have to set Off GCD? If you'd prefer screenshots, please provide one of the "DeathKnight" and "Unholy" settings.

**Comment by n3rdninja** [comment]
I wiped out all of my add-ons, reset interface settings, and it is working now. Thank you for looking into this.
