### ISSUE TITLE
[Arms Warrior] Sweeping Strikes not recommended with Ravager

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#736]
Sweeping strikes is never recommended with Ravager talent even when there are two targets or more.

Works fine with Bladestorm and obeys a good rotation prioritiy, but disappears with Ravager although enabling Sweeping Strikes while Ravager is running with >1 target is optimal.

**Comment by Cilraaz** [comment]
Arms has been updated to the latest APL in the most recent release (9.0.5.02). Please try this version and let us know if you still have problems.

**Comment by RussellAnas** [comment]
Thanks Cilraaz, I'll get back on this, for now the castqueue stuff is messing up the rotation even more so it's difficult to understand if this got fixed.

**Comment by RussellAnas** [comment]
This is working fine now! Thanks Cilraaz!
