### ISSUE TITLE
[Fury Warrior] Recklessness overlapping with Bloodthirst

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#740]
I see a spell recommended that has half the icon of bloodthirst, and half of Recklessness.

Also recklessness recommendations seem a bit off because of this as it doesn't get suggested when this happens. Can you look into this?

**Comment by c-ray-c** [comment]
I believe this is due to the "Cast queues". I agree it's very counterintuitive, confusing and needless... What's the point in BT/Heroic Leap queue? What's the point in BT/Recklessness queue...
Only happens if Signet of Tormented Kings is equiped...

`
    -- sequence,if=active_enemies=1&covenant.venthyr.enabled&runeforge.signet_of_tormented_kings.equipped,name=BT&Reck:bloodthirst:recklessness
    if (S.Bloodthirst:IsCastable() and S.Recklessness:IsCastable()) and (EnemiesCount8 == 1 and Player:Covenant() == "Venthyr" and SignetofTormentedKingsEquipped) then
      if HR.CastQueue(S.Bloodthirst, S.Recklessness) then return "BT&Reck sequence"; end
    end
    -- sequence,if=active_enemies=1&!covenant.venthyr.enabled&runeforge.signet_of_tormented_kings.equipped,name=BT&Charge:bloodthirst:heroic_charge
    if (S.Bloodthirst:IsCastable() and S.HeroicLeap:IsCastable()) and (EnemiesCount8 == 1 and Player:Covenant() ~= "Venthyr" and SignetofTormentedKingsEquipped) then
      if HR.CastQueue(S.Bloodthirst, S.HeroicLeap) then return "BT&Charge sequence"; end
    end
`

**Comment by RussellAnas** [comment]
What even are cast queues? Does this mean it's saying we macro the spells together or what? The previous version was so smooth comparatively. It showed recklessness as a small icon on top of main when you were enraged.

**Comment by c-ray-c** [comment]
Not exactly sure... My understanding is that when you see a cast queue double faced icon, you want to first activate the ability on the left and then right away - ability on the right. Something like a /castsequence macro. 
It can be coded so you only see one ability at a time, just a bit more code logic needed...
@Cilraaz Am I understanding it right? Is it really needed? I dislike the idea of macroing together anything with the heroic leap. Especially bloodthirst... why would you bloodthirst and then heroic leap anyways?.. you're already in a melee. What's the point and how it's related to the legendary at all? Chaining together bloodthirst and recklessness also seem to be very strange... What for? Why? Not to mention that anything with recklessness should probably take into account time to kill value.
Very-very, extremely confusing indeed....

**Comment by Cilraaz** [comment]
CastQueue typically works like a cast sequence macro, but it's not necessarily suggesting that the user macro abilities together. I have no idea about the logic behind them. That would be a question for the Simulationcraft guys. Another place you'll often see CastQueue used is in the Subtlety rotation.

Is it really needed? Frankly, I don't know. Our goal has always been to adhere as closely to the intent of Simulationcraft as possible. I can't say I know exactly the logic behind these sequence lines, but they're in the SimC APL...

**Comment by RussellAnas** [comment]
Think we need to wait for SimC APL to update then. For some reason I went back to the curseforge version and everything is working fine now (no castsequence stuff). But when I update from here, the rotation becomes really weird

**Comment by Cilraaz** [comment]
The SimC APL _is_ updated. We are simply updating to match.

**Comment by c-ray-c** [comment]
> The SimC APL _is_ updated. We are simply updating to match.

I think Russel mean that the SimC APL itself have to be fixed. 
Meanwhile what do you think if we make this part optional? With default turned on?

**Comment by Cilraaz** [comment]
I temporarily removed the BT&Charge sequence.
