### ISSUE TITLE
[Fury Warrior] BT + Recklessness Icons

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#742]
The Bloodthirst + Recklessness icon shared in half really confuses the rotation. Can you please disable this castsequence so that recklessness is always suggested as a cooldown that does not overlap with Bloodthirst?

**Comment by Cilraaz** [comment]
I added an option to hide CastQueue suggestions in commit https://github.com/herotc/hero-rotation/commit/478a5241f516cb5a5e62b1e36847a9a85dd3b371
