### ISSUE TITLE
Stutter/Lag on mouseover

### ISSUE THREAD

**Issue by DoomFiskarna** [herotc/hero-rotation#743]
When I have the addon enabled and I mouseover an ally (e.g. to heal with macro) I get a brief but huge fps drop to the point where it seems to be frozen for up to about 0.2 sec. This happens both when mousing over or off of a friendly player or pet, so if I'm running my mouse across the screen I will be at less than 10 fps for most of that.

I found this issue most noticable on my druid in restoration spec, even though the addon technically wasn't showing anything. When I disabled this addon and reloaded, the mouseover lag was gone.

**Comment by Cilraaz** [comment]
I have to assume that you're using a horribly out of date version of the addon. The current version does not support Restoration Druid.

**Comment by DoomFiskarna** [comment]
It's up-to-date, but still causes lag despite not supporting the current spec (like I mentioned in my first post "the addon...wasn't showing anything"). The problem isn't the lack of rotation, it's the lag caused by mouseover even though there is not a rotation to load.

**Comment by Cilraaz** [comment]
I'm unable to replicate this issue. Are you receiving any lua errors? Have you tried completely removing the addon and reinstalling to ensure there are not orphaned files from an old version (unlikely, but _could_ happen)?

**Comment by Cilraaz** [comment]
No further responses to questions asked. Closing this issue.
