### ISSUE TITLE
Arms Warrior Addon Dissappering

### ISSUE THREAD

**Issue by Tellasarin** [herotc/hero-rotation#745]
On occasions when using the Arms warrior rotation the addon will disappear. Sometimes it comes back after killing a mob, other times the main rotation will remain not visible whilst things like Charge will remain visible as a suggested button. 
Currently running addon at level 55. I've also noticed alongside this doing this I often get popups saying that I'm experiencing a lot of addon errors. This error message never pops up unless I'm using the Arms Warrior Rotation.

**Comment by Cilraaz** [comment]
I would need the error message to be able to fix the issue.

**Comment by Tellasarin** [comment]
I'll see about replicating it and get some screenshots over to you asap.

**Comment by Tellasarin** [comment]
The lua error that comes up is

Message: Interface\AddOns\HeroRotation_Warrior\Arms.lua:364: attempt to index field 'VictoryRush' (a nil value)
Time: Fri Mar 26 12:18:41 2021
Count: 21
Stack: Interface\AddOns\HeroRotation_Warrior\Arms.lua:364: attempt to index field 'VictoryRush' (a nil value)
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:364: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:446: in function <Interface\AddOns\HeroRotation\Main.lua:424>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Comment by Tellasarin** [comment]
Which is odd because of rcloot council having nothing to do with it but yeah..

**Comment by Tellasarin** [comment]
Message: Interface\AddOns\HeroRotation_Warrior\Arms.lua:364: attempt to index field 'VictoryRush' (a nil value)
Time: Fri Mar 26 12:20:54 2021
Count: 42
Stack: Interface\AddOns\HeroRotation_Warrior\Arms.lua:364: attempt to index field 'VictoryRush' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation_Warrior\Arms.lua"]:364: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:446: in function <Interface\AddOns\HeroRotation\Main.lua:424>

Locals:

**Comment by Cilraaz** [comment]
That should be fixed with commit https://github.com/herotc/hero-rotation/commit/2bc35b288d8973adcee23067fcdf3a58c8e02348

You can either update from the github or wait for the next release version.
