### ISSUE TITLE
Wrong keybindings on spells

### ISSUE THREAD

**Issue by teo6667** [herotc/hero-rotation#747]
Hi.

In some cases the keybindings on a spell shows another spell's key. And when a battle starts sometimes just does not show any keybinding.

This happens with balance druid in moonkin form. In normal form does not happens. The spells are in the same bindings in all forms.

![not showing](https://user-images.githubusercontent.com/13005539/113574052-a1eed780-961b-11eb-8590-25aed04fd079.png)
![wrong key](https://user-images.githubusercontent.com/13005539/113574055-a3200480-961b-11eb-8f1e-28ac8d020681.png)
![wrong key2](https://user-images.githubusercontent.com/13005539/113574056-a3200480-961b-11eb-9356-e41d897b3cf3.png)
![wrong key3](https://user-images.githubusercontent.com/13005539/113574058-a3b89b00-961b-11eb-8d36-5505411663c0.png)

Ty.

**Comment by Cilraaz** [comment]
With version 9.0.5.06, I'm unable to replicate this issue. With both ElvUI and the default Blizzard bars, hotkeys are showing properly.

**Comment by Cilraaz** [comment]
I found where this issue may be occurring. Please try the changes in commit https://github.com/herotc/hero-lib/commit/ebbd8a3d18c8a545f7d5f9a04daeb09e96202378 and see if it is still a problem.

**Comment by teo6667** [comment]
> I found where this issue may be occurring. Please try the changes in commit [herotc/hero-lib@ebbd8a3](https://github.com/herotc/hero-lib/commit/ebbd8a3d18c8a545f7d5f9a04daeb09e96202378) and see if it is still a problem.

Yes! Working fine with this one. :D

**Comment by Cilraaz** [comment]
Great! Thanks for the update.
