### ISSUE TITLE
[UI] Keybinding detection problem

### ISSUE THREAD

**Issue by MrSmurfy** [herotc/hero-rotation#748]
Hello,

I came across some weird keybind detection playing on my rogue.

For example:
![image](https://user-images.githubusercontent.com/11522121/113721967-43dff400-96f0-11eb-857b-4ac6a1afb31c.png)

Slice n Dice is bound to Control + 3 for me but the addon sometimes leaves out the modifier key.
I am not sure why it is doing that, I don't use any actionbar addon.

During stealth it doesn't show a keybind at all;
![image](https://user-images.githubusercontent.com/11522121/113722389-aafda880-96f0-11eb-9682-1b1ef0c1e705.png)

**Comment by Cilraaz** [comment]
I made a small change to HeroLib that _may_ fix the issue. Please try commit https://github.com/herotc/hero-lib/commit/75b86a932c5670528fd7a1a39b97e05a5d86e172 and see if you still have the problem.

**Comment by Cilraaz** [comment]
I found a second issue that may also be affecting you. Please try commit https://github.com/herotc/hero-lib/commit/ebbd8a3d18c8a545f7d5f9a04daeb09e96202378 which adds some changes for people using Blizzard default bars number 3 through 6.

**Comment by MrSmurfy** [comment]
Hey Cilraaz, glad to see you still working on the project! :) I hope you're doing well and everything is alright with Aethys.

Keybinds seem to work correctly throughout the normal rotation now. In stealth however it's still broken;

- Opening from stealth it wants me to cast mutilate (assa rogue), the keybind for it is not being shown but I have mutilate in the same slot for my normal actionbar and my stealth actionbar.
- for some reason it does show trinkets correctly when in stealth.

This is my stealth actionbar;
![image](https://user-images.githubusercontent.com/11522121/113744371-f621b680-9704-11eb-90a0-37bfead9331f.png)

**Comment by MrSmurfy** [comment]
The stealth one is being inconsistent it seems.. sometimes it works, sometimes it doesn't. I am trying to replicate it..

![image](https://user-images.githubusercontent.com/11522121/113744841-5ca6d480-9705-11eb-8c26-d14c4828190d.png)

Okay so when the keybind isn't being detected from stealth I just simply move the mutilate to another slot and put it in slot1 again. Then the detection works again.

**Comment by c-ray-c** [comment]
Confirming - still an issue for rogues. Not only in stealth, btw. Probably has to do with bar switching when coming out of stealth.

**Comment by Cilraaz** [comment]
This should be fixed with the updates that you'd suggested in issue #849. If not, please let me know.
