### ISSUE TITLE
Not Showing Keybinds Correctly

### ISSUE THREAD

**Issue by esc-scripts** [herotc/hero-rotation#749]
Here is an example for Pyroblast. Some keys it shows, others not at all.

![image](https://user-images.githubusercontent.com/73078719/113753606-2cac0100-9706-11eb-9b07-6666ba279891.png)

**Comment by Cilraaz** [comment]
Duplicate of #747. Please update to HeroLib version 9.0.5.04.

**Comment by esc-scripts** [comment]
I have updated to 9.0.5.04. and switched to Frost as the spec is finished and now the keys show the wrong binds.

![image](https://user-images.githubusercontent.com/73078719/113758499-de016580-970b-11eb-96df-39df01a07d74.png)

**Comment by Cilraaz** [comment]
What hotbar addon are you using?

**Comment by esc-scripts** [comment]
Bartender4. I am using that on my pally too and hero is working flawlessly there.

**Comment by esc-scripts** [comment]
Have fixed myself. Please close this.
