### ISSUE TITLE
Fire Mage to many lua errors

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#750]
I have Fire Mage in main.lua deactivated

**Comment by Cilraaz** [comment]
Please try HeroRotation version 9.0.5.07.

**Comment by ReglohPri** [comment]
> Please try HeroRotation version 9.0.5.07.

I don't see anything changes for fire mage.

Here are the errors:
27x HeroRotation_Mage\Fire.lua:479: attempt to call method 'ExecuteRemains' (a nil value)
[string "@HeroRotation_Mage\Fire.lua"]:479: in function <HeroRotation_Mage\Fire.lua:432>
[string "@HeroRotation_Mage\Fire.lua"]:890: in function `?'
[string "@HeroRotation\Main.lua"]:446: in function <HeroRotation\Main.lua:424>

**Comment by Cilraaz** [comment]
Your HeroLib version is out of date. ExecuteRemains was a recently added function.

**Comment by ReglohPri** [comment]
I have HerLib installed from Mar 9, 2021

**Comment by Cilraaz** [comment]
That is an old version. There have been 3 new release versions since then.

**Comment by ReglohPri** [comment]
No, on curceforge is this the latest

**Comment by ReglohPri** [comment]
Version: 9.0.5.01

**Comment by Cilraaz** [comment]
https://github.com/herotc/hero-lib/releases/download/9.0.5.04/HeroLib-9.0.5.04.zip

**Comment by ReglohPri** [comment]
Then you forgot to update on Curseforge 

Thanks for the new link.

Sincerely
Holger -> ReglohPri

**Comment by Cilraaz** [comment]
CurseForge pulls their packages automatically from the github. We'll have to figure out exactly how they managed to break their system yet again.

**Comment by ReglohPri** [comment]
I will test the new HeroLib version and then I will let you know. Then we can close the issue.

**Comment by ReglohPri** [comment]
It's working perfect now. Many thank's.
