### ISSUE TITLE
Frost mage - Covenant ability

### ISSUE THREAD

**Issue by MrSmurfy** [herotc/hero-rotation#751]
The frost mage rotation when casting the venthyr covenant ability keeps showing even though it should be showing the next recommendation already. I guess a small QoL tweak could be nice.

**Comment by MrSmurfy** [comment]
Created a pull request for it; https://github.com/herotc/hero-rotation/pull/752

**Comment by Cilraaz** [comment]
I missed this issue, but the PR was closed, as the change was added in commit https://github.com/herotc/hero-rotation/commit/310ddfbeb644cf6a2b59a19192b0eca7275e3ae8

Thanks for the input!
