### ISSUE TITLE
Shadow Priest - Prism Legendary Rotation Supported?

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#753]
Not seeing support for the prism legendary.  Is this an error with how I'm using the addon, or does shadowpriest rotation not currently support this legendary?

**Comment by Cilraaz** [comment]
Shadowflame Prism is supported. It has minimal impact on the APL, though.

**Comment by GarrettCottrell** [comment]
During voidform, I am never recommended a shadowword death, while mindbender is active, and prism is equipped. Is this correct, or am I possibly not getting the correct information from the addon?

I do receive a recommendation to use shadowword death, prior to using eruption -- just once in voidform, there are no death recommendations. 

I am using the version of the addon available via curseforge updates  - I will try adjustments on my end, it sounds liek thats what this issue is most likely.

**Comment by Cilraaz** [comment]
Shadowflame Prism is included in five lines in the APL. One out of the five refers to Shadow Word: Death. That condition is "shadow_word_death,target_if=(target.health.pct<20&spell_targets.mind_sear<4)|(pet.fiend.active&runeforge.shadowflame_prism.equipped)", which means at this point it'll suggest SW:D if the target is under 20% health while fighting less than 4 enemies or if your Mindbender is active while wearing Shadowflame Prism.

I double checked the implementation within HeroRotation. It appears to be correct. Unfortunately, I don't have the Shadowflame Prism legendary to test. I currently have Talbadar and Eternal Call to the Void. However, running a sim with Shadowflame Prism shows very few casts. In the sim, there were eight casts of SW:D, with two being during opening Bloodlust, one during normal combat, and the remaining five with the boss at sub-20%.

As I said, I don't have the legendary (and, frankly, don't play my Shadow Priest very often any longer), but it _appears_ to be working as intended.
