### ISSUE TITLE
[Assassination Rogue] Poisoned Knife suggested while in melee range

### ISSUE THREAD

**Issue by TatsumaZangarmarsh** [herotc/hero-rotation#756]
The addon keeps suggesting Poisoned Knife, our throw ability, in my rotation when I am still in melee range. I have tried turning off all other addons except for HeroRotation, but the issue does not go away. Would there be a way to either fix this, or add a check box to remove that ability from the rotation?

Thanks!

**Comment by TatsumaZangarmarsh** [comment]
Debug mode below. I believe it replaces multiple abilities. I have seen it pop up when I have zero combo points and should be mutilating, and also when I have full combo points and should be applying rupture or using envenom.

![image](https://user-images.githubusercontent.com/83601802/116904491-9d094d80-abf2-11eb-90b8-3d10060b2f0d.png)

**Comment by Cilraaz** [comment]
It appears this was only an issue when AoE was disabled. This is fixed in commit https://github.com/herotc/hero-rotation/commit/e4e4ac8539a9563ad6f5581f615db63200a9900a

**Comment by TatsumaZangarmarsh** [comment]
Thank you!!
