### ISSUE TITLE
[Feral Druid] Feral Frenzy Lua Error

### ISSUE THREAD

**Issue by BelakJG** [herotc/hero-rotation#758]
When taking Feral frenzy it will cause a lot of Lua errors and not suggest any spells.
Here's the errors given:
12x HeroRotation_Druid\Feral.lua:260: attempt to compare nil with number
[string "@HeroRotation_Druid\Feral.lua"]:260: in function `Condition'
[string "@HeroRotation\Commons.lua"]:78: in function `CastTargetIf'
[string "@HeroRotation_Druid\Feral.lua"]:402: in function <HeroRotation_Druid\Feral.lua:395>
[string "@HeroRotation_Druid\Feral.lua"]:573: in function `?'
[string "@HeroRotation\Main.lua"]:446: in function <HeroRotation\Main.lua:424>

**Comment by Cilraaz** [comment]
There was a typo in a variable name. That should be fixed as of commit https://github.com/herotc/hero-rotation/commit/e0503d96b58beb78ecf221a90b1bada1d0506b2a
