### ISSUE TITLE
dh hero rotation

### ISSUE THREAD

**Issue by ayanokoji-wdh** [herotc/hero-rotation#759]
Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
Time: Tue May 11 14:17:43 2021
Count: 759
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
[string "=[C]"]: in function `TrinketHasStatAnyDps'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:148: in function <Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:141>
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:390: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:446: in function <Interface\AddOns\HeroRotation\Main.lua:424>

**Comment by Cilraaz** [comment]
Please update your version of HeroLib. I assume you're updating from CurseForge, which is 2 months out of date at this point. Please use version 9.0.5.05, found [here](https://github.com/herotc/hero-lib/releases/download/9.0.5.05/HeroLib-9.0.5.05.zip).
