### ISSUE TITLE
Afflicion warlock - blood fury racial not recommended

### ISSUE THREAD

**Issue by MrSmurfy** [herotc/hero-rotation#762]
Using the affliction warlock rotation the blood fury racial is not being recommended.
Any thoughts?

**Comment by Cilraaz** [comment]
Blood Fury is suggested during both the Darkglare Prep phase and any time trinkets are suggested.

**Comment by MrSmurfy** [comment]
Hi Cilraaz, I know it should be suggesting it but it isn't suggesting blood fury at all for me.
I use these settings so I'd expect it to show up as a main icon;
https://i.imgur.com/nVmnpXj.png

Let me know if I should provide anything else.

**Comment by Cilraaz** [comment]
This should be fixed as of commit https://github.com/herotc/hero-rotation/commit/f680acd9542ace6dd4f1d0cb93d13a006d5550b5

It looks like Blood Fury was using an incorrect spell ID.
