### ISSUE TITLE
[Hunter] Survival error despite being in different spec

### ISSUE THREAD

**Issue by RavenDT** [herotc/hero-rotation#763]
Receiving the following Lua error, despite the fact that my character is Beast Master spec:
```
Message: Interface\AddOns\HeroRotation_Hunter\Survival.lua:140: function arguments expected near 'and'
Time: Fri May 28 18:30:54 2021
Count: 4
Stack: Interface\AddOns\HeroRotation_Hunter\Survival.lua:140: function arguments expected near 'and'

Locals: <none>
```

This occurs upon initial UI load, but doesn't seem to reappear and Beast Mastery rotation appears to work just fine.

**Comment by Cilraaz** [comment]
This was already fixed in previous commit https://github.com/herotc/hero-rotation/commit/08ee779b1f75fb785eda1f502062a8c3c120b37b

Either grab the new file from github, make the change to the file manually, or it will be updated in the next release (which I'll probably push tonight).
