### ISSUE TITLE
Affliciton Warlock - Permanently Suggesting Drain Life

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#764]
After applying dots, the addon seems to just permanently suggest drain soul

**Comment by GarrettCottrell** [comment]
Ah, I'm leveling and don't have shadow embrace, so most likely it's trying to cast drain soul to stack shadow embrace but since I don't have the passive, it's just permanently looping to try and get the stacks buty can't.

Does this sound like it could be the issue?

**Comment by Cilraaz** [comment]
That's absolutely the issue. The addon tries to build SE stacks. Since you can't, it doesn't know what to do.
