### ISSUE TITLE
[RET] PVP +  Final Verdict

### ISSUE THREAD

**Issue by fistenyolo** [herotc/hero-rotation#765]
Hello,

First and foremost I would like to thank the devs that run this add on it's wonderful!!

I'd like to point out that Final Verdict is not working and only shows POOL. It needs to be a top priority when 3 holy power or more is achieved. 
I've attached a Screenshot of Final Verdict not popping up at all once the Legendary is Equipt, I can confirm that Templars Verdict does pop up, but again not made a priority when you have 3 or more Holy Power.

Also, is there a way to remove Divine Storm in PVP,  maybe in the Hero Rotation interface in-game checkbox under Retribution?
DS being a priority with 3 or more mobs(PVE) is correct, however in PVP when trying to nuke one guy, you want either Templar's Verdict or Final Verdict to pop up.

Please PM me for a once complete. 

Thank you,

Fisten

![RET](https://user-images.githubusercontent.com/85357819/120826777-a5191d80-c50f-11eb-98f7-8f64f5f04e3a.png)

**Comment by Cilraaz** [comment]
The profile has been re-written for 9.2 launch. There was previously an issue with FV/TV being skipped if cooldowns were not used as suggested, as spells like Crusade/Execution Sentence/etc being on cooldown were pre-requisites of use. That issue may or may not be resolved with the re-write. If it's not, please let us know.

As far as removing Divine Storm, you can disable AoE suggestions, which should mean it no longer suggests Divine Storm or any other AoE abilities.

**Comment by Atlentys** [comment]
Hello,
Problem not solved final verdict not showing at all in rotation instead writing pool or consecration even with all cd up
Add on even select crusader strike when we have 5 holy power

**Comment by Cilraaz** [comment]
It looks like Simulationcraft replaces Templar's Verdict with Final Verdict behind the scenes, rather than in the APL. I hadn't taken that into account. I've added the substitution in HeroRotation now. Please let me know if it is working after commit https://github.com/herotc/hero-rotation/commit/4579cdcf939a83d5d2d55982c3dc44a132faed0f

**Comment by Atlentys** [comment]
I copy the 2 new files and replace the old ones manually cause it seems curse software have not put automatic update yet
When loging paladin it said no rotation supported for this class spe add on disabled

**Comment by Cilraaz** [comment]
There was a typo in the file. This has been fixed as of commit https://github.com/herotc/hero-rotation/commit/6e78ee608e0b3134f73e8693429908983458c61f

Please copy the latest Retribution.lua and try it again.

**Comment by Atlentys** [comment]
same no rotation find for this spe
maybe i do it incorectly but i reinstalled all package to have a clean set up then i opened in blockpad retribution.lua and clik copy raw content here then save it and close

**Comment by Cilraaz** [comment]
I pushed version 9.2.0.03. It should show up on Curse soon and will include the updates.

**Comment by Atlentys** [comment]
i installed clean one from curse still not working

**Comment by Cilraaz** [comment]
Not working in what way? Just Final Verdict/Templar's Verdict or are you still getting the no rotation error?

**Comment by Atlentys** [comment]
Just Final verdict not showing,  i tested without legendary and templar verdict is showing perfectly

**Comment by Cilraaz** [comment]
Does your UI of choice allow you to see spell IDs? Unfortunately, I don't have a level 60 paladin to test, so I can't be sure that I have the correct spell ID for Final Verdict.

**Comment by Atlentys** [comment]
According to wowhead spell=337247

**Comment by Cilraaz** [comment]
337247 is the spell ID of the legendary, which may or may not be the same as the resulting ability on the bar. There's also 336872 (which appears to be the HoW proc associated with FV) and 337228. To confirm, with the legendary equipped, can you please type the following in-game: `HeroLib.Spell(337247):IsAvailable()` and press enter (capitalization does matter). If this returns true, then we can confirm that it is indeed the spell ID being used for the on-bar ability. If you could do the same for all three spell IDs, that would be very helpful. Thank you!

**Comment by Atlentys** [comment]
I try with 337247 336872 337228 with HeroLib.Spell(337247):IsAvailable() and nothing happens
And thx to you for taking care of this you're doing an amazing work with this add on

**Comment by Atlentys** [comment]
![Sans titre1](https://user-images.githubusercontent.com/82400978/156025946-d7de8a18-069f-40dd-84ce-bea5079abe3c.png)

**Comment by Cilraaz** [comment]
I must have not been fully awake when I typed that up. The command would be `/dump HeroLib.Spell(337247):IsAvailable()`. Sorry about that.

**Comment by Atlentys** [comment]
337247 false
336872 false
337228 false

**Comment by Cilraaz** [comment]
Hmm, so somehow it's none of them? Just to verify, this was done with the Final Verdict legendary equipped? Also, can you double check 336872? According to the spell data from wowhead, it looks like that's the ID that's supposed to replace TV on the bar. I might have to finish leveling my paladin to get this sorted out.

There's always at least one oddity when it comes to Blizzard programming...

**Comment by Atlentys** [comment]
Yes i checked i had the legendary equip and the spell final verdict in my bar and i double check everything

**Comment by Cilraaz** [comment]
One other thing we can try is open your spell book, type `/dump "`, then shift-click Final Verdict which should create a link for the spell in chat, add another quotation mark at the end, and press enter. This will return a string similar to this (which is from Enh Shaman's Stormstrike):

`|Cff71d5ff|Hspell:17364:0|h[Stormstrike]|h|r` where 17364 is the spell ID.

Perhaps that will work for us? Thank you for being willing to do this testing for us!

**Comment by Atlentys** [comment]
![Sans titre](https://user-images.githubusercontent.com/82400978/156063669-71a53f3d-6c96-47a0-ac1d-8d646e0e4b5a.png)

I don't understand when i do /dump HeroLib.Spell(336872):IsAvailable() answer is false
I'm very glad if i can help i have all lego and all char lvl 60

**Comment by Cilraaz** [comment]
Can you try again with the latest Retribution.lua file after commit https://github.com/herotc/hero-rotation/commit/33b9ddf08f7062e1900aa7013ad7ecbf53583a79 ? We tried a different workaround.

If you wanted to download the entire addon package, the latest files can be found [here](https://github.com/herotc/hero-rotation/archive/refs/heads/shadowlands.zip)

**Comment by Atlentys** [comment]
It's working ! Gl man you're good
Last problem is : 
Empyrean power talent row 2 is selected addon never see the proc and never display divine storm
Add on doesn't show Divine toll kiryan covenant even if i put main icon/suggested/suggested right

**Comment by Cilraaz** [comment]
Try the latest files again. This should be fixed in commit https://github.com/herotc/hero-rotation/commit/81639aa340b01b9e92698a63bc65f1c1f415140c

For Divine Toll, it should be suggested if either Execution Sentence or Final Reckoning are active on the target while you have 2 or fewer holy power or if...
- You have 0 or 1 holy power AND
- The target does not have the Judgment debuff AND
- Seraphim is active on the target (or that talent is not selected) AND
- Final Reckoning talent is not selected AND
- Execution Sentence talent is not selected or the fight is about to end or there are 5+ targets AND
- Avenging Wrath or Crusade are on cooldown

The APL is very specific about the use condition for Divine Toll.
