### ISSUE TITLE
[Feral] - Should Tiger's Fury be on CDs

### ISSUE THREAD

**Issue by Darkmoded** [herotc/hero-rotation#766]
Tiger's Fury has a 30 sec cool down and a instant Reset when talented  Predator

Not a bug but I don't think Tiger's Fury's should be off the CDs

**Comment by Cilraaz** [comment]
Tiger's Fury is part of the cooldown function/APL list. The entire function is only checked if CDs are enabled. Rather than complicating the code to exclude Tiger's Fury, it was decided to treat it as a CD ability.
