### ISSUE TITLE
Mage - Arcane - attempt to index field 'Fire' (a nil value)

### ISSUE THREAD

**Issue by RavenDT** [herotc/hero-rotation#767]
Message: Interface\AddOns\HeroRotation_Mage\Arcane.lua:1173: attempt to index field 'Fire' (a nil value)
Time: Sat Jun 12 14:34:59 2021
Count: 71
Stack: Interface\AddOns\HeroRotation_Mage\Arcane.lua:1173: attempt to index field 'Fire' (a nil value)

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/335f53bf0cbdde642361bb18072684a279cbdce9
