### ISSUE TITLE
Demon Hunter - Havoc: LUA Errors on Target

### ISSUE THREAD

**Issue by Denixerianer** [herotc/hero-rotation#768]
When i target something while out of combat as havoc i get error messages which stack really fast like 100 in 10 seconds. The errors are gone once im in combat:

Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
Time: Fri Jun 18 23:07:42 2021
Count: 186
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:148: in function <Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:141>
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:390: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:447: in function <Interface\AddOns\HeroRotation\Main.lua:425>

Locals: (*temporary) = nil
(*temporary) = <table> {
 ItemName = "Brand of the Banshee Queen"
 ItemSlotIDs = <table> {
 }
 LastCastTime = 0
 ItemRarity = 3
 ItemMinLevel = 0
 ItemID = 129104
 ItemLevel = 44
 LastDisplayTime = 0
 LastHitTime = 0
}
(*temporary) = "attempt to call method 'TrinketHasStatAnyDps' (a nil value)"
trinket1 = <table> {
 ItemName = "Brand of the Banshee Queen"
 ItemSlotIDs = <table> {
 }
 LastCastTime = 0
 ItemRarity = 3
 ItemMinLevel = 0
 ItemID = 129104
 ItemLevel = 44
 LastDisplayTime = 0
 LastHitTime = 0
}
trinket2 = <table> {
 ItemName = "Harlan's Loaded Dice"
 ItemSlotIDs = <table> {
 }
 LastCastTime = 0
 ItemRarity = 3
 ItemMinLevel = 0
 ItemID = 155881
 ItemLevel = 59
 LastDisplayTime = 0
 LastHitTime = 0
}
VarTrinketSyncSlot = 0
VarUseEyeBeamFuryCondition = false
S = <table> {
 ThrowGlaive = <table> {
 }
 FirstBlood = <table> {
 }
 FelBarrage = <table> {
 }
 ImmolationAuraBuff = <table> {
 }
 EssenceBreak = <table> {
 }
 FuriousGazeBuff = <table> {
 }
 FelRush = <table> {
 }
 CycleofHatred = <table> {
 }
 MomentumBuff = <table> {
 }
 EyeBeam = <table> {
 }
 MetamorphosisBuff = <table> {
 }
 BladeDance = <table> {
 }
 EssenceBreakDebuff = <table> {
 }
 UnboundChaos = <table> {
 }
 UnboundChaosBuff = <table> {
 }
 FelEruption = <table> {
 }
 ChaosStrike = <table> {
 }
 Blur = <table> {
 }
 DemonBlades = <table> {
 }
 DemonsBite = <table> {
 }
 DeathSweep = <table> {
 }
 Metamorphosis = <table> {
 }
 SinfulBrandDebuff = <table> {
 }
 ExposedWoundDebuff = <table> {
 }
 BurningWoundDebuff = <table> {
 }
 PreparedBuff = <table> {
 }
 ChaosTheoryBuff = <table> {
 }
 SinfulBrand = <table> {
 }
 GlaiveTempest = <table> {
 }
 ChaosNova = <table> {
 }
 Demonic = <table> {
 }
 Disrupt = <table> {
 }
 Felblade = <table> {
 }
 TheHunt = <table> {
 }
 SerratedGlaive = <table> {
 }
 Annihilation = <table> {
 }
 ElysianDecree = <table> {
 }
 TrailofRuin = <table> {
 }
 BlindFury = <table> {
 }
 FelBombardmentBuff = <table> {
 }
 Momentum = <table> {
 }
 ImmolationAura = <table> {
 }
 VengefulRetreat = <table> {
 }
}
DarkglareEquipped = false
Target = <table> {
 UnitExists = true
 UnitName = "Felsoul Fleshcarver"
 UnitNPCID = 95329
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
 UnitGUID = "Creature-0-3111-1498-29253-95329-00004D09B2"
}
Cast = <function> defined @Interface\AddOns\HeroRotation\Core.lua:132

**Comment by Cilraaz** [comment]
What version of HeroLib are you using? The TrinketHasStatAnyDps function was added in version 9.0.5.03.

**Comment by Denixerianer** [comment]
i use the curseforge app and the newest version there seems to be "HeroLib-9.0.5.01". Where can i download the newer version? Thx for the fast reply :D

**Comment by Cilraaz** [comment]
You can download it from the github releases. Here's the zip for the latest version: [9.0.5.05](https://github.com/herotc/hero-lib/releases/download/9.0.5.05/HeroLib-9.0.5.05.zip)

**Comment by Denixerianer** [comment]
Thanks i downloaded everything from here now. One more question: Do i need to move files like "License" or ".gitignore" also into the addons folder or just the folders? Thanks

**Comment by Cilraaz** [comment]
Just the folders.

**Comment by Denixerianer** [comment]
what folders go in from dbc

**Comment by Cilraaz** [comment]
HeroDBC is an oddity because of how it's structured. Everything inside the "addon" folder on the github will get placed in the HeroDBC folder in your Interface\Addons.

**Comment by Denixerianer** [comment]
alrighty did that and now it works thx for the help, sorry for the wrong bug report feel free to delete it (idk how to) :)
Just as friendly feedback: Maybe add install description on how to do it i would have never figured that out on my own love your addon tho <3

**Comment by Cilraaz** [comment]
No worries. Glad it's working now!
