### ISSUE TITLE
Demon Hunter - Havoc

### ISSUE THREAD

**Issue by MrCyphyr** [herotc/hero-rotation#769]
Getting repeated LUA message warnings.  Bug Sack has: 

1559x HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
[string "@HeroRotation_DemonHunter\Havoc.lua"]:148: in function <HeroRotation_DemonHunter\Havoc.lua:141>
[string "@HeroRotation_DemonHunter\Havoc.lua"]:390: in function `?'
[string "@HeroRotation\Main.lua"]:447: in function <HeroRotation\Main.lua:425>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 ItemName = "Darkmoon Deck: Voracity"
 ItemSlotIDs = <table> {
 }
 LastCastTime = 0
 ItemRarity = 4
 ItemMinLevel = 60
 ItemID = 173087
 ItemLevel = 200
 LastDisplayTime = 0
 LastHitTime = 0
}
(*temporary) = "attempt to call method 'TrinketHasStatAnyDps' (a nil value)"
trinket1 = <table> {
 ItemName = "Darkmoon Deck: Voracity"
 ItemSlotIDs = <table> {
 }
 LastCastTime = 0
 ItemRarity = 4
 ItemMinLevel = 60
 ItemID = 173087
 ItemLevel = 200
 LastDisplayTime = 0
 LastHitTime = 0
}
trinket2 = <table> {
 ItemName = "Memory of Past Sins"
 ItemSlotIDs = <table> {
 }
 LastCastTime = 0
 ItemRarity = 4
 ItemMinLevel = 60
 ItemID = 184025
 ItemLevel = 200
 LastDisplayTime = 0
 LastHitTime = 0
}
VarTrinketSyncSlot = 0
VarUseEyeBeamFuryCondition = false
S = <table> {
 ThrowGlaive = <table> {
 }
 FirstBlood = <table> {
 }
 FelBarrage = <table> {
 }
 ImmolationAuraBuff = <table> {
 }
 EssenceBreak = <table> {
 }
 FuriousGazeBuff = <table> {
 }
 FelRush = <table> {
 }
 CycleofHatred = <table> {
 }
 MomentumBuff = <table> {
 }
 EyeBeam = <table> {
 }
 MetamorphosisBuff = <table> {
 }
 BladeDance = <table> {
 }
 EssenceBreakDebuff = <table> {
 }
 UnboundChaos = <table> {
 }
 UnboundChaosBuff = <table> {
 }
 FelEruption = <table> {
 }
 ChaosStrike = <table> {
 }
 Blur = <table> {
 }
 DemonBlades = <table> {
 }
 DemonsBite = <table> {
 }
 DeathSweep = <table> {
 }
 Metamorphosis = <table> {
 }
 SinfulBrandDebuff = <table> {
 }
 ExposedWoundDebuff = <table> {
 }
 BurningWoundDebuff = <table> {
 }
 PreparedBuff = <table> {
 }
 ChaosTheoryBuff = <table> {
 }
 SinfulBrand = <table> {
 }
 GlaiveTempest = <table> {
 }
 ChaosNova = <table> {
 }
 Demonic = <table> {
 }
 Disrupt = <table> {
 }
 Felblade = <table> {
 }
 TheHunt = <table> {
 }
 SerratedGlaive = <table> {
 }
 Annihilation = <table> {
 }
 ElysianDecree = <table> {
 }
 TrailofRuin = <table> {
 }
 BlindFury = <table> {
 }
 FelBombardmentBuff = <table> {
 }
 Momentum = <table> {
 }
 ImmolationAura = <table> {
 }
 VengefulRetreat = <table> {
 }
}
DarkglareEquipped = false
Target = <table> {
 UnitExists = true
 UnitName = "Boneweave Ambusher"
 UnitNPCID = 159737
 UnitGUID = "Creature-0-4217-2222-1184-159737-00004F8C26"
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
}
Cast = <function> defined @HeroRotation\Core.lua:132

**Comment by Cilraaz** [comment]
Update your version of HeroLib. CurseForge is out of date. 9.0.5.05 can be found [here](https://github.com/herotc/hero-lib/releases/download/9.0.5.05/HeroLib-9.0.5.05.zip)

**Comment by MrCyphyr** [comment]
Thanks!!!



Chuck


Charles J. Armstrong

Londonderry, NH 03053

603-965-4501 (Home)

614-270-6336 (Mobile/Cell)

(Sent from home MS Outlook)

________________________________
