### ISSUE TITLE
Havoc Demon Hunter Not Working

### ISSUE THREAD

**Issue by Verimir** [herotc/hero-rotation#771]
I get a lua error every time I right click a target. every other class works fine but the DH just won't cooperate

**Comment by Verimir** [comment]
I also use elv.ui but idk what that would have to do with it

**Comment by Cilraaz** [comment]
Update HeroLib to the latest version. 9.0.5.05 is available [here](https://github.com/herotc/hero-lib/releases/download/9.0.5.05/HeroLib-9.0.5.05.zip)
