### ISSUE TITLE
[FROST DK] AOE issues

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#772]
Rotation keeps getting stuck on pooling during AOE situations, and wants me to constantly swap target for it to trigger next ability on main icon. Would love to get a fix on this, since it ruins most of the Aoe rotation. using talents: 1-2-1-1-1-1-2

**Comment by Cilraaz** [comment]
Frost DK's rotation wants you to change targets based on Razor Ice stacks, as per the Simc APL. This is intended.

**Comment by azzi1103** [comment]
Well in highscale AOE, it's impossible. The Addon wants to target on specific mob to continue to next icon. That's really hard in M+ when there are big pulls.

**Comment by azzi1103** [comment]
The main icon should continue as normal and we have a 2nd suggestion icon already suggesting what we should do to maximize our AOE dmg. It's pointless to have main icon frozen mate.

**Comment by Cilraaz** [comment]
That's not how the addon works. The logic of the main icon is tied to the other icons. When a CastTargetIf is used (as is the case for a lot of the abilities in Frost DK), the main icon and left icon are tied together. If the current target is the selected target, the icon shows in the main icon slot. If another target is suggested, it shows in the left icon slot.

**Comment by azzi1103** [comment]
The rogue rotation literally puts main rotation in big icon, whilst we have "rupture" and AOE solutions on the left. And of course we have the icons on top of their nameplates too. And again if a rotation is gonna be stuck untill you target that 1 mob in 20 other mobs. It's not really gonna help much is it?
