### ISSUE TITLE
Shadow Priest - lua error

### ISSUE THREAD

**Issue by imarkvisser** [herotc/hero-rotation#775]
Hello,

I'm not sure if Shadow Priest is supported but I get the following lua error;
![image](https://user-images.githubusercontent.com/85161590/126052074-a22b6c9d-b812-4ab8-8def-e937dd8eb488.png)

Any thoughts on what causes this?

**Comment by Cilraaz** [comment]
That's a typo. It's been fixed in commit https://github.com/herotc/hero-rotation/commit/886e2ca3e9fce3900cbc0b2eeeb3954fb0632127

**Comment by imarkvisser** [comment]
Thanks for the quick reply!
