### ISSUE TITLE
DemonHunter Havoc Lua-Error

### ISSUE THREAD

**Issue by Hexus-Proud** [herotc/hero-rotation#776]
Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
Time: Thu Jul 22 14:02:29 2021
Count: 174
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
[string "=[C]"]: in function `TrinketHasStatAnyDps'
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:148: in function <Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:141>
[string "@Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua"]:390: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\Main.lua:427>

Locals:

**Comment by Kutikuti** [comment]
see https://github.com/herotc/hero-rotation/issues/769
