### ISSUE TITLE
Brewmaster

### ISSUE THREAD

**Issue by madmons** [herotc/hero-rotation#781]
Hey,

whatever options are selected, Celstial Infusion always appears in the main Icon. Is it a bug or is it possible to see it in one of the small icons ?

Thanks

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/945702f50a94ad55357e352d250c756e192f762f

**Comment by madmons** [comment]
Great ! Thanks
