### ISSUE TITLE
Celestial Brew not obeying off-gcd (despite updating addon on curseforge 5 minutes ago)

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#783]
I posted this issue earlier and it was immediately closed and told to update addon. Addon has been updated via curseforge (5 mins ago) and the exact issue persists.

**Comment by GarrettCottrell** [comment]
Is there another way of updating the addon that would include the fix to this solution? Maybe it just hasn't been pushed to curseforge yet? I just don't know another way of updating other than via curseforge.

I have release type as alpha on curseforge. I have a feeling this is just an issue of me not having the right update because this issue has been addressed. I just can't get the version I have to update to include the fix

**Comment by Kutikuti** [comment]
The update was only available on github at the time.
I just made a new release, you should be able to update the addon in the next few minutes when cureseforge releases it
