### ISSUE TITLE
{Guardian Druid} - Option to disable "Use" on weapon

### ISSUE THREAD

**Issue by agr8lemon** [herotc/hero-rotation#785]
I have the polearm, Jotungeirr, Destiny's Call, which has a clickable use much like a trinket. I'd like to ability to remove this from the main rotation, much like  a trinket. I've disabled all trinket options, but that does not affect this item.

**Comment by Kutikuti** [comment]
Should be good with this commit : https://github.com/herotc/hero-rotation/commit/a2014a7f278d95b2eabbd30054f6f891d9039ec0

There is now a new option for Item display style. I don't have the weapon myself to test this. Could you confirm it works fine ?

**Comment by agr8lemon** [comment]
I see the Display Style: Items option. I currently have it set to Suggested. I don't see the weapon use come up at all now (which is OK in my case), but may not be the desired effect for others. I'll do some more testing tonight. Thanks for the response on this.

**Comment by Kutikuti** [comment]
If you selected "Suggested" it should show up on the upper left corner. 
Can you try again after reloading the game (or if you closed the game it should show up now)? I just saw that the first time a new setting is introduced, you have to reload the game for it to be taken into consideration.

**Comment by agr8lemon** [comment]
You are correct, it is working correctly now.

Thank you again!
