### ISSUE TITLE
Trinkets (Havoc DH)

### ISSUE THREAD

**Issue by chrisjk007** [herotc/hero-rotation#786]
The TrinketHasStatAnyDps() doesn't seem to be defined or when player has two non-usable trinkets like Phial of Putrefaction and Infinitely Divisible Ooze, it throws errors.
I commented out the lines in precombat  area in Havoc.lua to bypass this check for now.

When player has Bottle Flayedwing Toxin, it checks if trinket isReady() which causes it to recommend reapplying the buff every 30 secs instead of checking if the Flayedwing Toxin buff is still active. ( i have it active in slot 2 so i only check there)
to bypass this i created a variable
local FlayedwingToxinBuff = Spell(345545)
and added this check in precombat and again in rotation
trinket2:IsReady() and not Player:BuffUp(FlayedwingToxinBuff, nil, true) and ..

I hope this helps.

**Comment by Cilraaz** [comment]
Update to the latest HeroLib version, found [here](https://github.com/herotc/hero-lib/releases/download/9.1.0.05/HeroLib-9.1.0.05.zip). CurseForge is woefully out of date due to an issue with their system that we've been trying to get fixed for months.
