### ISSUE TITLE
Havoc Issue

### ISSUE THREAD

**Issue by Wigglefox** [herotc/hero-rotation#788]
Every time I target a hostile npc that is not in combat I get an LUI error:

          Message: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)
Time: Tue Aug 31 18:57:16 2021
Count: 332
Stack: Interface\AddOns\HeroRotation_DemonHunter\Havoc.lua:148: attempt to call method 'TrinketHasStatAnyDps' (a nil value)

Locals: 

Addon is up to date, I even tried taking my trinkets off and trying it and got the same result.

**Comment by Cilraaz** [comment]
Update your version of HeroLib. The version on CurseForge is out of date. https://github.com/herotc/hero-lib/releases/download/9.1.0.05/HeroLib-9.1.0.05.zip
