### ISSUE TITLE
[Druid Balance] CD usage

### ISSUE THREAD

**Issue by Zekke** [herotc/hero-rotation#795]
Addon keeps suggesting usage of covenant ability (only tested NF's Convoke the Spirits), racial (trolls' Berserking) and trinkets while CDs are off.

**Comment by Cilraaz** [comment]
Covenant abilities are considered rotational and are not subject to the CD toggle.
Racials (Berserking is actually the only racial currently in the APL) already check against the CD toggles.
Trinkets have their own setting if you'd like to turn them off.

**Comment by Zekke** [comment]
Is it possible to considere covenant abilities as CDs like it does in the feral rotation (or all other classes and spec I've tried) ?

**Comment by Cilraaz** [comment]
Added the CD check for Ravenous Frenzy and Convoke in commit https://github.com/herotc/hero-rotation/commit/4cd2b0d0e7b279a23d9038da229a7ce9785a4acb
