### ISSUE TITLE
[Balance Druid] attempt to call method 'BaseDuration' (a nil value)

### ISSUE THREAD

**Issue by BelakJG** [herotc/hero-rotation#796]
I'm getting two Lua errors right after the Balance opener.

79x HeroRotation_Druid\Balance-Balance.lua:558: attempt to call method 'BaseDuration' (a nil value)
[string "@HeroRotation_Druid\Balance-Balance.lua"]:558: in function <HeroRotation_Druid\Balance.lua:509>
[string "@HeroRotation_Druid\Balance-Balance.lua"]:853: in function `?'
[string "@HeroRotation\Main.lua"]:443: in function <HeroRotation\Main.lua:427>

11x HeroRotation_Druid\Balance-Balance.lua:431: attempt to call method 'BaseDuration' (a nil value)
[string "@HeroRotation_Druid\Balance-Balance.lua"]:431: in function <HeroRotation_Druid\Balance.lua:393>
[string "@HeroRotation_Druid\Balance-Balance.lua"]:861: in function `?'
[string "@HeroRotation\Main.lua"]:443: in function <HeroRotation\Main.lua:427>

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/6906975855deb24444307d0ecafb12d8bb4c2d5d
