### ISSUE TITLE
[Druid Balance] Sunfire glitch

### ISSUE THREAD

**Issue by Zekke** [herotc/hero-rotation#797]
When AOE is on, sunfire is suggested on targets who are not in combat which (I think) make a weird bug appears : the addon suggests spamming sunfire on the main target until we disable AOE.

It happens often in M+ and sometimes in raid encounter (even if it's a pure single target fight with absolutely no adds, maybe caused by the presence of trash mobs outside of the room).

I think the possible fix to this is to suggest multi dotting only on enemies that are in combat and/or check the radius of the sunfire spread.

**Comment by Cilraaz** [comment]
I'm unable to replicate this issue. Sunfire might be suggested on the left icon for targets within 40y that aren't in combat, but it should not be continually suggested for the main target. Could you please enable debug output and let me know what Sunfire cast is being repeatedly suggested?

**Comment by Zekke** [comment]
https://puu.sh/IhPc3/de4f9fb0a3.png

This screenshot is from the very first pack of MoTS +15 (fortified), and it happenned again multiple times during this dungeon.
As you can see, the addon stays blocked at "Sunfire aoe 7" despite the debuff is active on the target and on every close enemies in combat, it stops suggesting sunfire when I disable aoe but re-suggests it again if I enable it again.
Talents build : 3-3-3-1-1-2-2

I had the same issue on few encounters in SoD HM (I don't remember which one sadly).

**Comment by Cilraaz** [comment]
Sunfire aoe 7 is a line that suggests Sunfire in coordination with the use of the Inscrutable Quantum Device while CA/Inc is active. Are you delaying use of the trinket? That's most likely what's stalling the profile.

Toggling AoE likely doesn't actually affect anything, but rather buys enough time for your CA/Inc buff to fall below 15 seconds remaining, which causes the variable checked to become false.

**Comment by Zekke** [comment]
Yes I delay it, i use IQD with CA/Inc and racial in a macro. CA wasn't active at this time.

Edit: I was probably under the CA proc of my legendary (Primordial Arcanic Pulsar), is it possible to check if CA is in cooldown in this case ?

**Comment by Cilraaz** [comment]
Sunfire aoe 7 will be suggested if IQD is equipped and ready to be used and a variable is set to true. That variable requires:

- CA/Inc buff has >15 seconds remaining and any one of the following:

- Sinful Hysteria not equipped OR Ravenous Frenzy buff time remaining is under a certain amount
- The calculated remaining length of time of the fight is less than 25 seconds
- Empyreal Ordinance is equipped and currently on CD

If you are delaying trinket usage, I would suggest disabling trinket suggestions (found within the Druid settings: Esc menu -> Interface -> AddOns -> HeroRotation -> Druid -> Show: Trinkets). This should bypass the issue after the latest update. I've added a check to sunfire aoe 7 that requires trinket suggestions to be enabled. This is in the latest commit, https://github.com/herotc/hero-rotation/commit/6f61f744f74a9d094a03a9e1d4462997966b96ff

**Comment by Cilraaz** [comment]
No further reports of issues after nearly a month. The profile has also been updated since. If this is still a problem, please feel free to reply here or open a new issue.
