### ISSUE TITLE
Brewmaster HeroRotation_Monk Bug

### ISSUE THREAD

**Issue by Hexus-Proud** [herotc/hero-rotation#799]
3393x HeroRotation_Monk\Brewmaster.lua:262: attempt to index field 'PustuleEruption' (a nil value)
[string "@HeroRotation_Monk\Brewmaster.lua"]:262: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 528957.557000
(*temporary) = 1
(*temporary) = -0.052000
(*temporary) = 0
(*temporary) = "attempt to index field 'PustuleEruption' (a nil value)"
Enemies5y = <table> {
 1 = <table> {
 }
}
Player = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:135
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:160
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @HeroLib\Class\Unit\Player\Main.lua:28
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:389
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:703
 Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:628
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Uni

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/eb3cc871bc0e100f59fd447e451fa0800af82ab1
