### ISSUE TITLE
Brewmaster HeroRotation_Monk Bug

### ISSUE THREAD

**Issue by Hexus-Proud** [herotc/hero-rotation#800]

**Comment by Hexus-Proud** [comment]
27x HeroRotation_Monk\Events.lua:107: attempt to index field '?' (a nil value)
[string "@HeroRotation_Monk\Events.lua"]:107: in function <HeroRotation_Monk\Events.lua:104>
[string "@HeroRotation_Monk\Events.lua"]:180: in function `Handler'
[string "@HeroLib\Events\Main.lua"]:235: in function <HeroLib\Events\Main.lua:231>
[string "@HeroLib\Events\Main.lua"]:278: in function `Handler'
[string "@HeroLib\Events\Main.lua"]:80: in function <HeroLib\Events\Main.lua:78>

Locals:
Amount = 140
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = <table> {
 1 = 16.302000
 2 = 11
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
IncomingDamage = <table> {
}
HL = <table> {
 RegisterForEvent = <function> defined @HeroLib\Events\Main.lua:46
 MAXIMUM = 40
 BossFilteredFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:371
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 Pulse = <function> defined @HeroLib\Main.lua:29
 PulseInitialized = true
 Item = <table> {
 }
 CacheHasBeenReset = false
 LiveRealm = <function> defined @HeroLib\Core.lua:34
 RegisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:133
 UnregisterForEvent = <function> defined @HeroLib\Events\Main.lua:62
 AddCoreOverride = <function> defined @HeroLib\Misc\Overrides.lua:26
 BetaRealm = <function> defined @HeroLib\Core.lua:44
 Spell = <table> {
 }
 BossFightRemainsIsNotValid = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:356
 GetInstanceInfo = <function> defined @HeroLib\Misc\ToSort.lua:37
 Action = <table> {
 }
 LoadRestores = <function> defined @HeroLib\Misc\Overrides.lua:42
 RegisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:148
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 0
 RecoveryTimer = <function> defined @HeroLib\Misc\ToSort.lua:116
 BMPullTime = <function> defined @HeroLib\Misc\ToSort.lua:87
 RegisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:88
 OutOfCombatTime = <function> defined @HeroLib\Misc\ToSort.lua:82
 UnregisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:177
 Latency = <function> defined @HeroLib\Misc\ToSort.lua:111
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 GetInstanceDifficulty = <function> defined @HeroLib\Misc\ToSort.lua:72
 LoadOverrides = <function> defined @HeroLib\Misc\Overrides.lua:48
 Print = <function> defined @HeroLib\Core.lua:49
 UnregisterAuraTracking = <function> defined @HeroLib\Events\Aura.lua:37
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @HeroLib\Core.lua:29
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @HeroLib\Misc\ToSort.lua:77
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 UnregisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:163
 BossFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:351
 FightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:319
 TTDRefresh = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:53
 RecoveryOffset = <function> defined @HeroLib\Misc\ToSort.lua:124
 FilteredFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:361
 CombatStarted = 530452.874000
 SpecID_ClassesSpecs = <table> {
 }
 RegisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:103
 UnregisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:205
 GUI = <table> {
 }
 UnregisterForPetCombatEvent = <function> defined @HeroLib\Events\Main.lua:191
 UnregisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:219
 Timer = <table> {
 }
 PTRRealm = <function> defined @HeroLib\Core.lua:39
 RegisterForPetCombatEvent = <function> defined @HeroLib\Events\Main.lua:118
 Debug = <function> defined @HeroLib\Core.lua:56
}
tableremove = <function> defined =[C]:-1
tableinsert =

**Comment by Cilraaz** [comment]
I made a change to try to fix this issue. Please try again with the changes from commit https://github.com/herotc/hero-rotation/commit/23464002b6da007d1fd8ada7ea6d5c1d3ad426e1

**Comment by Hexus-Proud** [comment]
Thank you for the fast answer. I try it and now I get this bug message:

5874x HeroRotation_Monk\Brewmaster.lua:262: attempt to index field 'PustuleEruption' (a nil value)
[string "@HeroRotation_Monk\Brewmaster.lua"]:262: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 528957.557000
(*temporary) = 1
(*temporary) = -0.052000
(*temporary) = 0
(*temporary) = "attempt to index field 'PustuleEruption' (a nil value)"
Enemies5y = <table> {
 1 = <table> {
 }
}
Player = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:135
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:160
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @HeroLib\Class\Unit\Player\Main.lua:28
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:389
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:703
 Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:628
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Uni

**Comment by Hexus-Proud** [comment]
I found it sorry. Everything seems to be working again. Thank you
