### ISSUE TITLE
HeroRotation_Monk Brewmaster 'VolatileSolvent' (a nil value)

### ISSUE THREAD

**Issue by Hexus-Proud** [herotc/hero-rotation#803]
24x HeroRotation_Monk\Brewmaster.lua:340: attempt to index field 'VolatileSolvent' (a nil value)
[string "@HeroRotation_Monk\Brewmaster.lua"]:340: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'VolatileSolvent' (a nil value)"
Enemies5y = <table> {
 1 = <table> {
 }
}
Player = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:135
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:160
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @HeroLib\Class\Unit\Player\Main.lua:28
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:389
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:703
 Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:628
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Unit\Player\Pow

----------------------------------------------------------------------------------------------------------

4x HeroRotation_Monk\Events.lua:108: attempt to index field '?' (a nil value)
[string "@HeroRotation_Monk\Events.lua"]:108: in function <HeroRotation_Monk\Events.lua:106>
[string "@HeroRotation_Monk\Events.lua"]:174: in function `Handler'
[string "@HeroLib\Events\Main.lua"]:235: in function <HeroLib\Events\Main.lua:231>
[string "@HeroLib\Events\Main.lua"]:278: in function `Handler'
[string "@HeroLib\Events\Main.lua"]:80: in function <HeroLib\Events\Main.lua:78>

Locals:
Amount = 375
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = <table> {
 1 = 54304.394000
 2 = 449
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
IncomingDamage = <table> {
}
GetTime = <function> defined =[C]:-1
tableremove = <function> defined =[C]:-1
tableinsert = <function> defined =[C]:-1

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/4fde4c3231c6127858a5a9f49bb1cd2fba39e007

**Comment by Hexus-Proud** [comment]
Thank you, the first part is working but the other one not:

1x HeroRotation_Monk\Events.lua:108: attempt to index field '?' (a nil value)
[string "@HeroRotation_Monk\Events.lua"]:108: in function <HeroRotation_Monk\Events.lua:106>
[string "@HeroRotation_Monk\Events.lua"]:174: in function `Handler'
[string "@HeroLib\Events\Main.lua"]:235: in function <HeroLib\Events\Main.lua:231>
[string "@HeroLib\Events\Main.lua"]:278: in function `Handler'
[string "@HeroLib\Events\Main.lua"]:80: in function <HeroLib\Events\Main.lua:78>

Locals:
Amount = 372
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = <table> {
 1 = 139951.293000
 2 = 36
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
IncomingDamage = <table> {
}
GetTime = <function> defined =[C]:-1
tableremove = <function> defined =[C]:-1
tableinsert = <function> defined =[C]:-1
