### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Oep55** [herotc/hero-rotation#804]
Please let me know if this is the wrong place to seek out help for this type of error. I only get this error in one spec (Brewmaster). Can you point me in the right direction to fix?
I done clean install have the proper dependencies. I have tried everything I can think of. 

Message: Interface\AddOns\HeroRotation\Core.lua:48: attempt to index local 'Object' (a nil value)
Time: Fri Nov 19 22:25:58 2021
Count: 515
Stack: Interface\AddOns\HeroRotation\Core.lua:48: attempt to index local 'Object' (a nil value)
[string "@Interface\AddOns\HeroRotation\Core.lua"]:48: in function `GetTexture'
[string "@Interface\AddOns\HeroRotation\Core.lua"]:133: in function <Interface\AddOns\HeroRotation\Core.lua:132>
[string "@Interface\AddOns\HeroRotation_Monk\Brewmaster.lua"]:197: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\Main.lua:427>

Locals: Object = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Object' (a nil value)"
Cache = <table> {
 GUIDInfo = <table> {
 }
 Set = <function> defined @Interface\AddOns\HeroCache\Main.lua:269
 APLVar = <table> {
 }
 Enemies = <table> {
 }
 Get = <function> defined @Interface\AddOns\HeroCache\Main.lua:253
 HasBeenReset = true
 SpellInfo = <table> {
 }
 UnitInfo = <table> {
 }
 MiscInfo = <table> {
 }
 Persistent = <table> {
 }
 ItemInfo = <table> {
 }
 Reset = <function> defined @Interface\AddOns\HeroCache\Main.lua:42
}
tostring = <function> defined =[C]:-1

**Comment by Cilraaz** [comment]
This is now fixed in commit https://github.com/herotc/hero-rotation/commit/19ae3e95b0a46e7a8ad79ab4f52277e6ab9bbbbf
