### ISSUE TITLE
Monk - Brewmaster - Lua error

### ISSUE THREAD

**Issue by Oep55** [herotc/hero-rotation#805]
If this is wrong place to post this error, please let me know. 
Thanks for you help.

Message: Interface\AddOns\HeroRotation_Monk\Events.lua:108: attempt to index field '?' (a nil value)
Time: Sat Nov 20 10:05:31 2021
Count: 1
Stack: Interface\AddOns\HeroRotation_Monk\Events.lua:108: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\HeroRotation_Monk\Events.lua"]:108: in function <Interface\AddOns\HeroRotation_Monk\Events.lua:106>
[string "@Interface\AddOns\HeroRotation_Monk\Events.lua"]:174: in function `Handler'
[string "@Interface\AddOns\HeroLib\Events\Main.lua"]:235: in function <Interface\AddOns\HeroLib\Events\Main.lua:231>
[string "@Interface\AddOns\HeroLib\Events\Main.lua"]:278: in function `Handler'
[string "@Interface\AddOns\HeroLib\Events\Main.lua"]:80: in function <Interface\AddOns\HeroLib\Events\Main.lua:78>

Locals: Amount = 492
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = <table> {
 1 = 2822.921000
 2 = 171
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
IncomingDamage = <table> {
}
GetTime = <function> defined =[C]:-1
tableremove = <function> defined =[C]:-1
tableinsert = <function> defined =[C]:-1

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/d834f54e7f1743d00fefd9fdf162f5306d2dc529
