### ISSUE TITLE
HeroRotation_Mage\Fire.lua error

### ISSUE THREAD

**Issue by Hexus-Proud** [herotc/hero-rotation#806]
I get this error:

366x HeroRotation_Mage\Fire.lua:353: attempt to compare number with nil
[string "@HeroRotation_Mage\Fire.lua"]:353: in function <HeroRotation_Mage\Fire.lua:349>
[string "@HeroRotation_Mage\Fire.lua"]:863: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
(*temporary) = 3.426000
(*temporary) = <function> defined @HeroRotation_Mage\Fire.lua:200
(*temporary) = 1
(*temporary) = nil
(*temporary) = false
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Flammenzuwachs"
 IsMelee = true
 SpellType = "Player"
 MaximumRange = 0
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 337224
}
(*temporary) = "attempt to compare number with nil"
var_combustion_ready_time = 0
S = <table> {
 SunKingsBlessingBuff = <table> {
 }
 RemoveCurse = <table> {
 }
 MirrorsofTorment = <table> {
 }
 TomeofMonstruousConstructionsBuff = <table> {
 }
 HeatingUpBuff = <table> {
 }
 RuneofPower = <table> {
 }
 FromTheAshes = <table> {
 }
 RingOfFrost = <table> {
 }
 BloodFury = <table> {
 }
 BerserkingBuff = <table> {
 }
 Blink = <table> {
 }
 Counterspell = <table> {
 }
 DragonsBreath = <table> {
 }
 AlexstraszasFury = <table> {
 }
 ArcaneExplosion = <table> {
 }
 Fireball = <table> {
 }
 ArcaneIntellectBuff = <table> {
 }
 SunKingsBlessingBuffReady = <table> {
 }
 MirrorImage = <table> {
 }
 Meteor = <table> {
 }
 GroveInvigoration = <table> {
 }
 FlameAccretion = <table> {
 }
 IreOfTheAscended = <table> {
 }
 BagofTricks = <table> {
 }
 SearingTouch = <table> {
 }
 FireBlast = <table> {
 }
 FlamePatch = <table> {
 }
 FrostNova = <table> {
 }
 SlowFall = <table> {
 }
 Invisibility = <table> {
 }
 ArcaneIntellect = <table> {
 }
 Kindling = <table> {
 }
 AncestralCall = <table> {
 }
 LightsJudgment = <table> {
 }
 Pyroblast = <table> {
 }
 BlazingBarrier = <table> {
 }
 RaidantSparkVulnerability = <table> {
 }
 SiphonedMalice = <table> {
 }
 ShiftingPower = <table> {
 }
 Combustion = <table> {
 }
 Fireblood = <table> {
 }
 BloodFuryBuff = <table> {
 }
 DoorofShadows = <table> {
 }
 SoulIgnitionBuff = <table> {
 }
 DisciplinaryCommandBuff = <table> {
 }
 GrislyIcicleDebuff = <table> {
 }
 GrislyIcicleBuff = <table> {
 }
 FirestormBuff = <table> {
 }
 InfernalCascadeBuff = <table> {
 }
 InfernalCascade = <table> {
 }
 HotStreakBuff = <table> {
 }
 Frostbolt = <table> {
 }
 Firestarter = <table> {
 }
 FieldOfBlossoms = <table> {
 }
 PyroclasmBuff = <table> {
 }
 TimeWarp = <table> {
 }
 CombustionBuff = <table> {
 }
 WastelandPropriety = <table> {
 }
 Scorch = <table> {
 }
 Flamestrike = <table> {
 }
 PhoenixFlames = <table> {
 }
 SpellSteal = <table> {
 }
 RadiantSparkDebuff = <table> {
 }
 RadiantSpark = <table> {
 }
 Fleshcraft = <table> {
 }
 Ignite = <table> {
 }
 Deathborne = <table> {
 }
 FlameOn = <table> {
 }
 BlastWave = <table> {
 }
 FocusMagic = <table> {
 }
 Pyroclasm = <table> {
 }
 LivingBomb = <table> {
 }
 AlterTime = <table> {
 }
 Berserking = <table> {
 }
 IceBlock = <table> {
 }
 Soulshape = <table> {
 }
 RuneofPowerBuff = <table> {
 }
 DeathborneBuff = <table> {
 }
}
var_kindling_reduction = 0.400000
var_combustion_precast_time = nil
num = <function> defined @HeroRotation_Mage\Fire.lua:200
EnemiesCount8ySplash = 1
var_combustion_flamestrike = nil
var_combustion_cast_remains = nil
var_time_to_combustion = nil
var_firestarter_combustion = -1
max = <function> defined =[C]:-1
CovenantID = 3
DeathFathomEquipped = false
Player = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit =

**Comment by Cilraaz** [comment]
The profiles have been re-written for 9.2 launch day. This should no longer be an issue. If the problem persists, please let us know.
