### ISSUE TITLE
LUA Error - Brewmaster Monk

### ISSUE THREAD

**Issue by Oep55** [herotc/hero-rotation#810]
Hello, if you would like me to post this elsewhere  please let me know, thanks. 

Message: Interface\AddOns\HeroRotation_Monk\Brewmaster.lua:340: attempt to index field 'VolatileSolvent' (a nil value)
Time: Wed Dec 22 11:28:39 2021
Count: 63
Stack: Interface\AddOns\HeroRotation_Monk\Brewmaster.lua:340: attempt to index field 'VolatileSolvent' (a nil value)
[string "@Interface\AddOns\HeroRotation_Monk\Brewmaster.lua"]:340: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\Main.lua:427>

Locals: ShouldReturn = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'VolatileSolvent' (a nil value)"
Enemies5y = <table> {
 1 = <table> {
 }
}
Player = <table> {
 CovenantID = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Equipment.lua:135
 SoulShardsDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Main.lua:160
 PainDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @Interface\AddOns\HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @Interface\AddOns\HeroLib\Class\Unit\Player\Pow

**Comment by Cilraaz** [comment]
This was previously fixed. The fix is included in version 9.1.5.06.
