### ISSUE TITLE
Arcane Mage w/ Harmony Leggo

### ISSUE THREAD

**Issue by Mlynn360** [herotc/hero-rotation#812]
Message: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
Time: Sat Jan  1 19:13:08 2022
Count: 687
Stack: Interface\AddOns\HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:32: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\Aura.lua"]:81: in function <Interface\AddOns\HeroLib\Class\Unit\Aura.lua:80>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HeroRotation_Mage\Arcane.lua"]:1005: in function <Interface\AddOns\HeroRotation_Mage\Arcane.lua:905>
[string "@Interface\AddOns\HeroRotation_Mage\Arcane.lua"]:1387: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\M

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/e61af652785e443480c83834b873d4157dbfb476

If it's still a problem, please let us know.
