### ISSUE TITLE
HeroRotation_DeathKnight\Unholy.lua error

### ISSUE THREAD

**Issue by Hexus-Proud** [herotc/hero-rotation#813]
Hi, I get this error message every time I attack an npc ...

27x HeroRotation\Core.lua:48: attempt to index local 'Object' (a nil value)
[string "@HeroRotation\Core.lua"]:48: in function `GetTexture'
[string "@HeroRotation\Core.lua"]:133: in function <HeroRotation\Core.lua:132>
[string "@HeroRotation_DeathKnight\Unholy.lua"]:648: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
Object = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Object' (a nil value)"
Cache = <table> {
 GUIDInfo = <table> {
 }
 Set = <function> defined @HeroCache\Main.lua:269
 APLVar = <table> {
 }
 Enemies = <table> {
 }
 Get = <function> defined @HeroCache\Main.lua:253
 HasBeenReset = true
 SpellInfo = <table> {
 }
 UnitInfo = <table> {
 }
 MiscInfo = <table> {
 }
 Persistent = <table> {
 }
 ItemInfo = <table> {
 }
 Reset = <function> defined @HeroCache\Main.lua:42
}
tostring = <function> defined =[C]:-1

Thank you.....

**Comment by Cilraaz** [comment]
This was previously fixed in commit https://github.com/herotc/hero-rotation/commit/50eed15c692b0e805ff8e13481d1625f2fc895e2
