### ISSUE TITLE
Mage: Frost

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#814]
--When freezing rain is talented, blizzard is not recommended ever

It says that frost is "good" but the version I have when loaded says it is still a work in progress and only updated for 9.1. I have updated all addons from curseforge. Is there a version of frost that is updated that isn't pushed to curseforge yet that may be more up to date than what I have?

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/ef8314c54ecf3e8f0d920b2e2142fe5e57577cd3
