### ISSUE TITLE
[DH Havoc] Blade Dance in Demonic window

### ISSUE THREAD

**Issue by framara** [herotc/hero-rotation#815]
With the synergie between Blance Dance + First Blood talent + Dancig with Fate conduict + Demonic talent you always want to squeeze two DB (Death Sweep actually) inside the 6 seconds windows of Demonic after Eye Beam. It would be great that APL doesn't suggest to use DB if Eye Beam is coming soon (around 6-7 seconds) or if fury is below 45 when both spells are ready.

**Comment by Herdrage** [comment]
It's written correctly as far as following the APL (don't BD if eye beam CD is less than 5 secs) but I agree I think it should add one more GCD's worth of time because sometimes that second death sweep doesn't appear until like a millisecond of demonic is left.

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
