### ISSUE TITLE
[SV Hunter] Bombs disappear in the rotation of the addon.

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#816]
Hello. Now I was in a raid on Dormazain and my addon stopped offering Shrapnel Bomb in the rotation. After when I myself already pressed the button with Shrapnel Bomb, then the addon began to recommend it in the rotation. But during the fight, the addon could again forget to recommend me to use the Shrapnel Bomb when even there were already 2 bombs, the addon anyway did not recommend until I myself pressed it. Please see why, after clicking on the bombs, the addon began to recommend them immediately, and if I didn’t click, then the addon ignored them until I clicked it.

**Comment by Cilraaz** [comment]
The profile has been re-written for 9.2 launch day. Please let us know if the issue persists.
