### ISSUE TITLE
MM Hunter

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#817]
I notiiced that mm hunter is marked as "good" in the supported rotation documentation but there are a few issues that I have noticed.  If there was a recent update to the MM hunter rotation that may not be live yet then obv disregard these points: 

1. During trueshot/resonating arrow window, on aoe with no lust, the addon will recommend a steady shot after the first two aimed shots, right before your second rapid fire in the window (there may be other scenarios but I am describing the exact scenario it was recommended to me in)

2. On two targets, the addon will often recommend rapid fire

3. On single target, during trueshot, the addon will recommend consuming precise shot procs with an arcane shot recommendation after precise shot buff is gained

**Comment by GarrettCottrell** [comment]
The talents I had selected when noticing these issues was:
1/3/3/2/2/3/3

I was Kyrian covenant

**Comment by GarrettCottrell** [comment]
Another issue: 

4. On ST, the addon will sometimes recommend rapid fire

**Comment by Cilraaz** [comment]
The profile has re-written for 9.2 launch day. Please let us know if the issue continues.
