### ISSUE TITLE
Wind Walker monk rotation EWF spam. 

### ISSUE THREAD

**Issue by GitJD82** [herotc/hero-rotation#820]
Wind Walker monk rotation spams Earth Wind and Fire once you use it.  No matter how many times you click it...it just keeps interrupting the rotation making it difficult to  use correct rotation.

**Comment by Cilraaz** [comment]
Please enable debug output and let us know which line is repeatedly suggested.

**Comment by GitJD82** [comment]
storm_earth_and_fire_fixate cd-sef 14.          Once you enable SEF  it tells you to press it after every other button you press.  Its for the fixate that the conduit is used for, but yhou shouldnt have to press it after every other button.  Especially on a single target.

**Comment by Cilraaz** [comment]
I added a change that should mean it's only suggested once per SEF in commit https://github.com/herotc/hero-rotation/commit/74fdf05d613283c44499dcbf93e8225843614658.

Let me know if that makes it work more as expected.

**Comment by GitJD82** [comment]
Im not educated enough to make that change unless there is a whole file i can copy from here? I usually just grab it from CurseFOrge.

**Comment by Cilraaz** [comment]
You can download a zip with the latest files [here](https://github.com/herotc/hero-rotation/archive/refs/heads/shadowlands.zip)

**Comment by GitJD82** [comment]
Looks  like that fixed it! Thanks!
