### ISSUE TITLE
[Survival Hunter] AoE Error

### ISSUE THREAD

**Issue by Zekke** [herotc/hero-rotation#821]
Sometimes the addon stop suggest anything during AoE (Venthyr SV)

212x HeroLib\Utils.lua:102: attempt to call field '?' (a nil value)
[string "@HeroLib\Utils.lua"]:102: in function `CompareThis'
[string "@HeroRotation\Commons.lua"]:86: in function `CastTargetIf'
[string "@HeroRotation_Hunter\Survival.lua"]:675: in function <HeroRotation_Hunter\Survival.lua:578>
[string "@HeroRotation_Hunter\Survival.lua"]:805: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
Operator = <function> defined @HeroRotation_Hunter\Survival.lua:97
A = true
B = true
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = "attempt to call field '?' (a nil value)"
CompareThisTable = <table> {
 min = <function> defined @HeroLib\Utils.lua:98
 >= = <function> defined @HeroLib\Utils.lua:95
 == = <function> defined @HeroLib\Utils.lua:97
 <= = <function> defined @HeroLib\Utils.lua:96
 < = <function> defined @HeroLib\Utils.lua:94
 max = <function> defined @HeroLib\Utils.lua:99
 > = <function> defined @HeroLib\Utils.lua:93
}

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/6204b293810a4a554c129ac36b51093e63773ef0
