### ISSUE TITLE
Fury Warrior - Recommendations dissappear instantly on pull

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#822]
Pre-pull there are recomendations but as soon as boss is pulled, all recommendations go away except for an occasional whirlwind

**Comment by Cilraaz** [comment]
I am unable to replicate this. The profile seems to work fine for me. Please provide the following:

- HeroRotation version
- HeroLib version
- Talents used
- Legendary used
- Any lua errors being shown

**Comment by GarrettCottrell** [comment]
HeroRotation-9.2.0.01.zip
HeroLib-9.2.0.01.zip
HeroDBC-9.1.5.01.zip
Talents: 2/1/2/2/3/2/1
No Legendary
No lua errors

**Comment by Cilraaz** [comment]
There was an error in HeroRotation 9.2.0.01. Please update to 9.2.0.03.

**Comment by GarrettCottrell** [comment]
Is this able to be done via curseforge? Curseforge thinks I have the latest available version

**Comment by Cilraaz** [comment]
CurseForge is showing 9.2.0.02 as the latest version (which does include the fix for Fury), but 9.2.0.03 can be downloaded from the github: [here](https://github.com/herotc/hero-rotation/releases/download/9.2.0.03/HeroRotation-9.2.0.03.zip)

**Comment by GarrettCottrell** [comment]
Thank you for this - apologies for not looking into this sooner
