### ISSUE TITLE
SV Hunter  Rotation doesn't show bombs

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#823]
Hello. A bug was noticed in the surv rotation that sometimes the addon does not recommend bombs, even when 2. Just the rotation goes on but without the use of bombs. If you yourself click on the bomb in non-rotation, then after the rotation starts to show them.

**Comment by tflo** [comment]
Noticed this too some days ago, with the Chakrams talent selected. (With Wildfire Infusion it seemed OK.)

**Comment by Cilraaz** [comment]
I've updated the logic for bombs in commit https://github.com/herotc/hero-rotation/commit/f73c3319358e34d2f37cc4605c9fcda32935b6dd

Please try this update and see if it is working better for you.

**Comment by Dragonfo** [comment]
Thanks, this fixed the problem, only the addon recommends using Jotungeirr when it is not on my character https://imgur.com/mRk49IE

**Comment by Cilraaz** [comment]
That should be fixed in commit https://github.com/herotc/hero-rotation/commit/967372683fa70fca54fd8b1856b9af9f0542810c

**Comment by Dragonfo** [comment]
Thanks again everything is great now.
