### ISSUE TITLE
Shadow Priest 

### ISSUE THREAD

**Issue by awtsigma** [herotc/hero-rotation#825]
Doesn't seem to load not sure why tried it with just HR on and still got the same error I've tried all the standard troubleshooting that I know not sure why this issue is going on. I have also re-installed all HR addons still no dice. Sorry if this is a waste of time and it's something on my end. Love the project hope to be able to support it soon

Date: 2022-03-04 06:09:49
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\HeroRotation_Priest\Shadow.lua line 35:
   attempt to index field 'ArchitectsIngenuityCore' (a nil value)
Debug:
   [string "@HeroRotation_Priest\Shadow.lua"]:35: in main chunk
   [string "=[C]"]: LoadAddOn()
   [string "@HeroRotation\Main.lua"]:384: PulseInit()
   [string "@HeroRotation\Main.lua"]:296:
      HeroRotation\Main.lua:293
Locals:
addonName = "HeroRotation_Priest"
addonTable = <table> {
}
DBC = <table> {
 ItemRange = <table> {
 }
 SpellAuraStat = <table> {
 }
 SpellConduits = <table> {
 }
 SpellRPPM = <table> {
 }
 ItemSpell = <table> {
 }
 SpellTickTime = <table> {
 }
 metaTime = "2021-11-02T17:59:33.911700"
 SpellMeleeRange = <table> {
 }
 SpellProjectileSpeed = <table> {
 }
 SpellEnchants = <table> {
 }
 metaVersion = "9.1.5.40871"
 SpellGCD = <table> {
 }
 SpellDuration = <table> {
 }
}
HL = <table> {
 RegisterForEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:46
 MAXIMUM = 40
 BossFilteredFightRemains = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:371
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 Item = <table> {
 }
 Pulse = <function> defined @Interface\AddOns\HeroLib\Main.lua:29
 LiveRealm = <function> defined @Interface\AddOns\HeroLib\Core.lua:34
 RegisterForCombatPrefixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:133
 UnregisterForEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:62
 AddCoreOverride = <function> defined @Interface\AddOns\HeroLib\Misc\Overrides.lua:26
 BetaRealm = <function> defined @Interface\AddOns\HeroLib\Core.lua:44
 Spell = <table> {
 }
 BossFightRemainsIsNotValid = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:356
 GetInstanceInfo = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:37
 Action = <table> {
 }
 LoadRestores = <function> defined @Interface\AddOns\HeroLib\Misc\Overrides.lua:42
 RegisterForCombatSuffixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:148
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 1
 RecoveryTimer = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:116
 BMPullTime = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:87
 RegisterForCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:88
 OutOfCombatTime = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:82
 UnregisterForSelfCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:177
 Latency = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:111
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 GetInstanceDifficulty = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:72
 LoadOverrides = <function> defined @Interface\AddOns\HeroLib\Misc\Overrides.lua:48
 Print = <function> defined @Interface\AddOns\HeroLib\Core.lua:49
 UnregisterAuraTracking = <function> defined @Interface\AddOns\HeroLib\Events\Aura.lua:37
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @Interface\AddOns\HeroLib\Core.lua:29
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:77
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 UnregisterForCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:163
 BossFightRemains = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:351
 FightRemains = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:319
 TTDRefresh = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:53
 RecoveryOffset = <function> defined @Interface\AddOns\HeroLib\Misc\ToSort.lua:124
 FilteredFightRemains = <function> defined @Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:361
 CombatStarted = 0
 SpecID_ClassesSpecs = <table> {
 }
 RegisterForSelfCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:103
 UnregisterForCombatPrefixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:205
 GUI = <table> {
 }
 UnregisterForPetCombatEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:191
 UnregisterForCombatSuffixEvent = <function> defined @Interface\AddOns\HeroLib\Events\Main.lua:219
 Timer = <table> {
 }
 PTRRealm = <function> defined @Interface\AddOns\HeroLib\Core.lua:39
 RegisterForPetCombatEvent = <function> defined @Int
AddOns:
  Swatter, v9.1.BETA.5.3 (OneMawTime)
  AAPCore, v9.063
  AdiBags, vv1.9.26
  AstralKeys, v3.47
  Auctioneer, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.3 (OneMawTime)
  BigWigs, vv235
  CovenantMissionHelper, v3.2.0
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v12.66
  ExRT, v4620
  FishingBuddy, v1.16.10
  GatherMate2, v1.47.1
  HeroCache, v9.2.0.01
  HeroDBC, v9.1.5.01
  HeroLib, v9.2.0.01
  HeroRotation, v9.2.0.04
  HeroRotationPriest, v
  Informant, v9.1.BETA.5.3 (OneMawTime)
  MRT, v4620
  OmniCD, v2.6.40
  ParagonReputation, v1.39
  Pawn, v2.5.32 (WoW 9.2.0)
  Plater, vPlater-v344-Retail
  SavedInstances, v9.2.1
  Simulationcraft, v9.1.5-01
  SlideBar, v9.1.BETA.5.3 (OneMawTime)
  SpeedyAutoLoot, v2.1.8
  Stubby, v9.1.BETA.5.3 (OneMawTime)
  TomCats, v2.4.3
  UnlimitedMapPinDistance, v1.1.4
  WeakAuras, v3.7.13
  WeakAurasCompanion, v1.1.0
  WIM, v3.9.5
  WorldQuestTracker, v
  ZerethMortisPuzzleHelper, v1.2
  BlizRuntimeLib_enUS v9.2.0.90200 <none>
  (ck=4a9)

**Comment by Cilraaz** [comment]
There is an updated version that fixes this problem that was not picked up by CurseForge for some reason. It can be found [here](https://github.com/herotc/hero-rotation/releases/download/9.2.0.05/HeroRotation-9.2.0.05.zip)

**Comment by awtsigma** [comment]
thanks for the speedy response
