### ISSUE TITLE
[SV Hunter] mono? error

### ISSUE THREAD

**Issue by Zekke** [herotc/hero-rotation#826]
Sometimes the addon stops suggesting spells for few sec during fight (venthyr 3-1-2-1-2-2-2 theotar + covenant leg).

291x HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "@HeroLib\Class\Unit\Aura.lua"]:32: in function <HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@HeroLib\Class\Unit\Aura.lua"]:148: in function `DebuffRemains'
[string "@HeroRotation_Hunter\Survival.lua"]:155: in function `Condition'
[string "@HeroRotation\Commons.lua"]:78: in function `CastTargetIf'
[string "@HeroRotation_Hunter\Survival.lua"]:410: in function <HeroRotation_Hunter\Survival.lua:346>
[string "@HeroRotation_Hunter\Survival.lua"]:806: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/b6efd46565036189f3ad3279d4707629dbd518f0
