### ISSUE TITLE
Ret Pal - Ashen Hallow as "off GCD" in rotation?

### ISSUE THREAD

**Issue by bobkat2000** [herotc/hero-rotation#828]
I'm a huge fan of this add-on, since I'm a passive player but also have a lot of alts... so this add-on helps me with the different rotations for each character to be effective.

I've been playing my Ret Pally and notice that my Ashen Hallow (Venthyr) shows up in the rotation early and cannot be bypassed... although this is very powerful, it can be also quite dangerous, given the large AOE range it has.  In many cases, I find casting this can draw in a lot of attackers and turn a battle the wrong way.  However, I'm not expert by any stretch, so there could still be a reason to include it.  I'm just wondering if there's a way/possibility to set this as an "Off GCD" or something so it doesn't stop the rest of the rotation?

Thanks!

**Comment by Cilraaz** [comment]
The location of the suggestion icon for Ashen Hallow should have been determined by the "DisplayStyle: Covenant" setting under class settings. This was bugged, though. I've fixed it as of commit https://github.com/herotc/hero-rotation/commit/777e8e9926f075899566c66fc5fe5299ae8e52a0
