### ISSUE TITLE
Error on frost mage

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#829]
255x HeroRotation_Mage\Frost.lua:306: attempt to index field 'IcyPropulsion' (a nil value)
[string "@HeroRotation_Mage\Frost.lua"]:306: in function <HeroRotation_Mage\Frost.lua:288>
[string "@HeroRotation_Mage\Frost.lua"]:434: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'IcyPropulsion' (a nil value)"

Target = <table> {
 UnitCanBeAttacked = true
 UnitID = "target"
 UseCache = true
 UnitExists = true
 UnitGUID = "Creature-0-3103-2374-6157-178913-0000237694"
 DebuffStack = <function> defined @HeroRotation_Mage\Overrides.lua:342
 UnitNPCID = 178913
 UnitName = "Graslandvombata"
 DebuffRemains = <function> defined @HeroRotation_Mage\Overrides.lua:364
}

Player = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 BuffUp = <function> defined @HeroRotation_Mage\Overrides.lua:310

**Comment by Cilraaz** [comment]
The spell object for Icy Propulsion was accidentally not included in the spell definitions. This has been fixed as of commit https://github.com/herotc/hero-rotation/commit/4a5a76c5d4acae2f23a7587404248f084e911872

**Comment by ReglohPri** [comment]
Ok, i have the same problem with Holy priest.

153x HeroRotation_Priest\Holy.lua:141: attempt to index field 'ArcanePulse' (a nil value)
[string "@HeroRotation_Priest\Holy.lua"]:141: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Urteil des Lichts"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 255647
}

Sincerely Holger -> ReglohPri
