### ISSUE TITLE
Error on holy priest

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#830]
153x HeroRotation_Priest\Holy.lua:141: attempt to index field 'ArcanePulse' (a nil value)
[string "@HeroRotation_Priest\Holy.lua"]:141: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Urteil des Lichts"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 255647
}
(*temporary) = false
(*temporary) = 255647
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Urteil des Lichts"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 255647
}
(*temporary) = "attempt to index field 'ArcanePulse' (a nil value)"
Enemies8yMelee = <table> {
}
Player = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined
@HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:53
ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:135
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:160
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib\Class\Unit\Player\Power.lua:208
PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @HeroLib\Class\Unit\Player\Main.lua:28

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/a4e7e1e421c29643c03781e08d69a2ceb2f747c3

**Comment by ReglohPri** [comment]
You are very fast.
