### ISSUE TITLE
[Mage - Frost] Rotation Suggestions Bugged for Necrolord

### ISSUE THREAD

**Issue by garnetri** [herotc/hero-rotation#831]
I've noticed that since I've switched to Necrolord, when I'm specced for commet storm it bugs out the rotation and it will stop showing when to use my ice lances. It then subsequently will only show flurry for my brain freeze procs. Not a huge deal I know, but it was really convenient to use hero rotation to track how many of my empowered ice lances I've used so far.

**Comment by Cilraaz** [comment]
I checked the profile. There's no interaction between specific Covenants and Ice Lance suggestions. There was a bug in version 9.2.0.05 that, while it shouldn't be causing the issue you're seeing, has been fixed. Can you try version 9.2.0.06 and confirm if the issue is still occurring?

**Comment by garnetri** [comment]
Thank you very much for the quick response. I've updated to 9.2.0.06 and will let you know what happens once I get a chance to try!

**Comment by garnetri** [comment]
Confirming that the update to 9.2.0.06 has worked. All of my beautiful ice lance procs are showing up properly! Thank you Cilraaz.

**Comment by Cilraaz** [comment]
Glad to hear it!
