### ISSUE TITLE
Don't often use bombs in AOE and CT at tier 2 set Surv hunter

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#833]
I decided to test a new set. And I only have 2 tier sets. And I noticed that the addon simply did not have time to use bombs, the counter reached 2 bombs. I decided to sim my character in ST and AOE and saw that in the rotation bombs should be used more often than the addon recommends them. I've attached a screenshot with bomb stats.  https://imgur.com/a/RiEzflv
I just look at my statistics according to the addon recommendations and they are very different from what I should strive for.
Without a set, it is not noticeable that the bombs are slowly reloading. But when the set starts to work, the addon does not recommend me to use them more often when the mechanics of the set is that I use bombs on targets as much and as often as possible. If you need any information from me about the set and how it works, I will do everything that is necessary. 
Thanks

**Comment by Cilraaz** [comment]
Closing duplicate to issue #823
