### ISSUE TITLE
Sub Rogue: When 2pc is equipped w/ shadow focus talent - still being recommended storm on 3 targets while in dance

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#835]
HeroRotation Version https://github.com/herotc/hero-rotation/issues/9.2.0.06
HeroDBC Version https://github.com/herotc/hero-rotation/issues/9.2.0.01
HeroLib Version 9.2.0.01

Talents: 2/3/2/2/2/3/3

Issue in Title - Addon does not appear to support 3 target rotation changes with shadow focus talented and 2 piece equipped.

**Comment by EvanMichaels** [comment]
Please update to 9.2.0.07, this should already be resolved. Thanks!

**Comment by GarrettCottrell** [comment]
Thank you - I realized there was an update right  after I posted this :( my mistake
