### ISSUE TITLE
Trinket displaying on main icon despite option selected to display as suggeseted

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#836]
I have attached  images but overhwelming power crystal is being suggested as a main icon, despite in options, having selected to have trinkets show as suggested - images below
![trinksuggestion](https://user-images.githubusercontent.com/49660931/158079085-54dbe31b-c2d0-4ef1-a812-addf08f4e640.PNG)
![trinkoptions](https://user-images.githubusercontent.com/49660931/158079089-024653c9-68ac-4004-b6b0-42780d3751a1.PNG)
:

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/805db4eb7b2c9aedb266b9344b00e9c475acc710
