### ISSUE TITLE
Outlaw Rogue - Rotation shows using Slice & Dice on an Animcharged (Kyrian) combo points, only damaging finishers counts

### ISSUE THREAD

**Issue by Thormor** [herotc/hero-rotation#838]
Hello!

I dunno if this will get triaged, but right now if you have an anima charged combo point, it will suggest you hit slice & dice as a finisher (when on that charged combo points) instead of your damaging finishers and even if your slice & dice is up.

Anime-charged combo points only works on damaging abilities and thus it serves no purpose to redo a slice & dice on this charged cp.

Thank you!

**Comment by EvanMichaels** [comment]
This is essentially a "happy accident" about the APL. It feels strange, but it's technically correct to potentially use lower combo point SnD casts under the right criteria. This only does this case when in pandemic range. It's doing the right thing (going into the Finisher list) for the "wrong" reason, but this was tested with the APL and shown as no particular gain to remove the normal SnD checks.

However, the logic is not assuming the animacharge has any effect:
`
and Player:BuffRemains(S.SliceandDice) < (1 + ComboPoints) * 1.8 then
`

In this case, it isn't checking against EffectiveComboPoints, and only looking at your actual CP amount for this logic.
