### ISSUE TITLE
Harpoon showing as main icon for surv hunter when option selected to show it as off GCD

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#839]
Evidence:
![Harpoon](https://user-images.githubusercontent.com/49660931/159053234-a148a9f9-b3a2-46d8-8af4-36d87353c925.PNG)
![harpoonicon](https://user-images.githubusercontent.com/49660931/159053255-746aa4b0-8473-4682-8e82-07ed18cc88f7.PNG)

HeroRotation Version: 9.2.0.10
HeroLib Version: 9.2.0.02
HeroDBC Version: 9.2.0.02

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/516ec8d3a075149394ac5b56d683d6aeeaaed2f9

**Comment by GarrettCottrell** [comment]
Thanks for being so responsive with changes when issues are discovered like this. Great work with the addon
