### ISSUE TITLE
Hero rotation throwing large amounts of errors for arcane mage

### ISSUE THREAD

**Issue by danamero35** [herotc/hero-rotation#840]
Within the last few updates HeroRotation now just throws a large number of errors on my Arcane Mage. I have tried removing and reinstalling the addon to no avail. Below is the error details:

1714x HeroRotation_Mage\Arcane.lua:1521: attempt to perform arithmetic on upvalue 'var_time_until_ap' (a nil value)
[string "@HeroRotation_Mage\Arcane.lua"]:1521: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
(*temporary) = nil
(*temporary) = 1.331000
(*temporary) = 1.331000
(*temporary) = <table> {
 LastCastTime = 0
 LastHitTime = 0
 LastAppliedOnPlayerTime = 0
 LastRemovedFromPlayerTime = 0
 SpellName = "Radiant Spark"
 IsMelee = false
 SpellType = "Player"
 MaximumRange = 40
 MinimumRange = 0
 LastDisplayTime = 0
 SpellID = 307443
}
(*temporary) = 1.331000
(*temporary) = 1.330645
(*temporary) = 1.331000
(*temporary) = "attempt to perform arithmetic on upvalue 'var_time_until_ap' (a nil value)"
Enemies8ySplash = <table> {
 1 = <table> {
 }
}
Target = <table> {
 UnitExists = true
 UnitName = "Scavenging Mite"
 UnitNPCID = 181110
 UnitGUID = "Creature-0-3887-2374-17544-181110-00003608E3"
 UnitID = "target"
 UseCache = true
 UnitCanBeAttacked = true
}
EnemiesCount8ySplash = 1
EnemiesCount10ySplash = 1
FightRemains = 8888
HL = <table> {
 RegisterForEvent = <function> defined @HeroLib\Events\Main.lua:46
 MAXIMUM = 40
 BossFilteredFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:371
 Pulse = <function> defined @HeroLib\Main.lua:29
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 PulseInitialized = true
 RoPTime = 0
 Item = <table> {
 }
 CacheHasBeenReset = false
 LiveRealm = <function> defined @HeroLib\Core.lua:34
 RegisterForCombatPrefixEvent = <function> defined @HeroLib\Events\Main.lua:133
 UnregisterForEvent = <function> defined @HeroLib\Events\Main.lua:62
 AddCoreOverride = <function> defined @HeroLib\Misc\Overrides.lua:26
 BetaRealm = <function> defined @HeroLib\Core.lua:44
 Spell = <table> {
 }
 BossFightRemainsIsNotValid = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:356
 GetInstanceInfo = <function> defined @HeroLib\Misc\ToSort.lua:37
 Action = <table> {
 }
 LoadRestores = <function> defined @HeroLib\Misc\Overrides.lua:42
 RegisterForCombatSuffixEvent = <function> defined @HeroLib\Events\Main.lua:148
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 0
 RecoveryTimer = <function> defined @HeroLib\Misc\ToSort.lua:116
 BMPullTime = <function> defined @HeroLib\Misc\ToSort.lua:87
 RegisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:88
 OutOfCombatTime = <function> defined @HeroLib\Misc\ToSort.lua:82
 UnregisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:177
 Latency = <function> defined @HeroLib\Misc\ToSort.lua:111
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 GetInstanceDifficulty = <function> defined @HeroLib\Misc\ToSort.lua:72
 LoadOverrides = <function> defined @HeroLib\Misc\Overrides.lua:48
 Print = <function> defined @HeroLib\Core.lua:49
 UnregisterAuraTracking = <function> defined @HeroLib\Events\Aura.lua:37
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @HeroLib\Core.lua:29
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @HeroLib\Misc\ToSort.lua:77
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 UnregisterForCombatEvent = <function> defined @HeroLib\Events\Main.lua:163
 BossFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:351
 FightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:319
 TTDRefresh = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:53
 RecoveryOffset = <function> defined @HeroLib\Misc\ToSort.lua:124
 FilteredFightRemains = <function> defined @HeroLib\Class\Unit\TimeToDie.lua:361
 CombatStarted = 526626.046000
 SpecID_ClassesSpecs = <table> {
 }
 RegisterForSelfCombatEvent = <function> defined @HeroLib\Events\Main.lua:103
 UnregisterForCombatPr

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/01a17e3ae3855d7c7b0a1970928a267f220184fe

**Comment by Cilraaz** [comment]
No response in 24 days. Assuming this is fixed. If not, please let me know.
