### ISSUE TITLE
Variables seem not to work at all

### ISSUE THREAD

**Issue by MatteoLombardi** [herotc/hero-rotation#843]
Hi, after the last update, even if variables are correctly stored in lua file, the behavior is not correct. Trinkets are set to "suggested" but show up in the main icon, and for kyrian prot pally, divine toll is NEVER suggested. Trinkets are still in main icon also if set as disabled entirely. Done a fresh install, restarts, reloads. Nothing fixed it. Any idea?

**Comment by Cilraaz** [comment]
What spec are you having the settings issue with?

For Protection Paladin, it looks like the Divine Toll issue was an error in APL transcription, which has been fixed as of commit https://github.com/herotc/hero-rotation/commit/46ae760d13b7a4d556ff3e7303ae9be68a6da524

**Comment by MatteoLombardi** [comment]
The trinket issue still applies to Prot paladin.

**Comment by Cilraaz** [comment]
That is fixed as of commit https://github.com/herotc/hero-rotation/commit/cb5bc6cdaf5ed22a14f641d340d499c8e9cba060

Were there any other issues?

**Comment by MatteoLombardi** [comment]
Not that I noticed, I'll comment once again after a few tests on new release.
Ty for the quick response!

**Comment by Cilraaz** [comment]
Please let us know if you are having any further issues. Closing this issue for now.
