### ISSUE TITLE
Surv Hunter: Issues with addon delaying or simply ignoring 2pc bomb proc on st (apepars to be fixed - may have been running an older version accidentally)

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#844]
On ST target, while I have an active 2pc proc, the addon continues to recommend kill command/raptor strike but does not recommend the bomb. With survivor tier, on st, if you get a 2pc proc, that should be cast immediately.

To further elaborate, the addon continues to ignore bombs entirely on st (even when bombs are fully capped at 2 - regardless of tier procs)

Not sure why these are happening. While a bomb proc is active, there shouldn't be a scenario where the addon is recommending kill commands becuase that could potentially overwrite the bomb proc I already have.

HeroRotation Version: HeroRotation-9.2.0.13.zip
Herolib Version: HeroLib-9.2.0.04.zip

**Comment by Cilraaz** [comment]
If this is still an issue or re-appears in a later version, please let us know.
