### ISSUE TITLE
After targeting enemy getting lua errors 

### ISSUE THREAD

**Issue by Wolfynko** [herotc/hero-rotation#845]
please help :( 

Message: ...nterface\AddOns\HeroRotation_Paladin\Retribution.lua:144: attempt to index field 'PustuleEruption' (a nil value)
Time: Fri Apr  1 19:14:34 2022
Count: 1336
Stack: ...nterface\AddOns\HeroRotation_Paladin\Retribution.lua:144: attempt to index field 'PustuleEruption' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroRotation_Paladin\Retribution.lua"]:144: in function <...nterface\AddOns\HeroRotation_Paladin\Retribution.lua:138>
[string "@Interface\AddOns\HeroRotation_Paladin\Retribution.lua"]:579: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\Main.lua:427>

Locals:

**Comment by Cilraaz** [comment]
This is now fixed in commit https://github.com/herotc/hero-rotation/commit/27ff81d26a59ab2354129caae8c542f8f8133fb5
