### ISSUE TITLE
[Frost DK] AoE recommendation to switch between targets with T4 set

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#846]
Hello. From t4, as far as I know, we don't switch to AoE targets to hang Rune of Razorice. Because we have other runes for weapons and we hang Rune of Razorice on the target at the expense of T4 set. Is it possible to fix this in AOE? Thanks

**Comment by Cilraaz** [comment]
The Simulationcraft APL does not reflect this and currently suggests target changes. If the APL changes, HeroRotation will change accordingly.

**Comment by Dragonfo** [comment]
I specifically requested my character with a t4 set, in different simulation conditions. And I saw that when we refuse the Rune of Razorice rune, we do not switch to nearby targets. The Sim clearly shows the switch being made only on the Howling Blast. And abilities like Frost Strike Obliterate only affect the primary target. This problem is on your addon side not on the APL side. I can provide all the sims I made on the Raidbots site. Because the APL developer assured me that this is taken into account when we have t4 and we refuse the Rune of Razorice rune. https://www.raidbots.com/simbot/report/qwi8j3Yj2juxBbnMxXPRVe.

**Comment by nyterage** [comment]
> I specifically requested my character with a t4 set, in different simulation conditions. And I saw that when we refuse the Rune of Razorice rune, we do not switch to nearby targets. The Sim clearly shows the switch being made only on the Howling Blast. And abilities like Frost Strike Obliterate only affect the primary target. This problem is on your addon side not on the APL side. I can provide all the sims I made on the Raidbots site. Because the APL developer assured me that this is taken into account when we have t4 and we refuse the Rune of Razorice rune. https://www.raidbots.com/simbot/report/qwi8j3Yj2juxBbnMxXPRVe.

Hi, APL dev here for frost dk. i dont remember talking to you about this? 

but, either way. the formula used for sims switching targets multiplies against the runeforge being present. if the runeforge isnt present, it wont switch targets. So your assumption is correct.

**Comment by Cilraaz** [comment]
I've added some checks to the profile. For the abilities that would suggest target changes to spread Razorice stacks, target changes will not be suggested if Razorice is not in use.

This is included in commit https://github.com/herotc/hero-rotation/commit/7c9e9d46318145c6366ee8f88020230f79f42990
