### ISSUE TITLE
Condemn - wrong id's

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#847]
Currently, HeroRotation is never showing icon for Condemn due to wrong ids in the Warrior.lua.
GetSpellInfo("Condemn") returns id - 330334, but in the code it is:

`
  Condemn                               = MultiSpell(330325, 317485),
`

Also, a question: wouldn't it be better to use GetSpellInfo by spell name to get the id instead of hardcoding them like that?

**Comment by Cilraaz** [comment]
This spell ID has been added in commit https://github.com/herotc/hero-rotation/commit/733a3ab20875c4a168817d23601143fd4e3b6db4

We don't use GetSpellInfo, as that would break based on localization for all non-English clients.
