### ISSUE TITLE
[Rogue_Sub] Please help check if my code can be used

### ISSUE THREAD

**Issue by mizone** [herotc/hero-rotation#848]
I have some idea for you. please check if my code can be used. 

--- ============================ CD for Mythic +  ============================ use ( HR.CDsON()  and MayCDsON() ) replace HR.CDsON()
local function MayCDsON()
  if Player:IsInDungeonArea() then
      if Target:IsInBossList() then
	      return true
      elseif Target:TimeToDie() >= 20 then   --TTD>=25sfor 20+；20s for 17-20   only use CDs when TTD of add target >= 20s
          return true
      else 
	  return false
	  end
   else 
   return true
  end
end

--- ============================ Auto Use Priority Rotation = AUPR ============================
AUPRTargetIDlist = {   
171343,
185685,
166969,
166971,
166970,
163618,
163621,
163620,
172981,
165911,
168942,
163894,
168318,
163520,
162047,
178141,
178165,
184141, --赛财团助战者
}

local function AutoRoationTarget()
  for i = 0 , #AUPRTargetIDlist do
    if AUPRTargetIDlist[i] == Target:NPCID() then
      return true
    end
  end
  return false
end

local function UsePriorityRotation()
  if MeleeEnemies10yCount < 2 then
    return false
  elseif Settings.Commons.UsePriorityRotation == "Always" then
    return true
  elseif Settings.Commons.UsePriorityRotation == "On Bosses" and Target:IsInBossList() then
    return true
  elseif Settings.Commons.UsePriorityRotation == "Auto" then
    if AutoRoationTarget() then
      return true
    end
  end
  return false
end

**Comment by EvanMichaels** [comment]
I don't mind adding more NPCs to the auto priority list, however I'd need to know what NPCs those map to in order to confirm. Perhaps we can support a user-editable list though.

**Comment by mizone** [comment]
it would be great to have a User-editable list in the UI.


AUPRTargetIDlist = {
--Mythic+ Part--
185685,  --Urh Relic
171343,  -- DOS, Bladebeak Matriarch
168942,  --DOS, Death Speaker
169905,  --DOS, Risen Warlord
164557,  --HOA, Shard of Halkias
164929,  --MOTS, Tirnenn Villager
170850,  --TOP, Raging Bloodhorn
164596,  --TOP, Ancient Captain
167998,  --TOP, Portal Guardian
162763,  --TOP, Soulforged Bonereaver
163086,  --TOP, Rancid Gasbag
163618,  --NW, Zolramus Necromancer
163621,  --NW, Goregrind
165824,  --NW, Nar'zudah
163620,  --NW, Rotspew
172981,  --NW, Kyrian Stitchwerk
165911,  --NW, Loyal Creation
168153,  --PF, Plagueroc
163894,  --PF, Blighted Spinebreaker
164797,  --PF, Congealed Slime
168318,  --SOA, Forsworn Goliath
163520,  --SOA, Forsworn Squad-Leader
162047,  --SD, Insatiable Brute
171376,  --SD, Head Custodian Javlin
178165,  --TAZ:SG, Coastwalker Goliath
178141,  --TAZ:SG, Murkbrine Scalebinder
--Raid Part--
184140,  --Artificer Xy'mox Mythic, XY ACOLYTE
183671,  --Anduin Wrynn Mythic, Monstrous Soul
}

**Comment by mizone** [comment]
Could you also give a trigger that do not use SymbolsofDeath and Shadowdance when TTD <=10 seconds,  when deal with Adds in Mythic + ? or a editeable time setting?

**Comment by hubikys** [comment]
подскажите информацию по обновлению аддона для актуапльной версии?
