### ISSUE TITLE
Missing event subscriptions causing key binds to not show up correctly for sub rogue

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#849]
Current (old) problem: for classes with bar swapping the keybinds may not always correctly show.
Sample: sub rogue, activating shadow dance swaps bar to the "stealth" one and then the key binds stop showing up (observed specifically for Eviscerate which is present on slot 3 both of the normal and "stealth" bars.

Looks like this change in the HeroLib fixes it (need to more testing but so far is looking good):

![image](https://user-images.githubusercontent.com/80422771/162424774-0b0f22a6-6837-4ee6-90f8-db2e399c7660.png)

**Comment by c-ray-c** [comment]
Also likely subscribing here to ACTIONBAR_SLOT_CHANGED is not a good idea, as it triggers for specific slot and we are handling that properly at line 143.

**Comment by Cilraaz** [comment]
After some quick testing, this seems to work fine, so the changes have been included in commit https://github.com/herotc/hero-lib/commit/575cf6179ebbd99af009c79371e660baf8a250af
