### ISSUE TITLE
[Priest - Shadow] Lua Errors almost at any pull

### ISSUE THREAD

**Issue by MatteoLombardi** [herotc/hero-rotation#850]
Hello, during normal rotation, almost every pull the main icon stops being shown, and out of combat (thanks to ElvUI), I get greeted by this error.

Never happened to me in 9.1.5

Count: 75
Stack: Interface\AddOns\HeroRotation\Commons.lua:62: attempt to call local 'Condition' (a nil value)
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: in function `Condition'
[string "@Interface\AddOns\HeroRotation\Commons.lua"]:62: in function `CastCycle'
[string "@Interface\AddOns\HeroRotation_Priest\Shadow.lua"]:378: in function <Interface\AddOns\HeroRotation_Priest\Shadow.lua:354>
[string "@Interface\AddOns\HeroRotation_Priest\Shadow.lua"]:589: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\Main.lua:427>

**Comment by Cilraaz** [comment]
This was due to a typo. It has been fixed in commit https://github.com/herotc/hero-rotation/commit/0a33746eb48eba14e0aa1e8adfc4c684c3a21c25
