### ISSUE TITLE
[Hunter Survival Venthyr] Flayed Shot is never seen

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#852]
Somehow Flayed Shot is **never** showing up for Survival hunter (have Covenant abilities set to show up in the Main icon).

**Comment by Cilraaz** [comment]
Can you please provide the spell ID for your Hunter's Flayed Shot? If your UI does not do this for you, please type into chat `/dump "`, then shift click the spell from your spellbook, then add another `"`. This will print the spell string, which will contain the spell ID.

The profile currently should suggest Flayed Shot effectively on CD in all scenarios. For 1-2 target scenarios, it should be suggested on the primary target. In 3+ target scenarios, it will be suggested on the target with the highest health. If this is not the primary target, it would show as a nameplate spell suggestion.

As such, if it's not showing for you, the most likely issue is an incorrect spell ID.

**Comment by c-ray-c** [comment]
after changing specs, reloading, changing display style for covenant between Main and Suggested - now it finally is showing up for higher HP mobs
