### ISSUE TITLE
Frost mage rotation - broken?

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#853]
So, I almost **only** get to see Ice Lance in the main icon. Even when it's a single target, it is not frozen etc. Almost never seeing frostbolts or anything else...

Spec: 2312121

**Comment by c-ray-c** [comment]
![image](https://user-images.githubusercontent.com/80422771/163561588-c1a0a122-adbd-4969-81b4-9097ed8e4eb0.png)
Here following the rotation I had to press ice lance until mob was dead.

**Comment by c-ray-c** [comment]
Here, the condition seem to be erronous:
`
  if S.IceLance:IsCastable() and (Target:DebuffUp(S.WintersChillDebuff) and Target:DebuffStack(S.WintersChillDebuff) > num(Player:BuffUp(S.FingersofFrostBuff)) and Target:DebuffRemains(S.WintersChillDebuff) > S.IceLance:TravelTime()) then
    if Cast(S.IceLance, nil, nil, not Target:IsSpellInRange(S.IceLance)) then return "ice_lance single 18"; end
  end
`

Specifically, `Target:DebuffStack(S.WintersChillDebuff) > num(Player:BuffUp(S.FingersofFrostBuff))` If ` num(Player:BuffUp(S.FingersofFrostBuff))` is always 0 it will always be suggested to get cast.

**Comment by c-ray-c** [comment]
Changing to `Target:DebuffStack(S.WintersChillDebuff) > 3` unlocks the rotation, but obviously this is not a fix

**Comment by Cilraaz** [comment]
I'm unable to replicate this issue. The rotation works as expected for me. 

The line you're referencing requires the Winter's Chill debuff to be active on the target, so I highly doubt that it would somehow hang the rotation on that line.

**Comment by c-ray-c** [comment]
Not sure how that can work for you, because the condition is definitely wrong `Target:DebuffStack(S.WintersChillDebuff) > num(Player:BuffUp(S.FingersofFrostBuff)` The `num(Player:BuffUp(S.FingersofFrostBuff)` part will be either 0 or 1, so obviously it will just get locked in the Cast(S.IceLance, nil, nil, not Target:IsSpellInRange(S.IceLance)). There is absolutely NO point in casting ice lance when there are only 1 or 2 stacks of winter chill.
