### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#855]
Message: Interface\AddOns\HeroLib\Class\Item.lua:135: Usage: GetSpellBaseCooldown(spellID)
Time: Wed Apr 20 08:33:27 2022
Count: 10
Stack: Interface\AddOns\HeroLib\Class\Item.lua:135: Usage: GetSpellBaseCooldown(spellID)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellBaseCooldown'
[string "@Interface\AddOns\HeroLib\Class\Item.lua"]:135: in function `Cooldown'
[string "@Interface\AddOns\HeroLib\Class\Item.lua"]:178: in function `HasCooldown'
[string "@Interface\AddOns\HeroRotation_Hunter\Survival.lua"]:314: in function <Interface\AddOns\HeroRotation_Hunter\Survival.lua:286>
[string "@Interface\AddOns\HeroRotation_Hunter\Survival.lua"]:864: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:449: in function <Interface\AddOns\HeroRotation\Main.lua:427>

Locals:

**Comment by Cilraaz** [comment]
What trinkets are you using when this error occurs?

**Comment by Cilraaz** [comment]
Added a check to Item:Cooldown() that should prevent the errors mentioned above. This was added in commit https://github.com/herotc/hero-lib/commit/56fee37121e37da46b851a96b66bcf8b189d1905
