### ISSUE TITLE
FrostDK - wrong "OutOfRange" condition for Glacial Advance

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#856]
Lines: 302, 314, 608, 649, 673, 716, 792 have wrong value passed as "OutOfRange" resulting in icon showing up as if the spell is out of range, when it's not.
![image](https://user-images.githubusercontent.com/80422771/164884233-c01b7a82-aa39-431a-808e-1326e9f5345a.png)

**Comment by Cilraaz** [comment]
This has been updated in commit https://github.com/herotc/hero-rotation/commit/165d7ab2966a4481d16442d1c4c8ff081c6883e1

The ComputeTargetRange function, which resulted in the TargetIsInRange table, has been removed. The profile now uses Target:IsInRange, Target:IsSpellInRange, and Target:IsInMeleeRange instead.
