### ISSUE TITLE
[DH Havoc] Rotation shows "Demon Blades" - a passive talent

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#857]
Havoc rotation for some reason shows an icon for... Demon Blades - a passive talent. Why???

`
  -- Manually added: Demon's Bite/Demon Blades if in melee range
  if Target:IsInMeleeRange(5) and (S.DemonsBite:IsCastable() or S.DemonBlades:IsAvailable()) then
    if Cast(S.DemonsBite, nil, nil, not Target:IsInMeleeRange(5)) then return "demons_bite or demon_blades precombat 4"; end
  end
`

**Comment by c-ray-c** [comment]
![image](https://user-images.githubusercontent.com/80422771/165470281-b3718697-17e1-498c-9d5b-ba0d47f062ad.png)

**Comment by c-ray-c** [comment]
![image](https://user-images.githubusercontent.com/80422771/165470478-6270164b-b4ab-4b4e-89ef-2a6218ef6f63.png)

**Comment by Cilraaz** [comment]
Because it's the end of the Precombat chain, so the alternative was no icon at all.

**Comment by c-ray-c** [comment]
> Because it's the end of the Precombat chain, so the alternative was no icon at all.

I don't get it... What's the purpose to show an icon for a passive skill... What should I do when I see it? Maybe something like pooling would be more meaningful?

**Comment by Cilraaz** [comment]
When you see that icon, you should attack your target. There is no other icon to show at that point. Showing no icon usually indicates a problem with the addon, so that's not preferred. I fail to see how the Pooling icon would be preferred over an icon that effectively tells you to attack your target.

**Comment by c-ray-c** [comment]
How should I know this is an icon that tells me that I need to attack, tho? I mean, I didn't see that for any other rotation. Usually "attack it with auto-attack" is a pooling icon, isn't it?

**Comment by Cilraaz** [comment]
The Pooling icon denotes that there is no action to take.
