### ISSUE TITLE
[Feral druid] Exceptions

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#858]
This code is throwing exceptions if combat was initiated before the Precombat() was called

`    if (ComboPoints >= (5 - VarFourCPBite)) then
      local ShouldReturn = Finisher(); if ShouldReturn then return ShouldReturn; end
    end
`

Reason is VarFourCPBite is initialized in the Precombat().

**Comment by Cilraaz** [comment]
I've moved the variable definitions into their own function, which is called in the main APL loop, rather than from Precombat. This should resolve the issue. This is included in commit https://github.com/herotc/hero-rotation/commit/e8df384cb006de1f49f2c527d8448a322f3b4564
