### ISSUE TITLE
[Demonology Warlock] A lot of errors due to missing argument

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#860]
`
    if Cast(I.ResonantReservoir, nil, Settings.Commons.DisplayStyle.Trinkets, not Target:IsInRange()) then return "resonant_reservoir dmg 4"; end
  end
  -- use_item,name=architects_ingenuity_core
  if I.ArchitectsIngenuityCore:IsEquippedAndReady() then
    if Cast(I.ArchitectsIngenuityCore, nil, Settings.Commons.DisplayStyle.Trinkets, not Target:IsInRange()) then return "architects_ingenuity_core dmg 6"; end
  end
  -- use_item,name=cosmic_gladiators_resonator
  if I.CosmicGladiatorsResonator:IsEquippedAndReady() then
    if Cast(I.CosmicGladiatorsResonator, nil, Settings.Commons.DisplayStyle.Trinkets, not Target:IsInRange()) then return "cosmic_gladiators_resonator dmg 8"; end
  end
`

`not Target:IsInRange()` should have a number passed as argument, looks like:

![image](https://user-images.githubusercontent.com/80422771/165902751-ca035cc0-4277-4601-ad36-e536e9edca1b.png)

**Comment by Cilraaz** [comment]
This is fixed in commit https://github.com/herotc/hero-rotation/commit/3d394a0643c34004617c795f29dcbae1ba8df486
