### ISSUE TITLE
[Destruction Warlock] Shadowburn - check for IsReady instead of IsCastable

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#861]
For Shadowburn check the IsCastable is not enough, because then it will get suggested to be used when there are no shards. Should be replaced with IsReady
Probably wouldn't hurt to do the same for the rest of checks of other spells

**Comment by Cilraaz** [comment]
Shadowburn has been fixed as of commit https://github.com/herotc/hero-rotation/commit/431f5c142467bb51be34fe1ec8571f86b12b019d

I checked the remainder of spells using IsCastable, which all appear to be fine.
