### ISSUE TITLE
SV Hunter rotation

### ISSUE THREAD

**Issue by cyberbook78** [herotc/hero-rotation#862]
the single target rotation is broken. he only does Serpent Sting. Thx

**Comment by framara** [comment]
rotation is broken since last update

**Comment by cyberbook78** [comment]
Yes

**Comment by Cilraaz** [comment]
I'm unable to replicate this. Please provide the following:

- Talents used
- Legendary used
- Covenant used
- Tier set status
- Debug output (enable debug output in settings and let me know which Serpent Sting line is getting stuck)

**Comment by zerxyboy** [comment]
Same issue for me with this update. Reverted back to version xx.17 and it doesn't have the same issue.

Talents used
- Alpha Predator
- Guerilla Tactics
- Camo
- Bloodseeker
- Binding Shot
- Tip of the Spear
- Wildfire Infusion

Legendary used
- Wildfire Cluster

Covenant used
- Kyrian

Tier set status
- 4 Set

Debug output (enable debug output in settings and let me know which Serpent Sting line is getting stuck)
- I'm not sure it's getting stuck, more that it sets this as the priority spell. If you spam it 5-6 times, it chooses another spell before coming back to SS as prio.

**Comment by zerxyboy** [comment]
It seems to be at "serpent_sting st 4"

**Comment by Cilraaz** [comment]
Thank you for the report and the further information. I found an error that I made in transcribing that Serpent Sting line. I used an "or" where an "and" should have been. This has been fixed in commit https://github.com/herotc/hero-rotation/commit/b1e760b685ce50a38c5223fe9e6f7cc913b1e901

Please let me know if you have any further issues after applying this update.

**Comment by cyberbook78** [comment]
Gesendet mit der mobilen Mail AppAm 04.05.22 um 11:18 schrieb Francisco Martínez Alejandro
                
            
            
                
                    Von: "Francisco Martínez Alejandro" ***@***.***>Datum: 4. Mai 2022An: "herotc/hero-rotation" ***@***.***>Cc: "Author" ***@***.***>,"cyberbook78" ***@***.***>Betreff: Re: [herotc/hero-rotation] SV Hunter rotation (Issue #862)
                
                
rotation is broken since last update

**Comment by Cilraaz** [comment]
I have no errors in version 9.2.7.03. You'll have to be more specific.
