### ISSUE TITLE
[Fleshcraft] Add an option to never display it

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#864]
Currently, the problem is that casting Fleshcraft is very-very situational and really shouldn't be a part of the combat rotation, in my opinion, while the other one necrolord ability - should be a part of the rotation, for sure. So would be nice either to move Fleshcraft to some another icon or to give an option to fully disable suggestions to cast it, as we anyways have WA or something else to remind us about Fleshcraft.

**Comment by Cilraaz** [comment]
Fleshcraft is part of the Simulationcraft APL, so it's included in HeroRotation. There is the option to move where Covenant spells are located.

**Comment by c-ray-c** [comment]
I don't get it... Why defensive situational spell is part of the rotation? If anything, it only results in loss of dps if not cast at appropriate time of the encounter...

**Comment by nyterage** [comment]
Some soulbind abilities, such as marileths volatile solvent are big dps increases to cast fleshcraft on cooldown. same with emenis pustule eruption. it should only be suggested in the APLs with these traits selected, so not using it will be a dps loss, hence why it casts it in the APLs.

**Comment by c-ray-c** [comment]
As I said: it **will** result in dps loss if not cast at **appropriate** time of the encounter. A lot of times I see it's suggested when casting it **will** result in dps loss.
