### ISSUE TITLE
[Warlock] Summon pet - can we make it optional?

### ISSUE THREAD

**Issue by c-ray-c** [herotc/hero-rotation#865]
Can we have an option to disable Summon pet altogether? As destruction I find myself in situations when pet is killed, but it's not an appropriate time to summon it... Meaning that the spell is very situational.

**Comment by Cilraaz** [comment]
Added the option in commit https://github.com/herotc/hero-rotation/commit/45d66823bb235fcbba24afe686dc6d9ec9a9871e
