### ISSUE TITLE
Arcane Mage - still lua Errors upon targeting enemy

### ISSUE THREAD

**Issue by Hyrpsup** [herotc/hero-rotation#868]
Date: 2022-05-13 16:56:52
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\HeroRotation_Mage\Arcane.lua line 224:
   attempt to perform arithmetic on a boolean value
Debug:
   [string "=[C]"]: ?
   [string "@HeroRotation_Mage\Arcane.lua"]:224:
      HeroRotation_Mage\Arcane.lua:148
   [string "@HeroRotation_Mage\Arcane.lua"]:279:
      HeroRotation_Mage\Arcane.lua:276
   [string "@HeroRotation_Mage\Arcane.lua"]:1430: ?()
   [string "@HeroRotation\Main.lua"]:449:
      HeroRotation\Main.lua:427
Locals:

AddOns:
  Swatter, v9.1.BETA.5.3 (OneMawTime)
  AddOnSkins, v4.58
  AdvancedInterfaceOptions, v1.7.1
  BigWigs, vv241.3
  CovenantMissionHelper, v3.2.0
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v12.76
  ElvUIGlobalFadePersist, v0.1
  GatherMate2, v1.47.1
  HandyNotes, vv1.6.5
  HandyNotesBattleForAzeroth, v9
  HandyNotesDraenor, v2.5
  HandyNotesOribos, vv16
  HandynotesPandaria, v1.5.1
  HandyNotesShadowlands, v46
  HandyNotesTravelGuide, vv2.7.0
  HeroCache, v9.2.0.08
  HeroDBC, v9.2.0.06
  HeroLib, v9.2.0.08
  HeroRotation, v9.2.0.19
  HeroRotationMage, v
  HidingBar, vv9.2.5
  Informant, v9.1.BETA.5.3 (OneMawTime)
  LibGroupInSpecT11, v1.4.0
  MazeHelper, v1.51
  MRT, v4620
  Myslot, vv5.8.0
  MythicDungeonTools, v3.9.2.2
  NameplateAuras, v90200.7-release
  NaowhUIInstaller, v1.0.0
  OmniCD, v2.7.16
  OPie, vXe 6
  Pawn, v2.5.37
  Plater, vPlater-v350-Retail
  Postal, vv3.8.0
  RaiderIO, v9.2.0 (v202205130716)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUF, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  RCLootCouncil, v3.3.0
  Routes, vv1.6.7
  RoutesImportExport, vv1.0.4
  SharedMedia, v3.1.0-191
  Simulationcraft, v9.2.0
  SlideBar, v9.1.BETA.5.3 (OneMawTime)
  Stubby, v9.1.BETA.5.3 (OneMawTime)
  WarpDeplete, v1.1.4
  WeakAuras, v3.7.16
  WeakAurasCompanion, v1.1.0
  WhatsYourCovenant, v1.4.2
  WhatsYourCovenantDBEUA, v1.4.2
  WhatsYourCovenantDBEUH, v1.4.2
  WorldQuestsList, v104
  BlizRuntimeLib_enUS v9.2.0.90200 <none>
  (ck=60a)

**Comment by Hyrpsup** [comment]
Addition to above: only happens if "Use fishing opener" is enabled in the settings. without fishing opener everything works just fine

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/f8f0a54f666aa5b70ffea098d4c0c3363c32d164
