### ISSUE TITLE
[Warrior - Fury] No rampage while bladestorm

### ISSUE THREAD

**Issue by thekk1** [herotc/hero-rotation#869]
While bladestorm is channeling and rage is above 80, RagingBlow or CrushingBlow is suggested as next spell which is switched immediatly to Rampage after Bladestorm ends.

The reason is, that the used method "S.Rampage:IsReady()", for example line 144 fury.lua, is inherit the method Spell:IsUsable() (from Spell:IsUsableP(Offset)).
Spell:IsUsable() returns false while casting bladestorm which is not what you want at this special case.

My local fix is replace "S.Rampage:IsReady()" with "S.Rampage:IsCastable() and not S.Rampage:IsUsablePPool(0)"
but there is maybe a better solution.

**Comment by Cilraaz** [comment]
I added an override for Rampage that should fix the issue. This is included in commit https://github.com/herotc/hero-rotation/commit/fa38d345d7b63476a22ad5745e2a0177f9bedac0

**Comment by thekk1** [comment]
This Patch works for the origin Bladestorm ability but NOT works with the Bladestorm triggered by Signet of Tormented Kings.
