### ISSUE TITLE
Shadow priest error

### ISSUE THREAD

**Issue by Oep55** [herotc/hero-rotation#871]
1166x HeroLib\Class\Unit\Aura.lua:32: attempt to index local 'ThisSpell' (a nil value)
[string "@HeroLib\Class\Unit\Aura.lua"]:32: in function <HeroLib\Class\Unit\Aura.lua:27>
[string "=(tail call)"]: ?
[string "@HeroLib\Class\Unit\Aura.lua"]:81: in function `BuffRemains'
[string "@HeroLib\Class\Unit\Aura.lua"]:99: in function `BuffUp'
[string "@HeroLib\Class\Unit\Aura.lua"]:104: in function `BuffDown'
[string "@HeroRotation_Priest\Shadow.lua"]:151: in function `Condition'
[string "@HeroRotation\Commons.lua"]:62: in function `CastCycle'
[string "@HeroRotation_Priest\Shadow.lua"]:393: in function <HeroRotation_Priest\Shadow.lua:357>
[string "@HeroRotation_Priest\Shadow.lua"]:603: in function `?'
[string "@HeroRotation\Main.lua"]:449: in function <HeroRotation\Main.lua:427>

Locals:
self = <table> {
 CovenantID = <function> defined @HeroLib\Class\Unit\Player\Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:596
 GCDStartTime = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:70
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:46
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:648
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:226
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:725
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 IsInParty = <function> defined @HeroLib\Class\Unit\Player\Main.lua:33
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:279
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:698
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:22
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:681
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:554
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:666
 IsInDungeonArea = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib\Class\Unit\Player\Equipment.lua:141
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:470
 GetEnemiesInRange = <function> defined @HeroLib\Class\Unit\Player\Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:160
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:740
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib\Class\Unit\Player\Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:745
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:633
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:113
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:708
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:482
 IsMounted = <function> defined @HeroLib\Class\Unit\Player\Main.lua:28
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:289
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:389
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:703
 Insanity = <function> defined @HeroRotation_Priest\Overrides.lua:41
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Unit\Player\Power.lua:336
 ArcaneChargesPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:671
 AstralPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:503
 MaelstromDeficitPercentage = <function> define

**Comment by Cilraaz** [comment]
This should be fixed as of commit https://github.com/herotc/hero-rotation/commit/77e0f3981468c7b9fcf788e99c46ac42ed0a0b59

If the issue continues after applying that update, please let us know.
