### ISSUE TITLE
[Mage - Arcane] Rotation broken

### ISSUE THREAD

**Issue by MatteoLombardi** [herotc/hero-rotation#872]
Hi,

Since I equipped my legendaries [(swapped from frost) Harmony + Unity] the rotation is completely broken.

All it does, both in ST and AoE, is making me spam arcane missile no matter what (no clearcasting, already at 18 stacks) and it's not making me use cooldowns

**Comment by MatteoLombardi** [comment]
Smol bump up. Been over a month and a half, not even a response about reading regarding the issue

**Comment by Cilraaz** [comment]
Do you have the option for "Use Fishing Opener" enabled? If so, the APL will continue to suggest Arcane Missiles until you reach 18 stacks of Harmony.

If you do not have "Use Fishing Opener" enabled, please enable debug output and let me know what line is being suggested repeatedly.

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
