### ISSUE TITLE
Not detecting/suggesting Unstable Affliction

### ISSUE THREAD

**Issue by Dubzie** [herotc/hero-rotation#874]
Char lvl 40
Spell ID 342938

Max DPS addon is also not working but is looking for ID (316099)
https://www.curseforge.com/wow/addons/maxdps-warlock/issues/16

**Comment by Cilraaz** [comment]
Spell ID 316099 is the ID that we use as well, as that is the Spell ID used at max level. Unfortunately, we do not guarantee functionality below max level.

**Comment by Dubzie** [comment]
War mode/Battlegrounds changes it to Spell ID 342938

**Comment by Cilraaz** [comment]
That's caused by the Rampant Afflictions PvP talent. As PvP is more situational and less rotational, we do not support PvP.
