### ISSUE TITLE
[Warlock - Destro] Rain never suggested

### ISSUE THREAD

**Issue by MatteoLombardi** [herotc/hero-rotation#875]
Hello, warlock is simply broken. I've done a dungeon run (full set + sigil) with 9+ mobs pulled. Addon suggests to chaos bolt. Always, as only shard spender.

Draught hit lock too? No rain!

**Comment by GarrettCottrell** [comment]
Yup - I actually came here to make the same exact post - never once has rain of fire ever been recommended at any point in ayn dungeon I've played regardless of pull size

4 pc equipped + double leggo 
Tlaent Setup:

2/1/3/1/2/2/1

**Comment by Cilraaz** [comment]
It looks like the target counter was being called incorrectly. This should be fixed in commit https://github.com/herotc/hero-rotation/commit/344519d5b087053c363c0f5cfb88898c69480f2e

**Comment by GarrettCottrell** [comment]
In order to get the most recent commit active in game can I do that via curseforge? In curseforge it says the most recent version is 9.2.5.04 but I doubt that's the one you just released

Thanks for making the change so quickly!

**Comment by Cilraaz** [comment]
You'd normally need to grab the update from the github. I went ahead and pushed a version 9.2.5.05, which includes this fix, though. That should show up on CurseForge soon-ish.

**Comment by GarrettCottrell** [comment]
It's working fine now - the only issue im seeing is that when inferno is talented, on 3 targets  its still recommending chaos bolts. 

With inferno talented, even with havoc up - it should recommend rain of fire on 3 targets (havoc is simply used for soul shard generation in this scenario) - of course this is all assuming tier is equipped
![4target](https://user-images.githubusercontent.com/49660931/180950670-8b9e4be6-2bf6-4e2e-a54a-418e992df723.png)

thats example of it recommending chaos bolt on 4 targets, which as far as I understand it should 100% be a ROF recommendation with 4set

**Comment by MatteoLombardi** [comment]
![WoWScrnShot_072622_104626](https://user-images.githubusercontent.com/38320292/180964517-83cb74a8-9b59-440e-b297-71813a352bae.jpg)

Not working at all for me, still same old chaos bolt spam

**Comment by Cilraaz** [comment]
> Not working at all for me, still same old chaos bolt spam

The only way for the addon to know that there are multiple targets (when playing solo) is to use an AoE ability, specifically Cataclysm or Summon Infernal. Havoc cleaving to extra targets won't work, as the addon doesn't understand the difference between Havoc cleaving multiple targets next to each other or hitting two targets across the room from each other with the same spell. When in a group or raid, it will also include targets hit by other party members' AoE abilities. That target count identification also resets after 5 seconds of solo play (4 seconds in a group, 3 seconds in a raid).

> It's working fine now - the only issue im seeing is that when inferno is talented, on 3 targets its still recommending chaos bolts.

It looks like handling of APL lines specific to Tier 28 bonuses had not been included. This has been included in commit https://github.com/herotc/hero-rotation/commit/e966b57fc514d1619d9adf60195f831d0d05c2dd

This update includes 2 lines specific to Rain of Fire and causes it to be suggested more often.

**Comment by GarrettCottrell** [comment]
Great explanation as to how the addon handles aoe scenarios

Yeah that commit seems like exactly what was missing - only issues left seemed (in my limited playtesting) to do with ROF use on smaller target counts, a situation which had rotationally been changed quite a bit by the tierset increasing ROF value at those target counts.

One heads-up - with the nerfs to destro's blasphemy hitting next week the target count changes to ROF recommendations may need to be updated again. (As you correctly updated in your commit - current target count recommendation should effectively be  > 1 but I would imagine its worth keeping an eye out for the blasphemy nerfs potentially (?) chaging the APL in very low target count scenarios specifically with regards to ROF recommendations - obviously just something to keep in mind - it may have no impact 

I'll play around with it a bit at lunch or after work today but my guess is that it will be good to go

Again, as always, thanks for the speed of getting a new commit pushed - always appreciated.

**Comment by GarrettCottrell** [comment]
For getting the latest commit, I assume I just download zip from the image below and then replace my current herorotation folder within my wow addon folder with the one I downloaded most recently?

![download zip](https://user-images.githubusercontent.com/49660931/181049906-0ccd1519-e30b-414a-8250-2753cf160146.png)

**Comment by Cilraaz** [comment]
That Download Zip option will pull the latest version of all files for the addon. If you download this zip, only copy the HeroRotation and class folders into your Interface\Addons folder. You don't need the HeroRotation_ClassTemplate folder, .github folder, or any of the individual files.

If you want to update just a single file, such as just Destruction.lua for this update, navigate to the file in the github, right-click Raw, and Save As. Then you can replace just the single file.

![image](https://user-images.githubusercontent.com/12204132/181056828-02b74563-ec45-4d50-864f-4e4a4153dfa9.png)

Either way would work for this update.

**Comment by GarrettCottrell** [comment]
hm, I copied the raw file and replaced my old file. I diff checked the two files and the contents of the destruction lua file on github and my local file are identical. I also made sure that wow wasn't running when I made the file changes and reloaded once I opened WoW just to be sure.  I am still not receiving ROF recommendations on 3 targets - prior to this clip I had both been spamming ROF and recently cast an infernal.

![3 target chaos bolt](https://user-images.githubusercontent.com/49660931/181064357-97678b5d-633b-4b4f-ae04-8d80c2c7be74.png)

**Comment by Cilraaz** [comment]
When you downloaded the updated file, which branch were you on (the dropdown on the left side)? If you want to be sure you have the latest version of the file, Destruction.lua line 229 should be:

`if S.RainofFire:IsReady() and Player:SoulShardsP() >= 3 and (Player:HasTier(28, 4)) then`

That was a newly added line in the latest update.

**Comment by GarrettCottrell** [comment]
Yeah that is identical to my local line 229 - I also had checked removed lines from the commit and those are no longer in the local file. I also checked other additions from the commit and those are all in my local

To answer your specific question - I was in the shadowlands branch

**Comment by Cilraaz** [comment]
It looks like an issue (again) with target detection. Since you're using Inferno, you don't have Cataclysm for AoE target counting. The Infernal seems to not be working currently, which is something that will take more time to dig into. In the meantime, I added Rain of Fire to the target counting system. So casting one should now properly update the target count and begin suggesting AoE abilites.

The target counting timeout is a bit tight for dummy testing, so it might still be a bit iffy on dummies, but in group content it should act much more as expected.

The HeroLib commit was https://github.com/herotc/hero-lib/commit/549269549e79a1820cb2ec4a13b6e7d298467080

**Comment by GarrettCottrell** [comment]
Awesome - thanks. Yeah, it seems like the main issue here is testing this on a dummy/solo play combined with how the target countingsystem works. For that specific purpose, having ROF as part of that system is very helpful (while in practice, in a group it is far less impactful since the group will be using aoe abilties much more consistently)

Will be on tonight to check out the updates. Thanks again

Is including soul rot as part of the target counting system practical/useful? 

I'm a user with no knowllege of how this works and  I open with a recommended incinerate prepull - im tthen recommended immolate + soul rot+infernal and becuase none of those trigger target counting currently, I continue to cast chaos bolts as recommended (never thinking to cast rain of fire because it has not been recommended to me yet)

 I don't know how lua works etc so no idea if this thought process is practical or not and even if practical would most likely only be very impactful in solo play/dummy practice

**Comment by GarrettCottrell** [comment]
Also - for this change, I assume I can just take the shadowlands/HeroLib/Events/SplashEnemies.lua file and replace the one I have with that?

**Comment by Cilraaz** [comment]
> Is including soul rot as part of the target counting system practical/useful?

I'd attempted to add it without success. The Splash Damage (target counting) system is fairly complex (and written by another dev), so I might have to have someone else take a peek.

**Comment by Cilraaz** [comment]
I've updated a few more things tonight. The Destruction.lua file had a minor update to use a wider range when checking for targets, which allows the Infernal's initial splash to be counted. I've also tweaked SplashEnemies.lua in HeroLib, which allows it to work with Soul Rot.  If you update both files, AoE should be more usable.

**Comment by GarrettCottrell** [comment]
ahh very nice - great changes. Thank you

**Comment by GarrettCottrell** [comment]
Changes work great btw - huge playability difference from a couple days ago
