### ISSUE TITLE
[Mage - Fire] Stuck on spamming Firestrike in AoE and Scorch is ST

### ISSUE THREAD

**Issue by MatteoLombardi** [herotc/hero-rotation#876]
Hi, I think something in Fire mage might be broken as APL predictions. In AoE fights the addon seems to want to hard cast flamestrike all the time. In Single Target it seems to fail to try and get hot streaks and scorches a whole lot, with some fireballs sometimes

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
