### ISSUE TITLE
Support for 10.0

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#878]
I guess just a general question - do you intend to continue support for this addon with the new talent system moving into 10.0?

**Comment by Cilraaz** [comment]
Yes. We've already created a dragonflight branch, which is functioning on beta (and should function on the PTR).

Note: APLs haven't been updated, just core functionality.

**Comment by GarrettCottrell** [comment]
Am I missing a dependency? I downloaded the herorotation shadowlands branch as well as the dbc/lib shadowlands branches and copied the files into my beta addon folder. 
![missingdependency](https://user-images.githubusercontent.com/49660931/191886992-a449d32c-63aa-4ef8-9a7f-9980e0a1412f.png)

**Comment by Cilraaz** [comment]
I have no idea what's in your hero-lib-dragonflight and hero-dbc-dragonflight folders, but that's not the proper file structure.
