### ISSUE TITLE
[DH Havoc] Double trinket trouble

### ISSUE THREAD

**Issue by MatteoLombardi** [herotc/hero-rotation#879]
Demon hunter seems to have pretty big issues with trinkets.

1) The "show trinket" setting is useless, even if set FALSE (also hardcoding it) it still shows trinket
2) So'leah's trinket keeps on getting suggested even if both own trinket and another player's trinket buffs are present.

**Comment by Cilraaz** [comment]
1. Items will obey the show trinket setting as of commit https://github.com/herotc/hero-rotation/commit/e4a5a09255bd1c1b1105f7bd5d93a45febdb70a6
2. So'leah's should only be suggested when neither buff is up. If it's being suggested while either is up, I would need to know the spell ID of the buff, as it would need to be added to the code.

**Comment by MatteoLombardi** [comment]
The ID of my buff on the So'leah is 368512, and I can confirm that with this buff up, it still gets suggested
When I'll happen to be selected by someone I will comment that ID as well

**Comment by Cilraaz** [comment]
I see the issue. Havoc bypasses our default trinket handler by referencing the trinket slots directly. I'll see if I can put together a fix for this.

**Comment by Cilraaz** [comment]
Please try again with the changes in the latest two commits:
https://github.com/herotc/hero-lib/commit/030c7e38689c1468afeb900dcdccc62aa8883f7c
and
https://github.com/herotc/hero-rotation/commit/e8f8de71f50907fa2e0970e8a6fad57ef27f07ca

These should make So'leah's act properly.

**Comment by MatteoLombardi** [comment]
Checked the code and it seems fine to me, unfortunately I'm having issues testing it in game cause with the current version on the addon, copying the commit for Havoc, the specId (577) seems not to match anything. Maybe another change in another commit I missed?

**Comment by Cilraaz** [comment]
From the past release version, you'd need the most recent Havoc commit as well as https://github.com/herotc/hero-rotation/commit/e4a5a09255bd1c1b1105f7bd5d93a45febdb70a6

Safest bet would probably just be to replace your Havoc.lua file with the contents of the github version: https://raw.githubusercontent.com/herotc/hero-rotation/shadowlands/HeroRotation_DemonHunter/Havoc.lua

**Comment by Cilraaz** [comment]
I've also pushed version 9.2.7.02 of HeroRotation and HeroLib, which will include these changes.
