### ISSUE TITLE
пират рога

### ISSUE THREAD

**Issue by hubikys** [herotc/hero-rotation#881]
при провидении ротации, не учитывает бонус сета, и место устранения рекомендует промеж глаз, но перед этим уже разредили 6 пуль с сета

**Comment by mhunk** [comment]
google translate: (when providing a rotation, it does not take into account the set bonus, and recommends the place of elimination between the eyes, but before that, 6 bullets from the set have already been thinned out)

**Comment by EvanMichaels** [comment]
Not aware of at Outlaw set bonus issues as far as I'm aware. Although set bonuses will be deleted in like 1-2 weeks so it's likely not an issue anyway.

**Comment by Cilraaz** [comment]
Closing this issue, as the release of 10.0 will require full rewrites of all spec profiles.
