### ISSUE TITLE
Hero Rotation isn't showing up on screen

### ISSUE THREAD

**Issue by orcphelia** [herotc/hero-rotation#884]
Exactly what the subject says. I have it enabled, but since pre patch, it isn't on the screen. I know the new UI is breaking a lot of addons. Is this just me?

**Comment by Hyrpsup** [comment]
Does work if you download the current HeroRotation / HeroDBC / HeroLib from github

**Comment by Cilraaz** [comment]
As stated, you would need to download the updated versions of HeroRotation, HeroLib, HeroCache, and HeroDBC from their respective github pages. Since there are currently only two completed spec profiles, we have not pushed a 10.0 version yet.
