### ISSUE TITLE
Outlaw RTB Logic doesn't seem to be working as intended

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#886]
`else
      -- # Reroll BT + GM or single buffs early other than Broadside, TB with Shadowdust, or SnC with Blunderbuss
      -- actions+=/variable,name=rtb_reroll,value=rtb_buffs<2&(!buff.broadside.up&(!runeforge.concealed_blunderbuss|!buff.skull_and_crossbones.up)&(!runeforge.invigorating_shadowdust|!buff.true_bearing.up))|rtb_buffs=2&buff.buried_treasure.up&buff.grand_melee.up
      if RtB_Buffs() == 2 and Player:BuffUp(S.BuriedTreasure) and Player:BuffUp(S.GrandMelee) then
        Cache.APLVar.RtB_Reroll = true
      elseif RtB_Buffs() < 2 and (not Player:BuffUp(S.Broadside) and (not ConcealedBlunderbussEquipped or not Player:BuffUp(S.SkullandCrossbones))
        and (not InvigoratingShadowdustEquipped or not Player:BuffUp(S.TrueBearing))) then
        Cache.APLVar.RtB_Reroll = true
      else
        Cache.APLVar.RtB_Reroll = false
      end
    end`
        
        
![rerolllogic](https://user-images.githubusercontent.com/49660931/198856882-bc2554e5-b89b-4b8e-a7e5-bbfa30ccf153.png)
 this seems to not be a correct recommendation - perhaps I'm wrong but there is a 5 buff with 11s remaining and I'm being recommended to reroll off of it

**Comment by EvanMichaels** [comment]
Sounds like you are likely on the older version. The pre-10.0 method for determining RtB duration was made non-functional by the patch. Please update to 10.0 version!

**Comment by GarrettCottrell** [comment]
Thanks - I currently have version 10.0.0.01 from curseforge. In order to get the version you're referring to, should I download directly from github? There does not appear to be an option to update past what I am currently using in curseforge
![herorotation](https://user-images.githubusercontent.com/49660931/198857814-513f4838-a024-4851-8dd0-0dad166acfed.png)

**Comment by EvanMichaels** [comment]
I've triggered a new version to be published. You can grab it directly from here or you can wait for CurseForge to pick it up. Hopefully shouldn't take long. Either 10.0.0.02 or 10.0.0.03 should work.

**Comment by GarrettCottrell** [comment]
Thanks - appreciate such a fast response - awesome work with the addon btw, very cool
