### ISSUE TITLE
Outlaw Rogue - Suggesting Early Finishers (without bs or 6 stacks of fth) also - suggesting BTE with gsw buff already active

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#888]
Title says most of it - again, if this isn't helpful let me know but there seems to be pretty consistent early finishers suggested when I don't have 6 opp stacks or bs buff. 

Also, I notice sometimes I'll already have a gsw buff and it recommends bte without consuming the active buff. 

Both of these could just be me misunderstanding outlaw rotation but I believe they are both mistakes so figured I'd just call it out again and if it's working as intended just ignore :)

**Comment by EvanMichaels** [comment]
BtE can still be recommended depending on the duration of the debuff regardless of if you have the GSW buff.

Not sure what you mean by early finishers though. Would need some more examples of that.

**Comment by GarrettCottrell** [comment]
yeah I figured that was too vague, ill try and grab some example screenshots this evening of what I believe to be mistakes (but could be me just bein dumb lol)

**Comment by GarrettCottrell** [comment]
wrt to the bte debuff - does this change in aoe? i.e if I'm hitting 10 mobs should I still be getting recommendations to overrite gsw in deference to refreshing bte debuff?
