### ISSUE TITLE
[Ret Paladin] Suggestions intermittent

### ISSUE THREAD

**Issue by daagar** [herotc/hero-rotation#89]
Protection paladin works perfectly. However, when in Retribution spec, the suggestions don't seem to work. It suggests Judgement then Wake of Ashes. At this point, it just goes blank. After some time, it will suggest Judgement again, and occasionally will suggest Crusader Strike. Templar's Verdict never comes up, and Wake of Ashes doesn't come back up until a new fight. This happens both with the current release, and the latest alpha. I suspect user error, just not sure what.

**Comment by daagar** [comment]
Just discovered that if I toggle the CDs option to 'off', the rotation works fine.

**Comment by Aethys256** [comment]
Most likely a bug, I have to rework the Retribution APL. I have some spare time during the holidays, I'll look into.

**Comment by aethys256** [comment]
Closing since BfA is around the corner and the discussion is no longer relevant.
