### ISSUE TITLE
Unholy DK - Recommends Outbreak and then stops recommendations (Beta)

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#890]
This may not be relevant since it's specific to the beta version of HeroRotation but on beta, the addon will recommend Outbreak but then as soon as I press outbreak,  the addon stops all recommendations entirely until the plague falls off and then it will recommend outbreak again and if I press outbreak again, it will do the same thing - just stop all further recommendations entirely. 

For Beta I am currently using:

HeroRotation-10.0.2.03
HeroLib-10.0.2.02
HeroDBC-10.0.2.01

Currently there is no ability to upgrade past any of these versions that I'm using in curseforge.

**Comment by GarrettCottrell** [comment]
Hm, yeah so I made another DK where the addon appeared to be working correctly but after casting outbreak+unholy assault+unholy blight... the addon just permanently recommends pooling and that remains the only recommendation

**Comment by GarrettCottrell** [comment]
Here's a video that hopefully clarifies what can tough to describe in text:

https://vimeo.com/773049507/e303506c16

**Comment by Cilraaz** [comment]
I can replicate the issue on beta, but not on live. It might be a talent change or something that hasn't been accounted for in the pre-patch APL. Since it's only an issue on the beta, we're probably going to just ignore it for now. If it becomes an issue upon expansion launch, we'll figure it out.
