### ISSUE TITLE
Assasination not supported on live currently

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#891]
This is the msg I get when I spec into assassination
![assasinationlive](https://user-images.githubusercontent.com/49660931/204195183-91a49eba-aa44-4812-898b-03cc31ded0b9.png)

If this is known/expected - no worries, just for some reason I thought it was supported currently

I am on:

HeroRotation-10.0.2.08
HeroLib-10.0.2.02
HeroDBC-10.0.2.01

**Comment by Cilraaz** [comment]
[https://github.com/herotc/hero-rotation#supported-rotations](https://github.com/herotc/hero-rotation#supported-rotations)

It is not yet supported.
