### ISSUE TITLE
[Rogue - Subtlety] shadowdance icon is half shadowstrike icon

### ISSUE THREAD

**Issue by TopherBrowne** [herotc/hero-rotation#892]
Icon shown for ShadowDance is 50/50 with icon for ShadowStrike.
![WoWScrnShot_112822_162012](https://user-images.githubusercontent.com/48744446/204394270-74c74f39-1c9e-4619-affc-4d0a65c1e297.jpg)

**Comment by EvanMichaels** [comment]
Yes, this is intentional. It is showing you are supposed to Shadow Dance into Shadow Strike. It shows both for anything going into Stealth to give you time to react.

**Comment by TopherBrowne** [comment]
Ok. That's good info. It's not very clear just by looking at it. Would two icons with an arrow (glowing?) be  a better way to communicate the intent?
