### ISSUE TITLE
[Rogue - Outlaw] KiR Icon Displaying in main icon

### ISSUE THREAD

**Issue by Exsol-bit** [herotc/hero-rotation#894]
Keep it Rolling (KiR) is displaying as the main icon, I think this should be recognized as a Cooldown.

If at all possible with the additional configuration some CD's have to place it to in Suggested/Suggested Right or Cooldown.
![Screenshot 2022-12-02 155239](https://user-images.githubusercontent.com/52397322/205224681-6f3a77d3-3ca8-4fa2-ac6d-c852cbfaf6a8.jpg)

**Comment by EvanMichaels** [comment]
Fixed in https://github.com/herotc/hero-rotation/commit/7c08282c26fbe6f41b08769f90b08950e4da6b7d
