### ISSUE TITLE
Destruction Warlock RagingDemonFire LUA error

### ISSUE THREAD

**Issue by shadofall** [herotc/hero-rotation#896]
2557x HeroRotation_Warlock/Destruction.lua:247: attempt to index field 'RagingDemonfire' (a nil value)
[string "@HeroRotation_Warlock/Destruction.lua"]:247: in function <HeroRotation_Warlock/Destruction.lua:219>
[string "@HeroRotation_Warlock/Destruction.lua"]:483: in function `?'
[string "@HeroRotation/Main.lua"]:455: in function <HeroRotation/Main.lua:433>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = "attempt to index field 'RagingDemonfire' (a nil value)"
Settings = <table> {
 Commons = <table> {
 }
 General = <table> {
 }
 Destruction = <table> {
 }
}
Items = <function> defined @HeroRotation_Warlock/Destruction.lua:142
oGCD = <function> defined @HeroRotation_Warlock/Destruction.lua:152
VarHavocActive = false
VarHavocRemains = nil
Player = <table> {
 CovenantID = <function> defined @HeroLib/Class/Unit/Player/Main.lua:58
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:595
 GCDStartTime = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:70
 Race = <function> defined @HeroLib/Class/Unit/Player/Main.lua:46
 Insanityrain = <function> defined @HeroLib/Class/Unit/Player/Power.lua:647
 FocusLossOnCastEnd = <function> defined @HeroLib/Class/Unit/Player/Power.lua:226
 PainMax = <function> defined @HeroLib/Class/Unit/Player/Power.lua:724
 IsInVehicle = <function> defined @HeroLib/Class/Unit/Player/Main.lua:124
 IsInParty = <function> defined @HeroLib/Class/Unit/Player/Main.lua:33
 EnergyDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:279
 Fury = <function> defined @HeroLib/Class/Unit/Player/Power.lua:697
 InstanceInfo = <function> defined @HeroLib/Class/Unit/Player/Instance.lua:22
 RageDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:119
 FocusTimeToXPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:202
 MaelstromPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:553
 ArcaneCharges = <function> defined @HeroLib/Class/Unit/Player/Power.lua:665
 IsInDungeonArea = <function> defined @HeroLib/Class/Unit/Player/Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib/Class/Unit/Player/Tank.lua:57
 UpdateActiveLegendaryEffects = <function> defined @HeroLib/Class/Unit/Player/Equipment.lua:144
 SoulShardsDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:469
 EssenceDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:766
 AffectingCombat = <function> defined @HeroRotation_Warlock/Overrides.lua:209
 GetEnemiesInRange = <function> defined @HeroLib/Class/Unit/Player/Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib/Class/Unit/Player/Main.lua:160
 PainDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:739
 AttackPower = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib/Class/Unit/Player/Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:744
 PrevOffGCD = <function> defined @HeroLib/Events/Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:632
 ManaDeficitPercentageP = <function> defined @HeroLib/Class/Unit/Player/Power.lua:113
 FuryDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:707
 PrevGCD = <function> defined @HeroLib/Events/Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib/Class/Unit/Player/Power.lua:481
 IsMounted = <function> defined @HeroLib/Class/Unit/Player/Main.lua:28
 E

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/9b53d9b3281367d20baf7b8f5a74850088e426a0
