### ISSUE TITLE
error in battle and or when enemy dies on feral druid

### ISSUE THREAD

**Issue by ghost** [herotc/hero-rotation#898]
Message: Interface/AddOns/HeroLib/Class/Unit/Range.lua:83: Distance must be a number.
Time: Mon Dec  5 18:55:50 2022
Count: 54
Stack: Interface/AddOns/HeroLib/Class/Unit/Range.lua:83: Distance must be a number.
[string "=[C]"]: ?
[string "=[C]"]: in function `assert'
[string "@Interface/AddOns/HeroLib/Class/Unit/Range.lua"]:83: in function `IsInRange'
[string "@Interface/AddOns/HeroRotation/Commons.lua"]:44: in function `Interrupt'
[string "@Interface/AddOns/HeroRotation_Druid/Feral.lua"]:494: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/4ad0aa169f102cee325ea296f22a4f8a7621d8be
