### ISSUE TITLE
[Druid Feral] Rotation stops beeing displayed without reason

### ISSUE THREAD

**Issue by ooniki** [herotc/hero-rotation#900]
Hello,

On the druid feral, rotation stops beeing displayed without reason after a while.

![image](https://user-images.githubusercontent.com/6315012/208300351-dfe8b664-2282-4827-8d6d-3463f521226b.png)

**Comment by ooniki** [comment]
in Druid.lua line 186 there is Sabertooth
![image](https://user-images.githubusercontent.com/6315012/208304246-214c747c-119b-49ab-b06a-83d7a0423ae1.png)
but in Feral.lua line 485 its used as SabertoothBuff
![image](https://user-images.githubusercontent.com/6315012/208304433-4c1117f2-73da-43d5-8ba9-709ac6ddd918.png)
Plz fix it for next release :)

**Comment by ooniki** [comment]
PR here: https://github.com/herotc/hero-rotation/pull/901

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/8091755a5268ddce072ecaa92f50fe6521661715
