### ISSUE TITLE
DK Unholy - When using the addon it doesn't show all the abilities for the rotation

### ISSUE THREAD

**Issue by JamesyBee** [herotc/hero-rotation#903]
![c79450355937dd0c4dcb2393a26812b8](https://user-images.githubusercontent.com/121110673/208691166-68183480-7be3-45ee-9690-660008e36942.png)
I included a screenshot where hekili shows scourge strike but when it comes to using it on rotation it doesn't show.

**Comment by flameninja00** [comment]
also can confirm. main ability area is blank, abilities around it (off-gcd, trinkets, potions, etc) show, but main button is blank.

**Comment by zerogott** [comment]
Any update to that? Was working fine until like lvl 58-60. Now its showing waiting for pool  most of the time. Even with spells and cd's ready.

**Comment by Cilraaz** [comment]
I'm unable to replicate any issue with the Unholy profile. Please provide your talent build.

**Comment by zerogott** [comment]
> 

BwPAAAAAAAAAAAAAAAAAAAAAAAAkISSkISEhIRIkkIRAAAAAAAAAAKHYBHYBHgD4AAAgDcAHo4AtFcAH4AH4AHYBWwBOA
Raiding

BwPAAAAAAAAAAAAAAAAAAAAAAAAiQSCJiERkIRIkkIRAAAAAAAAAAwBWwBWwB4AcgDcgGAAHo4AlDcAH4AH4AHYBWwBOwBA
M+

Builds are from icy-veins.

**Comment by Cilraaz** [comment]
I only have a level 60 DK, but I can't replicate any issues with the profile using either of those talent builds in single target or AoE. What version of HeroRotation are you using? Are you delaying the use of any cooldowns (Gargoyle, Apocalypse, etc)?

**Comment by zerogott** [comment]
> I only have a level 60 DK, but I can't replicate any issues with the profile using either of those talent builds in single target or AoE. What version of HeroRotation are you using? Are you delaying the use of any cooldowns (Gargoyle, Apocalypse, etc)?

Seems like that happens if no AotD is ready and a new mob is being pulled.
After that most of the time its showing Pool even with runes and enough rp, if AotD is up again it works again.
Using the latest version of HR.
