### ISSUE TITLE
LUA errors when equipped with windscar whetstone

### ISSUE THREAD

**Issue by Ryjhan** [herotc/hero-rotation#904]
If i have cooldown displays enabled, anytime my windscar whetstone is available to be used i am flooded with the following error:

11870x HeroRotation_Rogue/Assassination.lua:395: attempt to call method 'IsTrinketBlacklisted' (a nil value)
[string "@HeroRotation_Rogue/Assassination.lua"]:395: in function <HeroRotation_Rogue/Assassination.lua:366>
[string "@HeroRotation_Rogue/Assassination.lua"]:799: in function `?'
[string "@HeroRotation/Main.lua"]:455: in function <HeroRotation/Main.lua:433>

Locals:
Skipped (In Encounter)

if i disable cooldown display the errors stop, and if i actually use my whetstone the errors stop until the trinket comes back off cooldown.

**Comment by EvanMichaels** [comment]
You need to update HeroLib as well.

**Comment by Ryjhan** [comment]
I updated HeroLib and HeroDBC before i posted this issue, did not help.
