### ISSUE TITLE
outlaw

### ISSUE THREAD

**Issue by unrealshape** [herotc/hero-rotation#906]
new outlaw simc are available and blade rush is underused... anyone know why?

**Comment by mhunk** [comment]
because the APL's havnt been updated to match simc yet, you can find them;
https://github.com/herotc/hero-rotation/blob/dragonflight/HeroRotation_Rogue/Outlaw.lua
if you wanted to submit a PR with the correct implementation :).

**Comment by EvanMichaels** [comment]
Outlaw module will be updated in a few days. Although the difference to Blade Rush usage is fairly minimal. The rules did not change significantly.

**Comment by unrealshape** [comment]
> because the APL's havnt been updated to match simc yet, you can find them; https://github.com/herotc/hero-rotation/blob/dragonflight/HeroRotation_Rogue/Outlaw.lua if you wanted to submit a PR with the correct implementation :).

https://github.com/simulationcraft/simc/blob/dragonflight/engine/class_modules/apl/rogue/outlaw_df.simc here we have an simc that updated 2 days ago and sure i can read that but blade rush is underused, im m+ HOV 12 times .. i search that issue but cant find now

**Comment by EvanMichaels** [comment]
Given that I am the person who made those other changes, I am aware of what was changed. The changes were to relax the energy conditions in multi-target scenarios but it still is a relatively minor change and was only in the realm of 0.2-0.3% DPS.

**Comment by unrealshape** [comment]
> Given that I am the person who made those other changes, I am aware of what was changed. The changes were to relax the energy conditions in multi-target scenarios but it still is a relatively minor change and was only in the realm of 0.2-0.3% DPS.

fine

**Comment by unrealshape** [comment]
lets close this ticket thanks for information!³³
