### ISSUE TITLE
[Hunter] Racials showing in main icon with or without "Show GCD as Off GCD" checked

### ISSUE THREAD

**Issue by ryanbowen** [herotc/hero-rotation#909]
Noticed it with at least Blood Fury. MM (maybe BM/Survival also, didn't check) likely needs the same treatment Ret got in [this commit](https://github.com/herotc/hero-rotation/commit/eba94e44530335c21a513709f45710112e188765). 

CC: @Cilraaz since you handled it in that commit.

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/91894b154969b5c35b328a7481bdb7c51ad1d336
