### ISSUE TITLE
[Warrior Arms] Thunderous Roar suggested before Test of Might

### ISSUE THREAD

**Issue by Exsol-bit** [herotc/hero-rotation#910]
Thunderous Roar is suggested during Colossus Smash/Warbreaker (debuff on target), rather than after once Test of Might procs.

![image](https://user-images.githubusercontent.com/52397322/212798358-611abe07-31b4-4ec4-893c-a6020df461f3.png)
![image](https://user-images.githubusercontent.com/52397322/212798455-daf50c6d-a711-4152-b474-18354ce6ee53.png)

**Comment by Cilraaz** [comment]
Please enable debug output and let us know what it says when Thunderous Roar is suggested incorrectly.

**Comment by Exsol-bit** [comment]
[Hero Rotation] thunderous_roar single_target 103

Shows up when testing both Test of Might & In For The Kill.

Changing line 299 to:

`  if CDsON() and S.ThunderousRoar:IsCastable() and (Player:BuffUp(S.TestofMightBuff) or (Player:BuffUp(S.TestofMightBuff) and Target:DebuffUp(S.ColossusSmashDebuff))) then`

Resolved the issue, but I am almost certain anything after OR is redundant as both Test of Might & ColossusSmashDebuff can not be true at the same time.

**Comment by Cilraaz** [comment]
This should be fixed in commit https://github.com/herotc/hero-rotation/commit/e6619401fc1e61de6d9125b5ba47042a2ed4374a

The intent of that line is that Test of Might is active or not talented and Colossus Smash is up. That's been fixed.
