### ISSUE TITLE
Warlock only suggesting 3 abilities

### ISSUE THREAD

**Issue by batmanisme159** [herotc/hero-rotation#913]
hero only suggest that i use demonic strength then soul strike... and then only shadowbolt and soul strike on cd. 

this cannot be correct, as one of our best things is call dread stalkers

**Comment by Cilraaz** [comment]
I've tried multiple builds and can not replicate this issue. The rotation works as expected for me. What talent build are you using? Are you getting any lua errors from the addon?

**Comment by Soulsmacka** [comment]
Yeah, I've had the same issue where it bugs and suggests spamming choas bolts and it doesn't seem to clear until I personally remember to call dread stalkers, then it goes back to working.  He's probably using this cleave build: BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCAAAAAKRSSCJQCJSkSaJROABAAAAAAJ 
Or this Single target build: BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCAAAAAKRSSCCkEJkDkiWSSOABAAAAAAJ

It happens on both and some other builds.

**Comment by Soulsmacka** [comment]
> I've tried multiple builds and can not replicate this issue. The rotation works as expected for me. What talent build are you using? Are you getting any lua errors from the addon?

Yeah, I've had the same issue where it bugs and suggests spamming choas bolts and it doesn't seem to clear until I personally remember to call dread stalkers, then it goes back to working. He's probably using this cleave build: BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCAAAAAKRSSCJQCJSkSaJROABAAAAAAJ
Or this Single target build: BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCAAAAAKRSSCCkEJkDkiWSSOABAAAAAAJ

It happens on both and some other builds.

**Comment by Cilraaz** [comment]
I just tested both builds and they work as expected for me.
