### ISSUE TITLE
[Bug]: Incorrect Target Count on Valdrakken Cleave Dummies

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#914]
HeroRotation: 10.0.2.29
HeroDBC: 10.0.2.02
HeroLib: 10.0.2.11

**Comment by GarrettCottrell** [comment]
Also, not recommending shadow word: death while mind bender is active on 5 target dummy

**Comment by GarrettCottrell** [comment]
This is resolved - for some reason its behavior on 5 target dummies clumped up is different than how it behaves in an instance. Worked fine when I was in an instance

**Comment by Cilraaz** [comment]
Which dummies were you using when it was not acting correctly? I'll double check that we have the IDs set correctly in HeroLib.

**Comment by GarrettCottrell** [comment]
it was the 5 stack in the dummy room in valdraken

**Comment by Cilraaz** [comment]
For some reason, those 5 only count as 3 targets. I'll have to look into it further. The IDs are all the same, so I'm not sure why they're not all being counted.

**Comment by Cilraaz** [comment]
This doesn't appear to be an issue with those dummies any longer. They now get counted properly. I'm guessing it might have been something API related.
