### ISSUE TITLE
Shadow Priest stops recommendations randomly in dungeons

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#915]
The rotation works fine and then it just stops all recommendations for periods of time and then will start recommending again and then stop again etc

**Comment by Cilraaz** [comment]
Does it show a Pool icon or just disappear entirely? If the latter, it sounds like a lua error is occurring.

**Comment by GarrettCottrell** [comment]
recommendations disappear entirely. I will change back to default plater profile (I was thinking, if nothing is seemingly wrong with the app it could be that my new profile for some reason isn't registering) but yeah recs disappear entirely and it almost never happens on st from the one dungeon I did (in that dungeon it never happened on a st boss but happened verrry frequently on trash pulls)

**Comment by GarrettCottrell** [comment]
the behavior is akin to if someone was turning the addon off and then turning it back on - that's what the result was appearing like (I wasn't doing this obviosuly)

**Comment by GarrettCottrell** [comment]
Looks like the behavior is also happening on the 5 target dummy in valdraaken (none of this was happening before the new patch)

**Comment by Cilraaz** [comment]
I'm unable to replicate any issue, but my Priest is only 60. If the icon is disappearing entirely, there's a lua error. I would need that error to troubleshoot the issue.

**Comment by GarrettCottrell** [comment]
okay, I changed plater profile - issue persisted. I'll turn on LUA errors and see if I can grab it

**Comment by GarrettCottrell** [comment]
Message: Interface/AddOns/HeroLib/Class/Unit/Aura.lua:36: attempt to index local 'ThisSpell' (a nil value)
Time: Wed Jan 25 10:59:26 2023
Count: 706
Stack: Interface/AddOns/HeroLib/Class/Unit/Aura.lua:36: attempt to index local 'ThisSpell' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroLib/Class/Unit/Aura.lua"]:36: in function <Interface/AddOns/HeroLib/Class/Unit/Aura.lua:32>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HeroLib/Class/Unit/Aura.lua"]:101: in function `BuffRemains'
[string "@Interface/AddOns/HeroLib/Class/Unit/Aura.lua"]:119: in function `BuffUp'
[string "@Interface/AddOns/HeroRotation_Priest/Shadow.lua"]:565: in function <Interface/AddOns/HeroRotation_Priest/Shadow.lua:525>
[string "@Interface/AddOns/HeroRotation_Priest/Shadow.lua"]:660: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>

Locals:

**Comment by Cilraaz** [comment]
This has now been fixed in commit https://github.com/herotc/hero-rotation/commit/cfa3b5686ae0c3ada279856697c2a2a1fe1cb1cf

**Comment by GarrettCottrell** [comment]
is this commit included in HeroRotation-10.0.5.03 (only asking becuase after I saw it was commited I refreshed curseforge and had an update) if it is - I'm still having the same issue - if it isn't no worries, I'll wait for it to be released

**Comment by Cilraaz** [comment]
No. This is the first commit after 10.0.5.03's release. If you're comfortable modifying the files on your own, you can open HeroRotation_Priest\Priest.lua and modify line 135. Change:
DarkReveries                = Spell(394963),
to
DarkReveriesBuff            = Spell(394963),

That will resolve the issue.

**Comment by GarrettCottrell** [comment]
Yup sounds good - appreciate such fast response as always. Thanks
