### ISSUE TITLE
[Enhancement]: allow Void Torrent to be suggested off of the main icon (Shadow Priest)

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#921]
### What feature would you like to have added?

VoiT is a pretty powerful aoe burst tool and would be helpful to allow for it off the gcd so that one could more easily hold VoiT while still following the addon

**Comment by Kutikuti** [comment]
Added in https://github.com/herotc/hero-rotation/commit/77cf3b8d3b218d9060d68e12f674654c1a81a149

**Comment by GarrettCottrell** [comment]
Any idea of when this change will go live?

**Comment by Cilraaz** [comment]
I just pushed version 10.0.5.07, which should go to the normal download locations shortly. It will include this change.
