### ISSUE TITLE
[Bug]: Shadow Priest Recommendations get stuck on mind spike/mind flay sometimes

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#924]
### What version of HeroRotation are you using?

10.0.5.06

### What version of HeroLib are you using?

10.0.5.01

### What version of HeroDBC are you using?

10.0.5.01

### What is the issue?

90%+ of the time the recommendations work as intended but occasionally, the addon will just get stuck on suggesting mind spike, even with capped mind blast charges + free proc it'll just keep suggesting mind spike and the only way to break it out of this loop is to just press mind blast and then it will often start suggesting normal rotation again. 

Sometimes that doesn't work and then usually after a reload it works properly. Unfortunately, I do not have much more to go off of but figured I'd mention it

### Icon Behavior

None

**Comment by GarrettCottrell** [comment]
So, I figured out what the issue is with this and what causes it. This loop happens only when the target does not have vampiric touch +sw:p (not sure if its just one or the other specifically or wtvr since we play misery mostly but basically it just happens when you dont have dots on target). 

So the addon will recommend shadowcrash but if shadowcrash is recommended off of the main icon (and lets say its a M+ key where you dont want to use shadowcrash to reapply dots) there is no other reminder (specifically from the addon) to apply dots, so it wont recommend a vampiric touch or anything even if the target has no dots (and I'm purposely not wanting to use shadowcrash) - instead, it will just go into an infinite loop of wanting to either mindflay or use mind spike over and over. 

I think having another way other than shadowcrash for the addon to support dot maintenance on targets would be good (whether that's showing vt as a main icon ability when the target has no dots and shadowcrash is being suggested off main icon) but with the way our aoe works, it doesn't make sense for the addon to basically require the user to use shadowcrash in order to mantain dots (otherwise going into a loop of either using only mindflay or only mind spike)

In shadowlands, if you swapped to a target that didn't have dots on them, the addon would actually have like a vampiric touch icon when you swapped (i think it would be off gcd if I recall) but it was basically another way for the addon to support dot maintenance reminders on both st and aoe. 

But basically, because in some (a lot) of aoe builds, shadowcrash is essentially your engine to power all your aoe, it's almost more of a cd now and not something that I would ever want to just always use to apply dots and I think the addon is effectively only wanting to apply dots with shadowcrash and when a user is purposely holding shadowcrash, instead of recommending a vt or something as another way to dot, it just goes into a bugged infinite loop of mindflay or mind spike (until the user applies a dot to the target and then it will continue its rotation normally)

**Comment by GarrettCottrell** [comment]
An example of this, is the last boss of temple. You want to save shadowcrash for the add phase, so during the boss phase you'd only ever want to use vt. But when you hold shadowcrash, the addon doesn't seem to have a way of suggesting another form of dotting and so the boss just goes undotted

This issue only occurs when you are holding shadowcrash. If shadowcrash is on cd and something needs to be dotted, the addon will recognize it and suggest a vt.. but it doesn't seem to basically have a way of handling a situation where a user wants to hold shadowcrash while still dotting with manual vt

**Comment by GarrettCottrell** [comment]
Is this something that is doable or should I anticipate support for this issue not being addressed?

**Comment by Cilraaz** [comment]
Shadow has been updated to the latest APL in commit https://github.com/herotc/hero-rotation/commit/3b5c37a44ec614393244ae0138f941609c5a0b0b

Please let me know if this does not fix the issue.

**Comment by GarrettCottrell** [comment]
Thanks for that - great to see shadow priest being worked on. Thanks!

**Comment by GarrettCottrell** [comment]
If I just copied the HeroRotation_Priest folder from github and replaced my local, outdated, copy of that same folder would that work as a placeholder until this gets pushed to release on curseforge?

**Comment by Cilraaz** [comment]
That should work, but the change is included in version 10.0.5.11, which should be available from CurseForge at this time.

**Comment by GarrettCottrell** [comment]
Ah great - thanks again!
