### ISSUE TITLE
[Bug]: DH Havoc Essence Break not suggested any more

### ISSUE THREAD

**Issue by james-yin** [herotc/hero-rotation#925]
### What version of HeroRotation are you using?

10.0.5.07

### What version of HeroLib are you using?

10.0.5.05

### What version of HeroDBC are you using?

10.0.5.05

### What is the issue?

For Demon Hunter Havoc spec, Essence Break is no longer suggested. This used to work fine.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
If you are running a Momentum build, Essence Break will only be suggested when the Momentum buff is active. If this is not your issue, please provide your talent build.

**Comment by james-yin** [comment]
I usually do not run the momentum build. Here's my export:

`BEkACnvaHJn8GSPD6tpaeczPTRCIhUCSLJRkIkEAAAAAAAtkEEpQSSBJkWkikEJJJA`

Thanks for looking into this.

**Comment by james-yin** [comment]
This is working with latest release.
