### ISSUE TITLE
[Enhancement]: Add a way for addon to suggest manual vt (even if shadow crash is available) - Shadow Priest

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#926]
### What feature would you like to have added?

This is a dovetail off of the bug report I submitted which hasn't been responded to. 

Basically, in M+ it is very common to want to hold shadowcrash (by making sure shadowcrash is being shown off of the gcd). In this situation, a user should still be recommended vampiric touch if a mob needs to be dottted.

For some reason currently, if a user holds shadowcrash, the addon does not suggest any other way of dotting and instead just permanently suggests mindlfay/mindspike until the user either uses shadowcrash or manually dots. 

I would request that instead of going into a mindflay/mindspike loop the addon just suggests vt in concurrence with shadowcrash (if shadowcrash is opted to be shown as off gcd)

**Comment by Cilraaz** [comment]
Duplicate of #924
