### ISSUE TITLE
[Bug]: Cant move icons and after unlocking icons stay as cog wheels

### ISSUE THREAD

**Issue by WorkingBones** [herotc/hero-rotation#928]
### What version of HeroLib are you using?

10.0.5

### What is the issue?

Cant move icons and after unlocking icons stay as cog wheels

**Comment by Cilraaz** [comment]
This is a known issue that occurs when unlocking the addon while on an unsupported spec. If you are having the issue on a spec that is supported by the addon, please let us know which spec.
