### ISSUE TITLE
[Bug]: DK Blood - BugSack reports thousands of errors

### ISSUE THREAD

**Issue by julienripet** [herotc/hero-rotation#929]
### What version of HeroRotation are you using?

10.0.5.09

### What version of HeroLib are you using?

10.0.5.02

### What version of HeroDBC are you using?

10.0.5.02

### What is the issue?

BugSack keeps throwing the following error

<details>
<summary>error</summary>

3849x HeroRotation_DeathKnight/Blood.lua:377: attempt to compare number with nil
[string "@HeroRotation_DeathKnight/Blood.lua"]:377: in function `?'
[string "@HeroRotation/Main.lua"]:455: in function <HeroRotation/Main.lua:433>

Locals:
ShouldReturn = nil
ShouldReturn = nil
(*temporary) = 53
(*temporary) = nil
(*temporary) = 53
(*temporary) = 72
(*temporary) = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:595
 GCDStartTime = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:70
 Race = <function> defined @HeroLib/Class/Unit/Player/Main.lua:45
 Insanityrain = <function> defined @HeroLib/Class/Unit/Player/Power.lua:647
 FocusLossOnCastEnd = <function> defined @HeroLib/Class/Unit/Player/Power.lua:226
 PainMax = <function> defined @HeroLib/Class/Unit/Player/Power.lua:724
 IsInVehicle = <function> defined @HeroLib/Class/Unit/Player/Main.lua:104
 IsInParty = <function> defined @HeroLib/Class/Unit/Player/Main.lua:32
 EnergyDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:279
 Fury = <function> defined @HeroLib/Class/Unit/Player/Power.lua:697
 InstanceInfo = <function> defined @HeroLib/Class/Unit/Player/Instance.lua:22
 RageDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:680
 MaelstromPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:553
 ArcaneCharges = <function> defined @HeroLib/Class/Unit/Player/Power.lua:665
 GetOnUseTrinkets = <function> defined @HeroLib/Class/Unit/Player/Equipment.lua:30
 IsInDungeonArea = <function> defined @HeroLib/Class/Unit/Player/Instance.lua:53
 ActiveMitigationNeeded = <function> defined @HeroLib/Class/Unit/Player/Tank.lua:57
 SoulShardsDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:469
 EssenceDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:766
 GetEnemiesInRange = <function> defined @HeroLib/Class/Unit/Player/Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @HeroLib/Class/Unit/Player/Main.lua:140
 PainDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:739
 AttackPower = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:78
 FocusCastRegen = <function> defined @HeroLib/Class/Unit/Player/Power.lua:208
 PainDeficitPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:744
 PrevOffGCD = <function> defined @HeroLib/Events/Prev_Spell.lua:236
 MasteryPct = <function> defined @HeroLib/Class/Unit/Player/Stat.lua:114
 InsanityPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:632
 ManaDeficitPercentageP = <function> defined @HeroLib/Class/Unit/Player/Power.lua:113
 FuryDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:707
 PrevGCD = <function> defined @HeroLib/Events/Prev_Spell.lua:202
 AstralPowerMax = <function> defined @HeroLib/Class/Unit/Player/Power.lua:481
 IsMounted = <function> defined @HeroLib/Class/Unit/Player/Main.lua:27
 EnergyRegenPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:289
 RunicPowerDeficit = <function> defined @HeroLib/Class/Unit/Player/Power.lua:389
 FuryPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:702
 Insanity = <function> defined @HeroLib/Class/Unit/Player/Power.lua:627
 EnergyTimeToMaxPredicted = <function> defined @HeroLib/Class/Unit/Player/Power.lua:336
 ArcaneChargesPercentage = <function> defined @HeroLib/Class/Unit/Player/Power.lua:670
 AstralPowerDeficitPercentage = <function

</details>

It concerns this line I believe `    if S.DeathStrike:IsReady() and (Player:BuffRemains(S.CoagulopathyBuff) <= Player:GCD() or Player:BuffRemains(S.IcyTalonsBuff) <= Player:GCD() or Player:RunicPower() <= VarDeathStrikeDumpAmt or Player:RunicPowerDeficit() <= VarHeartStrikeRP or Target:TimeToDie() < 10) then`, but I'm not sure which part exactly

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
This should be resolved in commit https://github.com/herotc/hero-rotation/commit/3271e8df4292d87793f23bc6b26b78f1afd93ae1

Please let us know if it's still a problem after applying that change (via either update from github or when the next version is released).

**Comment by Cilraaz** [comment]
No further reports of issues.
