### ISSUE TITLE
[Prot warrior] rotation

### ISSUE THREAD

**Issue by weggert2** [herotc/hero-rotation#93]
Would be very helpful, especially for suggesting casts to properly use devastator talent and vengeance weaving

**Comment by aethys256** [comment]
There is currently no maintainer for Protection Warrior, I play it from time to time and do usually maintain tanks.
To be honest, the easiest way to have it in the addon would be to have a solid APL from SimC.
You should see with theorycrafters from your Discord how to setup one.
