### ISSUE TITLE
[Enhancement]: apl rogue sub works 100%?

### ISSUE THREAD

**Issue by unrealshape** [herotc/hero-rotation#931]
### What feature would you like to have added?

I have the feeling that the APL SUB Rogue is not used 100% - I only use hero as rotation helper and have the feeling that I always use the wrong spells ... when i took a closer look at the code i noticed that it is written a bit complicated i can't follow the apl because there is too much in sub functions...

so the question is there the executable code you have also in "simple" form so i can see or check myself if the "APL" is used...?

best regards

**Comment by EvanMichaels** [comment]
Sub is currently up to date as per the APL. Logic in the module is nested due to macro suggestions so there is not really much way to simplify that in a way that is usable for a player.

I would need more specific examples of what you feel is incorrect, or perhaps videos.

**Comment by unrealshape** [comment]
hey thanks for your fast feedback, i want to make a small video to preview you give me time :-)
