### ISSUE TITLE
[Bug]: Druid/Feral - Not working after opener

### ISSUE THREAD

**Issue by MephysGaming** [herotc/hero-rotation#932]
### What version of HeroRotation are you using?

10.0.5.12

### What version of HeroLib are you using?

10.0.5.02

### What version of HeroDBC are you using?

10.0.5.02

### What is the issue?

When start Feral Rotation, after Prowl/Rake, an error appears and cannot show me no more abilities.

Did reload not working, only GCD works!

Have all abilities in action bar (cat form)

Message: Interface/AddOns/HeroRotation_Druid/Feral.lua:381: attempt to compare boolean with number
Time: Tue Mar 21 11:35:02 2023
Count: 774
Stack: Interface/AddOns/HeroRotation_Druid/Feral.lua:381: attempt to compare boolean with number

Locals:  

![image](https://user-images.githubusercontent.com/128480314/226596473-c43070ca-7631-4318-b128-d873a1d13938.png)

![image](https://user-images.githubusercontent.com/128480314/226596650-eb7b66c0-854a-4b31-b7ad-ce2867389986.png)

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
This has been fixed in commit https://github.com/herotc/hero-rotation/commit/39e2195db5f3631d0730deb52f1deae42b24917f

I've pushed an updated version, 10.0.5.13, which should be available in the normal locations shortly.
