### ISSUE TITLE
Paladin no Templar Strike.[Bug]: 

### ISSUE THREAD

**Issue by Liffendir** [herotc/hero-rotation#933]
### What version of HeroRotation are you using?

10.0.7.01

### What version of HeroLib are you using?

10.0.7.01

### What version of HeroDBC are you using?

10.0.7.01

### What is the issue?

Hello.

So Hero rotation will not show Templar Strike. and just keeps saying pool.

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
Closing this issue. Ret was completely re-written since the 10.0.7.01 release.
