### ISSUE TITLE
[Priest/Shadow]: 

### ISSUE THREAD

**Issue by behemot011** [herotc/hero-rotation#935]
### What version of HeroRotation are you using?

10.1.0.01

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

Filler spell it recommends all the time is shadow word: pain, when it should be mind spike that is replacing mind flay as the new filler spell

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Shadow had not been updated for 10.1.0. It has as of commit https://github.com/herotc/hero-rotation/commit/3d7f05d467fecba8738fe1971a188c45300a8d8a
