### ISSUE TITLE
[Bug]: Getting The included lua error while playing Shadow Priest

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#936]
### What version of HeroRotation are you using?

10.1.0.02

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

![image](https://user-images.githubusercontent.com/49660931/236037977-ddf089f5-049b-48a5-835a-855cff339567.png)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Already fixed as of commit https://github.com/herotc/hero-rotation/commit/387ec4f506c7c9c785f8f6c4ce8e526b7fd9c416
