### ISSUE TITLE
[Bug]: Shadow Priest stops making any recommendations for brief moments 

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#938]
### What version of HeroRotation are you using?

10.1.0.03

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

The shadow priest recommendations will just completely stop for brief moments (not pooling etc - just stop as if the addon is turned off) and then recommendations will resume. This same exact issue happened earlier in 10.0 and was fixed (it seems almost identical to when the issue happened earlier)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
I'm unable to replicate this. 

- What talent build are you using?
- What is the spell suggested prior to the icon disappearing? (Debug Output would be helpful as well)
- Are you receiving any lua errors when this happens?

**Comment by GarrettCottrell** [comment]
I'll try and keep my lua errors enabled in dungeons to provide more information. FWIW - this issue was only happening in dungeons and not on training dummies.

**Comment by Cilraaz** [comment]
I committed a fix for your other bug report, which may be the same issue.

**Comment by GarrettCottrell** [comment]
Yeah I wasn't 100% positive so I made a new report but I had the same thought
