### ISSUE TITLE
[Bug]: Shadow Preist receieving the following LUA error

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#939]
### What version of HeroRotation are you using?

10.1.0.01

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

I received the following lua error while doing the intro quest for the new zone 

![image](https://user-images.githubusercontent.com/49660931/236630421-95ad58f3-f0f1-4ffa-8683-57f708618be7.png)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/bcada8e5aa96f63fc505c67f2a97611f156cd62c
