### ISSUE TITLE
[Bug]: Enhance Shaman receiving the following LUA error

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#941]
### What version of HeroRotation are you using?

10.1.0.03

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

![image](https://user-images.githubusercontent.com/49660931/236648863-8e06613f-6e2a-42b9-862d-2e5c611a49b8.png)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Update to version 10.1.0.04 or later.

**Comment by GarrettCottrell** [comment]
The option to update to version 10.1.0.04 is not currently available via curseforge - I'll wait until it is before making future bug reports

![image](https://user-images.githubusercontent.com/49660931/236649005-f7626ed2-1b3a-4fd8-b203-733a7a0f9edf.png)

**Comment by Cilraaz** [comment]
It looks like CurseForge randomly decided that the newest version was for Classic, rather than Live. I have no idea why. You can update from the github zip or wait for 10.1.0.05. I'll probably push another new version after I finish updating feral.
