### ISSUE TITLE
[Bug]: (subtlety): Cold Blood / Secret Technique / Dance Macabre Interaction

### ISSUE THREAD

**Issue by Furizaa** [herotc/hero-rotation#942]
### What version of HeroRotation are you using?

head

### What version of HeroLib are you using?

head

### What version of HeroDBC are you using?

head

### What is the issue?

Not sure if it is even a bug or what exactly is the cause for this, but the sims always hold Cold Blood for Secret Technique, while the addon uses Cold Blood for Eviscerate.

 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/365742/236678182-2e01de86-6bb5-4d1a-aa07-35fd608ea240.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/365742/236678208-705e0c84-0009-4ef6-8c77-c29dbc01c196.png">

### Reproduction
- Talent Cold Blood, Secret Technique, Dance Macabre
- Unselect "Show Off GCD as off GCD: Cold Blood" in the addon
- Do Rotation

### Workaround 
- Select "Show Off GCD as off GCD: Cold Blood" in the addon, ignore suggestion
- Macro Cold Blood to Secret Technique

### Icon Behavior

None

**Comment by EvanMichaels** [comment]
Haven't really seen this myself and the code specifically checks for SecTec in this regard.
```
  -- actions.cds+=/cold_blood,if=!talent.secret_technique&combo_points>=5
  if S.ColdBlood:IsReady() and not S.SecretTechnique:IsAvailable() and ComboPoints >= 5 then
    if HR.Cast(S.ColdBlood, Settings.Commons.OffGCDasOffGCD.ColdBlood) then return "Cast Cold Blood" end
  end
```
The line that is printing above "Cast Cold Blood" shouldn't be running if you have SecTec talented.

**Comment by mhunk** [comment]
Not able to replicate this either;
![image](https://user-images.githubusercontent.com/47985590/236902957-6b6863d2-f593-4f63-9d14-5b3d2151f10b.png)
![image](https://user-images.githubusercontent.com/47985590/236903193-e0f3b1fb-1da9-4dbe-9b00-6406ca6dde7c.png)
![image](https://user-images.githubusercontent.com/47985590/236902790-2947ffaf-6287-4b51-8523-18fbbccd793d.png)

**Comment by Furizaa** [comment]
I believe it comes from this line which returns CB as `ReturnSpellOnly`.
https://github.com/herotc/hero-rotation/blob/527f04fccf12f57f6bc223c9424c2469fc21414e/HeroRotation_Rogue/Subtlety.lua#L276

It then hits the actual `CastPooling` here: https://github.com/herotc/hero-rotation/blob/527f04fccf12f57f6bc223c9424c2469fc21414e/HeroRotation_Rogue/Subtlety.lua#L899

But if you can't reproduce it then I believe you and you can close it :D I'll try to do a fresh setup before the season hits.

@mhunk It doesn't seem to cast Cold Blood at all for you. Do you perhaps have `Show Off GCD as off GCD: Cold Blood` selected?

**Comment by mhunk** [comment]
those original screenshots were with OGCD enabled.  but it not recommending it i think is by design, your expected to have CB macro'd into SecTech.

Here's the logs with OGCD disabled;

![image](https://user-images.githubusercontent.com/47985590/236917553-903ce14e-a8a2-49b5-9c4f-11714ae11b03.png)
