### ISSUE TITLE
[Bug]: AoE Suggested in Single Target Scenarios

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#944]
### What version of HeroRotation are you using?

10.1.0.06

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

It is necessary to fix ST recognition on such bosses as, Forgotten Experiments when balls appear on the second boss, rotation in ST does not work with the AOE mode enabled. Regardless of where I stand next to or far away, the rotation always shows POOL. Zskarn when bombs and robots appear, it also writes POOL itself, regardless of the distance. Echo of Neltharion in general, everything is broken in AOE. Since the beginning of the battle, as the stone walls appear, the addon thinks that AOE battle is going on and always POOL. And this is only part of what I tested on Surv Hunter. In the raid, the addon often writes POOL in different places and considers some invisible targets in the raid on bosses. I was on a raid in heroic difficulty, and there were errors with the operation of the AOE script, I often had to turn off the function since the rotation always showed POOL.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
What spec?

**Comment by Dragonfo** [comment]
Surv Hunter.

**Comment by Cilraaz** [comment]
I'll have to look into the NPC IDs of some raid adds for ST/AoE detection.

As far as issues with the AoE rotation, I can't replicate any issues. There are times that the rotation shows POOL in the main icon while suggesting abilities for secondary targets. Ensure the CastLeft icon area is not obstructed by any WeakAuras or other UI elements. An example is below. If you confirm that this is not what is happening in your situation, please provide an export string for your talent build so I can test as closely to your setup as possible.

![image](https://github.com/herotc/hero-rotation/assets/12204132/5feb8e37-8ff1-4508-8846-14e680018f3d)

**Comment by Cilraaz** [comment]
I took a cursory glance through the wowhead guide for the fights for any mention of NPC objects during the fights. I didn't notice any that were immune targets, and I experienced no problems with ST/AoE detection when my guild raided. I'll keep an eye out for any NPCs that should be placed on the blacklist.

**Comment by Dragonfo** [comment]
If I was in AOE automatic mode. Then I just had a POOL icon with no recommendations from the left. In my raid, the AOE rotation function worked with the disabled. Just ST without AOE. Because the recommendations were chaotic in AOE in the sense that. I started the fight on the last boss neltharion and I immediately turned on AOE. When in fact there was one boss without additional goals. These are the problems I had. There are no complaints in the rotation, it works well. It's just that where there is 1 boss and there are no additional goals, the addon recommended using AOE rotation. There is a possibility that the boss has hidden goals for the appearance of other goals in the phases, and this most likely breaks the logic of the addon in the detection of goals.

**Comment by Cilraaz** [comment]
As requested, please supply an export string for your talent build so I can verify there is no problem with the rotation based on your specific talents.

**Comment by Dragonfo** [comment]
ST Build B8PAAAAAAAAAAAAAAAAAAAAAAIBaBJBKBBJkEJkIEJhkkAAAAAAREFhmQiESIoAAAAAA
Cleave Build B8PAAAAAAAAAAAAAAAAAAAAAA4AhWaBJBKBBJkkWIJCRSIJJAAAAAQQUkimQiEECKAAAAAA
AOE Build B8PAAAAAAAAAAAAAAAAAAAAAA4ABahkEhSQgkkkWiAEJpEhAAAAAARkSRKaQiESIhCAAAAA
Here are 3 builds that I used in the raid. Cleave and AOE did not work stably on bosses, and if you took the ST build, then that's what I described above, and there was a complete mess at all. Because the ST build didn't work, he always considered AOE. You can test it on the neltharion boss. There, right from the beginning of the battle, AOE scenario will be played in the ST build if AOE is enabled.

**Comment by Dragonfo** [comment]
Here's an example. the second boss, as soon as he converged into one goal, the addon simply wrote POOL had 100 resources, and the rotation did not use mongoose. This build used B8PAI6Hz82/AvTZSB0bPjW+5YJBaBJBKBBJkEJkIEJhkkAAAAAAREFhmQiESIoAAAAAA
![image](https://github.com/herotc/hero-rotation/assets/63850853/b381c7ed-e3aa-449f-8a7a-34b8b3fb570e)

**Comment by Cilraaz** [comment]
I wrote a weakaura to track HeroRotation's target counts on Neltharion. Until actual adds spawn, it shows only one target, so I have no idea why the addon would be flipping into the AoE rotation for you.

**Comment by Cilraaz** [comment]
In the Discord, at least some of this was determined to be due to Demon Hunter condemned demon spawns (even though they're not supposed to be hostile to other players). This should be resolved now.
