### ISSUE TITLE
[Survival]: Djaruun is not suggested

### ISSUE THREAD

**Issue by Zonarius** [herotc/hero-rotation#945]
### What version of HeroRotation are you using?

10.1.0.07

### What version of HeroLib are you using?

10.1.0.02

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

First of all thanks for your work on this addon. I really like the code style. Very functional, straight forward and easy to understand.

I'm a lucky survival hunter who got the polearm [Djaruun](https://www.wowhead.com/item=202569/djaruun-pillar-of-the-elder-flame) on normal yesterday and noticed that HeroRotation does not suggest using the on-use effect.

I believe the reason is that simc summarizes all item usages with `use_items`:

https://github.com/simulationcraft/simc/blob/dragonflight/profiles/Tier30/T30_Hunter_Survival.simc#LL52C32-L52C32

However, HeroRotation (or at least the surv hunter rotation) uses `Player:GetUseableTrinkets`:

https://github.com/herotc/hero-rotation/blob/a56c20b0bfeffebf6612c880a8458d1549c8d2bc/HeroRotation_Hunter/Survival.lua#L215-L219

Which, as the name suggests, does not use items other than trinkets.

I have made a workaround here:
https://github.com/Zonarius/hero-rotation/commit/5803647bccdd2f411818e3c0aa3ad6f7f4821711

This works, but it would be better to have a `Player:GetUsableItems` function and use that instead.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Djaruun handling added in commit https://github.com/herotc/hero-rotation/commit/0f594798f8351c545e70812409e1a0878f5b92ce
