### ISSUE TITLE
[Bug]: Shadow Priest - void torrent being shown as main icon despite option selected for it to show off gcd

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#947]
### What version of HeroRotation are you using?

10.1.0.07

### What version of HeroLib are you using?

10.1.0.02

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

In dungeons, VoiT is often shown as main icon despite me having the option selected for it to show off gcd. When I play on the target dummies in valdraaken, it is properly shown as off gcd. Also, it is sometimes inconsistent even in dungeons (sometimes but rarely it will correctly show off gcd but more commonly it shows as main icon)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/80b805a37d155d1cda631a3ab65acf34348dfb1a

Most cast suggestions for Void Torrent obeyed the OffGCD setting, but one CastCycle did not, which is why it was inconsistent for you.

**Comment by GarrettCottrell** [comment]
Thanks for this quick fix!
