### ISSUE TITLE
[Bug]: Summon Infernal is causing Addon to go blank and not show spells [Destruction Warlock}

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#949]
### What version of HeroRotation are you using?

10.1.0.08

### What version of HeroLib are you using?

10.1.0.03

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Just like the title states. Every time Summon Infernal comes out, the addon goes blank. and doesn't show what spells to cast. 

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
If the icon disappears, a lua error has occurred. Please provide that error.

You can enable them by issuing the command `/console scriptErrors 1` in game.
You can later disable them if you wish by issuing the command `/console scriptErrors 0`.

**Comment by Soulsmacka** [comment]
> If the icon disappears, a lua error has occurred. Please provide that error.
> 
> You can enable them by issuing the command `/console scriptErrors 1` in game. You can later disable them if you wish by issuing the command `/console scriptErrors 0`.

here it goes:

(Page 1)

Message: ...rface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:190: attempt to get length of local 'ExcludedItems' (a nil value)
Time: Wed May 17 13:46:22 2023
Count: 592
Stack: ...rface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:190: attempt to get length of local 'ExcludedItems' (a nil value)
[string "@Interface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua"]:190: in function `GetUseableItems'
[string "@Interface/AddOns/HeroRotation_Warlock/Destruction.lua"]:177: in function <...nterface/AddOns/HeroRotation_Warlock/Destruction.lua:174>
[string "@Interface/AddOns/HeroRotation_Warlock/Destruction.lua"]:565: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>

Locals: self = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:595
 GCDStartTime = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:70
 Race = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:45
 Insanityrain = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:647
 FocusLossOnCastEnd = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:226
 PainMax = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:724
 IsInVehicle = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:104
 IsInParty = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:32
 EnergyDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:279
 Fury = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:697
 InstanceInfo = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Instance.lua:22
 RageDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:139
 VersatilityDmgPct = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:680
 MaelstromPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:553
 ArcaneCharges = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:665
 IsInDungeonArea = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Instance.lua:53
 ActiveMitigationNeeded = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Tank.lua:64
 SoulShardsDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:469
 EssenceDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:766
 AffectingCombat = <function> defined @Interface/AddOns/HeroRotation_Warlock/Overrides.lua:211
 GetEnemiesInRange = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:142
 PainDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:739
 AttackPower = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:78
 FocusCastRegen = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:208
 PainDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:744
 PrevOffGCD = <function> defined @Interface/AddOns/HeroLib/Events/Prev_Spell.lua:236
 GetOnUseItems = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:30
 InsanityPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:632
 ManaDeficitPercentageP = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:113
 FuryDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:707
 PrevGCD = <function> defined @Interface/AddOns/HeroLib/Events/Prev_Spell.lua:202
 AstralPowerMax = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Playe

(Page 2)

Message: ...rface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:190: attempt to get length of local 'ExcludedItems' (a nil value)
Time: Wed May 17 13:45:57 2023
Count: 175
Stack: ...rface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:190: attempt to get length of local 'ExcludedItems' (a nil value)
[string "@Interface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua"]:190: in function `GetUseableItems'
[string "@Interface/AddOns/HeroRotation_Warlock/Destruction.lua"]:177: in function <...nterface/AddOns/HeroRotation_Warlock/Destruction.lua:174>
[string "@Interface/AddOns/HeroRotation_Warlock/Destruction.lua"]:287: in function <...nterface/AddOns/HeroRotation_Warlock/Destruction.lua:284>
[string "@Interface/AddOns/HeroRotation_Warlock/Destruction.lua"]:561: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>

Locals: self = <table> {
 UseCache = true
 ChiDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:595
 GCDStartTime = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:70
 Race = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:45
 Insanityrain = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:647
 FocusLossOnCastEnd = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:226
 PainMax = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:724
 IsInVehicle = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:104
 IsInParty = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:32
 EnergyDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:279
 Fury = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:697
 InstanceInfo = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Instance.lua:22
 RageDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:139
 VersatilityDmgPct = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:119
 ArcaneChargesDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:680
 MaelstromPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:553
 ArcaneCharges = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:665
 IsInDungeonArea = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Instance.lua:53
 ActiveMitigationNeeded = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Tank.lua:64
 SoulShardsDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:469
 EssenceDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:766
 AffectingCombat = <function> defined @Interface/AddOns/HeroRotation_Warlock/Overrides.lua:211
 GetEnemiesInRange = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Enemies.lua:53
 IsInWhitelistedVehicle = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:142
 PainDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:739
 AttackPower = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:78
 FocusCastRegen = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:208
 PainDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:744
 PrevOffGCD = <function> defined @Interface/AddOns/HeroLib/Events/Prev_Spell.lua:236
 GetOnUseItems = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:30
 InsanityPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:632
 ManaDeficitPercentageP = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:113
 FuryDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:707
 PrevGCD = <func

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/7e3de37920fe5060754ee2aa10c0818161944ca9
