### ISSUE TITLE
[Bug]:  Engineer CR bracers/helm are suggested.

### ISSUE THREAD

**Issue by framara** [herotc/hero-rotation#953]
### What version of HeroRotation are you using?

10.1.0.09

### What version of HeroLib are you using?

10.10.03

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Engineer bracers/helm with combat rest are suggested during rotation

![image](https://github.com/herotc/hero-rotation/assets/452670/8a1f3cca-bb04-4ab4-b25e-3acc988a2c70)

This doesnt happen is checkbox for 'use trinkets' is disabled

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Exclusions for engineering wrists and helms added in commit https://github.com/herotc/hero-lib/commit/c85bed529d2fd82af462aeb0b28d6e7c427e2a65
