### ISSUE TITLE
Hero rotation not working on fire mage[Bug]: 

### ISSUE THREAD

**Issue by Liffendir** [herotc/hero-rotation#955]
### What version of HeroRotation are you using?

10.1.0

### What version of HeroLib are you using?

10.1.0

### What version of HeroDBC are you using?

10.1.0

### What is the issue?

Hero rotation will not start in fire spec, it works fine in Frost.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fire is not supported at this time. You can find the list of supported specs [here](https://github.com/herotc/hero-rotation#supported-rotations).
