### ISSUE TITLE
Havoc DH

### ISSUE THREAD

**Issue by wepunz22** [herotc/hero-rotation#960]
### What version of HeroRotation are you using?

10.1.0.12

### What version of HeroLib are you using?

10.1.0.05

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Message: Interface/AddOns/HeroRotation_DemonHunter/Havoc.lua:379: attempt to index field 'FuriousThrows' (a nil value)
Time: Thu May 25 10:58:15 2023
Count: 99
Stack: Interface/AddOns/HeroRotation_DemonHunter/Havoc.lua:379: attempt to index field 'FuriousThrows' (a nil value)

Locals: 

### Icon Behavior

None

**Comment by Cilraaz** [comment]
This is now fixed in commit https://github.com/herotc/hero-rotation/commit/c59c226fbc91bee6d5d63fc0744556a3b9edba18

Thank you for the report!

**Comment by wepunz22** [comment]
Yw!  So, I updated addon and it pops at lua:293 same attempt (nil value).

**Comment by Cilraaz** [comment]
You updated the DemonHunter.lua file from the github? That prior commit added the missing spell, so with the update, the spell should be seen, regardless of whether it's checking it on line 379 or 293.

**Comment by wepunz22** [comment]
got it, ty kindly!
