### ISSUE TITLE
Dimensional Rift - Odyns Fury Treatment - Destruction Warlock 

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#961]
### What feature would you like to have added?

Dimensional Rift isn't in many PvE builds but I do use it for PvP or when I have WM off. 

Can Dimensional Rift get the same treatment you gave to Odyns Fury and have its own spot? 

It shouldn't be in the global cd window either because it would be nice to have agency on when to actually use it. 

When you have dimensional rift talented, it takes up the main window and it won't disappear until you use all 3 charges. 

Not ideal when you're fighting a boar in the woods.

**Comment by Cilraaz** [comment]
Added OffGCD option in commit https://github.com/herotc/hero-rotation/commit/84c443b3f56d95709282d58c06d4a64e05cb1448
