### ISSUE TITLE
shaman does not use Lightning Bolt when activating Primordial Wave in AOE

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#962]
### What version of HeroRotation are you using?

10.1.0.13

### What version of HeroLib are you using?

10.1.0.06

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

The essence of the problem is that the addon when activating Primordial Wave wants to see 6 Flame Shock on targets if it is more than 6 targets. The problem is that if we start the battle not with Flame shock-> Primordial Wave and do not make the maximum number of targets with the Flame shock buff, there will be a recommendation Chain Lightning and the addon will ignore the action Primordial Wave and Primordial Wave + Lightning Bolt recommendation will be at the very end of Primordial Wave action. How to avoid Chain Lightning recommendation while Primordial Wave is active? You always want to press Lightning Bolt as soon as you activate Primordial Wave to get % speed. I don't really want the addon to recommend to take advantage of Primordial Wave at the end. I think there is a problem with the calculation of targets in the shaman. Because it shows up in different builds even without playing with Primordial Wave. Here's the build once BcQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJpJEISSISSCUSkAAAAAAAAAAAAAAAAKRICJapIpQSLJpcAEKBBgA and here's the second build without Primordial Wave BcQAAAAAAAAAAAAAAAAAIJBQSSkkkASSLJJAAAAAAAAAAgSEkQiSKiSJtkoARpEEkCC 
Thank you in advance for your help.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Shaman profiles have been completely re-written for patch 10.1.5. If this is still a problem, please let us know.
