### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xItsMeChrisx** [herotc/hero-rotation#963]
### ### What version of HeroRotation are you using?

10.1.0.14

### What version of HeroLib are you using?

10.1.0.07

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Message: ...nterface/AddOns/HeroRotation_Paladin/Retribution.lua:47: attempt to index field 'ShadowedRazingAnnihilator' (a nil value)
Time: Tue May 30 10:18:50 2023
Count: 1
Stack: ...nterface/AddOns/HeroRotation_Paladin/Retribution.lua:47: attempt to index field 'ShadowedRazingAnnihilator' (a nil value)
[string "@Interface/AddOns/HeroRotation/Main.lua"]:390: in function `PulseInit'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:299: in function <Interface/AddOns/HeroRotation/Main.lua:296>

Locals: Spec = 3
SpecID = 70
HL = <table> {
 RegisterForEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:46
 MAXIMUM = 40
 BossFilteredFightRemains = <function> defined @Interface/AddOns/HeroLib/Class/Unit/TimeToDie.lua:385
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 Item = <table> {
 }
 Pulse = <function> defined @Interface/AddOns/HeroLib/Main.lua:29
 LiveRealm = <function> defined @Interface/AddOns/HeroLib/Core.lua:34
 RegisterForCombatPrefixEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:133
 UnregisterForEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:62
 AddCoreOverride = <function> defined @Interface/AddOns/HeroLib/Misc/Overrides.lua:26
 BetaRealm = <function> defined @Interface/AddOns/HeroLib/Core.lua:44
 Spell = <table> {
 }
 BossFightRemainsIsNotValid = <function> defined @Interface/AddOns/HeroLib/Class/Unit/TimeToDie.lua:370
 GetInstanceInfo = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:37
 Action = <table> {
 }
 LoadRestores = <function> defined @Interface/AddOns/HeroLib/Misc/Overrides.lua:42
 RegisterForCombatSuffixEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:148
 MainFrame = HeroLib_MainFrame {
 }
 GUISettings = <table> {
 }
 CombatEnded = 1
 RecoveryTimer = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:116
 BMPullTime = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:87
 RegisterForCombatEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:88
 OutOfCombatTime = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:82
 UnregisterForSelfCombatEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:177
 Latency = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:111
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 SplashEnemies = <table> {
 }
 GetInstanceDifficulty = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:72
 LoadOverrides = <function> defined @Interface/AddOns/HeroLib/Misc/Overrides.lua:48
 Print = <function> defined @Interface/AddOns/HeroLib/Core.lua:49
 UnregisterAuraTracking = <function> defined @Interface/AddOns/HeroLib/Events/Aura.lua:37
 TTD = <table> {
 }
 UnitGUIDMap = <table> {
 }
 BuildVersion = <function> defined @Interface/AddOns/HeroLib/Core.lua:29
 MultiSpell = <table> {
 }
 CombatTime = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:77
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 UnregisterForCombatEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:163
 BossFightRemains = <function> defined @Interface/AddOns/HeroLib/Class/Unit/TimeToDie.lua:365
 FightRemains = <function> defined @Interface/AddOns/HeroLib/Class/Unit/TimeToDie.lua:333
 TTDRefresh = <function> defined @Interface/AddOns/HeroLib/Class/Unit/TimeToDie.lua:53
 RecoveryOffset = <function> defined @Interface/AddOns/HeroLib/Misc/ToSort.lua:124
 FilteredFightRemains = <function> defined @Interface/AddOns/HeroLib/Class/Unit/TimeToDie.lua:375
 CombatStarted = 0
 SpecID_ClassesSpecs = <table> {
 }
 RegisterForSelfCombatEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:103
 UnregisterForCombatPrefixEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:205
 GUI = <table> {
 }
 UnregisterForPetCombatEvent = <function> defined @Interface/AddOns/HeroLib/Events/Main.lua:191
 UnregisterForCombatSuffixEvent = <function> defined @Interface/AddOns/HeroLib

Massage 2/2

Message: Interface/AddOns/HeroRotation_Paladin/Retribution.lua:1 (null)
Time: Tue May 30 10:18:50 2023
Count: 2
Stack: Interface/AddOns/HeroRotation_Paladin/Retribution.lua:1 (null)

Locals: 

### Icon Behavior

None

**Comment by Cilraaz** [comment]
This was previously fixed in commit https://github.com/herotc/hero-rotation/commit/924832b4e533b1b07ef33f0240c9a69c812fd993

You can grab the update from github or wait for the next full version release.
