### ISSUE TITLE
Ret paladin not working. [Bug]: 

### ISSUE THREAD

**Issue by Wreknar** [herotc/hero-rotation#964]
### What version of HeroRotation are you using?

10.1.0.14

### What version of HeroLib are you using?

10.1.0.07

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Ret paladin shows supported but does not work at all.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Update to the just released 10.1.0.15.
