### ISSUE TITLE
Ret paladin [Bug]: 

### ISSUE THREAD

**Issue by Wreknar** [herotc/hero-rotation#965]
### What version of HeroRotation are you using?

10.1.0.15

### What version of HeroLib are you using?

10.1.0.07

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Currently now showing Judgement in the rotation. Also:
![image](https://github.com/herotc/hero-rotation/assets/135073498/9d7c081f-e8c4-4b57-a75d-abb909a49a02)

 Added an image of what I am seeing.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/d08fafd618870a5fb7b652a32182a6a352732941
