### ISSUE TITLE
[Bug]: Thistle Tea not suggested in AOE

### ISSUE THREAD

**Issue by Exsol-bit** [herotc/hero-rotation#966]
### What version of HeroRotation are you using?

10.1.0.15

### What version of HeroLib are you using?

10.1.0.07

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

With the most recent changes pushed through Thistle Tea is not suggested in AOE.

Specfically when ShadowDancing on the cleave target dummies in Valdraken.

Changing new line 660 from:
` or (Player:BuffRemains(S.ShadowDance) >= 4 and not Player:BuffUp(S.ThistleTea) and MeleeEnemies10yCount >= 3)`

TO

`or Player:BuffRemains(S.ShadowDanceBuff) > 4 and not Player:BuffUp(S.ThistleTea) and MeleeEnemies10yCount >= 3`

Appears to resolve issue for me (simply copied bit from the previously working LUA.

Thistle Tea is recomended correctly in ST testing on Training Dummy.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/bd1816251e67be307710aefb4dadefe8adacd06c
