### ISSUE TITLE
[Enhancement]: Prot Paladin: Allow for Eye of Tyr to be shown Off GCD

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#970]
### What feature would you like to have added?

On some fights like mythic rashak, eye of tyr is a defensive button that you save for specific moments to pair with other defensives, so it would be cool if it could be shown as off gcd

**Comment by Cilraaz** [comment]
An OffGCD option for Eye of Tyr has been added as of commit https://github.com/herotc/hero-rotation/commit/42feb2209a7e28cf74b2ca94db4e40d01df48fb7
