### ISSUE TITLE
[Bug]: Mage (Fire) does not show up

### ISSUE THREAD

**Issue by eisenfuchs** [herotc/hero-rotation#971]
### What version of HeroRotation are you using?

10.1.0.18

### What version of HeroLib are you using?

10.1.0.08

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

On Fire Spec, the Interface is completely missing, despite being activated. Clicking "unlock" makes it show up like usual, with the demo graphics, so the addon is loaded properly. But when you lock the addon again, it is completely hidden (so no CAO buttons).

When speccing into Arcane, the interface shows up, but throws "Fatality" messages. I will check my partner's bug catcher later and update you with any info I can get. 

I've also tested it on my own account, and while I didn't get the error messages on Arcane, Fire still does not show up. Does it mean it's not supported?

![Bildschirmfoto 2023-06-13 um 14 30 28](https://github.com/herotc/hero-rotation/assets/79832708/494f9cea-c25c-4840-b477-118f44ef2df4)
![Bildschirmfoto 2023-06-13 um 14 30 13](https://github.com/herotc/hero-rotation/assets/79832708/01acb174-1176-4bf9-a652-426d8fb47354)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Fire is currently unsupported.
