### ISSUE TITLE
[Bug]: [Arcane] AoE rotation not being shown when entering combat with Valdrakken AoE dummies.

### ISSUE THREAD

**Issue by lyn3x** [herotc/hero-rotation#973]
### What version of HeroRotation are you using?

10.1.0.20

### What version of HeroLib are you using?

10.1.0.08

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

When entering combat to practice the AoE rotation with Hero Rotation as an Arcane Mage, the addon will first not display Arcane Orb to start the fight, but instead suggests Arcane Blast. Once combat has been engaged, following the rotation for over 3 minutes (one complete cycle of Berserking Racial), never once does it suggest to use Arcane Explosion, or to perform the proper AoE rotation with Arcane Barrages. I am unsure if this is a limitation of the addon, a variable set where AoE = >5 targets or something to that effect.

Additionally, I am using plater, nameplates are displaying properly and were visible to the camera. I can provide media on request where I perform the rotation in its entirety.

Unsure if this is related, but there are also times where Hero Rotation will not suggest anything at all if certain aspects of the rotation are done incorrectly (ie. Touch of the Magi being used while Arcane surge is off CD).

### Icon Behavior

None

**Comment by Cilraaz** [comment]
AoE target counting requires an AoE ability be used. For Arcane Mage, while solo, you have to use Arcane Explosion or Arcane Barrage to trigger AoE target counting. We cannot automatically use the nameplates to determine a target count.

When you say it "will not suggest anything", does the icon disappear entirely? If it disappears entirely, you are receiving a lua error, which we would need so we could fix the problem in the code.

Edit: You can enable lua errors by issuing the command `/console scriptErrors 1` in-game. You can later disable them with the command `/console scriptErrors 0`. You could also use an addon, such as BugSack to capture the lua error.

**Comment by lyn3x** [comment]
Here is media of the AoE issue, you can see I force AE in several cases and its never recommended to switch to AoE. I will work on see if a LUA error pops for the other issue and likely open another bug for that, so this one isn't muddled up.

https://drive.google.com/file/d/14o7Tw0UAkSZh2XgElziE_rNMtm8gBNhJ/view?usp=sharing

**Comment by Cilraaz** [comment]
Do you have 4 pieces of tier 30 gear? That's a separate function in the rotation that I was unable to test because my mage is only 60.

**Comment by lyn3x** [comment]
I do indeed! I likely should have mentioned that and will note it for the future. I can gather more info and do additional testing if needed (I work in QA). I can also provide my setting as I have a lot of the OGCD abilities show in Main

**Comment by Cilraaz** [comment]
If you can enable debug output with the in-game command `/hr debug`, it will tell you what abilities are being suggested (and will tell us which specific part of the code it is accessing). If you could, please enable the debug output and give me a few lines of the debug output during the time that AoE _should_ be suggested, but is not. At minimum, that will let me know what function it's going into versus where it should be.

**Comment by lyn3x** [comment]
Went ahead and grabbed the entire burst phase.

```
[Hero Rotation] conjure_mana_gem precombat 4 
[Hero Rotation] mirror_image precombat 6 
[Hero Rotation] conjure_mana_gem precombat 4 
[Hero Rotation] evocation precombat 8 
[Hero Rotation] arcane_blast precombat 10 
[Hero Rotation] arcane_orb t30_burst_phase 4 
[Hero Rotation] arcane_missiles t30_burst_phase 8 
[Hero Rotation] nether_tempest t30_burst_phase 14 
[Hero Rotation] arcane_surge t30_burst_phase 16 
[Hero Rotation] mana_gem main 42 
[Hero Rotation] arcane_barrage t30_burst_phase 22 
[Hero Rotation] touch_of_the_magi main 30 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] arcane_missiles t30_burst_phase 8 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] cancel_action arcane_missiles t30_burst_phase 32 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] arcane_missiles t30_burst_phase 8 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] cancel_action arcane_missiles t30_burst_phase 32 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] arcane_missiles t30_burst_phase 8 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] cancel_action arcane_missiles t30_burst_phase 32 
[Hero Rotation] arcane_blast t30_burst_phase 30 
[Hero Rotation] rune_of_power t30_rotation 6 
[Hero Rotation] arcane_blast t30_burst_phase 30 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] arcane_missiles t30_burst_phase 8 
[Hero Rotation] arcane_blast t30_burst_phase 36 
[Hero Rotation] arcane_blast t30_rotation 22
```

Whats interesting is even after using AE it seems to revert to suggesting a single target ability like Missles or Arcane Blast.

**Comment by Cilraaz** [comment]
I'm looking over it and it seems like it might be an issue with registering multiple targets for AE and ABarr, but I can't figure out why at first glance. I'll have to take a look at it more in depth.

**Comment by Cilraaz** [comment]
Arcane was updated to the latest APL this week. Is this still an issue?
