### ISSUE TITLE
mage/fire

### ISSUE THREAD

**Issue by nataliekburton** [herotc/hero-rotation#974]
### What version of HeroRotation are you using?

10.1.0

### What version of HeroLib are you using?

10.1.0.20

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

Nothing on my FIRE mage is working. There isn't even the ui for it. I unlocked and i can see the gear icons, but when relocking it the gears didn't go away.

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
Fire Mage is not currently supported.
