### ISSUE TITLE
Slice N Dice Global CD OPtion

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#975]
### What feature would you like to have added?

Please add Slice n Dice to the options panel to allow us to move it to the GCD window or a separate window like you have for other classes.  I know the importance of Slice n Dice but there are sometimes I want to press another finisher due to mob health or pvp scenario and the fact that nothing else shows up as an option until Slice n Dice is up, is extremely frustrating.

**Comment by Cilraaz** [comment]
Duplicate of #722
