### ISSUE TITLE
[Monk/Wind Walker]: LUA Error when using Serenity

### ISSUE THREAD

**Issue by Santotaku** [herotc/hero-rotation#977]
### What version of HeroRotation are you using?

10.1.0.17

### What version of HeroLib are you using?

10.1.0.11

### What version of HeroDBC are you using?

10.1.0.0.1

### What is the issue?

I've been receiving this issue for a while. The addon will suggest using Serenity when expected, but after hitting Rising Sun Kick I will receive a LUA error from the game. The error will return after clearing it next time you hit Rising Sun Kick.

In testing I also noted that it only happens when Rising Sun Kick is pressed **when suggested** and not any time that Serenity is active, only when it needs to make the next recommendation.

**Below is the LUA Message:**

> 
> 
> Message: Interface/AddOns/HeroLib/Class/Unit/Aura.lua:36: attempt to index local 'ThisSpell' (a nil value)
> Time: Thu Jul  6 14:48:39 2023
> Count: 12
> Stack: Interface/AddOns/HeroLib/Class/Unit/Aura.lua:36: attempt to index local 'ThisSpell' (a nil value)
> [string "@Interface/AddOns/HeroLib/Class/Unit/Aura.lua"]:36: in function <Interface/AddOns/HeroLib/Class/Unit/Aura.lua:32>
> [string "=(tail call)"]: ?
> [string "@Interface/AddOns/HeroLib/Class/Unit/Aura.lua"]:101: in function `BuffRemains'
> [string "@Interface/AddOns/HeroLib/Class/Unit/Aura.lua"]:119: in function `BuffUp'
> [string "@Interface/AddOns/HeroRotation_Monk/Windwalker.lua"]:973: in function <Interface/AddOns/HeroRotation_Monk/Windwalker.lua:953>
> [string "@Interface/AddOns/HeroRotation_Monk/Windwalker.lua"]:1159: in function `?'
> [string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>
> 
> Locals: self = <table> {
>  UseCache = true
>  ChiDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:595
>  GCDStartTime = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:70
>  Race = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:45
>  Insanityrain = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:647
>  FocusLossOnCastEnd = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:226
>  PainMax = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:724
>  IsInVehicle = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:104
>  IsInParty = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:32
>  EnergyDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:279
>  Fury = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:697
>  InstanceInfo = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Instance.lua:22
>  RageDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:139
>  VersatilityDmgPct = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:119
>  ArcaneChargesDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:680
>  MaelstromPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:553
>  ArcaneCharges = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:665
>  IsInDungeonArea = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Instance.lua:53
>  ActiveMitigationNeeded = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Tank.lua:64
>  SoulShardsDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:469
>  EssenceDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:766
>  GetEnemiesInRange = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Enemies.lua:53
>  IsInWhitelistedVehicle = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Main.lua:142
>  PainDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:739
>  AttackPower = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Stat.lua:78
>  FocusCastRegen = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:208
>  PainDeficitPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:744
>  PrevOffGCD = <function> defined @Interface/AddOns/HeroLib/Events/Prev_Spell.lua:236
>  GetOnUseItems = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Equipment.lua:32
>  InsanityPercentage = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:632
>  ManaDeficitPercentageP = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:113
>  FuryDeficit = <function> defined @Interface/AddOns/HeroLib/Class/Unit/Player/Power.lua:707
>  PrevGCD = <function> defined @Interface/AddOns/HeroLib/Events/Prev_Spell.lua:202
>  AstralPowerMax = <

### Icon Behavior

Icon does NOT disappear

**Comment by Santotaku** [comment]
Correction to my original post:

I found a script to disable LUA errors and when I disable them I find that the HeroRotation Icon **DOES** disappear after casting Rising Sun Kick. Pressing any key will move onto the next suggestion.

Ultimately I think the issue is that the addon is just having a hard time making a suggestion between two kicks, probably because the cost is reduced to 0 for chi spenders there are probably just too many options.

**Comment by Cilraaz** [comment]
Two spell IDs were missing, causing your errors. This has been fixed in commit https://github.com/herotc/hero-rotation/commit/215b8e7f5e75c20d4957fdd69e83ef07dfa199dd

**Comment by Santotaku** [comment]
> Two spell IDs were missing, causing your errors. This has been fixed in commit [215b8e7](https://github.com/herotc/hero-rotation/commit/215b8e7f5e75c20d4957fdd69e83ef07dfa199dd)

Thank you. Adding the lines for Jade Ignition and Invokers Delight eliminated the LUA error, however, now the addon will recommend Fists of Fury during the Serenity window (should be last cast prior to buff ending) and if you follow the suggestions, it will then recommend it even while Fists is on cooldown.

The display Icon shows half red X and half Fists of Fury when it makes this recommendation.
