### ISSUE TITLE
[Bug]: Frost Mage Not Recommending Cone of Cold with Coldest Snap Talented in AOE

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#979]
### What version of HeroRotation are you using?

10.1.5.07

### What version of HeroLib are you using?

10.1.5.01

### What version of HeroDBC are you using?

10.1.5.01

### What is the issue?

Pretty much title says it all. 
level 70 frost mage 
fresh char with no tier 

The addon doesn't seem to ever recommend cone of cold even while coldest snap is talented ever which seems like a bug - typically its used to reset frozen orb and commet storm (for example on pull in aoe you would frozen orb/blizzard/commet storm/cone of cold/frozen orb/commet storm/blizzard and then shifting power to get it all back - this is just an example and obv may not be perfect but the general idea is just that the addon *never* recommends cone of cold)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Frost Mage is not up to date with the current APL. I'm actually working on it currently.

**Comment by GarrettCottrell** [comment]
Ah, that's awesome. I did notice that the frost mage status indicator was changed to "good" sicne I last looked. Is it fair to assume that indicates your work on this is done for now?

**Comment by Cilraaz** [comment]
Frost is now up to date with the current APL.
