### ISSUE TITLE
[Bug]: debug code possibly left uncommented?

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#980]
### What version of HeroRotation are you using?

10.1.5.08

### What version of HeroLib are you using?

10.1.5.01

### What version of HeroDBC are you using?

10.1.5.02

### What is the issue?

This may not be a bug, but I noticed a piece of debug code is active and not sure if that was intended or not.

Line 505 in the Vengeance file.

https://github.com/herotc/hero-rotation/blob/f0e20c112cfd67f3c08e6695155a81dbdc7a936d/HeroRotation_DemonHunter/Vengeance.lua#L505

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Yep. That was left in accidentally. I've removed it in commit https://github.com/herotc/hero-rotation/commit/45f977f471b0320f4c71319cfc6c2421bd76ef8c

Thanks!
