### ISSUE TITLE
[Bug]: Unholy DK: Apocalypse not being suggested

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#982]
### What version of HeroRotation are you using?

10.1.5.08

### What version of HeroLib are you using?

10.1.5.01

### What version of HeroDBC are you using?

10.1.5.02

### What is the issue?

Since the new patch came out, Apocalypse has not been suggested to be used when it's supposed to be. The 4 festering wounds will be built up and available and the ability is off cd and lit up to use and the addon keeps suggesting everything else. Sometimes it shows the pooling window when you should actually be casting Apoc and other times it just keeps suggesting everything else. 

### Icon Behavior

None

**Comment by Demiralos** [comment]
Decided to test this too as I've noticed the same issue. When simming my DK with an M+ Disease build SIMC reports the same.
With 5 enemies Patchwork sim, Apoc was used 1 time, at the first UA use. Otherwise ignored.

With 3 enemies a little bit more. And with 1 target, used on cooldown in sync with DT.

All according to the APL. Even though we're supposed to sync their uses.
I've tried to use Apoc in sync, and blindly follow HR. Blindly gives me more DPS in dungeons.

**Comment by nyterage** [comment]
This is pretty much intentional. The only real use for Apocalypse in AoE scenarios is the Rune regeneration if its needed. so, it will rarely be suggested. You can use it if you so wish, but, saving it for some instant runes is generally better for AoE.

**Comment by Soulsmacka** [comment]
> This is pretty much intentional. The only real use for Apocalypse in AoE scenarios is the Rune regeneration if its needed. so, it will rarely be suggested. You can use it if you so wish, but, saving it for some instant runes is generally better for AoE.

Thank you for this, I wasn't aware of this. This does happen in the AoE Mythic plus build. I did try it with the single target build and it still requests to pool energy when Apoc is ready to go and Gargoyle is active. When Gargoyle is on cd, it doesn't recommend pooling and just lights up when there is enough FW and it's available. Is there something I'm missing during the opener that would require me to pool resources before using Apoc and I have GArgoyle up? or is this an addon issue?

Edit: I also noticed that it only happens when Army is active. It says to pool until all the runes are available then it finally suggests Apoc. I am not aware of any reason why I would need to max my runes before casting anything else. It's like 5 seconds of downtime during a burst window having gargoyle, DT and army active.  

When Army and gargoyle are on cd, the addon suggests using Apoc immediately once off cd and the fw are on the target.

**Comment by Cilraaz** [comment]
Your build doesn't matter. It's the actual count of mobs around you. Outside of Gargoyle prep, it will be suggested under the following conditions:

AoE:
- Bursting Sores talent is selected AND
- Target has Festering Wounds (any stack size) AND
- (DnD is not ticking AND Runes are less than 3) OR (DnD is ticking AND Runes are at 0)
OR
- Bursting Sores talent is not selected AND
- Target has Festering Wound at 4+ stacks

ST:
- Festering Wounds stack is at 4+ stacks

CDs must be enabled for either to be shown.

The Apocalypse conditions don't interact with Army in any way.

**Comment by Soulsmacka** [comment]
> Your build doesn't matter. It's the actual count of mobs around you. Outside of Gargoyle prep, it will be suggested under the following conditions:
> 
> AoE:
> 
> * Bursting Sores talent is selected AND
> * Target has Festering Wounds (any stack size) AND
> * (DnD is not ticking AND Runes are less than 3) OR (DnD is ticking AND Runes are at 0)
>   OR
> * Bursting Sores talent is not selected AND
> * Target has Festering Wound at 4+ stacks
> 
> ST:
> 
> * Festering Wounds stack is at 4+ stacks
> 
> CDs must be enabled for either to be shown.
> 
> The Apocalypse conditions don't interact with Army in any way.

Thanks for this, but it still doesn't explain why when ALL cooldowns are used and active on single target and all the conditions are met, I get a "pool resources" icon rather than use Apoc. 

And I'm mentioning army and gargoyle because when they are on cool down and not available to use, the addon will then correctly suggest Apoc when the festering wounds are at 4+. When they are active, for what ever reason, I get the pool resources icon.

**Comment by Cilraaz** [comment]
These two conditions have nothing to do with either Army or Gargoyle. To get to the above conditions, you simply need AoE and CDs enabled. For multiple targets, it goes into the AoE Cooldowns function, which checks the conditions listed for AoE. For single target, it goes into the Cooldowns function, which checks for the conditions listed for ST.

The only time Apoc interacts with Gargoyle is during the opener. The opener is active within the first 20 seconds of combat if there are only 1 or 2 targets and both Gargoyle and Apoc are on CD. During that opener, Apoc will be suggested if:
- FW stacks are 4+ AND
- Commander of the Dead is active with less than 23 seconds remaining on the Gargoyle OR Commander of the Dead talent is not selected

Those are the only 3 times Apoc is referenced in the APL.

I've tested and can't replicate the issue you're seeing. It suggests Apoc nearly on CD for me. Are you holding any CDs that are being suggested?

**Comment by Soulsmacka** [comment]
Not that I know of, everything is up and running. I do not get a lua error either because it is suggesting the pooling of resources. 

I guess it's not a big deal cause now with all the testing, my reflects cast apoc the moment I see pooling resources and it clears and continues with rotation
