### ISSUE TITLE
[Bug]: Arcane Mage / Abilities disappear

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#983]
### What version of HeroRotation are you using?

Latest

### What version of HeroLib are you using?

Latest

### What version of HeroDBC are you using?

Latest

### What is the issue?

Here is the Lua error:

Message: Interface/AddOns/HeroRotation_Mage/Arcane.lua:555: attempt to compare nil with number
Time: Sat Jul 22 19:42:21 2023
Count: 123
Stack: Interface/AddOns/HeroRotation_Mage/Arcane.lua:555: attempt to compare nil with number

Locals: 

### Icon Behavior

None

**Comment by Cilraaz** [comment]
It looks like this may have occurred due to entering combat before targeting a creature, causing some variables to not be assigned properly. The issue should be resolved as of commit https://github.com/herotc/hero-rotation/commit/6a33db6a0b109f192d0d7cce4e475b5390cd3671
