### ISSUE TITLE
[Bug]: With deathspeaker talented... recommendations get caught in a loop of constantly recommending sw:death

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#984]
### What version of HeroRotation are you using?

10.1.5.11

### What version of HeroLib are you using?

10.1.5.01

### What version of HeroDBC are you using?

10.1.5.02

### What is the issue?

![image](https://github.com/herotc/hero-rotation/assets/49660931/abcde675-7158-4d03-a5d6-5cb5555e1148)

using those talents, something weird happens with recommendations - shadow word death seems to be recoommended *far* more than I think is accurate... I can't say exactyly what's happening but there's soemthing going on i think with deathspeaker and shadow word death recommendations

### Icon Behavior

None

**Comment by Cilraaz** [comment]
The only interaction between Deathspeaker and SW:Death is that SW:Death becomes a higher priority filler when the Deathspeaker buff is active. Enable debug output (`/hr debug`) and see if the SW:Death you think is occurring too often is "shadow_word_death filler 4".

**Comment by GarrettCottrell** [comment]
I will do that. To clarify, basically in my head it would make sense for sw:d to be recommended when the player has the deathspeaker buff but as soon as i press sw:d - that consumes the deathspeaker buff. 

So, when I see shadow word death being recommended enough for me to press it 10+ times in a row something felt off becuase you dont get deathspeaker that often and on a full health enemy, you would use sw:d only when you have the buf

on that note, ill do what you just usggested and let you know what I get

**Comment by GarrettCottrell** [comment]
the output doesn't seem to register every shadow word death recommendation - particularly when im getting a bunch of them in a row. But mostly it was telling me shadow word death filler 3 (the first time i pressed it i got shadow word death filler 12)

**Comment by GarrettCottrell** [comment]
yeah its mostly saying filler 3

**Comment by Cilraaz** [comment]
There is no "filler 3".

**Comment by GarrettCottrell** [comment]
![image](https://github.com/herotc/hero-rotation/assets/49660931/202ce2f9-10af-4b88-bc1b-cfc98a7a02e2)


apparently there is? not sure

**Comment by Cilraaz** [comment]
You have an old version of the profile, then.

**Comment by GarrettCottrell** [comment]
Hm, okay - what would I need to update if that's the case?

**Comment by Cilraaz** [comment]
Update to 10.1.5.12 or grab a copy of Shadow.lua from the github.

**Comment by GarrettCottrell** [comment]
![image](https://github.com/herotc/hero-rotation/assets/49660931/6a3da9bc-0f0d-4840-8988-fcae9c84e758)
 on curseforge it doesn't seem to think I can upgrade past .11

**Comment by Cilraaz** [comment]
![image](https://github.com/herotc/hero-rotation/assets/12204132/de0f5d50-53be-456a-ba79-642a546de33f)

**Comment by GarrettCottrell** [comment]
Oh thanks - apologies for that, I hadn't gone into versions

**Comment by GarrettCottrell** [comment]
Yup -it's giving me filler 4 *but* when it goes into the loop that I previously identified as "weird behavior" it only outputs the first cast of sw:death and then when I follow the next couple sw:d recommendations it doesn't give me any output

**Comment by GarrettCottrell** [comment]
oh and then there are some filer 12's being recommended as well

**Comment by Cilraaz** [comment]
If it's the same suggestion, it won't spam the output. However, "filler 4" should only be suggested if the target is under 20% hp or if the Deathspeaker buff is up. Meanwhile, "filler 12" is SW:Death on the lowest hp target with Inescapable Torment talented and your fiend active.

**Comment by GarrettCottrell** [comment]
yeah so filler 4 on the first case makes sense but upon casting sw:d you consume the buff. so it seems super bizaree that it will recommend sw:d 3-4 casts in a row fairly often. 

I'll get a better wa to track my deathspeaker buff and  just try to confirm all of this

**Comment by Cilraaz** [comment]
I tested on a dummy with this talent setup and couldn't duplicate the issue. It would suggest SW:D, I'd use it, it would move to the next suggestion.

**Comment by GarrettCottrell** [comment]
yeah that happens often - im about to go into raid but maybe after i can try and capture a quick recording of the behavior happening
