### ISSUE TITLE
[Bug]: Fire Mage - Constantly recommends fireball during combustion 

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#985]
### What version of HeroRotation are you using?

10.1.5.14

### What version of HeroLib are you using?

10.1.5.02

### What version of HeroDBC are you using?

10.1.5.02

### What is the issue?

Constantly recommends hard casting fireballs during combust. Whereas if you look at, for example a sample rotation from raidbots apl its quite different - basically just alternating between fire blast and flame strike on 5 targets

![image](https://github.com/herotc/hero-rotation/assets/49660931/9efb5428-940c-406b-8ceb-6820c58c2c8d)

obviously the sample rotations aren't perfect but the fact that its just constantly rotating betwen fire blast and flamestrike and not once hard casting a fireball during combust vs. the recommendations that are basically just spam recommending hard cast fireball into fireblast into flamestrike - it's almost as if the recommendations aren't recognizing that we've entered combust (using fireball to generate heating up is very common *outside* of combustion)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Updated in commit https://github.com/herotc/hero-rotation/commit/a8566496e1af561ec129d27cbdcf1bdaeec9bd14 45 minutes ago.

**Comment by GarrettCottrell** [comment]
lol 90% of the time i catch something you've updated it like minutes earlier

**Comment by GarrettCottrell** [comment]
Changes for the most part do a good job. I think one thing that still feels weird is that in combust the main icon still recommends fireball (with the left icon being  fireblast) but in combust you are solely alternating between fire blast and flamestrike for the most part, so it would seem to make sense to have fireblast be the main icon in combust as opposed to fireball (which you basically just dont ever press ever in combust despite it showing as main suggestion icon)

**Comment by Cilraaz** [comment]
You can stop it from acting that way by disabling the Fire Blast CastLeft option.

**Comment by GarrettCottrell** [comment]
ah okay thats great to know thank you. So if i disable that button then it will recommend fire blast as main icon if fireblast is supposed to be pressed next (as opposed to showing fireball as main icon even if fireblast should be cast next when i have the option selected)?

**Comment by Cilraaz** [comment]
Yes. What's happening with the CastLeft option is Fire Blast is being recommended and pushed to the left icon. Since there's nothing in the main icon, the profile continues looking for the next spell that could be suggested. The next thing that fits is Fireball, so it puts it in the main icon.

Essentially, the addon will fill any other icon slot, but it will always continue searching for something else to suggest until it finds something to go in the main icon.

**Comment by GarrettCottrell** [comment]
that makes a lot of sense, appreciate it
