### ISSUE TITLE
[Bug]: [Outlaw] Blade Furry not recommended on single target after 10.1.5

### ISSUE THREAD

**Issue by framara** [herotc/hero-rotation#986]
### What version of HeroRotation are you using?

10.1.5.16

### What version of HeroLib are you using?

10.1.5.02

### What version of HeroDBC are you using?

10.1.5.01

### What is the issue?

After the WoW 10.1.5 changes, there was a change on Gran Melee that now says "_Blade Flurry deals 10% additional damage to nearby enemies, including your primary target._" so according to new rotation should be use like this in single target: 

For single target:
- KiR builds: keep BF up when GM buff has at least 10s remaining and you aren't in Dance or DreadBlades window.
- HO builds: keep BF up when GM buff is up and you aren't in Dance/Subterfuge.

### Icon Behavior

N/A

**Comment by Exsol-bit** [comment]
It looks like Outlaw hasn't been updated in 3 months, it's not up to date with the current APL yet.

It'll just be a waiting game, might be worth moving Outlaw to WIP in supported rotations.

**Comment by EvanMichaels** [comment]
No reason to move it to WIP, the current APL changes are extremely minimal in terms of DPS.

It's on my list to update. But not really a major concern. Single target Blade Flurry is worth less than 0.3% DPS even with all the supporting talents, last I checked.
