### ISSUE TITLE
[Frost Mage]: Profile Not Loading

### ISSUE THREAD

**Issue by Moma1706** [herotc/hero-rotation#987]
### What version of HeroRotation are you using?

10.1.5.17

### What version of HeroLib are you using?

10.1.5.02

### What version of HeroDBC are you using?

10.1.5.03

### What is the issue?

[Bug]: when i reload ui i get this error  No Rotation found for this class/spec (SpecID: 64), addon disabled. This is likely due to the rotation being unsupported at this time. Please check supported rotations here: https://github.com/herotc/hero-rotation#supported-rotations
But here on Github it sayes that frost mage i supported and its good 
please help

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
I'm unable to replicate this error. Please provide your talent build. Also, please enable lua errors (by typing `/console scriptErrors 1` in game) and report any errors you receive. You can later disable lua errors by typing `/console scriptErrors 0`.

**Comment by Moma1706** [comment]
this is my talent build:
BAEArSxcnei16P8xFL3rzzOyRKRIFFkkkkiAiERERSCAAQChESkkkIJJJRSOAAAAAAAAAAJCA
i have also enabled lua errors and nothing happened dont really know what should happen though :D

**Comment by Moma1706** [comment]
also this issue i have on my demon hunter(i have just checked) so its probably not problem with a mage, is there anything i can check rcheck or provide to you to be easier to help with problem

**Comment by Moma1706** [comment]
I have fixed the issue it was my fault, really sorry to bother you mage rotation part of the addon wasnt loaded...
Thank you again.
