### ISSUE TITLE
[Enhancement]: Should we expect rogue to be updated for the  new patch later today, or still need a bit more time?

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#993]
### What feature would you like to have added?

Just curious. Thanks!

**Comment by Cilraaz** [comment]
It'll be ready when it's ready.

**Comment by GarrettCottrell** [comment]
Okay, cool thanks - any estimate on eta? or prob woulda included that in your response if there was. I'm not worried, sorry if it came across a certain way
