### ISSUE TITLE
[Bug]: Outlaw Rogue Between the Eyes for Trinkets

### ISSUE THREAD

**Issue by unrealshape** [herotc/hero-rotation#996]
### What version of HeroRotation are you using?

latest

### What version of HeroLib are you using?

latest

### What version of HeroDBC are you using?

latest

### What is the issue?

Hello everyone,

We have a change to the spell "Between the Eyes" which does not add a debuff and therefore the fall will never occur for the Trinket.

Best regards

`    if Settings.Commons.UseTrinkets then
      -- actions.cds+=/use_item,name=manic_grieftorch,if=!stealthed.all&!buff.adrenaline_rush.up|fight_remains<5
      if I.ManicGrieftorch:IsEquippedAndReady() and Target:FilteredTimeToDie(">", 2) and not Player:StealthUp(true, true) then
        if HR.Cast(I.ManicGrieftorch, nil, Settings.Commons.TrinketDisplayStyle) then return "Manic Grieftorch"; end
      end
      -- actions.cds+=/use_item,name=windscar_whetstone,if=spell_targets.blade_flurry>desired_targets|raid_event.adds.in>60|fight_remains<7
      -- actions.cds+=/use_items,slots=trinket1,if=debuff.between_the_eyes.up|trinket.1.has_stat.any_dps|fight_remains<=20
      -- actions.cds+=/use_items,slots=trinket2,if=debuff.between_the_eyes.up|trinket.2.has_stat.any_dps|fight_remains<=20
      local TrinketToUse = Player:GetUseableItems(OnUseExcludes, 13) or Player:GetUseableItems(OnUseExcludes, 14)
      if TrinketToUse and (Target:DebuffUp(S.BetweentheEyes) or HL.BossFilteredFightRemains("<", 20) or TrinketToUse:HasStatAnyDps()) then
        if HR.Cast(TrinketToUse, nil, Settings.Commons.TrinketDisplayStyle) then return "Generic use_items for " .. TrinketToUse:Name() end
      end
    end
  end
end`

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Outlaw has not yet been updated for 10.2.
