### ISSUE TITLE
Outlaw rogue trinkets and shadow dance dont show up in rotation.[Bug]: 

### ISSUE THREAD

**Issue by djokassss** [herotc/hero-rotation#997]
### What version of HeroRotation are you using?

10.2.0

### What version of HeroLib are you using?

10.2.0

### What version of HeroDBC are you using?

10.2.0

### What is the issue?

I doesnt show trinkets and shadow dance in rotation for outlaw rogues on other specs it work I checked the settings all is alright I even reset the addon but it still does't show trinkets and shadow dance in rotation.

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Rogue specs have not yet been updated for 10.2
