### ISSUE TITLE
[Bug]: HR buttons not showing for Mage (Frost)

### ISSUE THREAD

**Issue by HesseHorst** [herotc/hero-rotation#998]
### What version of HeroRotation are you using?

10.2.0.06

### What version of HeroLib are you using?

10.2.0.01

### What version of HeroDBC are you using?

10.2.0.02

### What is the issue?

The hero lib buttons and symbols don't show up when looking into my mage. Paladin, Priest works fine, others I didn't test.
Rescaling the buttons makes them appear in principle but only cogwheels appear - it doesn't suggest any spells when doing damage.
Cheers and thanks for the great add-on!

### Icon Behavior

Icon does NOT appear

**Comment by Cilraaz** [comment]
Frost Mage has had multiple updates since this issue was created. Please report back if this is still an issue.
